// Estimated: ~115 lines
import { IndiaProduct } from "../types"

export const ITC_PRODUCTS: IndiaProduct[] = [
  // ITC FIAMA (001-010)
  { id: "IN-PC-ITC-001", name: "Fiama Shower Gel Blackcurrant and Bearberry 200ml", brand: "ITC", subBrand: "Fiama", category: "personal-care", subCategory: "bath-body", variant: "200ml", description: "Lather up with the goodness of Blackcurrant and Bearberry.", price: 175, originalPrice: 199, discount: 12, image: "/assets/products/IN-PC-ITC-001.jpg", affiliateUrl: "/go/IN-PC-ITC-001", affiliatePlatform: "amazon", affiliateSource: "amazon-pa-api-free", inStock: true, rating: 4.4, reviewCount: 15400, tags: ["shower-gel", "itc", "fiama", "body-wash"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-ITC-002", name: "Fiama Shower Gel Blackcurrant and Bearberry 500ml", brand: "ITC", subBrand: "Fiama", category: "personal-care", subCategory: "bath-body", variant: "500ml", description: "Soft and supple skin with moisturizing beads.", price: 395, originalPrice: 450, discount: 12, image: "/assets/products/IN-PC-ITC-002.jpg", affiliateUrl: "/go/IN-PC-ITC-002", affiliatePlatform: "flipkart", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.5, reviewCount: 22100, tags: ["shower-gel", "itc", "fiama", "body-wash"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-ITC-003", name: "Fiama Shower Gel Blackcurrant and Bearberry 2x200ml", brand: "ITC", subBrand: "Fiama", category: "personal-care", subCategory: "bath-body", variant: "2x200ml", description: "Value duo pack for daily refreshment.", price: 299, originalPrice: 398, discount: 25, image: "/assets/products/IN-PC-ITC-003.jpg", affiliateUrl: "/go/IN-PC-ITC-003", affiliatePlatform: "amazon", affiliateSource: "amazon-pa-api-free", inStock: true, rating: 4.5, reviewCount: 8400, tags: ["shower-gel", "itc", "fiama", "body-wash"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-ITC-004", name: "Fiama Shower Gel Blackcurrant and Bearberry 500ml Pump", brand: "ITC", subBrand: "Fiama", category: "personal-care", subCategory: "bath-body", variant: "500ml Pump", description: "Convenient dispenser pump for family use.", price: 425, originalPrice: 499, discount: 15, image: "/assets/products/IN-PC-ITC-004.jpg", affiliateUrl: "/go/IN-PC-ITC-004", affiliatePlatform: "flipkart", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.6, reviewCount: 12000, tags: ["shower-gel", "itc", "fiama", "body-wash"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-ITC-005", name: "Fiama Men Combo Pack Pulse 2-in-1", brand: "ITC", subBrand: "Fiama", category: "personal-care", subCategory: "bath-body", variant: "2-in-1 Pack", description: "Refreshment combo for the active man.", price: 345, originalPrice: 399, discount: 13, image: "/assets/products/IN-PC-ITC-005.jpg", affiliateUrl: "/go/IN-PC-ITC-005", affiliatePlatform: "amazon", affiliateSource: "amazon-pa-api-free", inStock: true, rating: 4.3, reviewCount: 5600, tags: ["men-grooming", "itc", "fiama", "combo"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-ITC-006", name: "Fiama Men Combo Pack Pulse 3-in-1", brand: "ITC", subBrand: "Fiama", category: "personal-care", subCategory: "bath-body", variant: "3-in-1 Pack", description: "Ultimate grooming trio for face, body, and hair.", price: 495, originalPrice: 599, discount: 17, image: "/assets/products/IN-PC-ITC-006.jpg", affiliateUrl: "/go/IN-PC-ITC-006", affiliatePlatform: "flipkart", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.4, reviewCount: 3200, tags: ["men-grooming", "itc", "fiama", "combo"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-ITC-007", name: "Fiama Men Pulse Body Wash 250ml", brand: "ITC", subBrand: "Fiama", category: "personal-care", subCategory: "bath-body", variant: "250ml", description: "Invigorating fragrance for men skin.", price: 225, originalPrice: 250, discount: 10, image: "/assets/products/IN-PC-ITC-007.jpg", affiliateUrl: "/go/IN-PC-ITC-007", affiliatePlatform: "amazon", affiliateSource: "amazon-pa-api-free", inStock: true, rating: 4.4, reviewCount: 9200, tags: ["body-wash", "itc", "fiama", "men"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-ITC-008", name: "Fiama Men Pulse Bathing Bar 125g", brand: "ITC", subBrand: "Fiama", category: "personal-care", subCategory: "bath-body", variant: "125g", description: "Glycerin-rich soap bar with sea minerals.", price: 95, originalPrice: 105, discount: 9, image: "/assets/products/IN-PC-ITC-008.jpg", affiliateUrl: "/go/IN-PC-ITC-008", affiliatePlatform: "flipkart", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.3, reviewCount: 15400, tags: ["soap", "itc", "fiama", "men"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-ITC-009", name: "Fiama Bathing Bar Mild Dew 75g", brand: "ITC", subBrand: "Fiama", category: "personal-care", subCategory: "bath-body", variant: "75g", description: "Moisturizing beauty bar with Peach and Avocado.", price: 54, originalPrice: 60, discount: 10, image: "/assets/products/IN-PC-ITC-009.jpg", affiliateUrl: "/go/IN-PC-ITC-009", affiliatePlatform: "amazon", affiliateSource: "amazon-pa-api-free", inStock: true, rating: 4.4, reviewCount: 45000, tags: ["soap", "itc", "fiama", "mild-dew"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-ITC-010", name: "Fiama Bathing Bar Mild Dew 125g", brand: "ITC", subBrand: "Fiama", category: "personal-care", subCategory: "bath-body", variant: "125g", description: "Enriched with skin conditioners for soft feel.", price: 90, originalPrice: 100, discount: 10, image: "/assets/products/IN-PC-ITC-010.jpg", affiliateUrl: "/go/IN-PC-ITC-010", affiliatePlatform: "flipkart", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.5, reviewCount: 38000, tags: ["soap", "itc", "fiama", "mild-dew"], apiSource: "amazon-pa-api-free" },

  // ITC ENGAGE (011-020)
  { id: "IN-PC-ITC-011", name: "Engage ON Cologne Spray Sport 150ml", brand: "ITC", subBrand: "Engage", category: "personal-care", subCategory: "fragrance", variant: "150ml", description: "Fresh and citrusy fragrance for active lifestyle.", price: 199, originalPrice: 225, discount: 12, image: "/assets/products/IN-PC-ITC-011.jpg", affiliateUrl: "/go/IN-PC-ITC-011", affiliatePlatform: "amazon", affiliateSource: "amazon-pa-api-free", inStock: true, rating: 4.2, reviewCount: 12400, tags: ["perfume", "itc", "engage", "sport"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-ITC-012", name: "Engage ON Cologne Spray Sport 200ml", brand: "ITC", subBrand: "Engage", category: "personal-care", subCategory: "fragrance", variant: "200ml", description: "Long-lasting cologne for all-day freshness.", price: 275, originalPrice: 315, discount: 13, image: "/assets/products/IN-PC-ITC-012.jpg", affiliateUrl: "/go/IN-PC-ITC-012", affiliatePlatform: "flipkart", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.3, reviewCount: 9200, tags: ["perfume", "itc", "engage", "sport"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-ITC-013", name: "Engage ON Cologne Spray Sport Pocket 18ml", brand: "ITC", subBrand: "Engage", category: "personal-care", subCategory: "fragrance", variant: "18ml", description: "Pocket-sized perfume for on-the-go fresh feel.", price: 60, originalPrice: 65, discount: 8, image: "/assets/products/IN-PC-ITC-013.jpg", affiliateUrl: "/go/IN-PC-ITC-013", affiliatePlatform: "amazon", affiliateSource: "amazon-pa-api-free", inStock: true, rating: 4.1, reviewCount: 45000, tags: ["perfume", "itc", "engage", "pocket"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-ITC-014", name: "Engage ON Cologne Spray Sport 2x150ml", brand: "ITC", subBrand: "Engage", category: "personal-care", subCategory: "fragrance", variant: "Twin Pack", description: "Double the freshness value duo pack.", price: 349, originalPrice: 450, discount: 22, image: "/assets/products/IN-PC-ITC-014.jpg", affiliateUrl: "/go/IN-PC-ITC-014", affiliatePlatform: "flipkart", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.4, reviewCount: 3100, tags: ["perfume", "itc", "engage", "combo"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-ITC-015", name: "Engage W1 Perfume Spray Women 120ml", brand: "ITC", subBrand: "Engage", category: "personal-care", subCategory: "fragrance", variant: "120ml", description: "Floral and fruity notes for the modern woman.", price: 225, originalPrice: 250, discount: 10, image: "/assets/products/IN-PC-ITC-015.jpg", affiliateUrl: "/go/IN-PC-ITC-015", affiliatePlatform: "amazon", affiliateSource: "amazon-pa-api-free", inStock: true, rating: 4.4, reviewCount: 8500, tags: ["perfume", "itc", "engage", "women"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-ITC-016", name: "Engage W1 Perfume Spray Women 200ml", brand: "ITC", subBrand: "Engage", category: "personal-care", subCategory: "fragrance", variant: "200ml", description: "Exquisite feminine scent for daily wear.", price: 345, originalPrice: 399, discount: 13, image: "/assets/products/IN-PC-ITC-016.jpg", affiliateUrl: "/go/IN-PC-ITC-016", affiliatePlatform: "flipkart", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.5, reviewCount: 6400, tags: ["perfume", "itc", "engage", "women"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-ITC-017", name: "Engage W1 Pocket Perfume 18ml", brand: "ITC", subBrand: "Engage", category: "personal-care", subCategory: "fragrance", variant: "18ml", description: "Miniature W1 spray for your handbag.", price: 65, originalPrice: 65, discount: 0, image: "/assets/products/IN-PC-ITC-017.jpg", affiliateUrl: "/go/IN-PC-ITC-017", affiliatePlatform: "amazon", affiliateSource: "amazon-pa-api-free", inStock: true, rating: 4.3, reviewCount: 38000, tags: ["perfume", "itc", "engage", "pocket"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-ITC-018", name: "Engage Cologne Aqua 150ml", brand: "ITC", subBrand: "Engage", category: "personal-care", subCategory: "fragrance", variant: "150ml", description: "Cooling aquatic notes for summer fresh feel.", price: 199, originalPrice: 225, discount: 12, image: "/assets/products/IN-PC-ITC-018.jpg", affiliateUrl: "/go/IN-PC-ITC-018", affiliatePlatform: "flipkart", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.2, reviewCount: 15400, tags: ["perfume", "itc", "engage", "aqua"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-ITC-019", name: "Engage Cologne Aqua 200ml", brand: "ITC", subBrand: "Engage", category: "personal-care", subCategory: "fragrance", variant: "200ml", description: "Premium aquatic cologne for men.", price: 275, originalPrice: 315, discount: 13, image: "/assets/products/IN-PC-ITC-019.jpg", affiliateUrl: "/go/IN-PC-ITC-019", affiliatePlatform: "amazon", affiliateSource: "amazon-pa-api-free", inStock: true, rating: 4.3, reviewCount: 7200, tags: ["perfume", "itc", "engage", "aqua"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-ITC-020", name: "Engage Cologne Aqua Pocket 18ml", brand: "ITC", subBrand: "Engage", category: "personal-care", subCategory: "fragrance", variant: "18ml", description: "Compact aqua cologne for instant revival.", price: 60, originalPrice: 60, discount: 0, image: "/assets/products/IN-PC-ITC-020.jpg", affiliateUrl: "/go/IN-PC-ITC-020", affiliatePlatform: "flipkart", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.2, reviewCount: 25000, tags: ["perfume", "itc", "engage", "pocket"], apiSource: "amazon-pa-api-free" },

  // ITC SAVLON (021-030)
  { id: "IN-PC-ITC-021", name: "Savlon Moisturising Germ Protection Handwash 200ml", brand: "ITC", subBrand: "Savlon", category: "personal-care", subCategory: "bath-body", variant: "200ml", description: "99.9% germ protection with skin moisture.", price: 95, originalPrice: 110, discount: 14, image: "/assets/products/IN-PC-ITC-021.jpg", affiliateUrl: "/go/IN-PC-ITC-021", affiliatePlatform: "amazon", affiliateSource: "amazon-pa-api-free", inStock: true, rating: 4.6, reviewCount: 55000, tags: ["handwash", "itc", "savlon", "hygiene"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-ITC-022", name: "Savlon Moisturising Germ Protection Handwash 500ml", brand: "ITC", subBrand: "Savlon", category: "personal-care", subCategory: "bath-body", variant: "500ml", description: "Standard pump pack for family hand hygiene.", price: 185, originalPrice: 210, discount: 12, image: "/assets/products/IN-PC-ITC-022.jpg", affiliateUrl: "/go/IN-PC-ITC-022", affiliatePlatform: "flipkart", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.7, reviewCount: 32000, tags: ["handwash", "itc", "savlon", "hygiene"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-ITC-023", name: "Savlon Moisturising Germ Protection Handwash 1L", brand: "ITC", subBrand: "Savlon", category: "personal-care", subCategory: "bath-body", variant: "1L", description: "Refill pack for handwash dispensers.", price: 320, originalPrice: 380, discount: 16, image: "/assets/products/IN-PC-ITC-023.jpg", affiliateUrl: "/go/IN-PC-ITC-023", affiliatePlatform: "amazon", affiliateSource: "amazon-pa-api-free", inStock: true, rating: 4.7, reviewCount: 18000, tags: ["handwash", "itc", "savlon", "refill"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-ITC-024", name: "Savlon Handwash Refill Pouch 1.5L", brand: "ITC", subBrand: "Savlon", category: "personal-care", subCategory: "bath-body", variant: "1.5L Pouch", description: "Mega savings refill pouch for Savlon.", price: 449, originalPrice: 550, discount: 18, image: "/assets/products/IN-PC-ITC-024.jpg", affiliateUrl: "/go/IN-PC-ITC-024", affiliatePlatform: "flipkart", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.8, reviewCount: 12000, tags: ["handwash", "itc", "savlon", "refill"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-ITC-025", name: "Savlon Surface Disinfectant Spray 200ml", brand: "ITC", subBrand: "Savlon", category: "personal-care", subCategory: "hygiene", variant: "200ml", description: "Kill 99.9% germs on hard and soft surfaces.", price: 155, originalPrice: 175, discount: 11, image: "/assets/products/IN-PC-ITC-025.jpg", affiliateUrl: "/go/IN-PC-ITC-025", affiliatePlatform: "amazon", affiliateSource: "amazon-pa-api-free", inStock: true, rating: 4.5, reviewCount: 88000, tags: ["disinfectant", "itc", "savlon", "spray"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-ITC-026", name: "Savlon Surface Disinfectant Spray 500ml", brand: "ITC", subBrand: "Savlon", category: "personal-care", subCategory: "hygiene", variant: "500ml", description: "Complete home hygiene disinfectant spray.", price: 345, originalPrice: 399, discount: 13, image: "/assets/products/IN-PC-ITC-026.jpg", affiliateUrl: "/go/IN-PC-ITC-026", affiliatePlatform: "flipkart", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.6, reviewCount: 42000, tags: ["disinfectant", "itc", "savlon", "spray"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-ITC-027", name: "Savlon Surface Disinfectant Spray 1L", brand: "ITC", subBrand: "Savlon", category: "personal-care", subCategory: "hygiene", variant: "1L", description: "Bulk surface protection for offices and homes.", price: 599, originalPrice: 750, discount: 20, image: "/assets/products/IN-PC-ITC-027.jpg", affiliateUrl: "/go/IN-PC-ITC-027", affiliatePlatform: "amazon", affiliateSource: "amazon-pa-api-free", inStock: true, rating: 4.7, reviewCount: 15000, tags: ["disinfectant", "itc", "savlon", "spray"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-ITC-028", name: "Savlon Antiseptic Liquid 50ml", brand: "ITC", subBrand: "Savlon", category: "personal-care", subCategory: "hygiene", variant: "50ml", description: "First aid antiseptic for cuts and bruises.", price: 45, originalPrice: 50, discount: 10, image: "/assets/products/IN-PC-ITC-028.jpg", affiliateUrl: "/go/IN-PC-ITC-028", affiliatePlatform: "flipkart", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.8, reviewCount: 120000, tags: ["antiseptic", "itc", "savlon", "liquid"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-ITC-029", name: "Savlon Antiseptic Liquid 500ml", brand: "ITC", subBrand: "Savlon", category: "personal-care", subCategory: "hygiene", variant: "500ml", description: "Powerful germ protection for home sanitization.", price: 299, originalPrice: 350, discount: 15, image: "/assets/products/IN-PC-ITC-029.jpg", affiliateUrl: "/go/IN-PC-ITC-029", affiliatePlatform: "amazon", affiliateSource: "amazon-pa-api-free", inStock: true, rating: 4.9, reviewCount: 56000, tags: ["antiseptic", "itc", "savlon", "liquid"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-ITC-030", name: "Savlon Antiseptic Liquid 1L", brand: "ITC", subBrand: "Savlon", category: "personal-care", subCategory: "hygiene", variant: "1L", description: "Hospital grade antiseptic protection.", price: 550, originalPrice: 650, discount: 15, image: "/assets/products/IN-PC-ITC-030.jpg", affiliateUrl: "/go/IN-PC-ITC-030", affiliatePlatform: "flipkart", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.9, reviewCount: 22000, tags: ["antiseptic", "itc", "savlon", "liquid"], apiSource: "amazon-pa-api-free" },

  // ITC CLASSMATE (031-040)
  { id: "IN-PC-ITC-031", name: "Classmate Interleaf Single Line Notebook 140 pages", brand: "ITC", subBrand: "Classmate", category: "personal-care", subCategory: "stationery", variant: "Single", description: "Superior paper quality for smooth writing.", price: 75, originalPrice: 85, discount: 12, image: "/assets/products/IN-PC-ITC-031.jpg", affiliateUrl: "/go/IN-PC-ITC-031", affiliatePlatform: "amazon", affiliateSource: "amazon-pa-api-free", inStock: true, rating: 4.6, reviewCount: 15000, tags: ["notebook", "itc", "classmate"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-ITC-032", name: "Classmate Interleaf Single Line Notebook Pack of 3", brand: "ITC", subBrand: "Classmate", category: "personal-care", subCategory: "stationery", variant: "Pack of 3", description: "Educational series notebooks bundle.", price: 210, originalPrice: 255, discount: 17, image: "/assets/products/IN-PC-ITC-032.jpg", affiliateUrl: "/go/IN-PC-ITC-032", affiliatePlatform: "flipkart", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.7, reviewCount: 8400, tags: ["notebook", "itc", "classmate"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-ITC-033", name: "Classmate Interleaf Single Line Notebook Pack of 6", brand: "ITC", subBrand: "Classmate", category: "personal-care", subCategory: "stationery", variant: "Pack of 6", description: "Value bundle of high-quality notebooks.", price: 395, originalPrice: 510, discount: 22, image: "/assets/products/IN-PC-ITC-033.jpg", affiliateUrl: "/go/IN-PC-ITC-033", affiliatePlatform: "amazon", affiliateSource: "amazon-pa-api-free", inStock: true, rating: 4.8, reviewCount: 5200, tags: ["notebook", "itc", "classmate"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-ITC-034", name: "Classmate Pulse Pen Blue Pack of 5", brand: "ITC", subBrand: "Classmate", category: "personal-care", subCategory: "stationery", variant: "Pack of 5", description: "Smooth ink flow ball pens for exams.", price: 50, originalPrice: 50, discount: 0, image: "/assets/products/IN-PC-ITC-034.jpg", affiliateUrl: "/go/IN-PC-ITC-034", affiliatePlatform: "flipkart", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.5, reviewCount: 12000, tags: ["pen", "itc", "classmate"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-ITC-035", name: "Classmate Pulse Pen Blue Pack of 10", brand: "ITC", subBrand: "Classmate", category: "personal-care", subCategory: "stationery", variant: "Pack of 10", description: "Premium blue ink ball pens pack.", price: 95, originalPrice: 100, discount: 5, image: "/assets/products/IN-PC-ITC-035.jpg", affiliateUrl: "/go/IN-PC-ITC-035", affiliatePlatform: "amazon", affiliateSource: "amazon-pa-api-free", inStock: true, rating: 4.6, reviewCount: 8500, tags: ["pen", "itc", "classmate"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-ITC-036", name: "Classmate Pulse Pen Blue Pack of 20", brand: "ITC", subBrand: "Classmate", category: "personal-care", subCategory: "stationery", variant: "Pack of 20", description: "Bulk pens pack for office and school.", price: 180, originalPrice: 200, discount: 10, image: "/assets/products/IN-PC-ITC-036.jpg", affiliateUrl: "/go/IN-PC-ITC-036", affiliatePlatform: "flipkart", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.7, reviewCount: 3400, tags: ["pen", "itc", "classmate"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-ITC-037", name: "Classmate Long Book 76 pages Single", brand: "ITC", subBrand: "Classmate", category: "personal-care", subCategory: "stationery", variant: "Single", description: "Long format book for extensive notes.", price: 45, originalPrice: 50, discount: 10, image: "/assets/products/IN-PC-ITC-037.jpg", affiliateUrl: "/go/IN-PC-ITC-037", affiliatePlatform: "amazon", affiliateSource: "amazon-pa-api-free", inStock: true, rating: 4.4, reviewCount: 9800, tags: ["notebook", "itc", "classmate"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-ITC-038", name: "Classmate Long Book 76 pages Pack of 6", brand: "ITC", subBrand: "Classmate", category: "personal-care", subCategory: "stationery", variant: "Pack of 6", description: "Semester value pack long books.", price: 240, originalPrice: 300, discount: 20, image: "/assets/products/IN-PC-ITC-038.jpg", affiliateUrl: "/go/IN-PC-ITC-038", affiliatePlatform: "flipkart", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.6, reviewCount: 4200, tags: ["notebook", "itc", "classmate"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-ITC-039", name: "Classmate Long Book 76 pages Pack of 12", brand: "ITC", subBrand: "Classmate", category: "personal-care", subCategory: "stationery", variant: "Pack of 12", description: "Yearly supply long books bundle.", price: 450, originalPrice: 600, discount: 25, image: "/assets/products/IN-PC-ITC-039.jpg", affiliateUrl: "/go/IN-PC-ITC-039", affiliatePlatform: "amazon", affiliateSource: "amazon-pa-api-free", inStock: true, rating: 4.7, reviewCount: 1500, tags: ["notebook", "itc", "classmate"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-ITC-040", name: "Classmate Stationery Kit Pro", brand: "ITC", subBrand: "Classmate", category: "personal-care", subCategory: "stationery", variant: "Kit", description: "Complete stationery kit with notebook, pen, and more.", price: 299, originalPrice: 350, discount: 15, image: "/assets/products/IN-PC-ITC-040.jpg", affiliateUrl: "/go/IN-PC-ITC-040", affiliatePlatform: "flipkart", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.8, reviewCount: 2200, tags: ["stationery", "itc", "classmate", "kit"], apiSource: "amazon-pa-api-free" },

  // ITC SUNFEAST (041-050)
  { id: "IN-PC-ITC-041", name: "Sunfeast Dark Fantasy Choco Fills 75g", brand: "ITC", subBrand: "Sunfeast", category: "food-grocery", subCategory: "snacks", variant: "75g", description: "Gooey chocolate fills inside a crunchy cookie.", price: 40, originalPrice: 40, discount: 0, image: "/assets/products/IN-PC-ITC-041.jpg", affiliateUrl: "/go/IN-PC-ITC-041", affiliatePlatform: "amazon", affiliateSource: "amazon-pa-api-free", inStock: true, rating: 4.7, reviewCount: 125000, tags: ["biscuits", "itc", "sunfeast", "chocolate"], apiSource: "open-food-facts-free" },
  { id: "IN-PC-ITC-042", name: "Sunfeast Dark Fantasy Choco Fills 300g", brand: "ITC", subBrand: "Sunfeast", category: "food-grocery", subCategory: "snacks", variant: "300g", description: "Premium choco filled cookies value pack.", price: 145, originalPrice: 160, discount: 9, image: "/assets/products/IN-PC-ITC-042.jpg", affiliateUrl: "/go/IN-PC-ITC-042", affiliatePlatform: "flipkart", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.8, reviewCount: 45000, tags: ["biscuits", "itc", "sunfeast", "chocolate"], apiSource: "open-food-facts-free" },
  { id: "IN-PC-ITC-043", name: "Sunfeast Dark Fantasy Choco Fills 600g", brand: "ITC", subBrand: "Sunfeast", category: "food-grocery", subCategory: "snacks", variant: "600g", description: "Mega indulgent choco fills family pack.", price: 275, originalPrice: 320, discount: 14, image: "/assets/products/IN-PC-ITC-043.jpg", affiliateUrl: "/go/IN-PC-ITC-043", affiliatePlatform: "amazon", affiliateSource: "amazon-pa-api-free", inStock: true, rating: 4.9, reviewCount: 22000, tags: ["biscuits", "itc", "sunfeast", "chocolate"], apiSource: "open-food-facts-free" },
  { id: "IN-PC-ITC-044", name: "Sunfeast Mom's Magic Cashew Almond 75g", brand: "ITC", subBrand: "Sunfeast", category: "food-grocery", subCategory: "snacks", variant: "75g", description: "Rich butter cookies with cashew and almond bits.", price: 30, originalPrice: 30, discount: 0, image: "/assets/products/IN-PC-ITC-044.jpg", affiliateUrl: "/go/IN-PC-ITC-044", affiliatePlatform: "flipkart", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.6, reviewCount: 88000, tags: ["biscuits", "itc", "sunfeast", "nuts"], apiSource: "open-food-facts-free" },
  { id: "IN-PC-ITC-045", name: "Sunfeast Mom's Magic Cashew Almond 300g", brand: "ITC", subBrand: "Sunfeast", category: "food-grocery", subCategory: "snacks", variant: "300g", description: "Handcrafted nutty cookies for tea time.", price: 115, originalPrice: 130, discount: 12, image: "/assets/products/IN-PC-ITC-045.jpg", affiliateUrl: "/go/IN-PC-ITC-045", affiliatePlatform: "amazon", affiliateSource: "amazon-pa-api-free", inStock: true, rating: 4.7, reviewCount: 32000, tags: ["biscuits", "itc", "sunfeast", "nuts"], apiSource: "open-food-facts-free" },
  { id: "IN-PC-ITC-046", name: "Sunfeast Mom's Magic Cashew Almond 600g", brand: "ITC", subBrand: "Sunfeast", category: "food-grocery", subCategory: "snacks", variant: "600g", description: "Mega nut cookies family savings pack.", price: 210, originalPrice: 250, discount: 16, image: "/assets/products/IN-PC-ITC-046.jpg", affiliateUrl: "/go/IN-PC-ITC-046", affiliatePlatform: "flipkart", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.8, reviewCount: 15000, tags: ["biscuits", "itc", "sunfeast", "nuts"], apiSource: "open-food-facts-free" },
  { id: "IN-PC-ITC-047", name: "Sunfeast Bounce Cream Biscuits 82.5g", brand: "ITC", subBrand: "Sunfeast", category: "food-grocery", subCategory: "snacks", variant: "82.5g", description: "Crunchy biscuits with smooth orange cream.", price: 10, originalPrice: 10, discount: 0, image: "/assets/products/IN-PC-ITC-047.jpg", affiliateUrl: "/go/IN-PC-ITC-047", affiliatePlatform: "amazon", affiliateSource: "amazon-pa-api-free", inStock: true, rating: 4.4, reviewCount: 155000, tags: ["biscuits", "itc", "sunfeast", "cream"], apiSource: "open-food-facts-free" },
  { id: "IN-PC-ITC-048", name: "Sunfeast Bounce Cream Biscuits 3x82.5g", brand: "ITC", subBrand: "Sunfeast", category: "food-grocery", subCategory: "snacks", variant: "3 Pack", description: "Orange cream biscuits value trio.", price: 28, originalPrice: 30, discount: 7, image: "/assets/products/IN-PC-ITC-048.jpg", affiliateUrl: "/go/IN-PC-ITC-048", affiliatePlatform: "flipkart", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.5, reviewCount: 56000, tags: ["biscuits", "itc", "sunfeast", "cream"], apiSource: "open-food-facts-free" },
  { id: "IN-PC-ITC-049", name: "Sunfeast Bounce Cream Biscuits 6x82.5g", brand: "ITC", subBrand: "Sunfeast", category: "food-grocery", subCategory: "snacks", variant: "6 Pack", description: "Bulk cream biscuits for kids snack.", price: 55, originalPrice: 60, discount: 8, image: "/assets/products/IN-PC-ITC-049.jpg", affiliateUrl: "/go/IN-PC-ITC-049", affiliatePlatform: "amazon", affiliateSource: "amazon-pa-api-free", inStock: true, rating: 4.6, reviewCount: 28000, tags: ["biscuits", "itc", "sunfeast", "cream"], apiSource: "open-food-facts-free" },
  { id: "IN-PC-ITC-050", name: "Sunfeast Bounce Cream Biscuits Chocolate 82.5g", brand: "ITC", subBrand: "Sunfeast", category: "food-grocery", subCategory: "snacks", variant: "Chocolate", description: "Rich chocolate cream filled crunch biscuits.", price: 10, originalPrice: 10, discount: 0, image: "/assets/products/IN-PC-ITC-050.jpg", affiliateUrl: "/go/IN-PC-ITC-050", affiliatePlatform: "flipkart", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.5, reviewCount: 65000, tags: ["biscuits", "itc", "sunfeast", "cream"], apiSource: "open-food-facts-free" }
]

export const GODREJ_CONSUMER_PRODUCTS: IndiaProduct[] = [
  // GOOD KNIGHT (001-010)
  { id: "IN-PC-GCP-001", name: "Good Knight Gold Flash Machine + Refill", brand: "Godrej CP", subBrand: "Good Knight", category: "personal-care", subCategory: "hygiene", variant: "Starter Pack", description: "Visible flash vapors for extreme protection.", price: 115, originalPrice: 135, discount: 15, image: "/assets/products/IN-PC-GCP-001.jpg", affiliateUrl: "/go/IN-PC-GCP-001", affiliatePlatform: "amazon", affiliateSource: "amazon-pa-api-free", inStock: true, rating: 4.4, reviewCount: 88000, tags: ["mosquito", "godrej", "good-knight"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-GCP-002", name: "Good Knight Gold Flash Refill 45ml", brand: "Godrej CP", subBrand: "Good Knight", category: "personal-care", subCategory: "hygiene", variant: "45ml Refill", description: "Standard liquid refill for mosquito repellent.", price: 85, originalPrice: 99, discount: 14, image: "/assets/products/IN-PC-GCP-002.jpg", affiliateUrl: "/go/IN-PC-GCP-002", affiliatePlatform: "flipkart", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.5, reviewCount: 155000, tags: ["mosquito", "godrej", "good-knight"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-GCP-003", name: "Good Knight Gold Flash Refill 2-pack", brand: "Godrej CP", subBrand: "Good Knight", category: "personal-care", subCategory: "hygiene", variant: "2 Pack", description: "Value bundle of liquid mosquito refills.", price: 160, originalPrice: 198, discount: 19, image: "/assets/products/IN-PC-GCP-003.jpg", affiliateUrl: "/go/IN-PC-GCP-003", affiliatePlatform: "amazon", affiliateSource: "amazon-pa-api-free", inStock: true, rating: 4.6, reviewCount: 45000, tags: ["mosquito", "godrej", "good-knight"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-GCP-004", name: "Good Knight Fabric Roll-On 8ml", brand: "Godrej CP", subBrand: "Good Knight", category: "personal-care", subCategory: "hygiene", variant: "8ml", description: "Outdoor protection with 100% natural oils.", price: 75, originalPrice: 85, discount: 12, image: "/assets/products/IN-PC-GCP-004.jpg", affiliateUrl: "/go/IN-PC-GCP-004", affiliatePlatform: "flipkart", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.4, reviewCount: 32000, tags: ["mosquito", "godrej", "good-knight", "roll-on"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-GCP-005", name: "Good Knight Fabric Roll-On 3x8ml", brand: "Godrej CP", subBrand: "Good Knight", category: "personal-care", subCategory: "hygiene", variant: "3 Pack", description: "Triple pack outdoor mosquito protection.", price: 199, originalPrice: 255, discount: 22, image: "/assets/products/IN-PC-GCP-005.jpg", affiliateUrl: "/go/IN-PC-GCP-005", affiliatePlatform: "amazon", affiliateSource: "amazon-pa-api-free", inStock: true, rating: 4.5, reviewCount: 12000, tags: ["mosquito", "godrej", "good-knight", "roll-on"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-GCP-006", name: "Good Knight Fast Card 10 cards", brand: "Godrej CP", subBrand: "Good Knight", category: "personal-care", subCategory: "hygiene", variant: "10 Cards", description: "Instant action mosquito repellent cards.", price: 15, originalPrice: 15, discount: 0, image: "/assets/products/IN-PC-GCP-006.jpg", affiliateUrl: "/go/IN-PC-GCP-006", affiliatePlatform: "flipkart", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.2, reviewCount: 210000, tags: ["mosquito", "godrej", "good-knight", "card"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-GCP-007", name: "Good Knight Fast Card 50 cards", brand: "Godrej CP", subBrand: "Good Knight", category: "personal-care", subCategory: "hygiene", variant: "50 Cards", description: "Bulk savings pack of fast cards.", price: 70, originalPrice: 75, discount: 7, image: "/assets/products/IN-PC-GCP-007.jpg", affiliateUrl: "/go/IN-PC-GCP-007", affiliatePlatform: "amazon", affiliateSource: "amazon-pa-api-free", inStock: true, rating: 4.3, reviewCount: 38000, tags: ["mosquito", "godrej", "good-knight", "card"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-GCP-008", name: "Good Knight Power Activ+ Starter Pack", brand: "Godrej CP", subBrand: "Good Knight", category: "personal-care", subCategory: "hygiene", variant: "Starter Pack", description: "Dual mode machine for normal and heavy protection.", price: 105, originalPrice: 125, discount: 16, image: "/assets/products/IN-PC-GCP-008.jpg", affiliateUrl: "/go/IN-PC-GCP-008", affiliatePlatform: "flipkart", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.4, reviewCount: 65000, tags: ["mosquito", "godrej", "good-knight"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-GCP-009", name: "Good Knight Power Activ+ Refill 45ml", brand: "Godrej CP", subBrand: "Good Knight", category: "personal-care", subCategory: "hygiene", variant: "45ml Refill", description: "Long-lasting liquid for Power Activ+ machine.", price: 80, originalPrice: 90, discount: 11, image: "/assets/products/IN-PC-GCP-009.jpg", affiliateUrl: "/go/IN-PC-GCP-009", affiliatePlatform: "amazon", affiliateSource: "amazon-pa-api-free", inStock: true, rating: 4.5, reviewCount: 124000, tags: ["mosquito", "godrej", "good-knight"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-GCP-010", name: "Good Knight Mosquito Repellent Cream 50g", brand: "Godrej CP", subBrand: "Good Knight", category: "personal-care", subCategory: "hygiene", variant: "50g", description: "Non-sticky mosquito repellent cream with Aloe.", price: 55, originalPrice: 65, discount: 15, image: "/assets/products/IN-PC-GCP-010.jpg", affiliateUrl: "/go/IN-PC-GCP-010", affiliatePlatform: "flipkart", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.3, reviewCount: 22000, tags: ["mosquito", "godrej", "good-knight", "cream"], apiSource: "amazon-pa-api-free" },

  // CINTHOL (011-020)
  { id: "IN-PC-GCP-011", name: "Cinthol Deo Soap Original 75g", brand: "Godrej CP", subBrand: "Cinthol", category: "personal-care", subCategory: "bath-body", variant: "75g", description: "Classic deodarant soap for 24hr freshness.", price: 38, originalPrice: 45, discount: 15, image: "/assets/products/IN-PC-GCP-011.jpg", affiliateUrl: "/go/IN-PC-GCP-011", affiliatePlatform: "amazon", affiliateSource: "amazon-pa-api-free", inStock: true, rating: 4.4, reviewCount: 150000, tags: ["soap", "godrej", "cinthol", "deo"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-GCP-012", name: "Cinthol Deo Soap Original 3x100g", brand: "Godrej CP", subBrand: "Cinthol", category: "personal-care", subCategory: "bath-body", variant: "3 Pack", description: "Value trio of original Cinthol soap.", price: 155, originalPrice: 195, discount: 20, image: "/assets/products/IN-PC-GCP-012.jpg", affiliateUrl: "/go/IN-PC-GCP-012", affiliatePlatform: "flipkart", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.5, reviewCount: 88000, tags: ["soap", "godrej", "cinthol", "deo"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-GCP-013", name: "Cinthol Confidence+ Deodorant Spray 150ml", brand: "Godrej CP", subBrand: "Cinthol", category: "personal-care", subCategory: "fragrance", variant: "150ml", description: "Active deo spray for high intensity protection.", price: 199, originalPrice: 225, discount: 12, image: "/assets/products/IN-PC-GCP-013.jpg", affiliateUrl: "/go/IN-PC-GCP-013", affiliatePlatform: "amazon", affiliateSource: "amazon-pa-api-free", inStock: true, rating: 4.2, reviewCount: 15400, tags: ["deo", "godrej", "cinthol"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-GCP-014", name: "Cinthol Confidence+ Deodorant Spray 200ml", brand: "Godrej CP", subBrand: "Cinthol", category: "personal-care", subCategory: "fragrance", variant: "200ml", description: "Premium long-lasting deo for men.", price: 275, originalPrice: 315, discount: 13, image: "/assets/products/IN-PC-GCP-014.jpg", affiliateUrl: "/go/IN-PC-GCP-014", affiliatePlatform: "flipkart", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.3, reviewCount: 9200, tags: ["deo", "godrej", "cinthol"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-GCP-015", name: "Cinthol Lime Fresh Bathing Soap 75g", brand: "Godrej CP", subBrand: "Cinthol", category: "personal-care", subCategory: "bath-body", variant: "75g", description: "Refreshing lime fragrance for a cool bath.", price: 38, originalPrice: 45, discount: 15, image: "/assets/products/IN-PC-GCP-015.jpg", affiliateUrl: "/go/IN-PC-GCP-015", affiliatePlatform: "amazon", affiliateSource: "amazon-pa-api-free", inStock: true, rating: 4.4, reviewCount: 120000, tags: ["soap", "godrej", "cinthol", "lime"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-GCP-016", name: "Cinthol Lime Fresh Bathing Soap 3x100g", brand: "Godrej CP", subBrand: "Cinthol", category: "personal-care", subCategory: "bath-body", variant: "3 Pack", description: "Value bundle of lime fresh beauty bars.", price: 155, originalPrice: 195, discount: 20, image: "/assets/products/IN-PC-GCP-016.jpg", affiliateUrl: "/go/IN-PC-GCP-016", affiliatePlatform: "flipkart", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.5, reviewCount: 65000, tags: ["soap", "godrej", "cinthol", "lime"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-GCP-017", name: "Cinthol Head to Toe Body Wash 250ml", brand: "Godrej CP", subBrand: "Cinthol", category: "personal-care", subCategory: "bath-body", variant: "250ml", description: "3-in-1 wash for face, body, and hair.", price: 225, originalPrice: 250, discount: 10, image: "/assets/products/IN-PC-GCP-017.jpg", affiliateUrl: "/go/IN-PC-GCP-017", affiliatePlatform: "amazon", affiliateSource: "amazon-pa-api-free", inStock: true, rating: 4.4, reviewCount: 8400, tags: ["body-wash", "godrej", "cinthol"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-GCP-018", name: "Cinthol Original Talc 300g", brand: "Godrej CP", subBrand: "Cinthol", category: "personal-care", subCategory: "bath-body", variant: "300g", description: "Deo protection in a cooling talcum powder.", price: 145, originalPrice: 180, discount: 19, image: "/assets/products/IN-PC-GCP-018.jpg", affiliateUrl: "/go/IN-PC-GCP-018", affiliatePlatform: "flipkart", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.3, reviewCount: 32000, tags: ["talc", "godrej", "cinthol"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-GCP-019", name: "Cinthol Play Refreshing Deo 150ml", brand: "Godrej CP", subBrand: "Cinthol", category: "personal-care", subCategory: "fragrance", variant: "150ml", description: "Sporty fragrance for long-lasting confidence.", price: 199, originalPrice: 225, discount: 12, image: "/assets/products/IN-PC-GCP-019.jpg", affiliateUrl: "/go/IN-PC-GCP-019", affiliatePlatform: "amazon", affiliateSource: "amazon-pa-api-free", inStock: true, rating: 4.2, reviewCount: 11200, tags: ["deo", "godrej", "cinthol"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-GCP-020", name: "Cinthol Skin Safe Shaving Cream 100g", brand: "Godrej CP", subBrand: "Cinthol", category: "personal-care", subCategory: "grooming", variant: "100g", description: "Lemon fresh shaving cream for smooth glide.", price: 75, originalPrice: 85, discount: 12, image: "/assets/products/IN-PC-GCP-020.jpg", affiliateUrl: "/go/IN-PC-GCP-020", affiliatePlatform: "flipkart", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.3, reviewCount: 25000, tags: ["shaving", "godrej", "cinthol"], apiSource: "amazon-pa-api-free" },

  // GODREJ NO.1 (021-030)
  { id: "IN-PC-GCP-021", name: "Godrej No.1 Sandal and Turmeric Soap 100g", brand: "Godrej CP", subBrand: "Godrej No.1", category: "personal-care", subCategory: "bath-body", variant: "100g", description: "Natural glow with Sandal and Turmeric.", price: 45, originalPrice: 50, discount: 10, image: "/assets/products/IN-PC-GCP-021.jpg", affiliateUrl: "/go/IN-PC-GCP-021", affiliatePlatform: "amazon", affiliateSource: "amazon-pa-api-free", inStock: true, rating: 4.3, reviewCount: 210000, tags: ["soap", "godrej", "no1", "sandal"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-GCP-022", name: "Godrej No.1 Sandal and Turmeric Soap 3x100g", brand: "Godrej CP", subBrand: "Godrej No.1", category: "personal-care", subCategory: "bath-body", variant: "3 Pack", description: "Value savings on natural glow soap.", price: 125, originalPrice: 150, discount: 17, image: "/assets/products/IN-PC-GCP-022.jpg", affiliateUrl: "/go/IN-PC-GCP-022", affiliatePlatform: "flipkart", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.4, reviewCount: 125000, tags: ["soap", "godrej", "no1", "sandal"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-GCP-023", name: "Godrej No.1 Sandal and Turmeric Soap 6x100g", brand: "Godrej CP", subBrand: "Godrej No.1", category: "personal-care", subCategory: "bath-body", variant: "6 Pack", description: "Jumbo family pack for traditional skin care.", price: 240, originalPrice: 300, discount: 20, image: "/assets/products/IN-PC-GCP-023.jpg", affiliateUrl: "/go/IN-PC-GCP-023", affiliatePlatform: "amazon", affiliateSource: "amazon-pa-api-free", inStock: true, rating: 4.5, reviewCount: 56000, tags: ["soap", "godrej", "no1", "sandal"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-GCP-024", name: "Godrej No.1 Rose and Milk Cream Soap 100g", brand: "Godrej CP", subBrand: "Godrej No.1", category: "personal-care", subCategory: "bath-body", variant: "100g", description: "Soft and smooth skin with Rose and Milk.", price: 45, originalPrice: 50, discount: 10, image: "/assets/products/IN-PC-GCP-024.jpg", affiliateUrl: "/go/IN-PC-GCP-024", affiliatePlatform: "flipkart", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.3, reviewCount: 92000, tags: ["soap", "godrej", "no1", "rose"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-GCP-025", name: "Godrej No.1 Rose and Milk Cream Soap 3x100g", brand: "Godrej CP", subBrand: "Godrej No.1", category: "personal-care", subCategory: "bath-body", variant: "3 Pack", description: "Value bundle for soft beauty bath.", price: 125, originalPrice: 150, discount: 17, image: "/assets/products/IN-PC-GCP-025.jpg", affiliateUrl: "/go/IN-PC-GCP-025", affiliatePlatform: "amazon", affiliateSource: "amazon-pa-api-free", inStock: true, rating: 4.4, reviewCount: 45000, tags: ["soap", "godrej", "no1", "rose"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-GCP-026", name: "Godrej No.1 Neem and Natural Extracts 100g", brand: "Godrej CP", subBrand: "Godrej No.1", category: "personal-care", subCategory: "bath-body", variant: "100g", description: "Germ protection with goodness of Neem.", price: 45, originalPrice: 50, discount: 10, image: "/assets/products/IN-PC-GCP-026.jpg", affiliateUrl: "/go/IN-PC-GCP-026", affiliatePlatform: "flipkart", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.3, reviewCount: 110000, tags: ["soap", "godrej", "no1", "neem"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-GCP-027", name: "Godrej No.1 Neem and Natural Extracts 3x100g", brand: "Godrej CP", subBrand: "Godrej No.1", category: "personal-care", subCategory: "bath-body", variant: "3 Pack", description: "Purity and protection value pack.", price: 125, originalPrice: 150, discount: 17, image: "/assets/products/IN-PC-GCP-027.jpg", affiliateUrl: "/go/IN-PC-GCP-027", affiliatePlatform: "amazon", affiliateSource: "amazon-pa-api-free", inStock: true, rating: 4.4, reviewCount: 52000, tags: ["soap", "godrej", "no1", "neem"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-GCP-028", name: "Godrej No.1 Jasmine and Milk Cream Soap 100g", brand: "Godrej CP", subBrand: "Godrej No.1", category: "personal-care", subCategory: "bath-body", variant: "100g", description: "Exotic Jasmine fragrance for soft skin.", price: 45, originalPrice: 50, discount: 10, image: "/assets/products/IN-PC-GCP-028.jpg", affiliateUrl: "/go/IN-PC-GCP-028", affiliatePlatform: "flipkart", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.3, reviewCount: 65000, tags: ["soap", "godrej", "no1", "jasmine"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-GCP-029", name: "Godrej No.1 Lime and Aloe Vera Soap 100g", brand: "Godrej CP", subBrand: "Godrej No.1", category: "personal-care", subCategory: "bath-body", variant: "100g", description: "Fresh and hydrated skin with Lime and Aloe.", price: 45, originalPrice: 50, discount: 10, image: "/assets/products/IN-PC-GCP-029.jpg", affiliateUrl: "/go/IN-PC-GCP-029", affiliatePlatform: "amazon", affiliateSource: "amazon-pa-api-free", inStock: true, rating: 4.4, reviewCount: 88000, tags: ["soap", "godrej", "no1", "lime"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-GCP-030", name: "Godrej No.1 Honey and Glycerin Soap 100g", brand: "Godrej CP", subBrand: "Godrej No.1", category: "personal-care", subCategory: "bath-body", variant: "100g", description: "Extra moisture for winter skin care.", price: 55, originalPrice: 65, discount: 15, image: "/assets/products/IN-PC-GCP-030.jpg", affiliateUrl: "/go/IN-PC-GCP-030", affiliatePlatform: "flipkart", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.5, reviewCount: 34000, tags: ["soap", "godrej", "no1", "honey"], apiSource: "amazon-pa-api-free" },

  // GODREJ EXPERT (031-040)
  { id: "IN-PC-GCP-031", name: "Godrej Expert Easy 5 Minute Hair Colour Natural Black", brand: "Godrej CP", subBrand: "Godrej Expert", category: "personal-care", subCategory: "hair-care", variant: "1 Pack", description: "No ammonia shampoo-based hair colour.", price: 30, originalPrice: 35, discount: 14, image: "/assets/products/IN-PC-GCP-031.jpg", affiliateUrl: "/go/IN-PC-GCP-031", affiliatePlatform: "amazon", affiliateSource: "amazon-pa-api-free", inStock: true, rating: 4.3, reviewCount: 150000, tags: ["hair-colour", "godrej", "expert"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-GCP-032", name: "Godrej Expert Easy Hair Colour Natural Black 6 pack", brand: "Godrej CP", subBrand: "Godrej Expert", category: "personal-care", subCategory: "hair-care", variant: "6 Pack", description: "Value bundle for regular root touch-ups.", price: 170, originalPrice: 210, discount: 19, image: "/assets/products/IN-PC-GCP-032.jpg", affiliateUrl: "/go/IN-PC-GCP-032", affiliatePlatform: "flipkart", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.4, reviewCount: 45000, tags: ["hair-colour", "godrej", "expert"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-GCP-033", name: "Godrej Expert Rich Crème Dark Brown 20g+20ml", brand: "Godrej CP", subBrand: "Godrej Expert", category: "personal-care", subCategory: "hair-care", variant: "Single", description: "Rich dark brown creme hair colour with Aloe.", price: 35, originalPrice: 40, discount: 12, image: "/assets/products/IN-PC-GCP-033.jpg", affiliateUrl: "/go/IN-PC-GCP-033", affiliatePlatform: "amazon", affiliateSource: "amazon-pa-api-free", inStock: true, rating: 4.4, reviewCount: 92000, tags: ["hair-colour", "godrej", "expert"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-GCP-034", name: "Godrej Expert Rich Crème Dark Brown 6-pack", brand: "Godrej CP", subBrand: "Godrej Expert", category: "personal-care", subCategory: "hair-care", variant: "6 Pack", description: "Mega savings creme hair colour bundle.", price: 199, originalPrice: 240, discount: 17, image: "/assets/products/IN-PC-GCP-034.jpg", affiliateUrl: "/go/IN-PC-GCP-034", affiliatePlatform: "flipkart", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.5, reviewCount: 32000, tags: ["hair-colour", "godrej", "expert"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-GCP-035", name: "Godrej Nupur Mehendi Natural Henna 120g", brand: "Godrej CP", subBrand: "Godrej Expert", category: "personal-care", subCategory: "hair-care", variant: "120g", description: "9 natural herbs infused pure Rajasthani Mehendi.", price: 65, originalPrice: 75, discount: 13, image: "/assets/products/IN-PC-GCP-035.jpg", affiliateUrl: "/go/IN-PC-GCP-035", affiliatePlatform: "amazon", affiliateSource: "amazon-pa-api-free", inStock: true, rating: 4.6, reviewCount: 125000, tags: ["mehendi", "godrej", "nupur", "henna"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-GCP-036", name: "Godrej Nupur Mehendi Natural Henna 400g", brand: "Godrej CP", subBrand: "Godrej Expert", category: "personal-care", subCategory: "hair-care", variant: "400g", description: "Professional mehendi pack for hair and hands.", price: 195, originalPrice: 240, discount: 19, image: "/assets/products/IN-PC-GCP-036.jpg", affiliateUrl: "/go/IN-PC-GCP-036", affiliatePlatform: "flipkart", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.7, reviewCount: 56000, tags: ["mehendi", "godrej", "nupur", "henna"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-GCP-037", name: "Godrej Expert Easy 5 Minute Hair Colour Natural Brown", brand: "Godrej CP", subBrand: "Godrej Expert", category: "personal-care", subCategory: "hair-care", variant: "1 Pack", description: "No ammonia shampoo-based brown colour.", price: 30, originalPrice: 35, discount: 14, image: "/assets/products/IN-PC-GCP-037.jpg", affiliateUrl: "/go/IN-PC-GCP-037", affiliatePlatform: "amazon", affiliateSource: "amazon-pa-api-free", inStock: true, rating: 4.2, reviewCount: 38000, tags: ["hair-colour", "godrej", "expert"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-GCP-038", name: "Godrej Expert Rich Crème Burgundy 20g+20ml", brand: "Godrej CP", subBrand: "Godrej Expert", category: "personal-care", subCategory: "hair-care", variant: "Single", description: "Vibrant burgundy hair colour with skin conditioners.", price: 35, originalPrice: 40, discount: 12, image: "/assets/products/IN-PC-GCP-038.jpg", affiliateUrl: "/go/IN-PC-GCP-038", affiliatePlatform: "flipkart", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.3, reviewCount: 18000, tags: ["hair-colour", "godrej", "expert"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-GCP-039", name: "Godrej Nupur Mehendi Natural Henna 800g", brand: "Godrej CP", subBrand: "Godrej Expert", category: "personal-care", subCategory: "hair-care", variant: "800g", description: "Jumbo Rajasthani mehendi pack for deep conditioning.", price: 380, originalPrice: 450, discount: 16, image: "/assets/products/IN-PC-GCP-039.jpg", affiliateUrl: "/go/IN-PC-GCP-039", affiliatePlatform: "amazon", affiliateSource: "amazon-pa-api-free", inStock: true, rating: 4.8, reviewCount: 22000, tags: ["mehendi", "godrej", "nupur", "henna"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-GCP-040", name: "Godrej Expert Rich Crème Natural Black 3-pack", brand: "Godrej CP", subBrand: "Godrej Expert", category: "personal-care", subCategory: "hair-care", variant: "3 Pack", description: "Convenient trio pack of black creme colour.", price: 100, originalPrice: 120, discount: 17, image: "/assets/products/IN-PC-GCP-040.jpg", affiliateUrl: "/go/IN-PC-GCP-040", affiliatePlatform: "flipkart", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.5, reviewCount: 5600, tags: ["hair-colour", "godrej", "expert"], apiSource: "amazon-pa-api-free" },

  // HIT (041-050)
  { id: "IN-PC-GCP-041", name: "Hit Cockroach Killer Spray 200ml", brand: "Godrej CP", subBrand: "Hit", category: "personal-care", subCategory: "hygiene", variant: "200ml", description: "Deep reach nozzle kills hidden cockroaches.", price: 195, originalPrice: 225, discount: 13, image: "/assets/products/IN-PC-GCP-041.jpg", affiliateUrl: "/go/IN-PC-GCP-041", affiliatePlatform: "amazon", affiliateSource: "amazon-pa-api-free", inStock: true, rating: 4.5, reviewCount: 65000, tags: ["insecticide", "godrej", "hit", "cockroach"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-GCP-042", name: "Hit Cockroach Killer Spray 425ml", brand: "Godrej CP", subBrand: "Hit", category: "personal-care", subCategory: "hygiene", variant: "425ml", description: "Instant kill formula for cockroach control.", price: 375, originalPrice: 450, discount: 17, image: "/assets/products/IN-PC-GCP-042.jpg", affiliateUrl: "/go/IN-PC-GCP-042", affiliatePlatform: "flipkart", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.6, reviewCount: 32000, tags: ["insecticide", "godrej", "hit", "cockroach"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-GCP-043", name: "Hit Cockroach Killer Spray 2x200ml", brand: "Godrej CP", subBrand: "Hit", category: "personal-care", subCategory: "hygiene", variant: "2 Pack", description: "Value bundle for total cockroach protection.", price: 349, originalPrice: 450, discount: 22, image: "/assets/products/IN-PC-GCP-043.jpg", affiliateUrl: "/go/IN-PC-GCP-043", affiliatePlatform: "amazon", affiliateSource: "amazon-pa-api-free", inStock: true, rating: 4.7, reviewCount: 15400, tags: ["insecticide", "godrej", "hit", "cockroach"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-GCP-044", name: "Hit Flying Insect Killer 200ml", brand: "Godrej CP", subBrand: "Hit", category: "personal-care", subCategory: "hygiene", variant: "200ml", description: "Kill mosquitoes and flies instantly.", price: 185, originalPrice: 210, discount: 12, image: "/assets/products/IN-PC-GCP-044.jpg", affiliateUrl: "/go/IN-PC-GCP-044", affiliatePlatform: "flipkart", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.4, reviewCount: 42000, tags: ["insecticide", "godrej", "hit", "mosquito"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-GCP-045", name: "Hit Flying Insect Killer 320ml", brand: "Godrej CP", subBrand: "Hit", category: "personal-care", subCategory: "hygiene", variant: "320ml", description: "Refreshing lime fragrance flying insect spray.", price: 295, originalPrice: 340, discount: 13, image: "/assets/products/IN-PC-GCP-045.jpg", affiliateUrl: "/go/IN-PC-GCP-045", affiliatePlatform: "amazon", affiliateSource: "amazon-pa-api-free", inStock: true, rating: 4.5, reviewCount: 18000, tags: ["insecticide", "godrej", "hit", "mosquito"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-GCP-046", name: "Hit Flying Insect Killer 425ml", brand: "Godrej CP", subBrand: "Hit", category: "personal-care", subCategory: "hygiene", variant: "425ml", description: "Mega pack for mosquito-free home.", price: 360, originalPrice: 425, discount: 15, image: "/assets/products/IN-PC-GCP-046.jpg", affiliateUrl: "/go/IN-PC-GCP-046", affiliatePlatform: "flipkart", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.6, reviewCount: 22000, tags: ["insecticide", "godrej", "hit", "mosquito"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-GCP-047", name: "Hit Crawling Insect Killer 320ml", brand: "Godrej CP", subBrand: "Hit", category: "personal-care", subCategory: "hygiene", variant: "320ml", description: "Kill ants and other crawling insects effectively.", price: 285, originalPrice: 320, discount: 11, image: "/assets/products/IN-PC-GCP-047.jpg", affiliateUrl: "/go/IN-PC-GCP-047", affiliatePlatform: "amazon", affiliateSource: "amazon-pa-api-free", inStock: true, rating: 4.5, reviewCount: 12400, tags: ["insecticide", "godrej", "hit", "ants"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-GCP-048", name: "Hit Crawling Insect Killer Refill pack 320ml", brand: "Godrej CP", subBrand: "Hit", category: "personal-care", subCategory: "hygiene", variant: "Refill", description: "Eco-friendly refill pack for crawling insect control.", price: 245, originalPrice: 285, discount: 14, image: "/assets/products/IN-PC-GCP-048.jpg", affiliateUrl: "/go/IN-PC-GCP-048", affiliatePlatform: "flipkart", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.6, reviewCount: 8400, tags: ["insecticide", "godrej", "hit", "ants"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-GCP-049", name: "Hit Anti-Roach Gel 20g", brand: "Godrej CP", subBrand: "Hit", category: "personal-care", subCategory: "hygiene", variant: "20g", description: "Kitchen-safe cockroach killing gel.", price: 265, originalPrice: 300, discount: 12, image: "/assets/products/IN-PC-GCP-049.jpg", affiliateUrl: "/go/IN-PC-GCP-049", affiliatePlatform: "amazon", affiliateSource: "amazon-pa-api-free", inStock: true, rating: 4.7, reviewCount: 45000, tags: ["insecticide", "godrej", "hit", "gel"], apiSource: "amazon-pa-api-free" },
  { id: "IN-PC-GCP-050", name: "Hit Chalk for Ants and Cockroaches", brand: "Godrej CP", subBrand: "Hit", category: "personal-care", subCategory: "hygiene", variant: "Single", description: "Easy to use insect repellent chalk.", price: 25, originalPrice: 25, discount: 0, image: "/assets/products/IN-PC-GCP-050.jpg", affiliateUrl: "/go/IN-PC-GCP-050", affiliatePlatform: "flipkart", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.2, reviewCount: 95000, tags: ["insecticide", "godrej", "hit", "chalk"], apiSource: "amazon-pa-api-free" }
]
