import { IndiaProduct } from "../types"

// ===================================================================
// boAt — 50 products (IN-EL-BOT-001 to IN-EL-BOT-050)
// Sub-categories: earbuds, headphones, speakers, smartwatches, cables
// ===================================================================
export const BOAT_PRODUCTS: IndiaProduct[] = [
  // EARBUDS (001–015)
  { id: "IN-EL-BOT-001", name: "boAt Airdopes 141 TWS Earbuds Active Black", brand: "boAt", subBrand: "Airdopes", category: "electronics", subCategory: "earbuds", variant: "Active Black", description: "42H playtime with ASAP charge and IWP technology.", price: 1299, originalPrice: 4490, discount: 71, image: "/assets/products/IN-EL-BOT-001.jpg", affiliateUrl: "/go/IN-EL-BOT-001", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.1, reviewCount: 284000, tags: ["earbuds", "boat", "tws", "airdopes-141"], apiSource: "static-only" },
  { id: "IN-EL-BOT-002", name: "boAt Airdopes 141 TWS Earbuds Cyan Cider", brand: "boAt", subBrand: "Airdopes", category: "electronics", subCategory: "earbuds", variant: "Cyan Cider", description: "8mm drivers deliver punchy bass and clear mids.", price: 1299, originalPrice: 4490, discount: 71, image: "/assets/products/IN-EL-BOT-002.jpg", affiliateUrl: "/go/IN-EL-BOT-002", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.1, reviewCount: 284000, tags: ["earbuds", "boat", "tws", "airdopes-141"], apiSource: "static-only" },
  { id: "IN-EL-BOT-003", name: "boAt Airdopes 161 TWS Earbuds Midnight Black", brand: "boAt", subBrand: "Airdopes", category: "electronics", subCategory: "earbuds", variant: "Midnight Black", description: "ENx noise cancelling for crystal clear calls.", price: 1499, originalPrice: 3990, discount: 62, image: "/assets/products/IN-EL-BOT-003.jpg", affiliateUrl: "/go/IN-EL-BOT-003", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.0, reviewCount: 156000, tags: ["earbuds", "boat", "tws", "airdopes-161"], apiSource: "static-only" },
  { id: "IN-EL-BOT-004", name: "boAt Airdopes 161 TWS Earbuds Cherry Blossom", brand: "boAt", subBrand: "Airdopes", category: "electronics", subCategory: "earbuds", variant: "Cherry Blossom", description: "Bluetooth v5.1 with multipoint connection support.", price: 1499, originalPrice: 3990, discount: 62, image: "/assets/products/IN-EL-BOT-004.jpg", affiliateUrl: "/go/IN-EL-BOT-004", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.0, reviewCount: 156000, tags: ["earbuds", "boat", "tws", "airdopes-161"], apiSource: "static-only" },
  { id: "IN-EL-BOT-005", name: "boAt Airdopes 191G Gaming TWS Earbuds Black Sabre", brand: "boAt", subBrand: "Airdopes", category: "electronics", subCategory: "earbuds", variant: "Black Sabre", description: "BEAST mode with 65ms ultra-low latency for gaming.", price: 1799, originalPrice: 4990, discount: 63, image: "/assets/products/IN-EL-BOT-005.jpg", affiliateUrl: "/go/IN-EL-BOT-005", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.2, reviewCount: 98000, tags: ["earbuds", "boat", "tws", "gaming", "airdopes-191g"], apiSource: "static-only" },
  { id: "IN-EL-BOT-006", name: "boAt Airdopes 311 Pro TWS Earbuds Silver Mist", brand: "boAt", subBrand: "Airdopes", category: "electronics", subCategory: "earbuds", variant: "Silver Mist", description: "ANC hybrid with 3 microphones per bud.", price: 2499, originalPrice: 5990, discount: 58, image: "/assets/products/IN-EL-BOT-006.jpg", affiliateUrl: "/go/IN-EL-BOT-006", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 72000, tags: ["earbuds", "boat", "tws", "anc", "airdopes-311"], apiSource: "static-only" },
  { id: "IN-EL-BOT-007", name: "boAt Airdopes 311 Pro TWS Earbuds Carbon Black", brand: "boAt", subBrand: "Airdopes", category: "electronics", subCategory: "earbuds", variant: "Carbon Black", description: "Up to 25dB active noise cancellation.", price: 2499, originalPrice: 5990, discount: 58, image: "/assets/products/IN-EL-BOT-007.jpg", affiliateUrl: "/go/IN-EL-BOT-007", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 72000, tags: ["earbuds", "boat", "tws", "anc", "airdopes-311"], apiSource: "static-only" },
  { id: "IN-EL-BOT-008", name: "boAt Airdopes Atom 81 TWS Earbuds Electric Blue", brand: "boAt", subBrand: "Airdopes", category: "electronics", subCategory: "earbuds", variant: "Electric Blue", description: "13mm drivers with boAt Signature Sound.", price: 999, originalPrice: 2990, discount: 66, image: "/assets/products/IN-EL-BOT-008.jpg", affiliateUrl: "/go/IN-EL-BOT-008", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 3.9, reviewCount: 145000, tags: ["earbuds", "boat", "tws", "budget", "atom-81"], apiSource: "static-only" },
  { id: "IN-EL-BOT-009", name: "boAt Airdopes Atom 81 TWS Earbuds Pebble Black", brand: "boAt", subBrand: "Airdopes", category: "electronics", subCategory: "earbuds", variant: "Pebble Black", description: "Featherweight 4g per bud for all-day comfort.", price: 999, originalPrice: 2990, discount: 66, image: "/assets/products/IN-EL-BOT-009.jpg", affiliateUrl: "/go/IN-EL-BOT-009", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 3.9, reviewCount: 145000, tags: ["earbuds", "boat", "tws", "budget", "atom-81"], apiSource: "static-only" },
  { id: "IN-EL-BOT-010", name: "boAt Airdopes 500 ANC TWS Earbuds Gunmetal Grey", brand: "boAt", subBrand: "Airdopes", category: "electronics", subCategory: "earbuds", variant: "Gunmetal Grey", description: "Premium ANC earbuds with 35dB noise cancellation and LHDC 5.0.", price: 3999, originalPrice: 7990, discount: 49, image: "/assets/products/IN-EL-BOT-010.jpg", affiliateUrl: "/go/IN-EL-BOT-010", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.4, reviewCount: 34000, tags: ["earbuds", "boat", "tws", "anc", "premium", "airdopes-500"], apiSource: "static-only" },
  { id: "IN-EL-BOT-011", name: "boAt Nirvana Ion ANC TWS Earbuds Ivory White", brand: "boAt", subBrand: "Nirvana", category: "electronics", subCategory: "earbuds", variant: "Ivory White", description: "Crystal Bionic Sound with 10mm carbon fiber drivers.", price: 4499, originalPrice: 9990, discount: 54, image: "/assets/products/IN-EL-BOT-011.jpg", affiliateUrl: "/go/IN-EL-BOT-011", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.5, reviewCount: 18000, tags: ["earbuds", "boat", "tws", "anc", "premium", "nirvana"], apiSource: "static-only" },
  { id: "IN-EL-BOT-012", name: "boAt Nirvana Ion ANC TWS Earbuds Smoky Black", brand: "boAt", subBrand: "Nirvana", category: "electronics", subCategory: "earbuds", variant: "Smoky Black", description: "Spatial audio with head tracking for immersive experience.", price: 4499, originalPrice: 9990, discount: 54, image: "/assets/products/IN-EL-BOT-012.jpg", affiliateUrl: "/go/IN-EL-BOT-012", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.5, reviewCount: 18000, tags: ["earbuds", "boat", "tws", "anc", "premium", "nirvana"], apiSource: "static-only" },
  { id: "IN-EL-BOT-013", name: "boAt Airdopes 131 TWS Earbuds Active Black", brand: "boAt", subBrand: "Airdopes", category: "electronics", subCategory: "earbuds", variant: "Active Black", description: "IWP instant pairing with 15H total playtime.", price: 899, originalPrice: 2490, discount: 63, image: "/assets/products/IN-EL-BOT-013.jpg", affiliateUrl: "/go/IN-EL-BOT-013", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 3.8, reviewCount: 320000, tags: ["earbuds", "boat", "tws", "budget", "airdopes-131"], apiSource: "static-only" },
  { id: "IN-EL-BOT-014", name: "boAt Airdopes 131 TWS Earbuds Cherry Blossom", brand: "boAt", subBrand: "Airdopes", category: "electronics", subCategory: "earbuds", variant: "Cherry Blossom", description: "Ergonomic in-ear fit with IPX4 sweat resistance.", price: 899, originalPrice: 2490, discount: 63, image: "/assets/products/IN-EL-BOT-014.jpg", affiliateUrl: "/go/IN-EL-BOT-014", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 3.8, reviewCount: 320000, tags: ["earbuds", "boat", "tws", "budget", "airdopes-131"], apiSource: "static-only" },
  { id: "IN-EL-BOT-015", name: "boAt Airdopes 441 Pro TWS Earbuds Active Black", brand: "boAt", subBrand: "Airdopes", category: "electronics", subCategory: "earbuds", variant: "Active Black", description: "150H standby with boAt Signature Sound tuning.", price: 1999, originalPrice: 4990, discount: 59, image: "/assets/products/IN-EL-BOT-015.jpg", affiliateUrl: "/go/IN-EL-BOT-015", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.1, reviewCount: 110000, tags: ["earbuds", "boat", "tws", "airdopes-441"], apiSource: "static-only" },

  // HEADPHONES (016–025)
  { id: "IN-EL-BOT-016", name: "boAt Rockerz 450 Bluetooth Headphones Luscious Black", brand: "boAt", subBrand: "Rockerz", category: "electronics", subCategory: "headphones", variant: "Luscious Black", description: "40mm dynamic drivers with 15H playback.", price: 1499, originalPrice: 3990, discount: 62, image: "/assets/products/IN-EL-BOT-016.jpg", affiliateUrl: "/go/IN-EL-BOT-016", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.1, reviewCount: 220000, tags: ["headphones", "boat", "bluetooth", "rockerz-450"], apiSource: "static-only" },
  { id: "IN-EL-BOT-017", name: "boAt Rockerz 450 Bluetooth Headphones Hazel Beige", brand: "boAt", subBrand: "Rockerz", category: "electronics", subCategory: "headphones", variant: "Hazel Beige", description: "Padded ear cushions with foldable design.", price: 1499, originalPrice: 3990, discount: 62, image: "/assets/products/IN-EL-BOT-017.jpg", affiliateUrl: "/go/IN-EL-BOT-017", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.1, reviewCount: 220000, tags: ["headphones", "boat", "bluetooth", "rockerz-450"], apiSource: "static-only" },
  { id: "IN-EL-BOT-018", name: "boAt Rockerz 550 ANC Bluetooth Headphones Black", brand: "boAt", subBrand: "Rockerz", category: "electronics", subCategory: "headphones", variant: "Black", description: "Hybrid ANC with ambient mode and 500mAh battery.", price: 2999, originalPrice: 5990, discount: 49, image: "/assets/products/IN-EL-BOT-018.jpg", affiliateUrl: "/go/IN-EL-BOT-018", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.2, reviewCount: 85000, tags: ["headphones", "boat", "bluetooth", "anc", "rockerz-550"], apiSource: "static-only" },
  { id: "IN-EL-BOT-019", name: "boAt Rockerz 550 ANC Bluetooth Headphones Silver Frost", brand: "boAt", subBrand: "Rockerz", category: "electronics", subCategory: "headphones", variant: "Silver Frost", description: "50mm drivers with 24-bit Hi-Res audio.", price: 2999, originalPrice: 5990, discount: 49, image: "/assets/products/IN-EL-BOT-019.jpg", affiliateUrl: "/go/IN-EL-BOT-019", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.2, reviewCount: 85000, tags: ["headphones", "boat", "bluetooth", "anc", "rockerz-550"], apiSource: "static-only" },
  { id: "IN-EL-BOT-020", name: "boAt Nirvana 751 ANC Headphones Space Black", brand: "boAt", subBrand: "Nirvana", category: "electronics", subCategory: "headphones", variant: "Space Black", description: "Hybrid ANC with Crystal Bionic Sound and LHDC 5.0.", price: 4999, originalPrice: 9990, discount: 49, image: "/assets/products/IN-EL-BOT-020.jpg", affiliateUrl: "/go/IN-EL-BOT-020", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.5, reviewCount: 22000, tags: ["headphones", "boat", "bluetooth", "anc", "premium", "nirvana-751"], apiSource: "static-only" },
  { id: "IN-EL-BOT-021", name: "boAt Nirvana 751 ANC Headphones Milky White", brand: "boAt", subBrand: "Nirvana", category: "electronics", subCategory: "headphones", variant: "Milky White", description: "65H playtime with adaptive ANC and transparency mode.", price: 4999, originalPrice: 9990, discount: 49, image: "/assets/products/IN-EL-BOT-021.jpg", affiliateUrl: "/go/IN-EL-BOT-021", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.5, reviewCount: 22000, tags: ["headphones", "boat", "bluetooth", "anc", "premium", "nirvana-751"], apiSource: "static-only" },
  { id: "IN-EL-BOT-022", name: "boAt Bassheads 100 Wired Earphones Black", brand: "boAt", subBrand: "Bassheads", category: "electronics", subCategory: "headphones", variant: "Black", description: "10mm dual-tone drivers with HD mic and tangle-free cable.", price: 399, originalPrice: 999, discount: 60, image: "/assets/products/IN-EL-BOT-022.jpg", affiliateUrl: "/go/IN-EL-BOT-022", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 3.9, reviewCount: 450000, tags: ["earphones", "boat", "wired", "bassheads-100"], apiSource: "static-only" },
  { id: "IN-EL-BOT-023", name: "boAt Bassheads 100 Wired Earphones Mint Green", brand: "boAt", subBrand: "Bassheads", category: "electronics", subCategory: "headphones", variant: "Mint Green", description: "Super extra bass with polished metal earshell.", price: 399, originalPrice: 999, discount: 60, image: "/assets/products/IN-EL-BOT-023.jpg", affiliateUrl: "/go/IN-EL-BOT-023", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 3.9, reviewCount: 450000, tags: ["earphones", "boat", "wired", "bassheads-100"], apiSource: "static-only" },
  { id: "IN-EL-BOT-024", name: "boAt Rockerz 255 Pro+ Neckband Earphones Active Black", brand: "boAt", subBrand: "Rockerz", category: "electronics", subCategory: "headphones", variant: "Active Black", description: "Magnetic earbuds with ASAP charge — 10min = 10H.", price: 1199, originalPrice: 2990, discount: 59, image: "/assets/products/IN-EL-BOT-024.jpg", affiliateUrl: "/go/IN-EL-BOT-024", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.0, reviewCount: 190000, tags: ["neckband", "boat", "bluetooth", "rockerz-255"], apiSource: "static-only" },
  { id: "IN-EL-BOT-025", name: "boAt Rockerz 255 Pro+ Neckband Earphones Teal Green", brand: "boAt", subBrand: "Rockerz", category: "electronics", subCategory: "headphones", variant: "Teal Green", description: "40H playtime with dual pairing and IPX5 water resistance.", price: 1199, originalPrice: 2990, discount: 59, image: "/assets/products/IN-EL-BOT-025.jpg", affiliateUrl: "/go/IN-EL-BOT-025", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.0, reviewCount: 190000, tags: ["neckband", "boat", "bluetooth", "rockerz-255"], apiSource: "static-only" },

  // SPEAKERS (026–035)
  { id: "IN-EL-BOT-026", name: "boAt Stone 180 5W Bluetooth Speaker Blue", brand: "boAt", subBrand: "Stone", category: "electronics", subCategory: "speakers", variant: "Blue", description: "Compact 5W speaker with 10H playtime and IPX7.", price: 899, originalPrice: 2490, discount: 63, image: "/assets/products/IN-EL-BOT-026.jpg", affiliateUrl: "/go/IN-EL-BOT-026", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.0, reviewCount: 125000, tags: ["speaker", "boat", "bluetooth", "portable", "stone-180"], apiSource: "static-only" },
  { id: "IN-EL-BOT-027", name: "boAt Stone 180 5W Bluetooth Speaker Black", brand: "boAt", subBrand: "Stone", category: "electronics", subCategory: "speakers", variant: "Black", description: "52mm full-range driver with passive bass radiator.", price: 899, originalPrice: 2490, discount: 63, image: "/assets/products/IN-EL-BOT-027.jpg", affiliateUrl: "/go/IN-EL-BOT-027", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.0, reviewCount: 125000, tags: ["speaker", "boat", "bluetooth", "portable", "stone-180"], apiSource: "static-only" },
  { id: "IN-EL-BOT-028", name: "boAt Stone 352 10W Bluetooth Speaker Raging Red", brand: "boAt", subBrand: "Stone", category: "electronics", subCategory: "speakers", variant: "Raging Red", description: "TWS pairing for stereo sound with RGB LED lights.", price: 1499, originalPrice: 3490, discount: 57, image: "/assets/products/IN-EL-BOT-028.jpg", affiliateUrl: "/go/IN-EL-BOT-028", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.2, reviewCount: 68000, tags: ["speaker", "boat", "bluetooth", "stone-352"], apiSource: "static-only" },
  { id: "IN-EL-BOT-029", name: "boAt Stone 352 10W Bluetooth Speaker Space Grey", brand: "boAt", subBrand: "Stone", category: "electronics", subCategory: "speakers", variant: "Space Grey", description: "12H playtime with Type-C fast charging.", price: 1499, originalPrice: 3490, discount: 57, image: "/assets/products/IN-EL-BOT-029.jpg", affiliateUrl: "/go/IN-EL-BOT-029", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.2, reviewCount: 68000, tags: ["speaker", "boat", "bluetooth", "stone-352"], apiSource: "static-only" },
  { id: "IN-EL-BOT-030", name: "boAt Stone 1200 14W Bluetooth Speaker Midnight Blue", brand: "boAt", subBrand: "Stone", category: "electronics", subCategory: "speakers", variant: "Midnight Blue", description: "Dual passive radiators with 9H playtime.", price: 2499, originalPrice: 5990, discount: 58, image: "/assets/products/IN-EL-BOT-030.jpg", affiliateUrl: "/go/IN-EL-BOT-030", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 42000, tags: ["speaker", "boat", "bluetooth", "stone-1200"], apiSource: "static-only" },
  { id: "IN-EL-BOT-031", name: "boAt Stone 1200 14W Bluetooth Speaker Military Green", brand: "boAt", subBrand: "Stone", category: "electronics", subCategory: "speakers", variant: "Military Green", description: "IPX7 waterproof rugged build for outdoors.", price: 2499, originalPrice: 5990, discount: 58, image: "/assets/products/IN-EL-BOT-031.jpg", affiliateUrl: "/go/IN-EL-BOT-031", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 42000, tags: ["speaker", "boat", "bluetooth", "stone-1200"], apiSource: "static-only" },
  { id: "IN-EL-BOT-032", name: "boAt Stone 1500 40W Bluetooth Speaker Black", brand: "boAt", subBrand: "Stone", category: "electronics", subCategory: "speakers", variant: "Black", description: "Party speaker with 40W output and built-in microphone.", price: 4999, originalPrice: 9990, discount: 49, image: "/assets/products/IN-EL-BOT-032.jpg", affiliateUrl: "/go/IN-EL-BOT-032", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.4, reviewCount: 18000, tags: ["speaker", "boat", "bluetooth", "party", "stone-1500"], apiSource: "static-only" },
  { id: "IN-EL-BOT-033", name: "boAt Aavante Bar 1160 60W Soundbar Midnight Black", brand: "boAt", subBrand: "Aavante", category: "electronics", subCategory: "speakers", variant: "Midnight Black", description: "2.0 soundbar with Bluetooth, AUX, USB, and HDMI.", price: 3999, originalPrice: 8990, discount: 55, image: "/assets/products/IN-EL-BOT-033.jpg", affiliateUrl: "/go/IN-EL-BOT-033", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 32000, tags: ["soundbar", "boat", "aavante", "60w"], apiSource: "static-only" },
  { id: "IN-EL-BOT-034", name: "boAt Aavante Bar 1680D 120W Soundbar Premium Black", brand: "boAt", subBrand: "Aavante", category: "electronics", subCategory: "speakers", variant: "Premium Black", description: "2.1 channel with wireless subwoofer and Dolby Audio.", price: 6999, originalPrice: 14990, discount: 53, image: "/assets/products/IN-EL-BOT-034.jpg", affiliateUrl: "/go/IN-EL-BOT-034", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.4, reviewCount: 15000, tags: ["soundbar", "boat", "aavante", "subwoofer", "dolby"], apiSource: "static-only" },
  { id: "IN-EL-BOT-035", name: "boAt Stone Symphony 20W Portable Speaker Charcoal Black", brand: "boAt", subBrand: "Stone", category: "electronics", subCategory: "speakers", variant: "Charcoal Black", description: "Premium metal body with 360° surround sound.", price: 3499, originalPrice: 6990, discount: 49, image: "/assets/products/IN-EL-BOT-035.jpg", affiliateUrl: "/go/IN-EL-BOT-035", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 25000, tags: ["speaker", "boat", "bluetooth", "premium", "stone-symphony"], apiSource: "static-only" },

  // SMARTWATCHES (036–045)
  { id: "IN-EL-BOT-036", name: "boAt Wave Lite Smartwatch Active Black", brand: "boAt", subBrand: "Wave", category: "electronics", subCategory: "smartwatches", variant: "Active Black", description: "1.69-inch HD display with 140+ watch faces.", price: 1799, originalPrice: 5990, discount: 69, image: "/assets/products/IN-EL-BOT-036.jpg", affiliateUrl: "/go/IN-EL-BOT-036", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.0, reviewCount: 95000, tags: ["smartwatch", "boat", "wave-lite", "fitness"], apiSource: "static-only" },
  { id: "IN-EL-BOT-037", name: "boAt Wave Lite Smartwatch Deep Blue", brand: "boAt", subBrand: "Wave", category: "electronics", subCategory: "smartwatches", variant: "Deep Blue", description: "SpO2, heart rate, and sleep tracking 24/7.", price: 1799, originalPrice: 5990, discount: 69, image: "/assets/products/IN-EL-BOT-037.jpg", affiliateUrl: "/go/IN-EL-BOT-037", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.0, reviewCount: 95000, tags: ["smartwatch", "boat", "wave-lite", "fitness"], apiSource: "static-only" },
  { id: "IN-EL-BOT-038", name: "boAt Wave Call 2 Smartwatch Active Black", brand: "boAt", subBrand: "Wave", category: "electronics", subCategory: "smartwatches", variant: "Active Black", description: "1.83-inch display with Bluetooth calling and AI voice assistant.", price: 2499, originalPrice: 6990, discount: 64, image: "/assets/products/IN-EL-BOT-038.jpg", affiliateUrl: "/go/IN-EL-BOT-038", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.2, reviewCount: 64000, tags: ["smartwatch", "boat", "wave-call", "bluetooth-calling"], apiSource: "static-only" },
  { id: "IN-EL-BOT-039", name: "boAt Wave Call 2 Smartwatch Cherry Blossom", brand: "boAt", subBrand: "Wave", category: "electronics", subCategory: "smartwatches", variant: "Cherry Blossom", description: "Advanced Bluetooth calling with built-in speaker and mic.", price: 2499, originalPrice: 6990, discount: 64, image: "/assets/products/IN-EL-BOT-039.jpg", affiliateUrl: "/go/IN-EL-BOT-039", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.2, reviewCount: 64000, tags: ["smartwatch", "boat", "wave-call", "bluetooth-calling"], apiSource: "static-only" },
  { id: "IN-EL-BOT-040", name: "boAt Lunar Oasis Smartwatch Steel Black", brand: "boAt", subBrand: "Lunar", category: "electronics", subCategory: "smartwatches", variant: "Steel Black", description: "1.39-inch AMOLED with always-on display and rotating crown.", price: 3499, originalPrice: 7990, discount: 56, image: "/assets/products/IN-EL-BOT-040.jpg", affiliateUrl: "/go/IN-EL-BOT-040", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 28000, tags: ["smartwatch", "boat", "lunar", "amoled", "premium"], apiSource: "static-only" },
  { id: "IN-EL-BOT-041", name: "boAt Lunar Oasis Smartwatch Rose Gold", brand: "boAt", subBrand: "Lunar", category: "electronics", subCategory: "smartwatches", variant: "Rose Gold", description: "Female health tracking with cycle and stress monitoring.", price: 3499, originalPrice: 7990, discount: 56, image: "/assets/products/IN-EL-BOT-041.jpg", affiliateUrl: "/go/IN-EL-BOT-041", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 28000, tags: ["smartwatch", "boat", "lunar", "amoled", "premium"], apiSource: "static-only" },
  { id: "IN-EL-BOT-042", name: "boAt Lunar Connect Ace Smartwatch Charcoal Black", brand: "boAt", subBrand: "Lunar", category: "electronics", subCategory: "smartwatches", variant: "Charcoal Black", description: "1.43-inch AMOLED with BT calling and 100+ sports modes.", price: 4499, originalPrice: 9990, discount: 55, image: "/assets/products/IN-EL-BOT-042.jpg", affiliateUrl: "/go/IN-EL-BOT-042", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.4, reviewCount: 15000, tags: ["smartwatch", "boat", "lunar", "amoled", "premium", "calling"], apiSource: "static-only" },
  { id: "IN-EL-BOT-043", name: "boAt Lunar Connect Ace Smartwatch Steel Silver", brand: "boAt", subBrand: "Lunar", category: "electronics", subCategory: "smartwatches", variant: "Steel Silver", description: "IP68 water resistance with 7-day battery life.", price: 4499, originalPrice: 9990, discount: 55, image: "/assets/products/IN-EL-BOT-043.jpg", affiliateUrl: "/go/IN-EL-BOT-043", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.4, reviewCount: 15000, tags: ["smartwatch", "boat", "lunar", "amoled", "premium", "calling"], apiSource: "static-only" },
  { id: "IN-EL-BOT-044", name: "boAt Enigma X500 Smartwatch Active Black", brand: "boAt", subBrand: "Enigma", category: "electronics", subCategory: "smartwatches", variant: "Active Black", description: "1.43-inch AMOLED with GPS and always-on display.", price: 5999, originalPrice: 12990, discount: 53, image: "/assets/products/IN-EL-BOT-044.jpg", affiliateUrl: "/go/IN-EL-BOT-044", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.5, reviewCount: 8500, tags: ["smartwatch", "boat", "enigma", "gps", "amoled", "premium"], apiSource: "static-only" },
  { id: "IN-EL-BOT-045", name: "boAt Enigma X500 Smartwatch Steel Grey", brand: "boAt", subBrand: "Enigma", category: "electronics", subCategory: "smartwatches", variant: "Steel Grey", description: "Built-in GPS with route tracking and altimeter.", price: 5999, originalPrice: 12990, discount: 53, image: "/assets/products/IN-EL-BOT-045.jpg", affiliateUrl: "/go/IN-EL-BOT-045", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.5, reviewCount: 8500, tags: ["smartwatch", "boat", "enigma", "gps", "amoled", "premium"], apiSource: "static-only" },

  // CABLES & CHARGERS (046–050)
  { id: "IN-EL-BOT-046", name: "boAt Deuce USB 300 2-in-1 Cable Mercurial Black", brand: "boAt", subBrand: "Deuce", category: "electronics", subCategory: "cables", variant: "Mercurial Black", description: "Micro USB + Type-C 2-in-1 cable with 3A fast charging.", price: 349, originalPrice: 999, discount: 65, image: "/assets/products/IN-EL-BOT-046.jpg", affiliateUrl: "/go/IN-EL-BOT-046", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.0, reviewCount: 85000, tags: ["cable", "boat", "type-c", "micro-usb", "fast-charge"], apiSource: "static-only" },
  { id: "IN-EL-BOT-047", name: "boAt Type-C A400 Cable Mercurial Black 1.5m", brand: "boAt", subBrand: "Deuce", category: "electronics", subCategory: "cables", variant: "Mercurial Black 1.5m", description: "480Mbps data transfer with 3A rapid charge.", price: 299, originalPrice: 799, discount: 62, image: "/assets/products/IN-EL-BOT-047.jpg", affiliateUrl: "/go/IN-EL-BOT-047", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.1, reviewCount: 120000, tags: ["cable", "boat", "type-c", "fast-charge"], apiSource: "static-only" },
  { id: "IN-EL-BOT-048", name: "boAt WCDL 20W USB-C PD Charger White", brand: "boAt", subBrand: "WCDL", category: "electronics", subCategory: "cables", variant: "White", description: "20W Power Delivery charger for iPhone and Android.", price: 699, originalPrice: 1499, discount: 53, image: "/assets/products/IN-EL-BOT-048.jpg", affiliateUrl: "/go/IN-EL-BOT-048", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.2, reviewCount: 42000, tags: ["charger", "boat", "usb-c", "pd", "20w"], apiSource: "static-only" },
  { id: "IN-EL-BOT-049", name: "boAt WCDL 65W GaN Charger Dual Port Black", brand: "boAt", subBrand: "WCDL", category: "electronics", subCategory: "cables", variant: "Black", description: "GaN technology with dual USB-C ports for laptop + phone.", price: 1999, originalPrice: 3990, discount: 49, image: "/assets/products/IN-EL-BOT-049.jpg", affiliateUrl: "/go/IN-EL-BOT-049", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 18000, tags: ["charger", "boat", "gan", "65w", "dual-port"], apiSource: "static-only" },
  { id: "IN-EL-BOT-050", name: "boAt Micro USB 500 Cable White 1.5m", brand: "boAt", subBrand: "Deuce", category: "electronics", subCategory: "cables", variant: "White 1.5m", description: "Tangle-free flat cable with durable strain relief.", price: 199, originalPrice: 599, discount: 66, image: "/assets/products/IN-EL-BOT-050.jpg", affiliateUrl: "/go/IN-EL-BOT-050", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 3.9, reviewCount: 95000, tags: ["cable", "boat", "micro-usb"], apiSource: "static-only" },
]

// ===================================================================
// Noise — 50 products (IN-EL-NOI-001 to IN-EL-NOI-050)
// Sub-categories: smartwatches, earbuds, headphones
// ===================================================================
export const NOISE_PRODUCTS: IndiaProduct[] = [
  // SMARTWATCHES (001–025)
  { id: "IN-EL-NOI-001", name: "Noise ColorFit Pulse 2 Max Smartwatch Jet Black", brand: "Noise", subBrand: "ColorFit", category: "electronics", subCategory: "smartwatches", variant: "Jet Black", description: "1.85-inch TFT display with BT calling and 100 sports modes.", price: 1799, originalPrice: 4999, discount: 64, image: "/assets/products/IN-EL-NOI-001.jpg", affiliateUrl: "/go/IN-EL-NOI-001", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.1, reviewCount: 78000, tags: ["smartwatch", "noise", "colorfit", "bluetooth-calling"], apiSource: "static-only" },
  { id: "IN-EL-NOI-002", name: "Noise ColorFit Pulse 2 Max Smartwatch Rose Pink", brand: "Noise", subBrand: "ColorFit", category: "electronics", subCategory: "smartwatches", variant: "Rose Pink", description: "AI voice assistant with smart notifications.", price: 1799, originalPrice: 4999, discount: 64, image: "/assets/products/IN-EL-NOI-002.jpg", affiliateUrl: "/go/IN-EL-NOI-002", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.1, reviewCount: 78000, tags: ["smartwatch", "noise", "colorfit", "bluetooth-calling"], apiSource: "static-only" },
  { id: "IN-EL-NOI-003", name: "Noise ColorFit Pulse 3 Smartwatch Jet Black", brand: "Noise", subBrand: "ColorFit", category: "electronics", subCategory: "smartwatches", variant: "Jet Black", description: "1.96-inch AMOLED display with always-on mode.", price: 2499, originalPrice: 5999, discount: 58, image: "/assets/products/IN-EL-NOI-003.jpg", affiliateUrl: "/go/IN-EL-NOI-003", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.2, reviewCount: 52000, tags: ["smartwatch", "noise", "colorfit", "amoled"], apiSource: "static-only" },
  { id: "IN-EL-NOI-004", name: "Noise ColorFit Pulse 3 Smartwatch Silver Grey", brand: "Noise", subBrand: "ColorFit", category: "electronics", subCategory: "smartwatches", variant: "Silver Grey", description: "Noise Health Suite with SpO2, HR, and stress tracking.", price: 2499, originalPrice: 5999, discount: 58, image: "/assets/products/IN-EL-NOI-004.jpg", affiliateUrl: "/go/IN-EL-NOI-004", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.2, reviewCount: 52000, tags: ["smartwatch", "noise", "colorfit", "amoled"], apiSource: "static-only" },
  { id: "IN-EL-NOI-005", name: "Noise ColorFit Pro 5 Smartwatch Jet Black", brand: "Noise", subBrand: "ColorFit", category: "electronics", subCategory: "smartwatches", variant: "Jet Black", description: "1.85-inch AMOLED with SOS alert and rapid health check.", price: 3999, originalPrice: 7999, discount: 50, image: "/assets/products/IN-EL-NOI-005.jpg", affiliateUrl: "/go/IN-EL-NOI-005", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 35000, tags: ["smartwatch", "noise", "colorfit-pro", "amoled", "premium"], apiSource: "static-only" },
  { id: "IN-EL-NOI-006", name: "Noise ColorFit Pro 5 Smartwatch Vintage Brown", brand: "Noise", subBrand: "ColorFit", category: "electronics", subCategory: "smartwatches", variant: "Vintage Brown", description: "Premium stainless steel body with leather strap.", price: 4499, originalPrice: 8999, discount: 50, image: "/assets/products/IN-EL-NOI-006.jpg", affiliateUrl: "/go/IN-EL-NOI-006", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 35000, tags: ["smartwatch", "noise", "colorfit-pro", "amoled", "premium"], apiSource: "static-only" },
  { id: "IN-EL-NOI-007", name: "Noise ColorFit Pro 5 Max Smartwatch Midnight Black", brand: "Noise", subBrand: "ColorFit", category: "electronics", subCategory: "smartwatches", variant: "Midnight Black", description: "1.96-inch AMOLED with built-in GPS and BT calling.", price: 5499, originalPrice: 9999, discount: 45, image: "/assets/products/IN-EL-NOI-007.jpg", affiliateUrl: "/go/IN-EL-NOI-007", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.4, reviewCount: 22000, tags: ["smartwatch", "noise", "colorfit-pro", "gps", "amoled", "premium"], apiSource: "static-only" },
  { id: "IN-EL-NOI-008", name: "Noise ColorFit Pro 5 Max Smartwatch Rose Gold", brand: "Noise", subBrand: "ColorFit", category: "electronics", subCategory: "smartwatches", variant: "Rose Gold", description: "Premium metal body with interchangeable straps.", price: 5499, originalPrice: 9999, discount: 45, image: "/assets/products/IN-EL-NOI-008.jpg", affiliateUrl: "/go/IN-EL-NOI-008", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.4, reviewCount: 22000, tags: ["smartwatch", "noise", "colorfit-pro", "gps", "amoled", "premium"], apiSource: "static-only" },
  { id: "IN-EL-NOI-009", name: "Noise NoiseFit Halo Smartwatch Classic Black", brand: "Noise", subBrand: "NoiseFit", category: "electronics", subCategory: "smartwatches", variant: "Classic Black", description: "1.43-inch round AMOLED with metallic build.", price: 3499, originalPrice: 6999, discount: 50, image: "/assets/products/IN-EL-NOI-009.jpg", affiliateUrl: "/go/IN-EL-NOI-009", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 28000, tags: ["smartwatch", "noise", "noisefit", "amoled", "round"], apiSource: "static-only" },
  { id: "IN-EL-NOI-010", name: "Noise NoiseFit Halo Smartwatch Silver Chain", brand: "Noise", subBrand: "NoiseFit", category: "electronics", subCategory: "smartwatches", variant: "Silver Chain", description: "Premium chain strap with rotating crown navigation.", price: 3999, originalPrice: 7999, discount: 50, image: "/assets/products/IN-EL-NOI-010.jpg", affiliateUrl: "/go/IN-EL-NOI-010", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 28000, tags: ["smartwatch", "noise", "noisefit", "amoled", "round", "premium"], apiSource: "static-only" },
  { id: "IN-EL-NOI-011", name: "Noise NoiseFit Evolve 4 Smartwatch Midnight Black", brand: "Noise", subBrand: "NoiseFit", category: "electronics", subCategory: "smartwatches", variant: "Midnight Black", description: "AMOLED always-on display with BT calling and GPS.", price: 6499, originalPrice: 12999, discount: 50, image: "/assets/products/IN-EL-NOI-011.jpg", affiliateUrl: "/go/IN-EL-NOI-011", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.5, reviewCount: 12000, tags: ["smartwatch", "noise", "noisefit", "evolve", "gps", "premium"], apiSource: "static-only" },
  { id: "IN-EL-NOI-012", name: "Noise NoiseFit Evolve 4 Smartwatch Space Grey", brand: "Noise", subBrand: "NoiseFit", category: "electronics", subCategory: "smartwatches", variant: "Space Grey", description: "Stainless steel case with sapphire crystal glass.", price: 6499, originalPrice: 12999, discount: 50, image: "/assets/products/IN-EL-NOI-012.jpg", affiliateUrl: "/go/IN-EL-NOI-012", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.5, reviewCount: 12000, tags: ["smartwatch", "noise", "noisefit", "evolve", "gps", "premium"], apiSource: "static-only" },
  { id: "IN-EL-NOI-013", name: "Noise ColorFit Icon 3 Smartwatch Jet Black", brand: "Noise", subBrand: "ColorFit", category: "electronics", subCategory: "smartwatches", variant: "Jet Black", description: "1.83-inch display with Tru Sync BT calling.", price: 1999, originalPrice: 4999, discount: 60, image: "/assets/products/IN-EL-NOI-013.jpg", affiliateUrl: "/go/IN-EL-NOI-013", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.0, reviewCount: 65000, tags: ["smartwatch", "noise", "colorfit", "icon", "bluetooth-calling"], apiSource: "static-only" },
  { id: "IN-EL-NOI-014", name: "Noise ColorFit Icon 3 Smartwatch Midnight Blue", brand: "Noise", subBrand: "ColorFit", category: "electronics", subCategory: "smartwatches", variant: "Midnight Blue", description: "IP68 dust and water resistance with 7-day battery.", price: 1999, originalPrice: 4999, discount: 60, image: "/assets/products/IN-EL-NOI-014.jpg", affiliateUrl: "/go/IN-EL-NOI-014", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.0, reviewCount: 65000, tags: ["smartwatch", "noise", "colorfit", "icon", "bluetooth-calling"], apiSource: "static-only" },
  { id: "IN-EL-NOI-015", name: "Noise Vortex Plus Smartwatch Classic Black", brand: "Noise", subBrand: "Vortex", category: "electronics", subCategory: "smartwatches", variant: "Classic Black", description: "1.46-inch AMOLED with metallic finish and rotating crown.", price: 2999, originalPrice: 5999, discount: 50, image: "/assets/products/IN-EL-NOI-015.jpg", affiliateUrl: "/go/IN-EL-NOI-015", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.2, reviewCount: 34000, tags: ["smartwatch", "noise", "vortex", "amoled", "round"], apiSource: "static-only" },
  { id: "IN-EL-NOI-016", name: "Noise Vortex Plus Smartwatch Rose Gold", brand: "Noise", subBrand: "Vortex", category: "electronics", subCategory: "smartwatches", variant: "Rose Gold", description: "Female health tracking with cycle and stress monitor.", price: 2999, originalPrice: 5999, discount: 50, image: "/assets/products/IN-EL-NOI-016.jpg", affiliateUrl: "/go/IN-EL-NOI-016", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.2, reviewCount: 34000, tags: ["smartwatch", "noise", "vortex", "amoled", "round"], apiSource: "static-only" },
  { id: "IN-EL-NOI-017", name: "Noise NoiseFit Force Rugged Smartwatch Camo Green", brand: "Noise", subBrand: "NoiseFit", category: "electronics", subCategory: "smartwatches", variant: "Camo Green", description: "Rugged MIL-STD-810H build with 1.32-inch round display.", price: 3499, originalPrice: 6999, discount: 50, image: "/assets/products/IN-EL-NOI-017.jpg", affiliateUrl: "/go/IN-EL-NOI-017", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 18000, tags: ["smartwatch", "noise", "noisefit", "rugged", "outdoor"], apiSource: "static-only" },
  { id: "IN-EL-NOI-018", name: "Noise NoiseFit Force Rugged Smartwatch Desert Sand", brand: "Noise", subBrand: "NoiseFit", category: "electronics", subCategory: "smartwatches", variant: "Desert Sand", description: "Built-in compass, altimeter, and barometer for outdoor use.", price: 3499, originalPrice: 6999, discount: 50, image: "/assets/products/IN-EL-NOI-018.jpg", affiliateUrl: "/go/IN-EL-NOI-018", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 18000, tags: ["smartwatch", "noise", "noisefit", "rugged", "outdoor"], apiSource: "static-only" },
  { id: "IN-EL-NOI-019", name: "Noise ColorFit Ultra 3 Smartwatch Classic Black", brand: "Noise", subBrand: "ColorFit", category: "electronics", subCategory: "smartwatches", variant: "Classic Black", description: "1.96-inch AMOLED with 60Hz refresh rate and BT calling.", price: 4499, originalPrice: 8999, discount: 50, image: "/assets/products/IN-EL-NOI-019.jpg", affiliateUrl: "/go/IN-EL-NOI-019", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.4, reviewCount: 25000, tags: ["smartwatch", "noise", "colorfit", "ultra", "amoled", "premium"], apiSource: "static-only" },
  { id: "IN-EL-NOI-020", name: "Noise ColorFit Ultra 3 Smartwatch Silver Grey", brand: "Noise", subBrand: "ColorFit", category: "electronics", subCategory: "smartwatches", variant: "Silver Grey", description: "Stainless steel build with smart gesture controls.", price: 4499, originalPrice: 8999, discount: 50, image: "/assets/products/IN-EL-NOI-020.jpg", affiliateUrl: "/go/IN-EL-NOI-020", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.4, reviewCount: 25000, tags: ["smartwatch", "noise", "colorfit", "ultra", "amoled", "premium"], apiSource: "static-only" },
  { id: "IN-EL-NOI-021", name: "Noise ColorFit Caliber 2 Smartwatch Jet Black", brand: "Noise", subBrand: "ColorFit", category: "electronics", subCategory: "smartwatches", variant: "Jet Black", description: "1.69-inch display with single-chip BT calling.", price: 1499, originalPrice: 3999, discount: 62, image: "/assets/products/IN-EL-NOI-021.jpg", affiliateUrl: "/go/IN-EL-NOI-021", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 3.9, reviewCount: 95000, tags: ["smartwatch", "noise", "colorfit", "budget", "bluetooth-calling"], apiSource: "static-only" },
  { id: "IN-EL-NOI-022", name: "Noise ColorFit Caliber 2 Smartwatch Olive Green", brand: "Noise", subBrand: "ColorFit", category: "electronics", subCategory: "smartwatches", variant: "Olive Green", description: "Noise Health Suite with 24/7 heart rate monitoring.", price: 1499, originalPrice: 3999, discount: 62, image: "/assets/products/IN-EL-NOI-022.jpg", affiliateUrl: "/go/IN-EL-NOI-022", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 3.9, reviewCount: 95000, tags: ["smartwatch", "noise", "colorfit", "budget", "bluetooth-calling"], apiSource: "static-only" },
  { id: "IN-EL-NOI-023", name: "Noise Twist Go Smartwatch Jet Black", brand: "Noise", subBrand: "Twist", category: "electronics", subCategory: "smartwatches", variant: "Jet Black", description: "Round dial with 1.39-inch TFT display and crown control.", price: 1999, originalPrice: 4999, discount: 60, image: "/assets/products/IN-EL-NOI-023.jpg", affiliateUrl: "/go/IN-EL-NOI-023", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.1, reviewCount: 42000, tags: ["smartwatch", "noise", "twist", "round", "bluetooth-calling"], apiSource: "static-only" },
  { id: "IN-EL-NOI-024", name: "Noise Twist Go Smartwatch Rose Gold", brand: "Noise", subBrand: "Twist", category: "electronics", subCategory: "smartwatches", variant: "Rose Gold", description: "Slim 10.8mm profile with metallic body.", price: 1999, originalPrice: 4999, discount: 60, image: "/assets/products/IN-EL-NOI-024.jpg", affiliateUrl: "/go/IN-EL-NOI-024", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.1, reviewCount: 42000, tags: ["smartwatch", "noise", "twist", "round", "bluetooth-calling"], apiSource: "static-only" },
  { id: "IN-EL-NOI-025", name: "Noise NoiseFit Origin Smartwatch Onyx Black", brand: "Noise", subBrand: "NoiseFit", category: "electronics", subCategory: "smartwatches", variant: "Onyx Black", description: "1.46-inch Super AMOLED with Nebula UI and BT calling.", price: 4999, originalPrice: 9999, discount: 50, image: "/assets/products/IN-EL-NOI-025.jpg", affiliateUrl: "/go/IN-EL-NOI-025", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.4, reviewCount: 16000, tags: ["smartwatch", "noise", "noisefit", "origin", "amoled", "premium"], apiSource: "static-only" },

  // EARBUDS (026–042)
  { id: "IN-EL-NOI-026", name: "Noise Buds VS104 TWS Earbuds Charcoal Black", brand: "Noise", subBrand: "Buds", category: "electronics", subCategory: "earbuds", variant: "Charcoal Black", description: "45H playtime with Hyper Sync and Instacharge.", price: 899, originalPrice: 2499, discount: 64, image: "/assets/products/IN-EL-NOI-026.jpg", affiliateUrl: "/go/IN-EL-NOI-026", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 3.9, reviewCount: 180000, tags: ["earbuds", "noise", "tws", "budget", "vs104"], apiSource: "static-only" },
  { id: "IN-EL-NOI-027", name: "Noise Buds VS104 TWS Earbuds Mint Green", brand: "Noise", subBrand: "Buds", category: "electronics", subCategory: "earbuds", variant: "Mint Green", description: "13mm drivers with Environmental Noise Cancellation.", price: 899, originalPrice: 2499, discount: 64, image: "/assets/products/IN-EL-NOI-027.jpg", affiliateUrl: "/go/IN-EL-NOI-027", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 3.9, reviewCount: 180000, tags: ["earbuds", "noise", "tws", "budget", "vs104"], apiSource: "static-only" },
  { id: "IN-EL-NOI-028", name: "Noise Buds VS303 TWS Earbuds Jet Black", brand: "Noise", subBrand: "Buds", category: "electronics", subCategory: "earbuds", variant: "Jet Black", description: "Tru Bass technology with 24H total playtime.", price: 1199, originalPrice: 2999, discount: 60, image: "/assets/products/IN-EL-NOI-028.jpg", affiliateUrl: "/go/IN-EL-NOI-028", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.0, reviewCount: 125000, tags: ["earbuds", "noise", "tws", "vs303"], apiSource: "static-only" },
  { id: "IN-EL-NOI-029", name: "Noise Buds VS303 TWS Earbuds Snow White", brand: "Noise", subBrand: "Buds", category: "electronics", subCategory: "earbuds", variant: "Snow White", description: "Bluetooth 5.3 with low-latency gaming mode.", price: 1199, originalPrice: 2999, discount: 60, image: "/assets/products/IN-EL-NOI-029.jpg", affiliateUrl: "/go/IN-EL-NOI-029", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.0, reviewCount: 125000, tags: ["earbuds", "noise", "tws", "vs303"], apiSource: "static-only" },
  { id: "IN-EL-NOI-030", name: "Noise Air Buds Pro 3 TWS Earbuds Pearl White", brand: "Noise", subBrand: "Air Buds", category: "electronics", subCategory: "earbuds", variant: "Pearl White", description: "Hybrid ANC up to 30dB with transparency mode.", price: 2499, originalPrice: 5999, discount: 58, image: "/assets/products/IN-EL-NOI-030.jpg", affiliateUrl: "/go/IN-EL-NOI-030", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.2, reviewCount: 45000, tags: ["earbuds", "noise", "tws", "anc", "air-buds-pro"], apiSource: "static-only" },
  { id: "IN-EL-NOI-031", name: "Noise Air Buds Pro 3 TWS Earbuds Charcoal Black", brand: "Noise", subBrand: "Air Buds", category: "electronics", subCategory: "earbuds", variant: "Charcoal Black", description: "11mm titanium drivers with 50H total playtime.", price: 2499, originalPrice: 5999, discount: 58, image: "/assets/products/IN-EL-NOI-031.jpg", affiliateUrl: "/go/IN-EL-NOI-031", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.2, reviewCount: 45000, tags: ["earbuds", "noise", "tws", "anc", "air-buds-pro"], apiSource: "static-only" },
  { id: "IN-EL-NOI-032", name: "Noise Buds N1 TWS Earbuds Jet Black", brand: "Noise", subBrand: "Buds", category: "electronics", subCategory: "earbuds", variant: "Jet Black", description: "40H playtime with quad mic ENC for clear calls.", price: 1499, originalPrice: 3499, discount: 57, image: "/assets/products/IN-EL-NOI-032.jpg", affiliateUrl: "/go/IN-EL-NOI-032", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.1, reviewCount: 82000, tags: ["earbuds", "noise", "tws", "buds-n1"], apiSource: "static-only" },
  { id: "IN-EL-NOI-033", name: "Noise Buds N1 TWS Earbuds Space Blue", brand: "Noise", subBrand: "Buds", category: "electronics", subCategory: "earbuds", variant: "Space Blue", description: "Instacharge — 10 min charge gives 3H playtime.", price: 1499, originalPrice: 3499, discount: 57, image: "/assets/products/IN-EL-NOI-033.jpg", affiliateUrl: "/go/IN-EL-NOI-033", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.1, reviewCount: 82000, tags: ["earbuds", "noise", "tws", "buds-n1"], apiSource: "static-only" },
  { id: "IN-EL-NOI-034", name: "Noise Buds Xero TWS Earbuds Charcoal Black", brand: "Noise", subBrand: "Buds", category: "electronics", subCategory: "earbuds", variant: "Charcoal Black", description: "Open-ear design with 11mm dynamic drivers.", price: 1999, originalPrice: 3999, discount: 50, image: "/assets/products/IN-EL-NOI-034.jpg", affiliateUrl: "/go/IN-EL-NOI-034", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.0, reviewCount: 32000, tags: ["earbuds", "noise", "tws", "open-ear", "buds-xero"], apiSource: "static-only" },
  { id: "IN-EL-NOI-035", name: "Noise Buds Xero TWS Earbuds Snow White", brand: "Noise", subBrand: "Buds", category: "electronics", subCategory: "earbuds", variant: "Snow White", description: "IPX5 water resistance for workout sessions.", price: 1999, originalPrice: 3999, discount: 50, image: "/assets/products/IN-EL-NOI-035.jpg", affiliateUrl: "/go/IN-EL-NOI-035", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.0, reviewCount: 32000, tags: ["earbuds", "noise", "tws", "open-ear", "buds-xero"], apiSource: "static-only" },
  { id: "IN-EL-NOI-036", name: "Noise NoiseFit Buds Connect TWS Earbuds Chrome Black", brand: "Noise", subBrand: "NoiseFit", category: "electronics", subCategory: "earbuds", variant: "Chrome Black", description: "Premium metal alloy case with ANC and LHDC support.", price: 3999, originalPrice: 7999, discount: 50, image: "/assets/products/IN-EL-NOI-036.jpg", affiliateUrl: "/go/IN-EL-NOI-036", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 15000, tags: ["earbuds", "noise", "tws", "anc", "premium", "noisefit"], apiSource: "static-only" },
  { id: "IN-EL-NOI-037", name: "Noise NoiseFit Buds Connect TWS Earbuds Chrome Silver", brand: "Noise", subBrand: "NoiseFit", category: "electronics", subCategory: "earbuds", variant: "Chrome Silver", description: "Adaptive ANC with 6 microphones for wind noise reduction.", price: 3999, originalPrice: 7999, discount: 50, image: "/assets/products/IN-EL-NOI-037.jpg", affiliateUrl: "/go/IN-EL-NOI-037", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 15000, tags: ["earbuds", "noise", "tws", "anc", "premium", "noisefit"], apiSource: "static-only" },
  { id: "IN-EL-NOI-038", name: "Noise Buds VS106 TWS Earbuds Jet Black", brand: "Noise", subBrand: "Buds", category: "electronics", subCategory: "earbuds", variant: "Jet Black", description: "50H playtime with Hyper Sync and touch controls.", price: 1099, originalPrice: 2499, discount: 56, image: "/assets/products/IN-EL-NOI-038.jpg", affiliateUrl: "/go/IN-EL-NOI-038", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.0, reviewCount: 98000, tags: ["earbuds", "noise", "tws", "budget", "vs106"], apiSource: "static-only" },
  { id: "IN-EL-NOI-039", name: "Noise Buds VS106 TWS Earbuds Celeste Blue", brand: "Noise", subBrand: "Buds", category: "electronics", subCategory: "earbuds", variant: "Celeste Blue", description: "13mm drivers with deep bass and clear treble.", price: 1099, originalPrice: 2499, discount: 56, image: "/assets/products/IN-EL-NOI-039.jpg", affiliateUrl: "/go/IN-EL-NOI-039", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.0, reviewCount: 98000, tags: ["earbuds", "noise", "tws", "budget", "vs106"], apiSource: "static-only" },
  { id: "IN-EL-NOI-040", name: "Noise Air Buds 2 TWS Earbuds Pearl White", brand: "Noise", subBrand: "Air Buds", category: "electronics", subCategory: "earbuds", variant: "Pearl White", description: "Semi-in-ear design with 13mm drivers for natural sound.", price: 1799, originalPrice: 3999, discount: 55, image: "/assets/products/IN-EL-NOI-040.jpg", affiliateUrl: "/go/IN-EL-NOI-040", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.1, reviewCount: 55000, tags: ["earbuds", "noise", "tws", "semi-in-ear", "air-buds"], apiSource: "static-only" },
  { id: "IN-EL-NOI-041", name: "Noise Air Buds 2 TWS Earbuds Charcoal Black", brand: "Noise", subBrand: "Air Buds", category: "electronics", subCategory: "earbuds", variant: "Charcoal Black", description: "Slide-to-pair case with 32H total playtime.", price: 1799, originalPrice: 3999, discount: 55, image: "/assets/products/IN-EL-NOI-041.jpg", affiliateUrl: "/go/IN-EL-NOI-041", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.1, reviewCount: 55000, tags: ["earbuds", "noise", "tws", "semi-in-ear", "air-buds"], apiSource: "static-only" },
  { id: "IN-EL-NOI-042", name: "Noise Buds VS205 TWS Earbuds Thunder Blue", brand: "Noise", subBrand: "Buds", category: "electronics", subCategory: "earbuds", variant: "Thunder Blue", description: "Tru Bass with 35H playtime and Instacharge.", price: 1299, originalPrice: 2999, discount: 56, image: "/assets/products/IN-EL-NOI-042.jpg", affiliateUrl: "/go/IN-EL-NOI-042", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.0, reviewCount: 72000, tags: ["earbuds", "noise", "tws", "vs205"], apiSource: "static-only" },

  // HEADPHONES (043–050)
  { id: "IN-EL-NOI-043", name: "Noise Two Bluetooth Headphones Jet Black", brand: "Noise", subBrand: "Two", category: "electronics", subCategory: "headphones", variant: "Jet Black", description: "40mm drivers with 50H playtime and BT 5.3.", price: 1499, originalPrice: 3999, discount: 62, image: "/assets/products/IN-EL-NOI-043.jpg", affiliateUrl: "/go/IN-EL-NOI-043", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.1, reviewCount: 65000, tags: ["headphones", "noise", "bluetooth", "two"], apiSource: "static-only" },
  { id: "IN-EL-NOI-044", name: "Noise Two Bluetooth Headphones Milky White", brand: "Noise", subBrand: "Two", category: "electronics", subCategory: "headphones", variant: "Milky White", description: "Foldable lightweight design with padded cushions.", price: 1499, originalPrice: 3999, discount: 62, image: "/assets/products/IN-EL-NOI-044.jpg", affiliateUrl: "/go/IN-EL-NOI-044", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.1, reviewCount: 65000, tags: ["headphones", "noise", "bluetooth", "two"], apiSource: "static-only" },
  { id: "IN-EL-NOI-045", name: "Noise Three ANC Bluetooth Headphones Space Black", brand: "Noise", subBrand: "Three", category: "electronics", subCategory: "headphones", variant: "Space Black", description: "Hybrid ANC with 40mm drivers and 70H playtime.", price: 2999, originalPrice: 5999, discount: 50, image: "/assets/products/IN-EL-NOI-045.jpg", affiliateUrl: "/go/IN-EL-NOI-045", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 28000, tags: ["headphones", "noise", "bluetooth", "anc", "three"], apiSource: "static-only" },
  { id: "IN-EL-NOI-046", name: "Noise Three ANC Bluetooth Headphones Silver Grey", brand: "Noise", subBrand: "Three", category: "electronics", subCategory: "headphones", variant: "Silver Grey", description: "Transparency mode and adaptive EQ via Noise app.", price: 2999, originalPrice: 5999, discount: 50, image: "/assets/products/IN-EL-NOI-046.jpg", affiliateUrl: "/go/IN-EL-NOI-046", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 28000, tags: ["headphones", "noise", "bluetooth", "anc", "three"], apiSource: "static-only" },
  { id: "IN-EL-NOI-047", name: "Noise NoiseFit Vibe Headphones Charcoal Black", brand: "Noise", subBrand: "NoiseFit", category: "electronics", subCategory: "headphones", variant: "Charcoal Black", description: "Premium ANC headphones with LDAC and spatial audio.", price: 4999, originalPrice: 9999, discount: 50, image: "/assets/products/IN-EL-NOI-047.jpg", affiliateUrl: "/go/IN-EL-NOI-047", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.4, reviewCount: 12000, tags: ["headphones", "noise", "bluetooth", "anc", "premium", "ldac"], apiSource: "static-only" },
  { id: "IN-EL-NOI-048", name: "Noise NoiseFit Vibe Headphones Ivory White", brand: "Noise", subBrand: "NoiseFit", category: "electronics", subCategory: "headphones", variant: "Ivory White", description: "40mm bio-cellulose drivers with Hi-Res audio certification.", price: 4999, originalPrice: 9999, discount: 50, image: "/assets/products/IN-EL-NOI-048.jpg", affiliateUrl: "/go/IN-EL-NOI-048", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.4, reviewCount: 12000, tags: ["headphones", "noise", "bluetooth", "anc", "premium", "ldac"], apiSource: "static-only" },
  { id: "IN-EL-NOI-049", name: "Noise Flair Neckband Earphones Jet Black", brand: "Noise", subBrand: "Flair", category: "electronics", subCategory: "headphones", variant: "Jet Black", description: "Magnetic earbuds with 35H battery and quick charge.", price: 999, originalPrice: 2499, discount: 60, image: "/assets/products/IN-EL-NOI-049.jpg", affiliateUrl: "/go/IN-EL-NOI-049", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.0, reviewCount: 88000, tags: ["neckband", "noise", "bluetooth", "flair"], apiSource: "static-only" },
  { id: "IN-EL-NOI-050", name: "Noise Flair Neckband Earphones Teal Green", brand: "Noise", subBrand: "Flair", category: "electronics", subCategory: "headphones", variant: "Teal Green", description: "IPX5 water resistance with ENC for calls.", price: 999, originalPrice: 2499, discount: 60, image: "/assets/products/IN-EL-NOI-050.jpg", affiliateUrl: "/go/IN-EL-NOI-050", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.0, reviewCount: 88000, tags: ["neckband", "noise", "bluetooth", "flair"], apiSource: "static-only" },
]
