import { IndiaProduct } from "../types"

// ===================================================================
// realme — 50 products (IN-EL-RLM-001 to IN-EL-RLM-050)
// Sub-categories: smartphones, earbuds, smartwatches, tablets, smart-home
// ===================================================================
export const REALME_PRODUCTS: IndiaProduct[] = [
  // SMARTPHONES (001–010)
  { id: "IN-EL-RLM-001", name: "realme C67 5G 6GB+128GB Starry Black", brand: "realme", subBrand: "C67", category: "electronics", subCategory: "smartphones", variant: "Starry Black", description: "Dimensity 6100+ processor with 6GB RAM and 128GB storage for smooth 5G performance.", price: 11999, originalPrice: 14999, discount: 20, image: "/assets/products/IN-EL-RLM-001.jpg", affiliateUrl: "/go/IN-EL-RLM-001", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.1, reviewCount: 85000, tags: ["smartphone", "realme", "5g", "c67", "budget"], apiSource: "static-only" },
  { id: "IN-EL-RLM-002", name: "realme C67 5G 6GB+128GB Sunny Oasis", brand: "realme", subBrand: "C67", category: "electronics", subCategory: "smartphones", variant: "Sunny Oasis", description: "50MP AI camera with 5000mAh battery and 33W SUPERVOOC charge.", price: 11999, originalPrice: 14999, discount: 20, image: "/assets/products/IN-EL-RLM-002.jpg", affiliateUrl: "/go/IN-EL-RLM-002", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.1, reviewCount: 85000, tags: ["smartphone", "realme", "5g", "c67", "budget"], apiSource: "static-only" },
  { id: "IN-EL-RLM-003", name: "realme C67 5G 8GB+256GB Sky Blue", brand: "realme", subBrand: "C67", category: "electronics", subCategory: "smartphones", variant: "Sky Blue", description: "8GB RAM with dynamic expansion and 256GB UFS 2.2 storage.", price: 13999, originalPrice: 16999, discount: 17, image: "/assets/products/IN-EL-RLM-003.jpg", affiliateUrl: "/go/IN-EL-RLM-003", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.2, reviewCount: 72000, tags: ["smartphone", "realme", "5g", "c67", "mid-range"], apiSource: "static-only" },
  { id: "IN-EL-RLM-004", name: "realme C67 5G 8GB+256GB Underwater Black", brand: "realme", subBrand: "C67", category: "electronics", subCategory: "smartphones", variant: "Underwater Black", description: "6.72-inch FHD+ display with 90Hz refresh rate for fluid visuals.", price: 13999, originalPrice: 16999, discount: 17, image: "/assets/products/IN-EL-RLM-004.jpg", affiliateUrl: "/go/IN-EL-RLM-004", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.2, reviewCount: 72000, tags: ["smartphone", "realme", "5g", "c67", "mid-range"], apiSource: "static-only" },
  { id: "IN-EL-RLM-005", name: "realme C67 5G 8GB+256GB Dark Purple", brand: "realme", subBrand: "C67", category: "electronics", subCategory: "smartphones", variant: "Dark Purple", description: "Side-mounted fingerprint sensor with IP54 dust and water resistance.", price: 13999, originalPrice: 16999, discount: 17, image: "/assets/products/IN-EL-RLM-005.jpg", affiliateUrl: "/go/IN-EL-RLM-005", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.2, reviewCount: 72000, tags: ["smartphone", "realme", "5g", "c67", "mid-range"], apiSource: "static-only" },
  { id: "IN-EL-RLM-006", name: "realme Narzo 70 Pro 5G 8GB+128GB Glass Green", brand: "realme", subBrand: "Narzo", category: "electronics", subCategory: "smartphones", variant: "Glass Green", description: "MediaTek Dimensity 7050 with 120Hz AMOLED display and 67W charge.", price: 16999, originalPrice: 19999, discount: 15, image: "/assets/products/IN-EL-RLM-006.jpg", affiliateUrl: "/go/IN-EL-RLM-006", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 48000, tags: ["smartphone", "realme", "5g", "narzo", "amoled"], apiSource: "static-only" },
  { id: "IN-EL-RLM-007", name: "realme Narzo 70 Pro 5G 8GB+128GB Glass Gold", brand: "realme", subBrand: "Narzo", category: "electronics", subCategory: "smartphones", variant: "Glass Gold", description: "108MP ProLight camera with OIS for sharp photos in any light.", price: 16999, originalPrice: 19999, discount: 15, image: "/assets/products/IN-EL-RLM-007.jpg", affiliateUrl: "/go/IN-EL-RLM-007", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 48000, tags: ["smartphone", "realme", "5g", "narzo", "amoled"], apiSource: "static-only" },
  { id: "IN-EL-RLM-008", name: "realme Narzo 70 Pro 5G 8GB+128GB Glass Black", brand: "realme", subBrand: "Narzo", category: "electronics", subCategory: "smartphones", variant: "Glass Black", description: "5000mAh battery with 67W SUPERVOOC for 0-50% in 19 minutes.", price: 16999, originalPrice: 19999, discount: 15, image: "/assets/products/IN-EL-RLM-008.jpg", affiliateUrl: "/go/IN-EL-RLM-008", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 48000, tags: ["smartphone", "realme", "5g", "narzo", "amoled"], apiSource: "static-only" },
  { id: "IN-EL-RLM-009", name: "realme 12+ 5G 8GB+256GB Navigator Beige", brand: "realme", subBrand: "12+", category: "electronics", subCategory: "smartphones", variant: "Navigator Beige", description: "MediaTek Dimensity 7050 with 50MP Sony IMX890 OIS camera.", price: 21999, originalPrice: 24999, discount: 12, image: "/assets/products/IN-EL-RLM-009.jpg", affiliateUrl: "/go/IN-EL-RLM-009", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.4, reviewCount: 32000, tags: ["smartphone", "realme", "5g", "realme-12-plus", "premium"], apiSource: "static-only" },
  { id: "IN-EL-RLM-010", name: "realme 12+ 5G 8GB+256GB Pioneer Green", brand: "realme", subBrand: "12+", category: "electronics", subCategory: "smartphones", variant: "Pioneer Green", description: "6.67-inch curved AMOLED with 2160Hz PWM dimming and 120Hz refresh.", price: 21999, originalPrice: 24999, discount: 12, image: "/assets/products/IN-EL-RLM-010.jpg", affiliateUrl: "/go/IN-EL-RLM-010", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.4, reviewCount: 32000, tags: ["smartphone", "realme", "5g", "realme-12-plus", "premium"], apiSource: "static-only" },

  // TWS AND AUDIO (011–020)
  { id: "IN-EL-RLM-011", name: "realme Buds T300 TWS Starlight White", brand: "realme", subBrand: "Buds", category: "electronics", subCategory: "earbuds", variant: "Starlight White", description: "30dB active noise cancellation with 40H total playtime.", price: 1499, originalPrice: 2999, discount: 50, image: "/assets/products/IN-EL-RLM-011.jpg", affiliateUrl: "/go/IN-EL-RLM-011", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.2, reviewCount: 62000, tags: ["earbuds", "realme", "tws", "anc", "buds-t300"], apiSource: "static-only" },
  { id: "IN-EL-RLM-012", name: "realme Buds T300 TWS Dark Grey", brand: "realme", subBrand: "Buds", category: "electronics", subCategory: "earbuds", variant: "Dark Grey", description: "12.4mm dynamic bass driver with Hi-Res Audio certification.", price: 1499, originalPrice: 2999, discount: 50, image: "/assets/products/IN-EL-RLM-012.jpg", affiliateUrl: "/go/IN-EL-RLM-012", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.2, reviewCount: 62000, tags: ["earbuds", "realme", "tws", "anc", "buds-t300"], apiSource: "static-only" },
  { id: "IN-EL-RLM-013", name: "realme Buds Air 5 Pro TWS ANC Blue", brand: "realme", subBrand: "Buds Air", category: "electronics", subCategory: "earbuds", variant: "Blue", description: "50dB industry-leading ANC with LDAC Hi-Res audio codec.", price: 3499, originalPrice: 5999, discount: 41, image: "/assets/products/IN-EL-RLM-013.jpg", affiliateUrl: "/go/IN-EL-RLM-013", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.4, reviewCount: 38000, tags: ["earbuds", "realme", "tws", "anc", "premium", "buds-air-5-pro"], apiSource: "static-only" },
  { id: "IN-EL-RLM-014", name: "realme Buds Air 5 Pro TWS ANC Yellow", brand: "realme", subBrand: "Buds Air", category: "electronics", subCategory: "earbuds", variant: "Yellow", description: "Dual driver with 11mm woofer and 6mm tweeter for balanced sound.", price: 3499, originalPrice: 5999, discount: 41, image: "/assets/products/IN-EL-RLM-014.jpg", affiliateUrl: "/go/IN-EL-RLM-014", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.4, reviewCount: 38000, tags: ["earbuds", "realme", "tws", "anc", "premium", "buds-air-5-pro"], apiSource: "static-only" },
  { id: "IN-EL-RLM-015", name: "realme Buds Air 5 Pro TWS ANC Red", brand: "realme", subBrand: "Buds Air", category: "electronics", subCategory: "earbuds", variant: "Red", description: "360 Spatial Audio with head tracking for immersive experience.", price: 3499, originalPrice: 5999, discount: 41, image: "/assets/products/IN-EL-RLM-015.jpg", affiliateUrl: "/go/IN-EL-RLM-015", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.4, reviewCount: 38000, tags: ["earbuds", "realme", "tws", "anc", "premium", "buds-air-5-pro"], apiSource: "static-only" },
  { id: "IN-EL-RLM-016", name: "realme Buds T110 Neckband Dark Grey", brand: "realme", subBrand: "Buds", category: "electronics", subCategory: "earbuds", variant: "Dark Grey", description: "AI ENC for clear calls with 38H total playtime on single charge.", price: 799, originalPrice: 1499, discount: 46, image: "/assets/products/IN-EL-RLM-016.jpg", affiliateUrl: "/go/IN-EL-RLM-016", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.0, reviewCount: 95000, tags: ["neckband", "realme", "bluetooth", "budget", "buds-t110"], apiSource: "static-only" },
  { id: "IN-EL-RLM-017", name: "realme Buds T110 Neckband White", brand: "realme", subBrand: "Buds", category: "electronics", subCategory: "earbuds", variant: "White", description: "Magnetic fast-pair instant connection with 12.4mm bass boost driver.", price: 799, originalPrice: 1499, discount: 46, image: "/assets/products/IN-EL-RLM-017.jpg", affiliateUrl: "/go/IN-EL-RLM-017", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.0, reviewCount: 95000, tags: ["neckband", "realme", "bluetooth", "budget", "buds-t110"], apiSource: "static-only" },
  { id: "IN-EL-RLM-018", name: "realme Buds T110 Neckband Blue", brand: "realme", subBrand: "Buds", category: "electronics", subCategory: "earbuds", variant: "Blue", description: "IPX5 water resistance with flexible neckband for active lifestyle.", price: 799, originalPrice: 1499, discount: 46, image: "/assets/products/IN-EL-RLM-018.jpg", affiliateUrl: "/go/IN-EL-RLM-018", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.0, reviewCount: 95000, tags: ["neckband", "realme", "bluetooth", "budget", "buds-t110"], apiSource: "static-only" },
  { id: "IN-EL-RLM-019", name: "realme Buds Wireless 3 Neo Green", brand: "realme", subBrand: "Buds Wireless", category: "electronics", subCategory: "earbuds", variant: "Green", description: "13.6mm dynamic bass driver with 32H playback and fast charge.", price: 999, originalPrice: 1999, discount: 50, image: "/assets/products/IN-EL-RLM-019.jpg", affiliateUrl: "/go/IN-EL-RLM-019", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.1, reviewCount: 78000, tags: ["neckband", "realme", "bluetooth", "wireless", "buds-wireless-3"], apiSource: "static-only" },
  { id: "IN-EL-RLM-020", name: "realme Buds Wireless 3 Neo Red", brand: "realme", subBrand: "Buds Wireless", category: "electronics", subCategory: "earbuds", variant: "Red", description: "Dual device connection with Bluetooth 5.3 and low-latency gaming mode.", price: 999, originalPrice: 1999, discount: 50, image: "/assets/products/IN-EL-RLM-020.jpg", affiliateUrl: "/go/IN-EL-RLM-020", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.1, reviewCount: 78000, tags: ["neckband", "realme", "bluetooth", "wireless", "buds-wireless-3"], apiSource: "static-only" },

  // SMARTWATCHES (021–030)
  { id: "IN-EL-RLM-021", name: "realme Watch S2 Black", brand: "realme", subBrand: "Watch", category: "electronics", subCategory: "smartwatches", variant: "Black", description: "1.43-inch AMOLED display with always-on mode and 100+ sport modes.", price: 2999, originalPrice: 4999, discount: 40, image: "/assets/products/IN-EL-RLM-021.jpg", affiliateUrl: "/go/IN-EL-RLM-021", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.2, reviewCount: 42000, tags: ["smartwatch", "realme", "amoled", "fitness", "watch-s2"], apiSource: "static-only" },
  { id: "IN-EL-RLM-022", name: "realme Watch S2 Grey", brand: "realme", subBrand: "Watch", category: "electronics", subCategory: "smartwatches", variant: "Grey", description: "SpO2 and heart rate monitoring with Bluetooth calling support.", price: 2999, originalPrice: 4999, discount: 40, image: "/assets/products/IN-EL-RLM-022.jpg", affiliateUrl: "/go/IN-EL-RLM-022", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.2, reviewCount: 42000, tags: ["smartwatch", "realme", "amoled", "fitness", "watch-s2"], apiSource: "static-only" },
  { id: "IN-EL-RLM-023", name: "realme Watch S2 Blue", brand: "realme", subBrand: "Watch", category: "electronics", subCategory: "smartwatches", variant: "Blue", description: "IP68 water resistance with 14-day battery life on typical usage.", price: 2999, originalPrice: 4999, discount: 40, image: "/assets/products/IN-EL-RLM-023.jpg", affiliateUrl: "/go/IN-EL-RLM-023", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.2, reviewCount: 42000, tags: ["smartwatch", "realme", "amoled", "fitness", "watch-s2"], apiSource: "static-only" },
  { id: "IN-EL-RLM-024", name: "realme TechLife Watch SZ100 GPS Green", brand: "realme", subBrand: "TechLife", category: "electronics", subCategory: "smartwatches", variant: "Green", description: "Built-in GPS with 1.69-inch display and 24/7 health monitoring.", price: 3499, originalPrice: 5999, discount: 41, image: "/assets/products/IN-EL-RLM-024.jpg", affiliateUrl: "/go/IN-EL-RLM-024", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 28000, tags: ["smartwatch", "realme", "gps", "techlife", "fitness"], apiSource: "static-only" },
  { id: "IN-EL-RLM-025", name: "realme TechLife Watch SZ100 GPS Silver", brand: "realme", subBrand: "TechLife", category: "electronics", subCategory: "smartwatches", variant: "Silver", description: "5ATM water resistance with multi-satellite positioning system.", price: 3499, originalPrice: 5999, discount: 41, image: "/assets/products/IN-EL-RLM-025.jpg", affiliateUrl: "/go/IN-EL-RLM-025", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 28000, tags: ["smartwatch", "realme", "gps", "techlife", "fitness"], apiSource: "static-only" },
  { id: "IN-EL-RLM-026", name: "realme Band 2 Black", brand: "realme", subBrand: "Band", category: "electronics", subCategory: "smartwatches", variant: "Black", description: "1.4-inch large colour display with 90+ sport modes and SpO2.", price: 1499, originalPrice: 2499, discount: 40, image: "/assets/products/IN-EL-RLM-026.jpg", affiliateUrl: "/go/IN-EL-RLM-026", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 3.9, reviewCount: 110000, tags: ["fitness-band", "realme", "budget", "band-2", "health"], apiSource: "static-only" },
  { id: "IN-EL-RLM-027", name: "realme Band 2 Green", brand: "realme", subBrand: "Band", category: "electronics", subCategory: "smartwatches", variant: "Green", description: "Continuous heart rate monitoring with 12-day battery life.", price: 1499, originalPrice: 2499, discount: 40, image: "/assets/products/IN-EL-RLM-027.jpg", affiliateUrl: "/go/IN-EL-RLM-027", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 3.9, reviewCount: 110000, tags: ["fitness-band", "realme", "budget", "band-2", "health"], apiSource: "static-only" },
  { id: "IN-EL-RLM-028", name: "realme Band 2 Grey", brand: "realme", subBrand: "Band", category: "electronics", subCategory: "smartwatches", variant: "Grey", description: "IP68 rating with smart notifications and music playback control.", price: 1499, originalPrice: 2499, discount: 40, image: "/assets/products/IN-EL-RLM-028.jpg", affiliateUrl: "/go/IN-EL-RLM-028", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 3.9, reviewCount: 110000, tags: ["fitness-band", "realme", "budget", "band-2", "health"], apiSource: "static-only" },
  { id: "IN-EL-RLM-029", name: "realme Watch 3 Pro GPS Blue", brand: "realme", subBrand: "Watch", category: "electronics", subCategory: "smartwatches", variant: "Blue", description: "1.78-inch AMOLED with dual-satellite GPS and Bluetooth calling.", price: 3999, originalPrice: 6999, discount: 42, image: "/assets/products/IN-EL-RLM-029.jpg", affiliateUrl: "/go/IN-EL-RLM-029", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.1, reviewCount: 35000, tags: ["smartwatch", "realme", "gps", "amoled", "watch-3-pro"], apiSource: "static-only" },
  { id: "IN-EL-RLM-030", name: "realme Watch 3 Pro GPS Silver", brand: "realme", subBrand: "Watch", category: "electronics", subCategory: "smartwatches", variant: "Silver", description: "AI health engine with stress, sleep, and women's health tracking.", price: 3999, originalPrice: 6999, discount: 42, image: "/assets/products/IN-EL-RLM-030.jpg", affiliateUrl: "/go/IN-EL-RLM-030", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.1, reviewCount: 35000, tags: ["smartwatch", "realme", "gps", "amoled", "watch-3-pro"], apiSource: "static-only" },

  // TABLETS AND ACCESSORIES (031–040)
  { id: "IN-EL-RLM-031", name: "realme Pad 2 WiFi 6GB+128GB Imagination Grey", brand: "realme", subBrand: "Pad", category: "electronics", subCategory: "tablets", variant: "Imagination Grey", description: "11.5-inch 2K display with MediaTek Helio G99 and quad speakers.", price: 17999, originalPrice: 21999, discount: 18, image: "/assets/products/IN-EL-RLM-031.jpg", affiliateUrl: "/go/IN-EL-RLM-031", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 18000, tags: ["tablet", "realme", "pad-2", "2k-display", "entertainment"], apiSource: "static-only" },
  { id: "IN-EL-RLM-032", name: "realme Pad 2 WiFi 6GB+128GB Inspiration Green", brand: "realme", subBrand: "Pad", category: "electronics", subCategory: "tablets", variant: "Inspiration Green", description: "8360mAh battery with 33W SUPERVOOC for all-day productivity.", price: 17999, originalPrice: 21999, discount: 18, image: "/assets/products/IN-EL-RLM-032.jpg", affiliateUrl: "/go/IN-EL-RLM-032", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 18000, tags: ["tablet", "realme", "pad-2", "2k-display", "entertainment"], apiSource: "static-only" },
  { id: "IN-EL-RLM-033", name: "realme Pad 2 WiFi 6GB+128GB Paper Green", brand: "realme", subBrand: "Pad", category: "electronics", subCategory: "tablets", variant: "Paper Green", description: "Dolby Atmos quad speakers with eye-care certification for reading.", price: 17999, originalPrice: 21999, discount: 18, image: "/assets/products/IN-EL-RLM-033.jpg", affiliateUrl: "/go/IN-EL-RLM-033", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 18000, tags: ["tablet", "realme", "pad-2", "2k-display", "entertainment"], apiSource: "static-only" },
  { id: "IN-EL-RLM-034", name: "realme Pad Mini WiFi 4GB+64GB Blue", brand: "realme", subBrand: "Pad Mini", category: "electronics", subCategory: "tablets", variant: "Blue", description: "8.7-inch compact display with Unisoc T616 and 6400mAh battery.", price: 10999, originalPrice: 13999, discount: 21, image: "/assets/products/IN-EL-RLM-034.jpg", affiliateUrl: "/go/IN-EL-RLM-034", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.0, reviewCount: 32000, tags: ["tablet", "realme", "pad-mini", "compact", "budget"], apiSource: "static-only" },
  { id: "IN-EL-RLM-035", name: "realme Pad Mini WiFi 4GB+64GB Grey", brand: "realme", subBrand: "Pad Mini", category: "electronics", subCategory: "tablets", variant: "Grey", description: "Lightweight 372g design with stereo speakers and kids mode.", price: 10999, originalPrice: 13999, discount: 21, image: "/assets/products/IN-EL-RLM-035.jpg", affiliateUrl: "/go/IN-EL-RLM-035", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.0, reviewCount: 32000, tags: ["tablet", "realme", "pad-mini", "compact", "budget"], apiSource: "static-only" },
  { id: "IN-EL-RLM-036", name: "realme Pad X WiFi 6GB+128GB Glacier Blue", brand: "realme", subBrand: "Pad X", category: "electronics", subCategory: "tablets", variant: "Glacier Blue", description: "11-inch 2K display with Snapdragon 695 and stylus support.", price: 19999, originalPrice: 24999, discount: 20, image: "/assets/products/IN-EL-RLM-036.jpg", affiliateUrl: "/go/IN-EL-RLM-036", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.2, reviewCount: 15000, tags: ["tablet", "realme", "pad-x", "2k-display", "stylus"], apiSource: "static-only" },
  { id: "IN-EL-RLM-037", name: "realme Pad X WiFi 6GB+128GB Glacier Grey", brand: "realme", subBrand: "Pad X", category: "electronics", subCategory: "tablets", variant: "Glacier Grey", description: "Quad speakers with Dolby Atmos and 8340mAh long-lasting battery.", price: 19999, originalPrice: 24999, discount: 20, image: "/assets/products/IN-EL-RLM-037.jpg", affiliateUrl: "/go/IN-EL-RLM-037", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.2, reviewCount: 15000, tags: ["tablet", "realme", "pad-x", "2k-display", "stylus"], apiSource: "static-only" },
  { id: "IN-EL-RLM-038", name: "realme Pad X WiFi 6GB+128GB Glacier Green", brand: "realme", subBrand: "Pad X", category: "electronics", subCategory: "tablets", variant: "Glacier Green", description: "13MP rear camera with 105-degree wide front camera for video calls.", price: 19999, originalPrice: 24999, discount: 20, image: "/assets/products/IN-EL-RLM-038.jpg", affiliateUrl: "/go/IN-EL-RLM-038", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.2, reviewCount: 15000, tags: ["tablet", "realme", "pad-x", "2k-display", "stylus"], apiSource: "static-only" },
  { id: "IN-EL-RLM-039", name: "realme 45W Dart Charge Adapter White", brand: "realme", subBrand: "Accessories", category: "electronics", subCategory: "tablets", variant: "White", description: "45W SUPERVOOC fast charger compatible with realme phones and tablets.", price: 999, originalPrice: 1499, discount: 33, image: "/assets/products/IN-EL-RLM-039.jpg", affiliateUrl: "/go/IN-EL-RLM-039", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.5, reviewCount: 55000, tags: ["charger", "realme", "supervooc", "45w", "fast-charge"], apiSource: "static-only" },
  { id: "IN-EL-RLM-040", name: "realme 45W Dart Charge Adapter Black", brand: "realme", subBrand: "Accessories", category: "electronics", subCategory: "tablets", variant: "Black", description: "Type-C output with intelligent power management and BIS certified.", price: 999, originalPrice: 1499, discount: 33, image: "/assets/products/IN-EL-RLM-040.jpg", affiliateUrl: "/go/IN-EL-RLM-040", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.5, reviewCount: 55000, tags: ["charger", "realme", "supervooc", "45w", "fast-charge"], apiSource: "static-only" },

  // SMART HOME (041–050)
  { id: "IN-EL-RLM-041", name: "realme TechLife Smart Plug 16A White", brand: "realme", subBrand: "TechLife", category: "electronics", subCategory: "smart-home", variant: "White", description: "16A high-power smart plug with energy monitoring and voice control.", price: 599, originalPrice: 999, discount: 40, image: "/assets/products/IN-EL-RLM-041.jpg", affiliateUrl: "/go/IN-EL-RLM-041", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.0, reviewCount: 22000, tags: ["smart-plug", "realme", "techlife", "iot", "alexa"], apiSource: "static-only" },
  { id: "IN-EL-RLM-042", name: "realme TechLife Smart Plug 16A Black", brand: "realme", subBrand: "TechLife", category: "electronics", subCategory: "smart-home", variant: "Black", description: "Works with Google Home and Alexa with timer and scheduling.", price: 599, originalPrice: 999, discount: 40, image: "/assets/products/IN-EL-RLM-042.jpg", affiliateUrl: "/go/IN-EL-RLM-042", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.0, reviewCount: 22000, tags: ["smart-plug", "realme", "techlife", "iot", "google-home"], apiSource: "static-only" },
  { id: "IN-EL-RLM-043", name: "realme TechLife Smart Bulb 9W Warm White", brand: "realme", subBrand: "TechLife", category: "electronics", subCategory: "smart-home", variant: "Warm White", description: "9W smart LED bulb with Wi-Fi control and 16 million colour options.", price: 699, originalPrice: 1299, discount: 46, image: "/assets/products/IN-EL-RLM-043.jpg", affiliateUrl: "/go/IN-EL-RLM-043", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 3.8, reviewCount: 45000, tags: ["smart-bulb", "realme", "techlife", "iot", "wifi"], apiSource: "static-only" },
  { id: "IN-EL-RLM-044", name: "realme TechLife Smart Bulb 9W Cool White", brand: "realme", subBrand: "TechLife", category: "electronics", subCategory: "smart-home", variant: "Cool White", description: "Dimmable brightness with scene mode and music sync feature.", price: 699, originalPrice: 1299, discount: 46, image: "/assets/products/IN-EL-RLM-044.jpg", affiliateUrl: "/go/IN-EL-RLM-044", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 3.8, reviewCount: 45000, tags: ["smart-bulb", "realme", "techlife", "iot", "wifi"], apiSource: "static-only" },
  { id: "IN-EL-RLM-045", name: "realme TechLife Smart Bulb 9W RGB", brand: "realme", subBrand: "TechLife", category: "electronics", subCategory: "smart-home", variant: "RGB", description: "Voice control with Alexa and Google Assistant for hands-free operation.", price: 699, originalPrice: 1299, discount: 46, image: "/assets/products/IN-EL-RLM-045.jpg", affiliateUrl: "/go/IN-EL-RLM-045", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 3.8, reviewCount: 45000, tags: ["smart-bulb", "realme", "techlife", "iot", "rgb"], apiSource: "static-only" },
  { id: "IN-EL-RLM-046", name: "realme TechLife Robot Vacuum Black", brand: "realme", subBrand: "TechLife", category: "electronics", subCategory: "smart-home", variant: "Black", description: "LiDAR navigation with 2-in-1 vacuum and mop and 5200mAh battery.", price: 14999, originalPrice: 19999, discount: 25, image: "/assets/products/IN-EL-RLM-046.jpg", affiliateUrl: "/go/IN-EL-RLM-046", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.1, reviewCount: 8000, tags: ["robot-vacuum", "realme", "techlife", "smart-home", "lidar"], apiSource: "static-only" },
  { id: "IN-EL-RLM-047", name: "realme TechLife Robot Vacuum White", brand: "realme", subBrand: "TechLife", category: "electronics", subCategory: "smart-home", variant: "White", description: "3000Pa suction with multi-floor mapping and app scheduling.", price: 14999, originalPrice: 19999, discount: 25, image: "/assets/products/IN-EL-RLM-047.jpg", affiliateUrl: "/go/IN-EL-RLM-047", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.1, reviewCount: 8000, tags: ["robot-vacuum", "realme", "techlife", "smart-home", "lidar"], apiSource: "static-only" },
  { id: "IN-EL-RLM-048", name: "realme TechLife Robot Vacuum Grey", brand: "realme", subBrand: "TechLife", category: "electronics", subCategory: "smart-home", variant: "Grey", description: "Carpet detection with auto-boost suction and virtual wall support.", price: 14999, originalPrice: 19999, discount: 25, image: "/assets/products/IN-EL-RLM-048.jpg", affiliateUrl: "/go/IN-EL-RLM-048", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.1, reviewCount: 8000, tags: ["robot-vacuum", "realme", "techlife", "smart-home", "lidar"], apiSource: "static-only" },
  { id: "IN-EL-RLM-049", name: "realme Smart Cam 360 WiFi White", brand: "realme", subBrand: "TechLife", category: "electronics", subCategory: "smart-home", variant: "White", description: "1080p Full HD with 360-degree pan-tilt and AI motion detection.", price: 2499, originalPrice: 3999, discount: 37, image: "/assets/products/IN-EL-RLM-049.jpg", affiliateUrl: "/go/IN-EL-RLM-049", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.0, reviewCount: 35000, tags: ["smart-camera", "realme", "techlife", "security", "wifi"], apiSource: "static-only" },
  { id: "IN-EL-RLM-050", name: "realme Smart Cam 360 WiFi Black", brand: "realme", subBrand: "TechLife", category: "electronics", subCategory: "smart-home", variant: "Black", description: "Two-way audio with night vision and micro-SD card storage up to 128GB.", price: 2499, originalPrice: 3999, discount: 37, image: "/assets/products/IN-EL-RLM-050.jpg", affiliateUrl: "/go/IN-EL-RLM-050", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.0, reviewCount: 35000, tags: ["smart-camera", "realme", "techlife", "security", "wifi"], apiSource: "static-only" },
]

// ===================================================================
// Samsung — 50 products (IN-EL-SAM-001 to IN-EL-SAM-050)
// Sub-categories: smartphones, tablets, earbuds, monitors, accessories
// ===================================================================
export const SAMSUNG_BUDGET_PRODUCTS: IndiaProduct[] = [
  // GALAXY A SERIES PHONES (001–010)
  { id: "IN-EL-SAM-001", name: "Samsung Galaxy A15 5G 8GB+128GB Blue Black", brand: "Samsung", subBrand: "Galaxy A", category: "electronics", subCategory: "smartphones", variant: "Blue Black", description: "MediaTek Dimensity 6100+ with 6.5-inch FHD+ Super AMOLED display.", price: 13999, originalPrice: 16999, discount: 17, image: "/assets/products/IN-EL-SAM-001.jpg", affiliateUrl: "/go/IN-EL-SAM-001", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.1, reviewCount: 125000, tags: ["smartphone", "samsung", "5g", "galaxy-a15", "budget"], apiSource: "static-only" },
  { id: "IN-EL-SAM-002", name: "Samsung Galaxy A15 5G 8GB+128GB Light Blue", brand: "Samsung", subBrand: "Galaxy A", category: "electronics", subCategory: "smartphones", variant: "Light Blue", description: "50MP triple camera with 5000mAh battery and 25W fast charging.", price: 13999, originalPrice: 16999, discount: 17, image: "/assets/products/IN-EL-SAM-002.jpg", affiliateUrl: "/go/IN-EL-SAM-002", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.1, reviewCount: 125000, tags: ["smartphone", "samsung", "5g", "galaxy-a15", "budget"], apiSource: "static-only" },
  { id: "IN-EL-SAM-003", name: "Samsung Galaxy A15 5G 8GB+128GB Peach", brand: "Samsung", subBrand: "Galaxy A", category: "electronics", subCategory: "smartphones", variant: "Peach", description: "Samsung Knox security with 4 years of OS upgrades and 5 years security updates.", price: 13999, originalPrice: 16999, discount: 17, image: "/assets/products/IN-EL-SAM-003.jpg", affiliateUrl: "/go/IN-EL-SAM-003", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.1, reviewCount: 125000, tags: ["smartphone", "samsung", "5g", "galaxy-a15", "budget"], apiSource: "static-only" },
  { id: "IN-EL-SAM-004", name: "Samsung Galaxy A25 5G 8GB+128GB Iceblue", brand: "Samsung", subBrand: "Galaxy A", category: "electronics", subCategory: "smartphones", variant: "Iceblue", description: "Exynos 1280 with 6.5-inch Super AMOLED 120Hz and OIS camera.", price: 17999, originalPrice: 21999, discount: 18, image: "/assets/products/IN-EL-SAM-004.jpg", affiliateUrl: "/go/IN-EL-SAM-004", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.2, reviewCount: 88000, tags: ["smartphone", "samsung", "5g", "galaxy-a25", "mid-range"], apiSource: "static-only" },
  { id: "IN-EL-SAM-005", name: "Samsung Galaxy A25 5G 8GB+128GB Yellow", brand: "Samsung", subBrand: "Galaxy A", category: "electronics", subCategory: "smartphones", variant: "Yellow", description: "50MP OIS main camera with nightography and 8MP ultrawide lens.", price: 17999, originalPrice: 21999, discount: 18, image: "/assets/products/IN-EL-SAM-005.jpg", affiliateUrl: "/go/IN-EL-SAM-005", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.2, reviewCount: 88000, tags: ["smartphone", "samsung", "5g", "galaxy-a25", "mid-range"], apiSource: "static-only" },
  { id: "IN-EL-SAM-006", name: "Samsung Galaxy A35 5G 8GB+256GB Awesome Iceblue", brand: "Samsung", subBrand: "Galaxy A", category: "electronics", subCategory: "smartphones", variant: "Awesome Iceblue", description: "Exynos 1380 with 6.6-inch Super AMOLED 120Hz and IP67 rating.", price: 24999, originalPrice: 29999, discount: 16, image: "/assets/products/IN-EL-SAM-006.jpg", affiliateUrl: "/go/IN-EL-SAM-006", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 65000, tags: ["smartphone", "samsung", "5g", "galaxy-a35", "premium-mid"], apiSource: "static-only" },
  { id: "IN-EL-SAM-007", name: "Samsung Galaxy A35 5G 8GB+256GB Awesome Navy", brand: "Samsung", subBrand: "Galaxy A", category: "electronics", subCategory: "smartphones", variant: "Awesome Navy", description: "50MP OIS triple camera with Samsung Knox Vault security.", price: 24999, originalPrice: 29999, discount: 16, image: "/assets/products/IN-EL-SAM-007.jpg", affiliateUrl: "/go/IN-EL-SAM-007", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 65000, tags: ["smartphone", "samsung", "5g", "galaxy-a35", "premium-mid"], apiSource: "static-only" },
  { id: "IN-EL-SAM-008", name: "Samsung Galaxy A35 5G 8GB+256GB Awesome Lilac", brand: "Samsung", subBrand: "Galaxy A", category: "electronics", subCategory: "smartphones", variant: "Awesome Lilac", description: "5000mAh battery with 25W super fast charging and stereo speakers.", price: 24999, originalPrice: 29999, discount: 16, image: "/assets/products/IN-EL-SAM-008.jpg", affiliateUrl: "/go/IN-EL-SAM-008", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 65000, tags: ["smartphone", "samsung", "5g", "galaxy-a35", "premium-mid"], apiSource: "static-only" },
  { id: "IN-EL-SAM-009", name: "Samsung Galaxy A55 5G 8GB+256GB Awesome Iceblue", brand: "Samsung", subBrand: "Galaxy A", category: "electronics", subCategory: "smartphones", variant: "Awesome Iceblue", description: "Exynos 1480 with 6.6-inch Super AMOLED 120Hz and vapor cooling.", price: 29999, originalPrice: 34999, discount: 14, image: "/assets/products/IN-EL-SAM-009.jpg", affiliateUrl: "/go/IN-EL-SAM-009", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.4, reviewCount: 42000, tags: ["smartphone", "samsung", "5g", "galaxy-a55", "flagship-killer"], apiSource: "static-only" },
  { id: "IN-EL-SAM-010", name: "Samsung Galaxy A55 5G 8GB+256GB Awesome Navy", brand: "Samsung", subBrand: "Galaxy A", category: "electronics", subCategory: "smartphones", variant: "Awesome Navy", description: "50MP OIS with AI-powered photo editing and IP67 water resistance.", price: 29999, originalPrice: 34999, discount: 14, image: "/assets/products/IN-EL-SAM-010.jpg", affiliateUrl: "/go/IN-EL-SAM-010", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.4, reviewCount: 42000, tags: ["smartphone", "samsung", "5g", "galaxy-a55", "flagship-killer"], apiSource: "static-only" },

  // GALAXY TABS (011–020)
  { id: "IN-EL-SAM-011", name: "Samsung Galaxy Tab A9 4GB+64GB WiFi Silver", brand: "Samsung", subBrand: "Galaxy Tab", category: "electronics", subCategory: "tablets", variant: "Silver", description: "8.7-inch display with Dolby Atmos dual speakers and One UI 5.1.", price: 12999, originalPrice: 15999, discount: 18, image: "/assets/products/IN-EL-SAM-011.jpg", affiliateUrl: "/go/IN-EL-SAM-011", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.1, reviewCount: 48000, tags: ["tablet", "samsung", "galaxy-tab-a9", "budget", "wifi"], apiSource: "static-only" },
  { id: "IN-EL-SAM-012", name: "Samsung Galaxy Tab A9 4GB+64GB WiFi Navy", brand: "Samsung", subBrand: "Galaxy Tab", category: "electronics", subCategory: "tablets", variant: "Navy", description: "5100mAh battery with Samsung Kids mode and multi-window support.", price: 12999, originalPrice: 15999, discount: 18, image: "/assets/products/IN-EL-SAM-012.jpg", affiliateUrl: "/go/IN-EL-SAM-012", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.1, reviewCount: 48000, tags: ["tablet", "samsung", "galaxy-tab-a9", "budget", "wifi"], apiSource: "static-only" },
  { id: "IN-EL-SAM-013", name: "Samsung Galaxy Tab A9 4GB+64GB WiFi Graphite", brand: "Samsung", subBrand: "Galaxy Tab", category: "electronics", subCategory: "tablets", variant: "Graphite", description: "Metal unibody design with expandable storage up to 1TB micro-SD.", price: 12999, originalPrice: 15999, discount: 18, image: "/assets/products/IN-EL-SAM-013.jpg", affiliateUrl: "/go/IN-EL-SAM-013", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.1, reviewCount: 48000, tags: ["tablet", "samsung", "galaxy-tab-a9", "budget", "wifi"], apiSource: "static-only" },
  { id: "IN-EL-SAM-014", name: "Samsung Galaxy Tab A9 Plus 8GB+128GB WiFi Silver", brand: "Samsung", subBrand: "Galaxy Tab", category: "electronics", subCategory: "tablets", variant: "Silver", description: "11-inch TFT display with Snapdragon 695 and quad speakers.", price: 19999, originalPrice: 24999, discount: 20, image: "/assets/products/IN-EL-SAM-014.jpg", affiliateUrl: "/go/IN-EL-SAM-014", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.2, reviewCount: 35000, tags: ["tablet", "samsung", "galaxy-tab-a9-plus", "mid-range", "wifi"], apiSource: "static-only" },
  { id: "IN-EL-SAM-015", name: "Samsung Galaxy Tab A9 Plus 8GB+128GB WiFi Navy", brand: "Samsung", subBrand: "Galaxy Tab", category: "electronics", subCategory: "tablets", variant: "Navy", description: "7040mAh battery with 15W adaptive fast charging and DeX mode.", price: 19999, originalPrice: 24999, discount: 20, image: "/assets/products/IN-EL-SAM-015.jpg", affiliateUrl: "/go/IN-EL-SAM-015", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.2, reviewCount: 35000, tags: ["tablet", "samsung", "galaxy-tab-a9-plus", "mid-range", "wifi"], apiSource: "static-only" },
  { id: "IN-EL-SAM-016", name: "Samsung Galaxy Tab S6 Lite 10.4 WiFi Oxford Gray", brand: "Samsung", subBrand: "Galaxy Tab", category: "electronics", subCategory: "tablets", variant: "Oxford Gray", description: "10.4-inch display with S Pen included and AKG-tuned speakers.", price: 22999, originalPrice: 27999, discount: 17, image: "/assets/products/IN-EL-SAM-016.jpg", affiliateUrl: "/go/IN-EL-SAM-016", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 62000, tags: ["tablet", "samsung", "galaxy-tab-s6-lite", "s-pen", "creative"], apiSource: "static-only" },
  { id: "IN-EL-SAM-017", name: "Samsung Galaxy Tab S6 Lite 10.4 WiFi Chiffon Pink", brand: "Samsung", subBrand: "Galaxy Tab", category: "electronics", subCategory: "tablets", variant: "Chiffon Pink", description: "Exynos 1280 with S Pen for note-taking and digital art.", price: 22999, originalPrice: 27999, discount: 17, image: "/assets/products/IN-EL-SAM-017.jpg", affiliateUrl: "/go/IN-EL-SAM-017", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 62000, tags: ["tablet", "samsung", "galaxy-tab-s6-lite", "s-pen", "creative"], apiSource: "static-only" },
  { id: "IN-EL-SAM-018", name: "Samsung Galaxy Tab S6 Lite 10.4 WiFi Chiffon Rose", brand: "Samsung", subBrand: "Galaxy Tab", category: "electronics", subCategory: "tablets", variant: "Chiffon Rose", description: "7040mAh battery with One UI Book Cover keyboard case support.", price: 22999, originalPrice: 27999, discount: 17, image: "/assets/products/IN-EL-SAM-018.jpg", affiliateUrl: "/go/IN-EL-SAM-018", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 62000, tags: ["tablet", "samsung", "galaxy-tab-s6-lite", "s-pen", "creative"], apiSource: "static-only" },
  { id: "IN-EL-SAM-019", name: "Samsung Galaxy Tab S9 FE 8GB+256GB WiFi Mint", brand: "Samsung", subBrand: "Galaxy Tab", category: "electronics", subCategory: "tablets", variant: "Mint", description: "10.9-inch TFT display with IP68 rating and S Pen included.", price: 34999, originalPrice: 42999, discount: 18, image: "/assets/products/IN-EL-SAM-019.jpg", affiliateUrl: "/go/IN-EL-SAM-019", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.5, reviewCount: 22000, tags: ["tablet", "samsung", "galaxy-tab-s9-fe", "premium", "s-pen"], apiSource: "static-only" },
  { id: "IN-EL-SAM-020", name: "Samsung Galaxy Tab S9 FE 8GB+256GB WiFi Lavender", brand: "Samsung", subBrand: "Galaxy Tab", category: "electronics", subCategory: "tablets", variant: "Lavender", description: "Exynos 1380 with AKG speakers and Dolby Atmos surround sound.", price: 34999, originalPrice: 42999, discount: 18, image: "/assets/products/IN-EL-SAM-020.jpg", affiliateUrl: "/go/IN-EL-SAM-020", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.5, reviewCount: 22000, tags: ["tablet", "samsung", "galaxy-tab-s9-fe", "premium", "s-pen"], apiSource: "static-only" },

  // GALAXY BUDS AND AUDIO (021–030)
  { id: "IN-EL-SAM-021", name: "Samsung Galaxy Buds FE TWS Graphite", brand: "Samsung", subBrand: "Galaxy Buds", category: "electronics", subCategory: "earbuds", variant: "Graphite", description: "ANC with 1-core AKG-tuned 6.5mm driver and 30H total playtime.", price: 4999, originalPrice: 6999, discount: 28, image: "/assets/products/IN-EL-SAM-021.jpg", affiliateUrl: "/go/IN-EL-SAM-021", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.2, reviewCount: 78000, tags: ["earbuds", "samsung", "tws", "anc", "galaxy-buds-fe"], apiSource: "static-only" },
  { id: "IN-EL-SAM-022", name: "Samsung Galaxy Buds FE TWS White", brand: "Samsung", subBrand: "Galaxy Buds", category: "electronics", subCategory: "earbuds", variant: "White", description: "IPX2 water resistance with touch controls and ambient sound mode.", price: 4999, originalPrice: 6999, discount: 28, image: "/assets/products/IN-EL-SAM-022.jpg", affiliateUrl: "/go/IN-EL-SAM-022", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.2, reviewCount: 78000, tags: ["earbuds", "samsung", "tws", "anc", "galaxy-buds-fe"], apiSource: "static-only" },
  { id: "IN-EL-SAM-023", name: "Samsung Galaxy Buds FE TWS Blue", brand: "Samsung", subBrand: "Galaxy Buds", category: "electronics", subCategory: "earbuds", variant: "Blue", description: "Seamless Galaxy ecosystem with SmartThings Find and auto switch.", price: 4999, originalPrice: 6999, discount: 28, image: "/assets/products/IN-EL-SAM-023.jpg", affiliateUrl: "/go/IN-EL-SAM-023", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.2, reviewCount: 78000, tags: ["earbuds", "samsung", "tws", "anc", "galaxy-buds-fe"], apiSource: "static-only" },
  { id: "IN-EL-SAM-024", name: "Samsung Galaxy Buds 2 TWS Graphite", brand: "Samsung", subBrand: "Galaxy Buds", category: "electronics", subCategory: "earbuds", variant: "Graphite", description: "Two-way dynamic speakers with ANC and 3 ambient sound levels.", price: 5999, originalPrice: 8999, discount: 33, image: "/assets/products/IN-EL-SAM-024.jpg", affiliateUrl: "/go/IN-EL-SAM-024", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 95000, tags: ["earbuds", "samsung", "tws", "anc", "galaxy-buds-2"], apiSource: "static-only" },
  { id: "IN-EL-SAM-025", name: "Samsung Galaxy Buds 2 TWS White", brand: "Samsung", subBrand: "Galaxy Buds", category: "electronics", subCategory: "earbuds", variant: "White", description: "Machine learning noise reduction with 360 Audio spatial sound.", price: 5999, originalPrice: 8999, discount: 33, image: "/assets/products/IN-EL-SAM-025.jpg", affiliateUrl: "/go/IN-EL-SAM-025", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 95000, tags: ["earbuds", "samsung", "tws", "anc", "galaxy-buds-2"], apiSource: "static-only" },
  { id: "IN-EL-SAM-026", name: "Samsung Galaxy Buds 2 TWS Olive", brand: "Samsung", subBrand: "Galaxy Buds", category: "electronics", subCategory: "earbuds", variant: "Olive", description: "Lightweight 5g per earbud with comfort fit for all-day wear.", price: 5999, originalPrice: 8999, discount: 33, image: "/assets/products/IN-EL-SAM-026.jpg", affiliateUrl: "/go/IN-EL-SAM-026", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 95000, tags: ["earbuds", "samsung", "tws", "anc", "galaxy-buds-2"], apiSource: "static-only" },
  { id: "IN-EL-SAM-027", name: "Samsung Galaxy Buds 2 Pro TWS ANC Graphite", brand: "Samsung", subBrand: "Galaxy Buds", category: "electronics", subCategory: "earbuds", variant: "Graphite", description: "24-bit Hi-Fi audio with intelligent ANC and 360 Audio recording.", price: 9999, originalPrice: 14999, discount: 33, image: "/assets/products/IN-EL-SAM-027.jpg", affiliateUrl: "/go/IN-EL-SAM-027", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.5, reviewCount: 52000, tags: ["earbuds", "samsung", "tws", "anc", "premium", "galaxy-buds-2-pro"], apiSource: "static-only" },
  { id: "IN-EL-SAM-028", name: "Samsung Galaxy Buds 2 Pro TWS ANC White", brand: "Samsung", subBrand: "Galaxy Buds", category: "electronics", subCategory: "earbuds", variant: "White", description: "Coaxial 2-way speakers with Samsung Seamless Codec for lossless audio.", price: 9999, originalPrice: 14999, discount: 33, image: "/assets/products/IN-EL-SAM-028.jpg", affiliateUrl: "/go/IN-EL-SAM-028", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.5, reviewCount: 52000, tags: ["earbuds", "samsung", "tws", "anc", "premium", "galaxy-buds-2-pro"], apiSource: "static-only" },
  { id: "IN-EL-SAM-029", name: "Samsung Galaxy Fit 3 Gray", brand: "Samsung", subBrand: "Galaxy Fit", category: "electronics", subCategory: "earbuds", variant: "Gray", description: "1.6-inch AMOLED with 100+ workout modes and up to 13 days battery.", price: 3999, originalPrice: 5999, discount: 33, image: "/assets/products/IN-EL-SAM-029.jpg", affiliateUrl: "/go/IN-EL-SAM-029", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 38000, tags: ["fitness-band", "samsung", "galaxy-fit-3", "health", "amoled"], apiSource: "static-only" },
  { id: "IN-EL-SAM-030", name: "Samsung Galaxy Fit 3 Pink Gold", brand: "Samsung", subBrand: "Galaxy Fit", category: "electronics", subCategory: "earbuds", variant: "Pink Gold", description: "5ATM and IP68 water resistance with sleep coaching and heart rate.", price: 3999, originalPrice: 5999, discount: 33, image: "/assets/products/IN-EL-SAM-030.jpg", affiliateUrl: "/go/IN-EL-SAM-030", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 38000, tags: ["fitness-band", "samsung", "galaxy-fit-3", "health", "amoled"], apiSource: "static-only" },

  // MONITORS (031–040)
  { id: "IN-EL-SAM-031", name: "Samsung 24-inch FHD LS24C330 Blue", brand: "Samsung", subBrand: "Monitor", category: "electronics", subCategory: "monitors", variant: "Blue", description: "24-inch FHD IPS panel with 75Hz refresh rate and AMD FreeSync.", price: 8999, originalPrice: 11999, discount: 25, image: "/assets/products/IN-EL-SAM-031.jpg", affiliateUrl: "/go/IN-EL-SAM-031", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.2, reviewCount: 28000, tags: ["monitor", "samsung", "24-inch", "fhd", "ips"], apiSource: "static-only" },
  { id: "IN-EL-SAM-032", name: "Samsung 24-inch FHD LS24C330 Black", brand: "Samsung", subBrand: "Monitor", category: "electronics", subCategory: "monitors", variant: "Black", description: "Borderless design with eye saver mode and flicker-free technology.", price: 8999, originalPrice: 11999, discount: 25, image: "/assets/products/IN-EL-SAM-032.jpg", affiliateUrl: "/go/IN-EL-SAM-032", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.2, reviewCount: 28000, tags: ["monitor", "samsung", "24-inch", "fhd", "ips"], apiSource: "static-only" },
  { id: "IN-EL-SAM-033", name: "Samsung 24-inch FHD LS24C330 Silver", brand: "Samsung", subBrand: "Monitor", category: "electronics", subCategory: "monitors", variant: "Silver", description: "HDMI and DisplayPort connectivity with VESA mount compatible.", price: 8999, originalPrice: 11999, discount: 25, image: "/assets/products/IN-EL-SAM-033.jpg", affiliateUrl: "/go/IN-EL-SAM-033", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.2, reviewCount: 28000, tags: ["monitor", "samsung", "24-inch", "fhd", "ips"], apiSource: "static-only" },
  { id: "IN-EL-SAM-034", name: "Samsung 27-inch FHD Curved Black", brand: "Samsung", subBrand: "Monitor", category: "electronics", subCategory: "monitors", variant: "Black", description: "1800R curvature with 75Hz and 4ms response time for immersive viewing.", price: 13999, originalPrice: 17999, discount: 22, image: "/assets/products/IN-EL-SAM-034.jpg", affiliateUrl: "/go/IN-EL-SAM-034", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 35000, tags: ["monitor", "samsung", "27-inch", "curved", "fhd"], apiSource: "static-only" },
  { id: "IN-EL-SAM-035", name: "Samsung 27-inch FHD Curved Silver", brand: "Samsung", subBrand: "Monitor", category: "electronics", subCategory: "monitors", variant: "Silver", description: "Game mode with low input lag and AMD FreeSync anti-tearing.", price: 13999, originalPrice: 17999, discount: 22, image: "/assets/products/IN-EL-SAM-035.jpg", affiliateUrl: "/go/IN-EL-SAM-035", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 35000, tags: ["monitor", "samsung", "27-inch", "curved", "fhd"], apiSource: "static-only" },
  { id: "IN-EL-SAM-036", name: "Samsung 32-inch QHD M7 Smart Monitor Black", brand: "Samsung", subBrand: "Smart Monitor", category: "electronics", subCategory: "monitors", variant: "Black", description: "32-inch 4K UHD with built-in Tizen OS for streaming without a PC.", price: 24999, originalPrice: 32999, discount: 24, image: "/assets/products/IN-EL-SAM-036.jpg", affiliateUrl: "/go/IN-EL-SAM-036", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.4, reviewCount: 18000, tags: ["monitor", "samsung", "32-inch", "smart", "4k", "m7"], apiSource: "static-only" },
  { id: "IN-EL-SAM-037", name: "Samsung 32-inch QHD M7 Smart Monitor White", brand: "Samsung", subBrand: "Smart Monitor", category: "electronics", subCategory: "monitors", variant: "White", description: "USB-C with 65W charging and wireless DeX for Galaxy phones.", price: 24999, originalPrice: 32999, discount: 24, image: "/assets/products/IN-EL-SAM-037.jpg", affiliateUrl: "/go/IN-EL-SAM-037", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.4, reviewCount: 18000, tags: ["monitor", "samsung", "32-inch", "smart", "4k", "m7"], apiSource: "static-only" },
  { id: "IN-EL-SAM-038", name: "Samsung 32-inch QHD M7 Smart Monitor Blue", brand: "Samsung", subBrand: "Smart Monitor", category: "electronics", subCategory: "monitors", variant: "Blue", description: "IoT hub with SmartThings integration and AirPlay 2 support.", price: 24999, originalPrice: 32999, discount: 24, image: "/assets/products/IN-EL-SAM-038.jpg", affiliateUrl: "/go/IN-EL-SAM-038", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.4, reviewCount: 18000, tags: ["monitor", "samsung", "32-inch", "smart", "4k", "m7"], apiSource: "static-only" },
  { id: "IN-EL-SAM-039", name: "Samsung Smart Monitor M8 32-inch 4K Warm White", brand: "Samsung", subBrand: "Smart Monitor", category: "electronics", subCategory: "monitors", variant: "Warm White", description: "32-inch 4K UHD with SlimFit camera and built-in far-field mic.", price: 34999, originalPrice: 44999, discount: 22, image: "/assets/products/IN-EL-SAM-039.jpg", affiliateUrl: "/go/IN-EL-SAM-039", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.6, reviewCount: 12000, tags: ["monitor", "samsung", "32-inch", "smart", "4k", "m8", "premium"], apiSource: "static-only" },
  { id: "IN-EL-SAM-040", name: "Samsung Smart Monitor M8 32-inch 4K Sunset Pink", brand: "Samsung", subBrand: "Smart Monitor", category: "electronics", subCategory: "monitors", variant: "Sunset Pink", description: "Matter and SmartThings hub with Netflix, YouTube, and Office 365 built-in.", price: 34999, originalPrice: 44999, discount: 22, image: "/assets/products/IN-EL-SAM-040.jpg", affiliateUrl: "/go/IN-EL-SAM-040", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.6, reviewCount: 12000, tags: ["monitor", "samsung", "32-inch", "smart", "4k", "m8", "premium"], apiSource: "static-only" },

  // ACCESSORIES (041–050)
  { id: "IN-EL-SAM-041", name: "Samsung 25W Charger Black", brand: "Samsung", subBrand: "Accessories", category: "electronics", subCategory: "accessories", variant: "Black", description: "25W super fast charger with USB-C to USB-C cable included.", price: 1099, originalPrice: 1999, discount: 45, image: "/assets/products/IN-EL-SAM-041.jpg", affiliateUrl: "/go/IN-EL-SAM-041", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.5, reviewCount: 180000, tags: ["charger", "samsung", "25w", "fast-charge", "usb-c"], apiSource: "static-only" },
  { id: "IN-EL-SAM-042", name: "Samsung 25W Charger White", brand: "Samsung", subBrand: "Accessories", category: "electronics", subCategory: "accessories", variant: "White", description: "Compatible with all Samsung Galaxy devices and PD-enabled phones.", price: 1099, originalPrice: 1999, discount: 45, image: "/assets/products/IN-EL-SAM-042.jpg", affiliateUrl: "/go/IN-EL-SAM-042", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.5, reviewCount: 180000, tags: ["charger", "samsung", "25w", "fast-charge", "usb-c"], apiSource: "static-only" },
  { id: "IN-EL-SAM-043", name: "Samsung 25W Charger Single", brand: "Samsung", subBrand: "Accessories", category: "electronics", subCategory: "accessories", variant: "Single", description: "Compact travel-friendly design with BIS certification and overcharge protection.", price: 1099, originalPrice: 1999, discount: 45, image: "/assets/products/IN-EL-SAM-043.jpg", affiliateUrl: "/go/IN-EL-SAM-043", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.5, reviewCount: 180000, tags: ["charger", "samsung", "25w", "fast-charge", "usb-c"], apiSource: "static-only" },
  { id: "IN-EL-SAM-044", name: "Samsung 45W Charger Black", brand: "Samsung", subBrand: "Accessories", category: "electronics", subCategory: "accessories", variant: "Black", description: "45W super fast charging 2.0 for Galaxy S and Note series.", price: 2199, originalPrice: 3499, discount: 37, image: "/assets/products/IN-EL-SAM-044.jpg", affiliateUrl: "/go/IN-EL-SAM-044", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.6, reviewCount: 92000, tags: ["charger", "samsung", "45w", "super-fast-charge", "usb-c"], apiSource: "static-only" },
  { id: "IN-EL-SAM-045", name: "Samsung 45W Charger White", brand: "Samsung", subBrand: "Accessories", category: "electronics", subCategory: "accessories", variant: "White", description: "PPS and PD 3.0 compatible with intelligent thermal management.", price: 2199, originalPrice: 3499, discount: 37, image: "/assets/products/IN-EL-SAM-045.jpg", affiliateUrl: "/go/IN-EL-SAM-045", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.6, reviewCount: 92000, tags: ["charger", "samsung", "45w", "super-fast-charge", "usb-c"], apiSource: "static-only" },
  { id: "IN-EL-SAM-046", name: "Samsung Wireless Charger Pad 15W Black", brand: "Samsung", subBrand: "Accessories", category: "electronics", subCategory: "accessories", variant: "Black", description: "15W fast wireless charging with LED indicator and fan cooling.", price: 1999, originalPrice: 2999, discount: 33, image: "/assets/products/IN-EL-SAM-046.jpg", affiliateUrl: "/go/IN-EL-SAM-046", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 55000, tags: ["wireless-charger", "samsung", "15w", "qi", "charging-pad"], apiSource: "static-only" },
  { id: "IN-EL-SAM-047", name: "Samsung Wireless Charger Pad 15W White", brand: "Samsung", subBrand: "Accessories", category: "electronics", subCategory: "accessories", variant: "White", description: "Qi-certified with universal compatibility for all wireless charging phones.", price: 1999, originalPrice: 2999, discount: 33, image: "/assets/products/IN-EL-SAM-047.jpg", affiliateUrl: "/go/IN-EL-SAM-047", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 55000, tags: ["wireless-charger", "samsung", "15w", "qi", "charging-pad"], apiSource: "static-only" },
  { id: "IN-EL-SAM-048", name: "Samsung Wireless Charger Pad 15W Single", brand: "Samsung", subBrand: "Accessories", category: "electronics", subCategory: "accessories", variant: "Single", description: "Slim 9mm profile with non-slip rubber base and foreign object detection.", price: 1999, originalPrice: 2999, discount: 33, image: "/assets/products/IN-EL-SAM-048.jpg", affiliateUrl: "/go/IN-EL-SAM-048", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 55000, tags: ["wireless-charger", "samsung", "15w", "qi", "charging-pad"], apiSource: "static-only" },
  { id: "IN-EL-SAM-049", name: "Samsung Clear Cover A55 Transparent", brand: "Samsung", subBrand: "Accessories", category: "electronics", subCategory: "accessories", variant: "Transparent", description: "Official Samsung clear cover with anti-yellowing and military-grade drop protection.", price: 999, originalPrice: 1499, discount: 33, image: "/assets/products/IN-EL-SAM-049.jpg", affiliateUrl: "/go/IN-EL-SAM-049", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 3.9, reviewCount: 45000, tags: ["case", "samsung", "galaxy-a55", "clear-cover", "protection"], apiSource: "static-only" },
  { id: "IN-EL-SAM-050", name: "Samsung Clear Cover A55 Black", brand: "Samsung", subBrand: "Accessories", category: "electronics", subCategory: "accessories", variant: "Black", description: "Precise cutouts with raised bezels for camera and screen protection.", price: 999, originalPrice: 1499, discount: 33, image: "/assets/products/IN-EL-SAM-050.jpg", affiliateUrl: "/go/IN-EL-SAM-050", affiliatePlatform: "flipkart", affiliateSource: "static", inStock: true, rating: 3.9, reviewCount: 45000, tags: ["case", "samsung", "galaxy-a55", "clear-cover", "protection"], apiSource: "static-only" },
]
