import { IndiaProduct } from "../types"

// ===================================================================
// Puma — 50 products (IN-FA-PUM-001 to IN-FA-PUM-050)
// Sub-categories: mens-footwear, mens-clothing, womens-footwear, womens-clothing, sports-accessories
// ===================================================================
export const PUMA_PRODUCTS: IndiaProduct[] = [
  // MENS FOOTWEAR (001–010)
  { id: "IN-FA-PUM-001", name: "Puma Softride Enzo Evo Running Shoes Black White", brand: "Puma", subBrand: "Softride", category: "fashion", subCategory: "mens-footwear", variant: "Black White", description: "Softride foam midsole delivers ultra-cushioned comfort for everyday runs.", price: 3499, originalPrice: 5999, discount: 41, image: "/assets/products/IN-FA-PUM-001.jpg", affiliateUrl: "/go/IN-FA-PUM-001", affiliatePlatform: "myntra", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.3, reviewCount: 45000, tags: ["mens", "shoes", "running", "puma", "softride"], apiSource: "flipkart-affiliate-free" },
  { id: "IN-FA-PUM-002", name: "Puma Softride Enzo Evo Running Shoes White Silver", brand: "Puma", subBrand: "Softride", category: "fashion", subCategory: "mens-footwear", variant: "White Silver", description: "Breathable mesh upper with Softride cushioning for all-day support.", price: 3499, originalPrice: 5999, discount: 41, image: "/assets/products/IN-FA-PUM-002.jpg", affiliateUrl: "/go/IN-FA-PUM-002", affiliatePlatform: "ajio", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 42000, tags: ["mens", "shoes", "running", "puma", "softride"], apiSource: "static-only" },
  { id: "IN-FA-PUM-003", name: "Puma Resolve Running Shoes Navy Blue", brand: "Puma", subBrand: "Resolve", category: "fashion", subCategory: "mens-footwear", variant: "Navy Blue", description: "Lightweight running shoe with rubber outsole for superior grip.", price: 2499, originalPrice: 4499, discount: 44, image: "/assets/products/IN-FA-PUM-003.jpg", affiliateUrl: "/go/IN-FA-PUM-003", affiliatePlatform: "myntra", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.1, reviewCount: 38000, tags: ["mens", "shoes", "running", "puma", "resolve"], apiSource: "flipkart-affiliate-free" },
  { id: "IN-FA-PUM-004", name: "Puma Resolve Running Shoes Red White", brand: "Puma", subBrand: "Resolve", category: "fashion", subCategory: "mens-footwear", variant: "Red White", description: "SoftFoam+ sockliner provides step-in comfort for daily training.", price: 2499, originalPrice: 4499, discount: 44, image: "/assets/products/IN-FA-PUM-004.jpg", affiliateUrl: "/go/IN-FA-PUM-004", affiliatePlatform: "ajio", affiliateSource: "static", inStock: true, rating: 4.0, reviewCount: 35000, tags: ["mens", "shoes", "running", "puma", "resolve"], apiSource: "static-only" },
  { id: "IN-FA-PUM-005", name: "Puma Resolve Running Shoes All Black", brand: "Puma", subBrand: "Resolve", category: "fashion", subCategory: "mens-footwear", variant: "All Black", description: "Sleek all-black design with durable rubber outsole for versatile wear.", price: 2499, originalPrice: 4499, discount: 44, image: "/assets/products/IN-FA-PUM-005.jpg", affiliateUrl: "/go/IN-FA-PUM-005", affiliatePlatform: "myntra", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.2, reviewCount: 40000, tags: ["mens", "shoes", "running", "puma", "resolve"], apiSource: "flipkart-affiliate-free" },
  { id: "IN-FA-PUM-006", name: "Puma Smash v3 Sneakers White Black", brand: "Puma", subBrand: "Smash", category: "fashion", subCategory: "mens-footwear", variant: "White Black", description: "Classic court-inspired sneaker with soft leather upper and Formstrip.", price: 2999, originalPrice: 4999, discount: 40, image: "/assets/products/IN-FA-PUM-006.jpg", affiliateUrl: "/go/IN-FA-PUM-006", affiliatePlatform: "ajio", affiliateSource: "static", inStock: true, rating: 4.4, reviewCount: 62000, tags: ["mens", "shoes", "sneakers", "puma", "smash"], apiSource: "static-only" },
  { id: "IN-FA-PUM-007", name: "Puma Smash v3 Sneakers Black White", brand: "Puma", subBrand: "Smash", category: "fashion", subCategory: "mens-footwear", variant: "Black White", description: "Timeless Puma Smash silhouette updated with v3 comfort upgrades.", price: 2999, originalPrice: 4999, discount: 40, image: "/assets/products/IN-FA-PUM-007.jpg", affiliateUrl: "/go/IN-FA-PUM-007", affiliatePlatform: "myntra", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.4, reviewCount: 58000, tags: ["mens", "shoes", "sneakers", "puma", "smash"], apiSource: "flipkart-affiliate-free" },
  { id: "IN-FA-PUM-008", name: "Puma Smash v3 Sneakers Navy White", brand: "Puma", subBrand: "Smash", category: "fashion", subCategory: "mens-footwear", variant: "Navy White", description: "Padded collar and tongue for a snug fit with SoftFoam+ insole.", price: 2999, originalPrice: 4999, discount: 40, image: "/assets/products/IN-FA-PUM-008.jpg", affiliateUrl: "/go/IN-FA-PUM-008", affiliatePlatform: "ajio", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 55000, tags: ["mens", "shoes", "sneakers", "puma", "smash"], apiSource: "static-only" },
  { id: "IN-FA-PUM-009", name: "Puma Graviton Slip-on Black White", brand: "Puma", subBrand: "Graviton", category: "fashion", subCategory: "mens-footwear", variant: "Black White", description: "Easy slip-on design with lightweight EVA midsole for casual outings.", price: 2199, originalPrice: 3999, discount: 45, image: "/assets/products/IN-FA-PUM-009.jpg", affiliateUrl: "/go/IN-FA-PUM-009", affiliatePlatform: "myntra", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.0, reviewCount: 28000, tags: ["mens", "shoes", "slip-on", "puma", "graviton"], apiSource: "flipkart-affiliate-free" },
  { id: "IN-FA-PUM-010", name: "Puma Graviton Slip-on White Grey", brand: "Puma", subBrand: "Graviton", category: "fashion", subCategory: "mens-footwear", variant: "White Grey", description: "Minimalist slip-on sneaker with mesh upper for breathable comfort.", price: 2199, originalPrice: 3999, discount: 45, image: "/assets/products/IN-FA-PUM-010.jpg", affiliateUrl: "/go/IN-FA-PUM-010", affiliatePlatform: "ajio", affiliateSource: "static", inStock: true, rating: 3.9, reviewCount: 25000, tags: ["mens", "shoes", "slip-on", "puma", "graviton"], apiSource: "static-only" },

  // MENS CLOTHING (011–020)
  { id: "IN-FA-PUM-011", name: "Puma Active Woven Track Pants Black", brand: "Puma", subBrand: "Active", category: "fashion", subCategory: "mens-clothing", variant: "Black", description: "Lightweight woven fabric with elasticated waistband and zip pockets.", price: 1499, originalPrice: 2999, discount: 50, image: "/assets/products/IN-FA-PUM-011.jpg", affiliateUrl: "/go/IN-FA-PUM-011", affiliatePlatform: "myntra", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.2, reviewCount: 32000, tags: ["mens", "clothing", "track-pants", "puma", "active"], apiSource: "flipkart-affiliate-free" },
  { id: "IN-FA-PUM-012", name: "Puma Active Woven Track Pants Navy", brand: "Puma", subBrand: "Active", category: "fashion", subCategory: "mens-clothing", variant: "Navy", description: "dryCELL moisture-wicking technology keeps you dry during workouts.", price: 1499, originalPrice: 2999, discount: 50, image: "/assets/products/IN-FA-PUM-012.jpg", affiliateUrl: "/go/IN-FA-PUM-012", affiliatePlatform: "ajio", affiliateSource: "static", inStock: true, rating: 4.1, reviewCount: 29000, tags: ["mens", "clothing", "track-pants", "puma", "active"], apiSource: "static-only" },
  { id: "IN-FA-PUM-013", name: "Puma Active Woven Track Pants Dark Grey", brand: "Puma", subBrand: "Active", category: "fashion", subCategory: "mens-clothing", variant: "Dark Grey", description: "Tapered leg fit with Puma Cat logo on the left thigh.", price: 1499, originalPrice: 2999, discount: 50, image: "/assets/products/IN-FA-PUM-013.jpg", affiliateUrl: "/go/IN-FA-PUM-013", affiliatePlatform: "myntra", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.0, reviewCount: 27000, tags: ["mens", "clothing", "track-pants", "puma", "active"], apiSource: "flipkart-affiliate-free" },
  { id: "IN-FA-PUM-014", name: "Puma Essentials Logo Tee Forest Night", brand: "Puma", subBrand: "Essentials", category: "fashion", subCategory: "mens-clothing", variant: "Forest Night", description: "Cotton jersey tee with iconic Puma No.1 Logo print on chest.", price: 799, originalPrice: 1499, discount: 46, image: "/assets/products/IN-FA-PUM-014.jpg", affiliateUrl: "/go/IN-FA-PUM-014", affiliatePlatform: "ajio", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 55000, tags: ["mens", "clothing", "tshirt", "puma", "essentials"], apiSource: "static-only" },
  { id: "IN-FA-PUM-015", name: "Puma Essentials Logo Tee Cobalt Glaze", brand: "Puma", subBrand: "Essentials", category: "fashion", subCategory: "mens-clothing", variant: "Cobalt Glaze", description: "Relaxed fit crew neck tee crafted from 100% cotton for everyday comfort.", price: 799, originalPrice: 1499, discount: 46, image: "/assets/products/IN-FA-PUM-015.jpg", affiliateUrl: "/go/IN-FA-PUM-015", affiliatePlatform: "myntra", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.2, reviewCount: 50000, tags: ["mens", "clothing", "tshirt", "puma", "essentials"], apiSource: "flipkart-affiliate-free" },
  { id: "IN-FA-PUM-016", name: "Puma Fit Training Tights Black", brand: "Puma", subBrand: "Fit", category: "fashion", subCategory: "mens-clothing", variant: "Black", description: "Compression fit training tights with dryCELL technology.", price: 1799, originalPrice: 2999, discount: 40, image: "/assets/products/IN-FA-PUM-016.jpg", affiliateUrl: "/go/IN-FA-PUM-016", affiliatePlatform: "ajio", affiliateSource: "static", inStock: true, rating: 4.1, reviewCount: 18000, tags: ["mens", "clothing", "tights", "puma", "fit", "training"], apiSource: "static-only" },
  { id: "IN-FA-PUM-017", name: "Puma Fit Training Tights Navy", brand: "Puma", subBrand: "Fit", category: "fashion", subCategory: "mens-clothing", variant: "Navy", description: "Flatlock seams reduce chafing during high-intensity workouts.", price: 1799, originalPrice: 2999, discount: 40, image: "/assets/products/IN-FA-PUM-017.jpg", affiliateUrl: "/go/IN-FA-PUM-017", affiliatePlatform: "myntra", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.0, reviewCount: 16000, tags: ["mens", "clothing", "tights", "puma", "fit", "training"], apiSource: "flipkart-affiliate-free" },
  { id: "IN-FA-PUM-018", name: "Puma Fit Training Tights Dark Grey", brand: "Puma", subBrand: "Fit", category: "fashion", subCategory: "mens-clothing", variant: "Dark Grey", description: "Ergonomic panelling for full range of motion and muscle support.", price: 1799, originalPrice: 2999, discount: 40, image: "/assets/products/IN-FA-PUM-018.jpg", affiliateUrl: "/go/IN-FA-PUM-018", affiliatePlatform: "ajio", affiliateSource: "static", inStock: true, rating: 4.1, reviewCount: 15000, tags: ["mens", "clothing", "tights", "puma", "fit", "training"], apiSource: "static-only" },
  { id: "IN-FA-PUM-019", name: "Puma Squad Polo Black", brand: "Puma", subBrand: "Squad", category: "fashion", subCategory: "mens-clothing", variant: "Black", description: "Classic polo with ribbed collar and Puma Squad branding on chest.", price: 1299, originalPrice: 2499, discount: 48, image: "/assets/products/IN-FA-PUM-019.jpg", affiliateUrl: "/go/IN-FA-PUM-019", affiliatePlatform: "myntra", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.2, reviewCount: 22000, tags: ["mens", "clothing", "polo", "puma", "squad"], apiSource: "flipkart-affiliate-free" },
  { id: "IN-FA-PUM-020", name: "Puma Squad Polo White", brand: "Puma", subBrand: "Squad", category: "fashion", subCategory: "mens-clothing", variant: "White", description: "Breathable pique cotton polo with two-button placket and contrast tipping.", price: 1299, originalPrice: 2499, discount: 48, image: "/assets/products/IN-FA-PUM-020.jpg", affiliateUrl: "/go/IN-FA-PUM-020", affiliatePlatform: "ajio", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 20000, tags: ["mens", "clothing", "polo", "puma", "squad"], apiSource: "static-only" },

  // WOMENS FOOTWEAR (021–030)
  { id: "IN-FA-PUM-021", name: "Puma Softride Ruby Running Shoes Black White", brand: "Puma", subBrand: "Softride", category: "fashion", subCategory: "womens-footwear", variant: "Black White", description: "Women-specific Softride cushioning for plush, responsive runs.", price: 3299, originalPrice: 5499, discount: 40, image: "/assets/products/IN-FA-PUM-021.jpg", affiliateUrl: "/go/IN-FA-PUM-021", affiliatePlatform: "myntra", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.3, reviewCount: 30000, tags: ["womens", "shoes", "running", "puma", "softride"], apiSource: "flipkart-affiliate-free" },
  { id: "IN-FA-PUM-022", name: "Puma Softride Ruby Running Shoes White Pink", brand: "Puma", subBrand: "Softride", category: "fashion", subCategory: "womens-footwear", variant: "White Pink", description: "Engineered mesh upper with Softride foam for weightless comfort.", price: 3299, originalPrice: 5499, discount: 40, image: "/assets/products/IN-FA-PUM-022.jpg", affiliateUrl: "/go/IN-FA-PUM-022", affiliatePlatform: "ajio", affiliateSource: "static", inStock: true, rating: 4.4, reviewCount: 28000, tags: ["womens", "shoes", "running", "puma", "softride"], apiSource: "static-only" },
  { id: "IN-FA-PUM-023", name: "Puma Softride Ruby Running Shoes Navy White", brand: "Puma", subBrand: "Softride", category: "fashion", subCategory: "womens-footwear", variant: "Navy White", description: "Rubber outsole with flex grooves for natural stride flexibility.", price: 3299, originalPrice: 5499, discount: 40, image: "/assets/products/IN-FA-PUM-023.jpg", affiliateUrl: "/go/IN-FA-PUM-023", affiliatePlatform: "myntra", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.2, reviewCount: 26000, tags: ["womens", "shoes", "running", "puma", "softride"], apiSource: "flipkart-affiliate-free" },
  { id: "IN-FA-PUM-024", name: "Puma Cruise Rider Women's Sneakers White Silver", brand: "Puma", subBrand: "Cruise Rider", category: "fashion", subCategory: "womens-footwear", variant: "White Silver", description: "Retro-inspired platform sneaker with stacked midsole and bold Formstrip.", price: 3999, originalPrice: 6999, discount: 42, image: "/assets/products/IN-FA-PUM-024.jpg", affiliateUrl: "/go/IN-FA-PUM-024", affiliatePlatform: "ajio", affiliateSource: "static", inStock: true, rating: 4.5, reviewCount: 35000, tags: ["womens", "shoes", "sneakers", "puma", "cruise-rider"], apiSource: "static-only" },
  { id: "IN-FA-PUM-025", name: "Puma Cruise Rider Women's Sneakers Pink White", brand: "Puma", subBrand: "Cruise Rider", category: "fashion", subCategory: "womens-footwear", variant: "Pink White", description: "Mixed material upper with suede overlays for a premium streetwear look.", price: 3999, originalPrice: 6999, discount: 42, image: "/assets/products/IN-FA-PUM-025.jpg", affiliateUrl: "/go/IN-FA-PUM-025", affiliatePlatform: "myntra", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.4, reviewCount: 32000, tags: ["womens", "shoes", "sneakers", "puma", "cruise-rider"], apiSource: "flipkart-affiliate-free" },
  { id: "IN-FA-PUM-026", name: "Puma Smash v3 Women's Sneakers White Black", brand: "Puma", subBrand: "Smash", category: "fashion", subCategory: "womens-footwear", variant: "White Black", description: "Women's court sneaker with leather upper and SoftFoam+ comfort insole.", price: 2999, originalPrice: 4999, discount: 40, image: "/assets/products/IN-FA-PUM-026.jpg", affiliateUrl: "/go/IN-FA-PUM-026", affiliatePlatform: "ajio", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 40000, tags: ["womens", "shoes", "sneakers", "puma", "smash"], apiSource: "static-only" },
  { id: "IN-FA-PUM-027", name: "Puma Smash v3 Women's Sneakers Lilac White", brand: "Puma", subBrand: "Smash", category: "fashion", subCategory: "womens-footwear", variant: "Lilac White", description: "Seasonal lilac colourway with padded collar for a snug, feminine fit.", price: 2999, originalPrice: 4999, discount: 40, image: "/assets/products/IN-FA-PUM-027.jpg", affiliateUrl: "/go/IN-FA-PUM-027", affiliatePlatform: "myntra", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.2, reviewCount: 37000, tags: ["womens", "shoes", "sneakers", "puma", "smash"], apiSource: "flipkart-affiliate-free" },
  { id: "IN-FA-PUM-028", name: "Puma Smash v3 Women's Sneakers All White", brand: "Puma", subBrand: "Smash", category: "fashion", subCategory: "womens-footwear", variant: "All White", description: "Clean all-white silhouette perfect for everyday casual styling.", price: 2999, originalPrice: 4999, discount: 40, image: "/assets/products/IN-FA-PUM-028.jpg", affiliateUrl: "/go/IN-FA-PUM-028", affiliatePlatform: "ajio", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 39000, tags: ["womens", "shoes", "sneakers", "puma", "smash"], apiSource: "static-only" },
  { id: "IN-FA-PUM-029", name: "Puma Graviton Women's Slip-on White", brand: "Puma", subBrand: "Graviton", category: "fashion", subCategory: "womens-footwear", variant: "White", description: "Minimalist women's slip-on with soft mesh upper and EVA midsole.", price: 2199, originalPrice: 3999, discount: 45, image: "/assets/products/IN-FA-PUM-029.jpg", affiliateUrl: "/go/IN-FA-PUM-029", affiliatePlatform: "myntra", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.0, reviewCount: 20000, tags: ["womens", "shoes", "slip-on", "puma", "graviton"], apiSource: "flipkart-affiliate-free" },
  { id: "IN-FA-PUM-030", name: "Puma Graviton Women's Slip-on Pink", brand: "Puma", subBrand: "Graviton", category: "fashion", subCategory: "womens-footwear", variant: "Pink", description: "Lightweight slip-on sneaker in blush pink for effortless everyday style.", price: 2199, originalPrice: 3999, discount: 45, image: "/assets/products/IN-FA-PUM-030.jpg", affiliateUrl: "/go/IN-FA-PUM-030", affiliatePlatform: "ajio", affiliateSource: "static", inStock: true, rating: 4.1, reviewCount: 18000, tags: ["womens", "shoes", "slip-on", "puma", "graviton"], apiSource: "static-only" },

  // WOMENS CLOTHING (031–040)
  { id: "IN-FA-PUM-031", name: "Puma Classics Relaxed Tee White", brand: "Puma", subBrand: "Classics", category: "fashion", subCategory: "womens-clothing", variant: "White", description: "Oversized relaxed fit tee with Puma Classics logo on chest.", price: 899, originalPrice: 1699, discount: 47, image: "/assets/products/IN-FA-PUM-031.jpg", affiliateUrl: "/go/IN-FA-PUM-031", affiliatePlatform: "myntra", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.2, reviewCount: 25000, tags: ["womens", "clothing", "tshirt", "puma", "classics"], apiSource: "flipkart-affiliate-free" },
  { id: "IN-FA-PUM-032", name: "Puma Classics Relaxed Tee Black", brand: "Puma", subBrand: "Classics", category: "fashion", subCategory: "womens-clothing", variant: "Black", description: "Soft cotton jersey with drop shoulders for a trendy relaxed silhouette.", price: 899, originalPrice: 1699, discount: 47, image: "/assets/products/IN-FA-PUM-032.jpg", affiliateUrl: "/go/IN-FA-PUM-032", affiliatePlatform: "ajio", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 23000, tags: ["womens", "clothing", "tshirt", "puma", "classics"], apiSource: "static-only" },
  { id: "IN-FA-PUM-033", name: "Puma Classics Relaxed Tee Pink", brand: "Puma", subBrand: "Classics", category: "fashion", subCategory: "womens-clothing", variant: "Pink", description: "Seasonal pink colourway in 100% cotton for all-day casual wear.", price: 899, originalPrice: 1699, discount: 47, image: "/assets/products/IN-FA-PUM-033.jpg", affiliateUrl: "/go/IN-FA-PUM-033", affiliatePlatform: "myntra", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.1, reviewCount: 21000, tags: ["womens", "clothing", "tshirt", "puma", "classics"], apiSource: "flipkart-affiliate-free" },
  { id: "IN-FA-PUM-034", name: "Puma Essentials Elevated Leggings Black", brand: "Puma", subBrand: "Essentials", category: "fashion", subCategory: "womens-clothing", variant: "Black", description: "High-rise leggings with dryCELL technology and flattering seam lines.", price: 1499, originalPrice: 2999, discount: 50, image: "/assets/products/IN-FA-PUM-034.jpg", affiliateUrl: "/go/IN-FA-PUM-034", affiliatePlatform: "ajio", affiliateSource: "static", inStock: true, rating: 4.4, reviewCount: 35000, tags: ["womens", "clothing", "leggings", "puma", "essentials"], apiSource: "static-only" },
  { id: "IN-FA-PUM-035", name: "Puma Essentials Elevated Leggings Navy", brand: "Puma", subBrand: "Essentials", category: "fashion", subCategory: "womens-clothing", variant: "Navy", description: "Stretchy cotton-blend fabric with Puma Cat logo at the left hip.", price: 1499, originalPrice: 2999, discount: 50, image: "/assets/products/IN-FA-PUM-035.jpg", affiliateUrl: "/go/IN-FA-PUM-035", affiliatePlatform: "myntra", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.3, reviewCount: 30000, tags: ["womens", "clothing", "leggings", "puma", "essentials"], apiSource: "flipkart-affiliate-free" },
  { id: "IN-FA-PUM-036", name: "Puma Fit Eversculpt Tight Purple", brand: "Puma", subBrand: "Fit", category: "fashion", subCategory: "womens-clothing", variant: "Purple", description: "Sculpting compression tight with mesh ventilation panels and dryCELL.", price: 1999, originalPrice: 3499, discount: 42, image: "/assets/products/IN-FA-PUM-036.jpg", affiliateUrl: "/go/IN-FA-PUM-036", affiliatePlatform: "ajio", affiliateSource: "static", inStock: true, rating: 4.2, reviewCount: 15000, tags: ["womens", "clothing", "tights", "puma", "fit", "training"], apiSource: "static-only" },
  { id: "IN-FA-PUM-037", name: "Puma Fit Eversculpt Tight Green", brand: "Puma", subBrand: "Fit", category: "fashion", subCategory: "womens-clothing", variant: "Green", description: "High-waist training tight with hidden pocket and four-way stretch.", price: 1999, originalPrice: 3499, discount: 42, image: "/assets/products/IN-FA-PUM-037.jpg", affiliateUrl: "/go/IN-FA-PUM-037", affiliatePlatform: "myntra", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.1, reviewCount: 13000, tags: ["womens", "clothing", "tights", "puma", "fit", "training"], apiSource: "flipkart-affiliate-free" },
  { id: "IN-FA-PUM-038", name: "Puma Fit Eversculpt Tight Cobalt", brand: "Puma", subBrand: "Fit", category: "fashion", subCategory: "womens-clothing", variant: "Cobalt", description: "Vibrant cobalt colourway with reflective details for low-light visibility.", price: 1999, originalPrice: 3499, discount: 42, image: "/assets/products/IN-FA-PUM-038.jpg", affiliateUrl: "/go/IN-FA-PUM-038", affiliatePlatform: "ajio", affiliateSource: "static", inStock: true, rating: 4.0, reviewCount: 12000, tags: ["womens", "clothing", "tights", "puma", "fit", "training"], apiSource: "static-only" },
  { id: "IN-FA-PUM-039", name: "Puma Squad Jogger Black", brand: "Puma", subBrand: "Squad", category: "fashion", subCategory: "womens-clothing", variant: "Black", description: "Relaxed jogger with elastic cuffs and Puma Squad graphic branding.", price: 1799, originalPrice: 2999, discount: 40, image: "/assets/products/IN-FA-PUM-039.jpg", affiliateUrl: "/go/IN-FA-PUM-039", affiliatePlatform: "myntra", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.3, reviewCount: 19000, tags: ["womens", "clothing", "jogger", "puma", "squad"], apiSource: "flipkart-affiliate-free" },
  { id: "IN-FA-PUM-040", name: "Puma Squad Jogger Lilac", brand: "Puma", subBrand: "Squad", category: "fashion", subCategory: "womens-clothing", variant: "Lilac", description: "Soft French terry jogger in lilac with front kangaroo pocket.", price: 1799, originalPrice: 2999, discount: 40, image: "/assets/products/IN-FA-PUM-040.jpg", affiliateUrl: "/go/IN-FA-PUM-040", affiliatePlatform: "ajio", affiliateSource: "static", inStock: true, rating: 4.2, reviewCount: 17000, tags: ["womens", "clothing", "jogger", "puma", "squad"], apiSource: "static-only" },

  // SPORTS ACCESSORIES (041–050)
  { id: "IN-FA-PUM-041", name: "Puma Phase Sports Backpack 21L Black", brand: "Puma", subBrand: "Phase", category: "fashion", subCategory: "sports-accessories", variant: "Black", description: "21-litre backpack with padded shoulder straps and front zip pocket.", price: 999, originalPrice: 1999, discount: 50, image: "/assets/products/IN-FA-PUM-041.jpg", affiliateUrl: "/go/IN-FA-PUM-041", affiliatePlatform: "myntra", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.3, reviewCount: 80000, tags: ["accessories", "backpack", "puma", "phase"], apiSource: "flipkart-affiliate-free" },
  { id: "IN-FA-PUM-042", name: "Puma Phase Sports Backpack 21L Navy", brand: "Puma", subBrand: "Phase", category: "fashion", subCategory: "sports-accessories", variant: "Navy", description: "Durable polyester construction with Puma Cat logo and laptop sleeve.", price: 999, originalPrice: 1999, discount: 50, image: "/assets/products/IN-FA-PUM-042.jpg", affiliateUrl: "/go/IN-FA-PUM-042", affiliatePlatform: "ajio", affiliateSource: "static", inStock: true, rating: 4.2, reviewCount: 75000, tags: ["accessories", "backpack", "puma", "phase"], apiSource: "static-only" },
  { id: "IN-FA-PUM-043", name: "Puma Phase Sports Backpack 21L Blue", brand: "Puma", subBrand: "Phase", category: "fashion", subCategory: "sports-accessories", variant: "Blue", description: "Versatile sports backpack with adjustable straps and mesh side pockets.", price: 999, originalPrice: 1999, discount: 50, image: "/assets/products/IN-FA-PUM-043.jpg", affiliateUrl: "/go/IN-FA-PUM-043", affiliatePlatform: "myntra", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.1, reviewCount: 70000, tags: ["accessories", "backpack", "puma", "phase"], apiSource: "flipkart-affiliate-free" },
  { id: "IN-FA-PUM-044", name: "Puma Team Goal Duffel Bag M Red", brand: "Puma", subBrand: "Team Goal", category: "fashion", subCategory: "sports-accessories", variant: "Red", description: "Medium duffel bag with separate shoe compartment and adjustable strap.", price: 1499, originalPrice: 2499, discount: 40, image: "/assets/products/IN-FA-PUM-044.jpg", affiliateUrl: "/go/IN-FA-PUM-044", affiliatePlatform: "ajio", affiliateSource: "static", inStock: true, rating: 4.0, reviewCount: 12000, tags: ["accessories", "duffel", "puma", "team-goal"], apiSource: "static-only" },
  { id: "IN-FA-PUM-045", name: "Puma Team Goal Duffel Bag M Green", brand: "Puma", subBrand: "Team Goal", category: "fashion", subCategory: "sports-accessories", variant: "Green", description: "Spacious main compartment with water-resistant base for gym and travel.", price: 1499, originalPrice: 2499, discount: 40, image: "/assets/products/IN-FA-PUM-045.jpg", affiliateUrl: "/go/IN-FA-PUM-045", affiliatePlatform: "myntra", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.1, reviewCount: 11000, tags: ["accessories", "duffel", "puma", "team-goal"], apiSource: "flipkart-affiliate-free" },
  { id: "IN-FA-PUM-046", name: "Puma Fundamentals Sports Bag S Black", brand: "Puma", subBrand: "Fundamentals", category: "fashion", subCategory: "sports-accessories", variant: "Black", description: "Compact sports bag with zip closure and removable shoulder strap.", price: 799, originalPrice: 1499, discount: 46, image: "/assets/products/IN-FA-PUM-046.jpg", affiliateUrl: "/go/IN-FA-PUM-046", affiliatePlatform: "ajio", affiliateSource: "static", inStock: true, rating: 4.0, reviewCount: 25000, tags: ["accessories", "sports-bag", "puma", "fundamentals"], apiSource: "static-only" },
  { id: "IN-FA-PUM-047", name: "Puma Fundamentals Sports Bag S Navy", brand: "Puma", subBrand: "Fundamentals", category: "fashion", subCategory: "sports-accessories", variant: "Navy", description: "Lightweight small duffel perfect for short gym sessions and weekend trips.", price: 799, originalPrice: 1499, discount: 46, image: "/assets/products/IN-FA-PUM-047.jpg", affiliateUrl: "/go/IN-FA-PUM-047", affiliatePlatform: "myntra", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 3.9, reviewCount: 22000, tags: ["accessories", "sports-bag", "puma", "fundamentals"], apiSource: "flipkart-affiliate-free" },
  { id: "IN-FA-PUM-048", name: "Puma Fundamentals Sports Bag S Blue", brand: "Puma", subBrand: "Fundamentals", category: "fashion", subCategory: "sports-accessories", variant: "Blue", description: "Durable polyester sports bag with inner pocket and Puma branding.", price: 799, originalPrice: 1499, discount: 46, image: "/assets/products/IN-FA-PUM-048.jpg", affiliateUrl: "/go/IN-FA-PUM-048", affiliatePlatform: "ajio", affiliateSource: "static", inStock: true, rating: 4.0, reviewCount: 20000, tags: ["accessories", "sports-bag", "puma", "fundamentals"], apiSource: "static-only" },
  { id: "IN-FA-PUM-049", name: "Puma Phase Beanie Red", brand: "Puma", subBrand: "Phase", category: "fashion", subCategory: "sports-accessories", variant: "Red", description: "Knitted acrylic beanie with embroidered Puma Cat logo for winter warmth.", price: 499, originalPrice: 999, discount: 50, image: "/assets/products/IN-FA-PUM-049.jpg", affiliateUrl: "/go/IN-FA-PUM-049", affiliatePlatform: "myntra", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.1, reviewCount: 8000, tags: ["accessories", "beanie", "puma", "phase", "winter"], apiSource: "flipkart-affiliate-free" },
  { id: "IN-FA-PUM-050", name: "Puma Phase Beanie White", brand: "Puma", subBrand: "Phase", category: "fashion", subCategory: "sports-accessories", variant: "White", description: "Snug-fit beanie with turn-up cuff and iconic Cat logo branding.", price: 499, originalPrice: 999, discount: 50, image: "/assets/products/IN-FA-PUM-050.jpg", affiliateUrl: "/go/IN-FA-PUM-050", affiliatePlatform: "ajio", affiliateSource: "static", inStock: true, rating: 4.0, reviewCount: 7000, tags: ["accessories", "beanie", "puma", "phase", "winter"], apiSource: "static-only" },
]

// ===================================================================
// Biba — 50 products (IN-FA-BIB-001 to IN-FA-BIB-050)
// Sub-categories: kurtas, kurta-sets, dupattas, palazzos-pants, suits-festive
// ===================================================================
export const BIBA_PRODUCTS: IndiaProduct[] = [
  // KURTAS (001–010)
  { id: "IN-FA-BIB-001", name: "Biba Printed Straight Kurta Red Floral", brand: "Biba", subBrand: "Printed", category: "fashion", subCategory: "kurtas", variant: "Red Floral", description: "Vibrant red floral print on pure cotton straight kurta with notch neck.", price: 899, originalPrice: 1599, discount: 43, image: "/assets/products/IN-FA-BIB-001.jpg", affiliateUrl: "/go/IN-FA-BIB-001", affiliatePlatform: "myntra", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.2, reviewCount: 28000, tags: ["womens", "kurta", "biba", "printed", "ethnic"], apiSource: "flipkart-affiliate-free" },
  { id: "IN-FA-BIB-002", name: "Biba Printed Straight Kurta Blue Paisley", brand: "Biba", subBrand: "Printed", category: "fashion", subCategory: "kurtas", variant: "Blue Paisley", description: "Traditional paisley motif on breathable cotton fabric with side slits.", price: 899, originalPrice: 1599, discount: 43, image: "/assets/products/IN-FA-BIB-002.jpg", affiliateUrl: "/go/IN-FA-BIB-002", affiliatePlatform: "ajio", affiliateSource: "static", inStock: true, rating: 4.1, reviewCount: 25000, tags: ["womens", "kurta", "biba", "printed", "ethnic"], apiSource: "static-only" },
  { id: "IN-FA-BIB-003", name: "Biba Printed Straight Kurta Green Geometric", brand: "Biba", subBrand: "Printed", category: "fashion", subCategory: "kurtas", variant: "Green Geometric", description: "Contemporary geometric print on cotton kurta with three-quarter sleeves.", price: 899, originalPrice: 1599, discount: 43, image: "/assets/products/IN-FA-BIB-003.jpg", affiliateUrl: "/go/IN-FA-BIB-003", affiliatePlatform: "myntra", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.0, reviewCount: 22000, tags: ["womens", "kurta", "biba", "printed", "ethnic"], apiSource: "flipkart-affiliate-free" },
  { id: "IN-FA-BIB-004", name: "Biba Embroidered A-Line Kurta Blue", brand: "Biba", subBrand: "Embroidered", category: "fashion", subCategory: "kurtas", variant: "Blue", description: "Delicate thread embroidery on A-line kurta with mandarin collar.", price: 1299, originalPrice: 2299, discount: 43, image: "/assets/products/IN-FA-BIB-004.jpg", affiliateUrl: "/go/IN-FA-BIB-004", affiliatePlatform: "ajio", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 20000, tags: ["womens", "kurta", "biba", "embroidered", "ethnic"], apiSource: "static-only" },
  { id: "IN-FA-BIB-005", name: "Biba Embroidered A-Line Kurta Pink", brand: "Biba", subBrand: "Embroidered", category: "fashion", subCategory: "kurtas", variant: "Pink", description: "Floral embroidery on pink cotton A-line kurta with button placket.", price: 1299, originalPrice: 2299, discount: 43, image: "/assets/products/IN-FA-BIB-005.jpg", affiliateUrl: "/go/IN-FA-BIB-005", affiliatePlatform: "myntra", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.2, reviewCount: 18000, tags: ["womens", "kurta", "biba", "embroidered", "ethnic"], apiSource: "flipkart-affiliate-free" },
  { id: "IN-FA-BIB-006", name: "Biba Embroidered A-Line Kurta Green", brand: "Biba", subBrand: "Embroidered", category: "fashion", subCategory: "kurtas", variant: "Green", description: "Rich green kurta with intricate yoke embroidery and flared hemline.", price: 1299, originalPrice: 2299, discount: 43, image: "/assets/products/IN-FA-BIB-006.jpg", affiliateUrl: "/go/IN-FA-BIB-006", affiliatePlatform: "ajio", affiliateSource: "static", inStock: true, rating: 4.1, reviewCount: 17000, tags: ["womens", "kurta", "biba", "embroidered", "ethnic"], apiSource: "static-only" },
  { id: "IN-FA-BIB-007", name: "Biba Cotton Straight Kurta White", brand: "Biba", subBrand: "Cotton", category: "fashion", subCategory: "kurtas", variant: "White", description: "Pure white cotton kurta with lace detailing at neckline and cuffs.", price: 799, originalPrice: 1399, discount: 42, image: "/assets/products/IN-FA-BIB-007.jpg", affiliateUrl: "/go/IN-FA-BIB-007", affiliatePlatform: "myntra", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.0, reviewCount: 30000, tags: ["womens", "kurta", "biba", "cotton", "ethnic"], apiSource: "flipkart-affiliate-free" },
  { id: "IN-FA-BIB-008", name: "Biba Cotton Straight Kurta Sky Blue", brand: "Biba", subBrand: "Cotton", category: "fashion", subCategory: "kurtas", variant: "Sky Blue", description: "Breathable sky blue cotton kurta with pintuck detailing on yoke.", price: 799, originalPrice: 1399, discount: 42, image: "/assets/products/IN-FA-BIB-008.jpg", affiliateUrl: "/go/IN-FA-BIB-008", affiliatePlatform: "ajio", affiliateSource: "static", inStock: true, rating: 4.1, reviewCount: 27000, tags: ["womens", "kurta", "biba", "cotton", "ethnic"], apiSource: "static-only" },
  { id: "IN-FA-BIB-009", name: "Biba Mirror Work Kurta Royal Blue", brand: "Biba", subBrand: "Mirror Work", category: "fashion", subCategory: "kurtas", variant: "Royal Blue", description: "Stunning mirror work embellishment on royal blue kurta for festive wear.", price: 1499, originalPrice: 2499, discount: 40, image: "/assets/products/IN-FA-BIB-009.jpg", affiliateUrl: "/go/IN-FA-BIB-009", affiliatePlatform: "myntra", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.4, reviewCount: 15000, tags: ["womens", "kurta", "biba", "mirror-work", "ethnic", "festive"], apiSource: "flipkart-affiliate-free" },
  { id: "IN-FA-BIB-010", name: "Biba Mirror Work Kurta Bottle Green", brand: "Biba", subBrand: "Mirror Work", category: "fashion", subCategory: "kurtas", variant: "Bottle Green", description: "Handcrafted mirror work on bottle green kurta with round neckline.", price: 1499, originalPrice: 2499, discount: 40, image: "/assets/products/IN-FA-BIB-010.jpg", affiliateUrl: "/go/IN-FA-BIB-010", affiliatePlatform: "ajio", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 14000, tags: ["womens", "kurta", "biba", "mirror-work", "ethnic", "festive"], apiSource: "static-only" },

  // KURTA SETS (011–020)
  { id: "IN-FA-BIB-011", name: "Biba 2-Piece Kurta Palazzo Set Red Floral", brand: "Biba", subBrand: "Sets", category: "fashion", subCategory: "kurta-sets", variant: "Red Floral", description: "Coordinated red floral kurta with matching palazzo pants for easy styling.", price: 1499, originalPrice: 2499, discount: 40, image: "/assets/products/IN-FA-BIB-011.jpg", affiliateUrl: "/go/IN-FA-BIB-011", affiliatePlatform: "myntra", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.3, reviewCount: 22000, tags: ["womens", "kurta-set", "biba", "palazzo", "ethnic"], apiSource: "flipkart-affiliate-free" },
  { id: "IN-FA-BIB-012", name: "Biba 2-Piece Kurta Palazzo Set Blue Paisley", brand: "Biba", subBrand: "Sets", category: "fashion", subCategory: "kurta-sets", variant: "Blue Paisley", description: "Blue paisley kurta paired with solid palazzo for a polished ethnic look.", price: 1499, originalPrice: 2499, discount: 40, image: "/assets/products/IN-FA-BIB-012.jpg", affiliateUrl: "/go/IN-FA-BIB-012", affiliatePlatform: "ajio", affiliateSource: "static", inStock: true, rating: 4.2, reviewCount: 20000, tags: ["womens", "kurta-set", "biba", "palazzo", "ethnic"], apiSource: "static-only" },
  { id: "IN-FA-BIB-013", name: "Biba 2-Piece Kurta Palazzo Set Green", brand: "Biba", subBrand: "Sets", category: "fashion", subCategory: "kurta-sets", variant: "Green", description: "Fresh green kurta set with contrast palazzo and tasselled neckline.", price: 1499, originalPrice: 2499, discount: 40, image: "/assets/products/IN-FA-BIB-013.jpg", affiliateUrl: "/go/IN-FA-BIB-013", affiliatePlatform: "myntra", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.1, reviewCount: 18000, tags: ["womens", "kurta-set", "biba", "palazzo", "ethnic"], apiSource: "flipkart-affiliate-free" },
  { id: "IN-FA-BIB-014", name: "Biba 3-Piece Kurta Salwar Dupatta Yellow", brand: "Biba", subBrand: "Sets", category: "fashion", subCategory: "kurta-sets", variant: "Yellow", description: "Complete three-piece set with kurta, salwar, and printed dupatta in sunny yellow.", price: 1999, originalPrice: 3499, discount: 42, image: "/assets/products/IN-FA-BIB-014.jpg", affiliateUrl: "/go/IN-FA-BIB-014", affiliatePlatform: "ajio", affiliateSource: "static", inStock: true, rating: 4.4, reviewCount: 16000, tags: ["womens", "kurta-set", "biba", "salwar", "dupatta", "ethnic"], apiSource: "static-only" },
  { id: "IN-FA-BIB-015", name: "Biba 3-Piece Kurta Salwar Dupatta Pink", brand: "Biba", subBrand: "Sets", category: "fashion", subCategory: "kurta-sets", variant: "Pink", description: "Elegant pink three-piece set with embroidered kurta, churidar, and net dupatta.", price: 1999, originalPrice: 3499, discount: 42, image: "/assets/products/IN-FA-BIB-015.jpg", affiliateUrl: "/go/IN-FA-BIB-015", affiliatePlatform: "myntra", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.3, reviewCount: 15000, tags: ["womens", "kurta-set", "biba", "salwar", "dupatta", "ethnic"], apiSource: "flipkart-affiliate-free" },
  { id: "IN-FA-BIB-016", name: "Biba Anarkali Kurta Pant Set Blue", brand: "Biba", subBrand: "Anarkali", category: "fashion", subCategory: "kurta-sets", variant: "Blue", description: "Flowy Anarkali kurta with fitted pants for a graceful festive silhouette.", price: 1799, originalPrice: 2999, discount: 40, image: "/assets/products/IN-FA-BIB-016.jpg", affiliateUrl: "/go/IN-FA-BIB-016", affiliatePlatform: "ajio", affiliateSource: "static", inStock: true, rating: 4.2, reviewCount: 14000, tags: ["womens", "kurta-set", "biba", "anarkali", "ethnic", "festive"], apiSource: "static-only" },
  { id: "IN-FA-BIB-017", name: "Biba Anarkali Kurta Pant Set Green", brand: "Biba", subBrand: "Anarkali", category: "fashion", subCategory: "kurta-sets", variant: "Green", description: "Rich green Anarkali with gota patti border and slim-fit pants.", price: 1799, originalPrice: 2999, discount: 40, image: "/assets/products/IN-FA-BIB-017.jpg", affiliateUrl: "/go/IN-FA-BIB-017", affiliatePlatform: "myntra", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.1, reviewCount: 13000, tags: ["womens", "kurta-set", "biba", "anarkali", "ethnic", "festive"], apiSource: "flipkart-affiliate-free" },
  { id: "IN-FA-BIB-018", name: "Biba Anarkali Kurta Pant Set Pink", brand: "Biba", subBrand: "Anarkali", category: "fashion", subCategory: "kurta-sets", variant: "Pink", description: "Blush pink Anarkali set with sequin embroidery and matching pants.", price: 1799, originalPrice: 2999, discount: 40, image: "/assets/products/IN-FA-BIB-018.jpg", affiliateUrl: "/go/IN-FA-BIB-018", affiliatePlatform: "ajio", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 12000, tags: ["womens", "kurta-set", "biba", "anarkali", "ethnic", "festive"], apiSource: "static-only" },
  { id: "IN-FA-BIB-019", name: "Biba Printed Kurta Palazzo Mustard", brand: "Biba", subBrand: "Printed", category: "fashion", subCategory: "kurta-sets", variant: "Mustard", description: "Mustard printed kurta with matching wide-leg palazzo for casual ethnic wear.", price: 1299, originalPrice: 2299, discount: 43, image: "/assets/products/IN-FA-BIB-019.jpg", affiliateUrl: "/go/IN-FA-BIB-019", affiliatePlatform: "myntra", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.0, reviewCount: 19000, tags: ["womens", "kurta-set", "biba", "printed", "palazzo", "ethnic"], apiSource: "flipkart-affiliate-free" },
  { id: "IN-FA-BIB-020", name: "Biba Printed Kurta Palazzo Teal", brand: "Biba", subBrand: "Printed", category: "fashion", subCategory: "kurta-sets", variant: "Teal", description: "Teal printed kurta and palazzo set with tassel detailing at neckline.", price: 1299, originalPrice: 2299, discount: 43, image: "/assets/products/IN-FA-BIB-020.jpg", affiliateUrl: "/go/IN-FA-BIB-020", affiliatePlatform: "ajio", affiliateSource: "static", inStock: true, rating: 4.1, reviewCount: 17000, tags: ["womens", "kurta-set", "biba", "printed", "palazzo", "ethnic"], apiSource: "static-only" },

  // DUPATTAS (021–030)
  { id: "IN-FA-BIB-021", name: "Biba Printed Chiffon Dupatta Red", brand: "Biba", subBrand: "Chiffon", category: "fashion", subCategory: "dupattas", variant: "Red", description: "Lightweight chiffon dupatta with traditional print and finished edges.", price: 499, originalPrice: 899, discount: 44, image: "/assets/products/IN-FA-BIB-021.jpg", affiliateUrl: "/go/IN-FA-BIB-021", affiliatePlatform: "myntra", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.0, reviewCount: 12000, tags: ["womens", "dupatta", "biba", "chiffon", "ethnic"], apiSource: "flipkart-affiliate-free" },
  { id: "IN-FA-BIB-022", name: "Biba Printed Chiffon Dupatta Blue", brand: "Biba", subBrand: "Chiffon", category: "fashion", subCategory: "dupattas", variant: "Blue", description: "Airy blue chiffon dupatta with block print motif and tassel trim.", price: 499, originalPrice: 899, discount: 44, image: "/assets/products/IN-FA-BIB-022.jpg", affiliateUrl: "/go/IN-FA-BIB-022", affiliatePlatform: "ajio", affiliateSource: "static", inStock: true, rating: 3.9, reviewCount: 11000, tags: ["womens", "dupatta", "biba", "chiffon", "ethnic"], apiSource: "static-only" },
  { id: "IN-FA-BIB-023", name: "Biba Printed Chiffon Dupatta Green", brand: "Biba", subBrand: "Chiffon", category: "fashion", subCategory: "dupattas", variant: "Green", description: "Fresh green chiffon dupatta with floral print perfect for summer styling.", price: 499, originalPrice: 899, discount: 44, image: "/assets/products/IN-FA-BIB-023.jpg", affiliateUrl: "/go/IN-FA-BIB-023", affiliatePlatform: "myntra", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.1, reviewCount: 10000, tags: ["womens", "dupatta", "biba", "chiffon", "ethnic"], apiSource: "flipkart-affiliate-free" },
  { id: "IN-FA-BIB-024", name: "Biba Embroidered Net Dupatta White", brand: "Biba", subBrand: "Net", category: "fashion", subCategory: "dupattas", variant: "White", description: "Delicate net dupatta with all-over thread embroidery and scallop border.", price: 699, originalPrice: 1199, discount: 41, image: "/assets/products/IN-FA-BIB-024.jpg", affiliateUrl: "/go/IN-FA-BIB-024", affiliatePlatform: "ajio", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 8000, tags: ["womens", "dupatta", "biba", "net", "embroidered", "ethnic"], apiSource: "static-only" },
  { id: "IN-FA-BIB-025", name: "Biba Embroidered Net Dupatta Ivory", brand: "Biba", subBrand: "Net", category: "fashion", subCategory: "dupattas", variant: "Ivory", description: "Ivory net dupatta with pearl-embellished border for bridal styling.", price: 699, originalPrice: 1199, discount: 41, image: "/assets/products/IN-FA-BIB-025.jpg", affiliateUrl: "/go/IN-FA-BIB-025", affiliatePlatform: "myntra", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.2, reviewCount: 7000, tags: ["womens", "dupatta", "biba", "net", "embroidered", "ethnic"], apiSource: "flipkart-affiliate-free" },
  { id: "IN-FA-BIB-026", name: "Biba Embroidered Net Dupatta Pink", brand: "Biba", subBrand: "Net", category: "fashion", subCategory: "dupattas", variant: "Pink", description: "Soft pink net dupatta with sequin embroidery for festive occasions.", price: 699, originalPrice: 1199, discount: 41, image: "/assets/products/IN-FA-BIB-026.jpg", affiliateUrl: "/go/IN-FA-BIB-026", affiliatePlatform: "ajio", affiliateSource: "static", inStock: true, rating: 4.1, reviewCount: 6500, tags: ["womens", "dupatta", "biba", "net", "embroidered", "ethnic"], apiSource: "static-only" },
  { id: "IN-FA-BIB-027", name: "Biba Bandhani Dupatta Blue", brand: "Biba", subBrand: "Bandhani", category: "fashion", subCategory: "dupattas", variant: "Blue", description: "Authentic Rajasthani bandhani tie-dye dupatta in vibrant blue.", price: 599, originalPrice: 999, discount: 40, image: "/assets/products/IN-FA-BIB-027.jpg", affiliateUrl: "/go/IN-FA-BIB-027", affiliatePlatform: "myntra", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.4, reviewCount: 9000, tags: ["womens", "dupatta", "biba", "bandhani", "ethnic", "rajasthani"], apiSource: "flipkart-affiliate-free" },
  { id: "IN-FA-BIB-028", name: "Biba Bandhani Dupatta Yellow", brand: "Biba", subBrand: "Bandhani", category: "fashion", subCategory: "dupattas", variant: "Yellow", description: "Bright yellow bandhani dupatta with mirror work border accents.", price: 599, originalPrice: 999, discount: 40, image: "/assets/products/IN-FA-BIB-028.jpg", affiliateUrl: "/go/IN-FA-BIB-028", affiliatePlatform: "ajio", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 8500, tags: ["womens", "dupatta", "biba", "bandhani", "ethnic", "rajasthani"], apiSource: "static-only" },
  { id: "IN-FA-BIB-029", name: "Biba Phulkari Dupatta Red", brand: "Biba", subBrand: "Phulkari", category: "fashion", subCategory: "dupattas", variant: "Red", description: "Traditional Punjabi phulkari embroidery on red dupatta with silk thread.", price: 799, originalPrice: 1399, discount: 42, image: "/assets/products/IN-FA-BIB-029.jpg", affiliateUrl: "/go/IN-FA-BIB-029", affiliatePlatform: "myntra", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.5, reviewCount: 7500, tags: ["womens", "dupatta", "biba", "phulkari", "ethnic", "punjabi"], apiSource: "flipkart-affiliate-free" },
  { id: "IN-FA-BIB-030", name: "Biba Phulkari Dupatta Pink", brand: "Biba", subBrand: "Phulkari", category: "fashion", subCategory: "dupattas", variant: "Pink", description: "Pink phulkari dupatta with multicolour floral embroidery and pompom lace.", price: 799, originalPrice: 1399, discount: 42, image: "/assets/products/IN-FA-BIB-030.jpg", affiliateUrl: "/go/IN-FA-BIB-030", affiliatePlatform: "ajio", affiliateSource: "static", inStock: true, rating: 4.4, reviewCount: 7000, tags: ["womens", "dupatta", "biba", "phulkari", "ethnic", "punjabi"], apiSource: "static-only" },

  // PALAZZOS AND PANTS (031–040)
  { id: "IN-FA-BIB-031", name: "Biba Printed Palazzo Pants Red", brand: "Biba", subBrand: "Palazzo", category: "fashion", subCategory: "palazzos-pants", variant: "Red", description: "Wide-leg printed palazzo pants with elasticated waistband for comfort.", price: 699, originalPrice: 1199, discount: 41, image: "/assets/products/IN-FA-BIB-031.jpg", affiliateUrl: "/go/IN-FA-BIB-031", affiliatePlatform: "myntra", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.1, reviewCount: 18000, tags: ["womens", "palazzo", "biba", "printed", "ethnic"], apiSource: "flipkart-affiliate-free" },
  { id: "IN-FA-BIB-032", name: "Biba Printed Palazzo Pants Blue", brand: "Biba", subBrand: "Palazzo", category: "fashion", subCategory: "palazzos-pants", variant: "Blue", description: "Blue printed palazzo with floral motif and drawstring waist closure.", price: 699, originalPrice: 1199, discount: 41, image: "/assets/products/IN-FA-BIB-032.jpg", affiliateUrl: "/go/IN-FA-BIB-032", affiliatePlatform: "ajio", affiliateSource: "static", inStock: true, rating: 4.0, reviewCount: 16000, tags: ["womens", "palazzo", "biba", "printed", "ethnic"], apiSource: "static-only" },
  { id: "IN-FA-BIB-033", name: "Biba Printed Palazzo Pants Green", brand: "Biba", subBrand: "Palazzo", category: "fashion", subCategory: "palazzos-pants", variant: "Green", description: "Fresh green palazzo pants in rayon fabric with ethnic block print.", price: 699, originalPrice: 1199, discount: 41, image: "/assets/products/IN-FA-BIB-033.jpg", affiliateUrl: "/go/IN-FA-BIB-033", affiliatePlatform: "myntra", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 3.9, reviewCount: 15000, tags: ["womens", "palazzo", "biba", "printed", "ethnic"], apiSource: "flipkart-affiliate-free" },
  { id: "IN-FA-BIB-034", name: "Biba Embroidered Palazzo White", brand: "Biba", subBrand: "Palazzo", category: "fashion", subCategory: "palazzos-pants", variant: "White", description: "White cotton palazzo with chikankari-inspired embroidery at hemline.", price: 899, originalPrice: 1499, discount: 40, image: "/assets/products/IN-FA-BIB-034.jpg", affiliateUrl: "/go/IN-FA-BIB-034", affiliatePlatform: "ajio", affiliateSource: "static", inStock: true, rating: 4.2, reviewCount: 14000, tags: ["womens", "palazzo", "biba", "embroidered", "ethnic"], apiSource: "static-only" },
  { id: "IN-FA-BIB-035", name: "Biba Embroidered Palazzo Blue", brand: "Biba", subBrand: "Palazzo", category: "fashion", subCategory: "palazzos-pants", variant: "Blue", description: "Blue palazzo with delicate thread embroidery and side pockets.", price: 899, originalPrice: 1499, discount: 40, image: "/assets/products/IN-FA-BIB-035.jpg", affiliateUrl: "/go/IN-FA-BIB-035", affiliatePlatform: "myntra", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.1, reviewCount: 13000, tags: ["womens", "palazzo", "biba", "embroidered", "ethnic"], apiSource: "flipkart-affiliate-free" },
  { id: "IN-FA-BIB-036", name: "Biba Embroidered Palazzo Pink", brand: "Biba", subBrand: "Palazzo", category: "fashion", subCategory: "palazzos-pants", variant: "Pink", description: "Soft pink palazzo with floral embroidery and comfortable elastic waist.", price: 899, originalPrice: 1499, discount: 40, image: "/assets/products/IN-FA-BIB-036.jpg", affiliateUrl: "/go/IN-FA-BIB-036", affiliatePlatform: "ajio", affiliateSource: "static", inStock: true, rating: 4.0, reviewCount: 12000, tags: ["womens", "palazzo", "biba", "embroidered", "ethnic"], apiSource: "static-only" },
  { id: "IN-FA-BIB-037", name: "Biba Flared Pants Black", brand: "Biba", subBrand: "Flared", category: "fashion", subCategory: "palazzos-pants", variant: "Black", description: "Solid black flared pants in stretchable cotton blend for versatile pairing.", price: 799, originalPrice: 1299, discount: 38, image: "/assets/products/IN-FA-BIB-037.jpg", affiliateUrl: "/go/IN-FA-BIB-037", affiliatePlatform: "myntra", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.2, reviewCount: 20000, tags: ["womens", "pants", "biba", "flared", "ethnic"], apiSource: "flipkart-affiliate-free" },
  { id: "IN-FA-BIB-038", name: "Biba Flared Pants Navy", brand: "Biba", subBrand: "Flared", category: "fashion", subCategory: "palazzos-pants", variant: "Navy", description: "Navy flared pants with subtle shimmer weave for semi-formal occasions.", price: 799, originalPrice: 1299, discount: 38, image: "/assets/products/IN-FA-BIB-038.jpg", affiliateUrl: "/go/IN-FA-BIB-038", affiliatePlatform: "ajio", affiliateSource: "static", inStock: true, rating: 4.1, reviewCount: 18000, tags: ["womens", "pants", "biba", "flared", "ethnic"], apiSource: "static-only" },
  { id: "IN-FA-BIB-039", name: "Biba Striped Palazzo Blue White", brand: "Biba", subBrand: "Striped", category: "fashion", subCategory: "palazzos-pants", variant: "Blue White", description: "Blue and white striped palazzo pants in lightweight cotton for summer.", price: 649, originalPrice: 1099, discount: 40, image: "/assets/products/IN-FA-BIB-039.jpg", affiliateUrl: "/go/IN-FA-BIB-039", affiliatePlatform: "myntra", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 3.9, reviewCount: 10000, tags: ["womens", "palazzo", "biba", "striped", "ethnic"], apiSource: "flipkart-affiliate-free" },
  { id: "IN-FA-BIB-040", name: "Biba Striped Palazzo Red White", brand: "Biba", subBrand: "Striped", category: "fashion", subCategory: "palazzos-pants", variant: "Red White", description: "Red and white striped palazzo with tassel drawstring and side pockets.", price: 649, originalPrice: 1099, discount: 40, image: "/assets/products/IN-FA-BIB-040.jpg", affiliateUrl: "/go/IN-FA-BIB-040", affiliatePlatform: "ajio", affiliateSource: "static", inStock: true, rating: 3.8, reviewCount: 9500, tags: ["womens", "palazzo", "biba", "striped", "ethnic"], apiSource: "static-only" },

  // SUITS AND FESTIVE (041–050)
  { id: "IN-FA-BIB-041", name: "Biba Embroidered Straight Suit 3-piece Royal Blue", brand: "Biba", subBrand: "Festive", category: "fashion", subCategory: "suits-festive", variant: "Royal Blue", description: "Royal blue straight suit with heavy embroidery, salwar, and dupatta.", price: 2999, originalPrice: 4999, discount: 40, image: "/assets/products/IN-FA-BIB-041.jpg", affiliateUrl: "/go/IN-FA-BIB-041", affiliatePlatform: "myntra", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.4, reviewCount: 10000, tags: ["womens", "suit", "biba", "festive", "embroidered", "ethnic"], apiSource: "flipkart-affiliate-free" },
  { id: "IN-FA-BIB-042", name: "Biba Embroidered Straight Suit 3-piece Bottle Green", brand: "Biba", subBrand: "Festive", category: "fashion", subCategory: "suits-festive", variant: "Bottle Green", description: "Bottle green festive suit with zari work and organza dupatta.", price: 2999, originalPrice: 4999, discount: 40, image: "/assets/products/IN-FA-BIB-042.jpg", affiliateUrl: "/go/IN-FA-BIB-042", affiliatePlatform: "ajio", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 9500, tags: ["womens", "suit", "biba", "festive", "embroidered", "ethnic"], apiSource: "static-only" },
  { id: "IN-FA-BIB-043", name: "Biba Embroidered Straight Suit 3-piece Maroon", brand: "Biba", subBrand: "Festive", category: "fashion", subCategory: "suits-festive", variant: "Maroon", description: "Rich maroon suit with gold thread embroidery and matching dupatta.", price: 2999, originalPrice: 4999, discount: 40, image: "/assets/products/IN-FA-BIB-043.jpg", affiliateUrl: "/go/IN-FA-BIB-043", affiliatePlatform: "myntra", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.5, reviewCount: 9000, tags: ["womens", "suit", "biba", "festive", "embroidered", "ethnic"], apiSource: "flipkart-affiliate-free" },
  { id: "IN-FA-BIB-044", name: "Biba Net Embellished Suit Pink", brand: "Biba", subBrand: "Festive", category: "fashion", subCategory: "suits-festive", variant: "Pink", description: "Sheer net suit with sequin embellishment for wedding and reception wear.", price: 3499, originalPrice: 5999, discount: 41, image: "/assets/products/IN-FA-BIB-044.jpg", affiliateUrl: "/go/IN-FA-BIB-044", affiliatePlatform: "ajio", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 7000, tags: ["womens", "suit", "biba", "festive", "net", "embellished", "ethnic"], apiSource: "static-only" },
  { id: "IN-FA-BIB-045", name: "Biba Net Embellished Suit Blue", brand: "Biba", subBrand: "Festive", category: "fashion", subCategory: "suits-festive", variant: "Blue", description: "Blue net suit with stone and pearl work for elegant occasion wear.", price: 3499, originalPrice: 5999, discount: 41, image: "/assets/products/IN-FA-BIB-045.jpg", affiliateUrl: "/go/IN-FA-BIB-045", affiliatePlatform: "myntra", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.2, reviewCount: 6500, tags: ["womens", "suit", "biba", "festive", "net", "embellished", "ethnic"], apiSource: "flipkart-affiliate-free" },
  { id: "IN-FA-BIB-046", name: "Biba Bandhani Silk Suit Red", brand: "Biba", subBrand: "Bandhani", category: "fashion", subCategory: "suits-festive", variant: "Red", description: "Traditional bandhani print on silk suit with contrast border and dupatta.", price: 2499, originalPrice: 3999, discount: 37, image: "/assets/products/IN-FA-BIB-046.jpg", affiliateUrl: "/go/IN-FA-BIB-046", affiliatePlatform: "ajio", affiliateSource: "static", inStock: true, rating: 4.4, reviewCount: 8000, tags: ["womens", "suit", "biba", "bandhani", "silk", "ethnic", "festive"], apiSource: "static-only" },
  { id: "IN-FA-BIB-047", name: "Biba Bandhani Silk Suit Green", brand: "Biba", subBrand: "Bandhani", category: "fashion", subCategory: "suits-festive", variant: "Green", description: "Green bandhani silk suit with gota patti lace and matching dupatta.", price: 2499, originalPrice: 3999, discount: 37, image: "/assets/products/IN-FA-BIB-047.jpg", affiliateUrl: "/go/IN-FA-BIB-047", affiliatePlatform: "myntra", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.3, reviewCount: 7500, tags: ["womens", "suit", "biba", "bandhani", "silk", "ethnic", "festive"], apiSource: "flipkart-affiliate-free" },
  { id: "IN-FA-BIB-048", name: "Biba Bandhani Silk Suit Yellow", brand: "Biba", subBrand: "Bandhani", category: "fashion", subCategory: "suits-festive", variant: "Yellow", description: "Bright yellow bandhani silk suit perfect for haldi and mehndi ceremonies.", price: 2499, originalPrice: 3999, discount: 37, image: "/assets/products/IN-FA-BIB-048.jpg", affiliateUrl: "/go/IN-FA-BIB-048", affiliatePlatform: "ajio", affiliateSource: "static", inStock: true, rating: 4.2, reviewCount: 7000, tags: ["womens", "suit", "biba", "bandhani", "silk", "ethnic", "festive"], apiSource: "static-only" },
  { id: "IN-FA-BIB-049", name: "Biba Bridal Embroidered Suit Red Gold", brand: "Biba", subBrand: "Bridal", category: "fashion", subCategory: "suits-festive", variant: "Red Gold", description: "Premium bridal suit with heavy zardozi embroidery and gold dupatta.", price: 4999, originalPrice: 8999, discount: 44, image: "/assets/products/IN-FA-BIB-049.jpg", affiliateUrl: "/go/IN-FA-BIB-049", affiliatePlatform: "myntra", affiliateSource: "flipkart-affiliate-free", inStock: true, rating: 4.5, reviewCount: 5000, tags: ["womens", "suit", "biba", "bridal", "embroidered", "ethnic", "wedding"], apiSource: "flipkart-affiliate-free" },
  { id: "IN-FA-BIB-050", name: "Biba Bridal Embroidered Suit Maroon", brand: "Biba", subBrand: "Bridal", category: "fashion", subCategory: "suits-festive", variant: "Maroon", description: "Maroon bridal suit with resham and kundan work for the wedding trousseau.", price: 4999, originalPrice: 8999, discount: 44, image: "/assets/products/IN-FA-BIB-050.jpg", affiliateUrl: "/go/IN-FA-BIB-050", affiliatePlatform: "ajio", affiliateSource: "static", inStock: true, rating: 4.5, reviewCount: 4500, tags: ["womens", "suit", "biba", "bridal", "embroidered", "ethnic", "wedding"], apiSource: "static-only" },
]
