import { IndiaProduct } from "../types"

// ===================================================================
// ITC — 50 products (IN-FG-ITC-001 to IN-FG-ITC-050)
// Sub-categories: biscuits, atta-flour, noodles-pasta, snacks, beverages
// ===================================================================
export const ITC_FOOD_PRODUCTS: IndiaProduct[] = [
  // SUNFEAST BISCUITS (001–010)
  { id: "IN-FG-ITC-001", name: "Sunfeast Dark Fantasy Choco Fills 75g", brand: "ITC", subBrand: "Sunfeast", category: "food-grocery", subCategory: "biscuits", variant: "75g", description: "Rich chocolate cream filled cookies with a crispy outer shell.", price: 30, originalPrice: 38, discount: 21, image: "/assets/products/IN-FG-ITC-001.jpg", affiliateUrl: "/go/IN-FG-ITC-001", affiliatePlatform: "bigbasket", affiliateSource: "static", inStock: true, rating: 4.4, reviewCount: 45200, tags: ["biscuits", "itc", "sunfeast", "dark-fantasy", "choco-fills"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-ITC-002", name: "Sunfeast Dark Fantasy Choco Fills 150g", brand: "ITC", subBrand: "Sunfeast", category: "food-grocery", subCategory: "biscuits", variant: "150g", description: "Double the delight with luscious chocolate filling in every bite.", price: 55, originalPrice: 69, discount: 20, image: "/assets/products/IN-FG-ITC-002.jpg", affiliateUrl: "/go/IN-FG-ITC-002", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.4, reviewCount: 38900, tags: ["biscuits", "itc", "sunfeast", "dark-fantasy", "choco-fills"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-ITC-003", name: "Sunfeast Dark Fantasy Choco Fills 300g", brand: "ITC", subBrand: "Sunfeast", category: "food-grocery", subCategory: "biscuits", variant: "300g", description: "Party-size pack of India's favourite chocolate-filled biscuits.", price: 99, originalPrice: 125, discount: 21, image: "/assets/products/IN-FG-ITC-003.jpg", affiliateUrl: "/go/IN-FG-ITC-003", affiliatePlatform: "bigbasket", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 27500, tags: ["biscuits", "itc", "sunfeast", "dark-fantasy", "choco-fills"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-ITC-004", name: "Sunfeast Dark Fantasy Choco Fills 600g", brand: "ITC", subBrand: "Sunfeast", category: "food-grocery", subCategory: "biscuits", variant: "600g", description: "Value pack of premium chocolate cream cookies for the whole family.", price: 185, originalPrice: 235, discount: 21, image: "/assets/products/IN-FG-ITC-004.jpg", affiliateUrl: "/go/IN-FG-ITC-004", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 18700, tags: ["biscuits", "itc", "sunfeast", "dark-fantasy", "choco-fills", "value-pack"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-ITC-005", name: "Sunfeast Dark Fantasy Choco Fills Family Pack 900g", brand: "ITC", subBrand: "Sunfeast", category: "food-grocery", subCategory: "biscuits", variant: "Family Pack 900g", description: "Mega family pack of Dark Fantasy Choco Fills for festive occasions.", price: 265, originalPrice: 335, discount: 21, image: "/assets/products/IN-FG-ITC-005.jpg", affiliateUrl: "/go/IN-FG-ITC-005", affiliatePlatform: "bigbasket", affiliateSource: "static", inStock: true, rating: 4.5, reviewCount: 12300, tags: ["biscuits", "itc", "sunfeast", "dark-fantasy", "choco-fills", "family-pack"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-ITC-006", name: "Sunfeast Dark Fantasy Pista Almond 75g", brand: "ITC", subBrand: "Sunfeast", category: "food-grocery", subCategory: "biscuits", variant: "75g", description: "Crunchy pistachio and almond biscuits dipped in rich chocolate.", price: 35, originalPrice: 44, discount: 20, image: "/assets/products/IN-FG-ITC-006.jpg", affiliateUrl: "/go/IN-FG-ITC-006", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.2, reviewCount: 31400, tags: ["biscuits", "itc", "sunfeast", "dark-fantasy", "pista-almond"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-ITC-007", name: "Sunfeast Dark Fantasy Pista Almond 150g", brand: "ITC", subBrand: "Sunfeast", category: "food-grocery", subCategory: "biscuits", variant: "150g", description: "Premium cookies with real pistachio and almond pieces.", price: 60, originalPrice: 75, discount: 20, image: "/assets/products/IN-FG-ITC-007.jpg", affiliateUrl: "/go/IN-FG-ITC-007", affiliatePlatform: "bigbasket", affiliateSource: "static", inStock: true, rating: 4.2, reviewCount: 25600, tags: ["biscuits", "itc", "sunfeast", "dark-fantasy", "pista-almond"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-ITC-008", name: "Sunfeast Dark Fantasy Pista Almond 300g", brand: "ITC", subBrand: "Sunfeast", category: "food-grocery", subCategory: "biscuits", variant: "300g", description: "Sharing pack of nutty chocolate biscuits with pistachio flavour.", price: 110, originalPrice: 139, discount: 21, image: "/assets/products/IN-FG-ITC-008.jpg", affiliateUrl: "/go/IN-FG-ITC-008", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.1, reviewCount: 19800, tags: ["biscuits", "itc", "sunfeast", "dark-fantasy", "pista-almond"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-ITC-009", name: "Sunfeast Dark Fantasy Pista Almond 600g", brand: "ITC", subBrand: "Sunfeast", category: "food-grocery", subCategory: "biscuits", variant: "600g", description: "Value pack with layers of chocolate and crunchy nut pieces.", price: 199, originalPrice: 249, discount: 20, image: "/assets/products/IN-FG-ITC-009.jpg", affiliateUrl: "/go/IN-FG-ITC-009", affiliatePlatform: "bigbasket", affiliateSource: "static", inStock: true, rating: 4.1, reviewCount: 14200, tags: ["biscuits", "itc", "sunfeast", "dark-fantasy", "pista-almond", "value-pack"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-ITC-010", name: "Sunfeast Dark Fantasy Pista Almond 900g", brand: "ITC", subBrand: "Sunfeast", category: "food-grocery", subCategory: "biscuits", variant: "900g", description: "Jumbo family pack of premium pista almond chocolate biscuits.", price: 285, originalPrice: 359, discount: 21, image: "/assets/products/IN-FG-ITC-010.jpg", affiliateUrl: "/go/IN-FG-ITC-010", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 8900, tags: ["biscuits", "itc", "sunfeast", "dark-fantasy", "pista-almond", "family-pack"], apiSource: "open-food-facts-free" },

  // AASHIRVAAD ATTA-FLOUR (011–020)
  { id: "IN-FG-ITC-011", name: "Aashirvaad Superior MP Atta 1kg", brand: "ITC", subBrand: "Aashirvaad", category: "food-grocery", subCategory: "atta-flour", variant: "1kg", description: "Made from the choicest Madhya Pradesh wheat for soft rotis.", price: 65, originalPrice: 75, discount: 13, image: "/assets/products/IN-FG-ITC-011.jpg", affiliateUrl: "/go/IN-FG-ITC-011", affiliatePlatform: "bigbasket", affiliateSource: "static", inStock: true, rating: 4.4, reviewCount: 50000, tags: ["atta", "itc", "aashirvaad", "wheat-flour", "1kg"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-ITC-012", name: "Aashirvaad Superior MP Atta 2kg", brand: "ITC", subBrand: "Aashirvaad", category: "food-grocery", subCategory: "atta-flour", variant: "2kg", description: "100% whole wheat atta with 0% maida for healthy rotis.", price: 125, originalPrice: 145, discount: 14, image: "/assets/products/IN-FG-ITC-012.jpg", affiliateUrl: "/go/IN-FG-ITC-012", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.4, reviewCount: 42000, tags: ["atta", "itc", "aashirvaad", "wheat-flour", "2kg"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-ITC-013", name: "Aashirvaad Superior MP Atta 5kg", brand: "ITC", subBrand: "Aashirvaad", category: "food-grocery", subCategory: "atta-flour", variant: "5kg", description: "India's most trusted atta brand for soft and fluffy chapatis.", price: 299, originalPrice: 349, discount: 14, image: "/assets/products/IN-FG-ITC-013.jpg", affiliateUrl: "/go/IN-FG-ITC-013", affiliatePlatform: "bigbasket", affiliateSource: "static", inStock: true, rating: 4.5, reviewCount: 38500, tags: ["atta", "itc", "aashirvaad", "wheat-flour", "5kg"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-ITC-014", name: "Aashirvaad Superior MP Atta 10kg", brand: "ITC", subBrand: "Aashirvaad", category: "food-grocery", subCategory: "atta-flour", variant: "10kg", description: "Bulk pack of premium whole wheat atta for large families.", price: 569, originalPrice: 659, discount: 14, image: "/assets/products/IN-FG-ITC-014.jpg", affiliateUrl: "/go/IN-FG-ITC-014", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.5, reviewCount: 29800, tags: ["atta", "itc", "aashirvaad", "wheat-flour", "10kg", "bulk"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-ITC-015", name: "Aashirvaad Superior MP Atta Combo 5kg+5kg", brand: "ITC", subBrand: "Aashirvaad", category: "food-grocery", subCategory: "atta-flour", variant: "Combo 5kg+5kg", description: "Twin-pack combo of Aashirvaad Superior MP Atta at great savings.", price: 649, originalPrice: 749, discount: 13, image: "/assets/products/IN-FG-ITC-015.jpg", affiliateUrl: "/go/IN-FG-ITC-015", affiliatePlatform: "bigbasket", affiliateSource: "static", inStock: true, rating: 4.4, reviewCount: 15600, tags: ["atta", "itc", "aashirvaad", "wheat-flour", "combo", "bulk"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-ITC-016", name: "Aashirvaad Multigrain Atta 1kg", brand: "ITC", subBrand: "Aashirvaad", category: "food-grocery", subCategory: "atta-flour", variant: "1kg", description: "Blend of 6 grains including wheat, oats, ragi, and soya for added nutrition.", price: 75, originalPrice: 87, discount: 14, image: "/assets/products/IN-FG-ITC-016.jpg", affiliateUrl: "/go/IN-FG-ITC-016", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 33200, tags: ["atta", "itc", "aashirvaad", "multigrain", "1kg"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-ITC-017", name: "Aashirvaad Multigrain Atta 2kg", brand: "ITC", subBrand: "Aashirvaad", category: "food-grocery", subCategory: "atta-flour", variant: "2kg", description: "High-fibre multigrain atta for health-conscious families.", price: 139, originalPrice: 162, discount: 14, image: "/assets/products/IN-FG-ITC-017.jpg", affiliateUrl: "/go/IN-FG-ITC-017", affiliatePlatform: "bigbasket", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 27400, tags: ["atta", "itc", "aashirvaad", "multigrain", "2kg"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-ITC-018", name: "Aashirvaad Multigrain Atta 5kg", brand: "ITC", subBrand: "Aashirvaad", category: "food-grocery", subCategory: "atta-flour", variant: "5kg", description: "Nutritious multigrain atta packed with essential vitamins and minerals.", price: 329, originalPrice: 385, discount: 15, image: "/assets/products/IN-FG-ITC-018.jpg", affiliateUrl: "/go/IN-FG-ITC-018", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.4, reviewCount: 21800, tags: ["atta", "itc", "aashirvaad", "multigrain", "5kg"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-ITC-019", name: "Aashirvaad Multigrain Atta 10kg", brand: "ITC", subBrand: "Aashirvaad", category: "food-grocery", subCategory: "atta-flour", variant: "10kg", description: "Family-size multigrain atta with goodness of 6 grains.", price: 629, originalPrice: 729, discount: 14, image: "/assets/products/IN-FG-ITC-019.jpg", affiliateUrl: "/go/IN-FG-ITC-019", affiliatePlatform: "bigbasket", affiliateSource: "static", inStock: true, rating: 4.4, reviewCount: 16500, tags: ["atta", "itc", "aashirvaad", "multigrain", "10kg", "bulk"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-ITC-020", name: "Aashirvaad Multigrain Atta Combo 5kg+5kg", brand: "ITC", subBrand: "Aashirvaad", category: "food-grocery", subCategory: "atta-flour", variant: "Combo 5kg+5kg", description: "Twin-pack combo of multigrain atta for monthly household needs.", price: 699, originalPrice: 809, discount: 14, image: "/assets/products/IN-FG-ITC-020.jpg", affiliateUrl: "/go/IN-FG-ITC-020", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 11200, tags: ["atta", "itc", "aashirvaad", "multigrain", "combo", "bulk"], apiSource: "open-food-facts-free" },

  // YIPPEE NOODLES (021–030)
  { id: "IN-FG-ITC-021", name: "Sunfeast Yippee Magic Masala Noodles 70g", brand: "ITC", subBrand: "Yippee", category: "food-grocery", subCategory: "noodles-pasta", variant: "70g", description: "Round noodle block with unique magic masala seasoning.", price: 14, originalPrice: 15, discount: 7, image: "/assets/products/IN-FG-ITC-021.jpg", affiliateUrl: "/go/IN-FG-ITC-021", affiliatePlatform: "bigbasket", affiliateSource: "static", inStock: true, rating: 4.2, reviewCount: 48000, tags: ["noodles", "itc", "yippee", "magic-masala", "instant"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-ITC-022", name: "Sunfeast Yippee Magic Masala Noodles 3-Pack", brand: "ITC", subBrand: "Yippee", category: "food-grocery", subCategory: "noodles-pasta", variant: "3-Pack", description: "Three-pack bundle of Yippee Magic Masala instant noodles.", price: 36, originalPrice: 40, discount: 10, image: "/assets/products/IN-FG-ITC-022.jpg", affiliateUrl: "/go/IN-FG-ITC-022", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.2, reviewCount: 35600, tags: ["noodles", "itc", "yippee", "magic-masala", "multi-pack"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-ITC-023", name: "Sunfeast Yippee Magic Masala Noodles 6-Pack", brand: "ITC", subBrand: "Yippee", category: "food-grocery", subCategory: "noodles-pasta", variant: "6-Pack", description: "Six-pack of India's number-two instant noodle brand.", price: 70, originalPrice: 78, discount: 10, image: "/assets/products/IN-FG-ITC-023.jpg", affiliateUrl: "/go/IN-FG-ITC-023", affiliatePlatform: "bigbasket", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 28900, tags: ["noodles", "itc", "yippee", "magic-masala", "multi-pack"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-ITC-024", name: "Sunfeast Yippee Magic Masala Noodles 12-Pack", brand: "ITC", subBrand: "Yippee", category: "food-grocery", subCategory: "noodles-pasta", variant: "12-Pack", description: "Monthly stock-up pack of Yippee Magic Masala noodles.", price: 135, originalPrice: 150, discount: 10, image: "/assets/products/IN-FG-ITC-024.jpg", affiliateUrl: "/go/IN-FG-ITC-024", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 19400, tags: ["noodles", "itc", "yippee", "magic-masala", "bulk"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-ITC-025", name: "Sunfeast Yippee Magic Masala Noodles 24-Pack", brand: "ITC", subBrand: "Yippee", category: "food-grocery", subCategory: "noodles-pasta", variant: "24-Pack", description: "Mega saver pack of Yippee Magic Masala for large families.", price: 260, originalPrice: 289, discount: 10, image: "/assets/products/IN-FG-ITC-025.jpg", affiliateUrl: "/go/IN-FG-ITC-025", affiliatePlatform: "bigbasket", affiliateSource: "static", inStock: true, rating: 4.4, reviewCount: 12100, tags: ["noodles", "itc", "yippee", "magic-masala", "mega-pack"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-ITC-026", name: "Sunfeast Yippee Classic Masala Noodles 70g", brand: "ITC", subBrand: "Yippee", category: "food-grocery", subCategory: "noodles-pasta", variant: "70g", description: "Classic masala flavour with long slurpy noodles that don't clump.", price: 14, originalPrice: 15, discount: 7, image: "/assets/products/IN-FG-ITC-026.jpg", affiliateUrl: "/go/IN-FG-ITC-026", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.1, reviewCount: 39500, tags: ["noodles", "itc", "yippee", "classic-masala", "instant"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-ITC-027", name: "Sunfeast Yippee Classic Masala Noodles 3-Pack", brand: "ITC", subBrand: "Yippee", category: "food-grocery", subCategory: "noodles-pasta", variant: "3-Pack", description: "Three-pack of classic masala noodles with a tangy twist.", price: 36, originalPrice: 40, discount: 10, image: "/assets/products/IN-FG-ITC-027.jpg", affiliateUrl: "/go/IN-FG-ITC-027", affiliatePlatform: "bigbasket", affiliateSource: "static", inStock: true, rating: 4.1, reviewCount: 27800, tags: ["noodles", "itc", "yippee", "classic-masala", "multi-pack"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-ITC-028", name: "Sunfeast Yippee Classic Masala Noodles 6-Pack", brand: "ITC", subBrand: "Yippee", category: "food-grocery", subCategory: "noodles-pasta", variant: "6-Pack", description: "Affordable six-pack of Yippee Classic Masala for weekly meals.", price: 70, originalPrice: 78, discount: 10, image: "/assets/products/IN-FG-ITC-028.jpg", affiliateUrl: "/go/IN-FG-ITC-028", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.0, reviewCount: 21300, tags: ["noodles", "itc", "yippee", "classic-masala", "multi-pack"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-ITC-029", name: "Sunfeast Yippee Classic Masala Noodles 12-Pack", brand: "ITC", subBrand: "Yippee", category: "food-grocery", subCategory: "noodles-pasta", variant: "12-Pack", description: "Dozen pack of classic flavoured instant noodles for pantry stock.", price: 135, originalPrice: 150, discount: 10, image: "/assets/products/IN-FG-ITC-029.jpg", affiliateUrl: "/go/IN-FG-ITC-029", affiliatePlatform: "bigbasket", affiliateSource: "static", inStock: true, rating: 4.0, reviewCount: 15700, tags: ["noodles", "itc", "yippee", "classic-masala", "bulk"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-ITC-030", name: "Sunfeast Yippee Classic Masala Noodles 24-Pack", brand: "ITC", subBrand: "Yippee", category: "food-grocery", subCategory: "noodles-pasta", variant: "24-Pack", description: "Mega value box of 24 Yippee Classic Masala noodle packs.", price: 260, originalPrice: 289, discount: 10, image: "/assets/products/IN-FG-ITC-030.jpg", affiliateUrl: "/go/IN-FG-ITC-030", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.1, reviewCount: 9800, tags: ["noodles", "itc", "yippee", "classic-masala", "mega-pack"], apiSource: "open-food-facts-free" },

  // BINGO SNACKS (031–040)
  { id: "IN-FG-ITC-031", name: "Bingo Mad Angles Achaari Masti 26g", brand: "ITC", subBrand: "Bingo", category: "food-grocery", subCategory: "snacks", variant: "26g", description: "Triangle-shaped chips with tangy achaari pickle flavour.", price: 10, originalPrice: 11, discount: 9, image: "/assets/products/IN-FG-ITC-031.jpg", affiliateUrl: "/go/IN-FG-ITC-031", affiliatePlatform: "bigbasket", affiliateSource: "static", inStock: true, rating: 4.1, reviewCount: 28900, tags: ["snacks", "itc", "bingo", "mad-angles", "achaari"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-ITC-032", name: "Bingo Mad Angles Achaari Masti 55g", brand: "ITC", subBrand: "Bingo", category: "food-grocery", subCategory: "snacks", variant: "55g", description: "Bigger pack of the addictive achaari flavoured corn snack.", price: 20, originalPrice: 22, discount: 9, image: "/assets/products/IN-FG-ITC-032.jpg", affiliateUrl: "/go/IN-FG-ITC-032", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.1, reviewCount: 24500, tags: ["snacks", "itc", "bingo", "mad-angles", "achaari"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-ITC-033", name: "Bingo Mad Angles Achaari Masti 3x55g", brand: "ITC", subBrand: "Bingo", category: "food-grocery", subCategory: "snacks", variant: "3x55g", description: "Triple pack of Mad Angles Achaari Masti for sharing.", price: 55, originalPrice: 61, discount: 10, image: "/assets/products/IN-FG-ITC-033.jpg", affiliateUrl: "/go/IN-FG-ITC-033", affiliatePlatform: "bigbasket", affiliateSource: "static", inStock: true, rating: 4.2, reviewCount: 16700, tags: ["snacks", "itc", "bingo", "mad-angles", "achaari", "multi-pack"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-ITC-034", name: "Bingo Mad Angles Achaari Masti 6x55g", brand: "ITC", subBrand: "Bingo", category: "food-grocery", subCategory: "snacks", variant: "6x55g", description: "Six-pack of tangy achaari corn triangles for parties.", price: 105, originalPrice: 116, discount: 9, image: "/assets/products/IN-FG-ITC-034.jpg", affiliateUrl: "/go/IN-FG-ITC-034", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.2, reviewCount: 11300, tags: ["snacks", "itc", "bingo", "mad-angles", "achaari", "party-pack"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-ITC-035", name: "Bingo Mad Angles Achaari Masti 12x55g", brand: "ITC", subBrand: "Bingo", category: "food-grocery", subCategory: "snacks", variant: "12x55g", description: "Mega carton of 12 packs for office pantry or home stocking.", price: 199, originalPrice: 220, discount: 10, image: "/assets/products/IN-FG-ITC-035.jpg", affiliateUrl: "/go/IN-FG-ITC-035", affiliatePlatform: "bigbasket", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 7600, tags: ["snacks", "itc", "bingo", "mad-angles", "achaari", "bulk"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-ITC-036", name: "Bingo Original Style Salted 26g", brand: "ITC", subBrand: "Bingo", category: "food-grocery", subCategory: "snacks", variant: "26g", description: "Thin crispy potato chips with classic salted flavour.", price: 10, originalPrice: 11, discount: 9, image: "/assets/products/IN-FG-ITC-036.jpg", affiliateUrl: "/go/IN-FG-ITC-036", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.0, reviewCount: 22100, tags: ["snacks", "itc", "bingo", "original-style", "salted"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-ITC-037", name: "Bingo Original Style Salted 55g", brand: "ITC", subBrand: "Bingo", category: "food-grocery", subCategory: "snacks", variant: "55g", description: "Perfectly salted potato chips for everyday snacking.", price: 20, originalPrice: 22, discount: 9, image: "/assets/products/IN-FG-ITC-037.jpg", affiliateUrl: "/go/IN-FG-ITC-037", affiliatePlatform: "bigbasket", affiliateSource: "static", inStock: true, rating: 4.0, reviewCount: 18900, tags: ["snacks", "itc", "bingo", "original-style", "salted"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-ITC-038", name: "Bingo Original Style Salted 3x55g", brand: "ITC", subBrand: "Bingo", category: "food-grocery", subCategory: "snacks", variant: "3x55g", description: "Triple pack of classic salted chips for the whole gang.", price: 55, originalPrice: 61, discount: 10, image: "/assets/products/IN-FG-ITC-038.jpg", affiliateUrl: "/go/IN-FG-ITC-038", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 3.9, reviewCount: 13400, tags: ["snacks", "itc", "bingo", "original-style", "salted", "multi-pack"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-ITC-039", name: "Bingo Original Style Salted 6x55g", brand: "ITC", subBrand: "Bingo", category: "food-grocery", subCategory: "snacks", variant: "6x55g", description: "Six-pack of salted potato chips for gatherings and events.", price: 105, originalPrice: 116, discount: 9, image: "/assets/products/IN-FG-ITC-039.jpg", affiliateUrl: "/go/IN-FG-ITC-039", affiliatePlatform: "bigbasket", affiliateSource: "static", inStock: true, rating: 3.9, reviewCount: 9200, tags: ["snacks", "itc", "bingo", "original-style", "salted", "party-pack"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-ITC-040", name: "Bingo Original Style Salted 12x55g", brand: "ITC", subBrand: "Bingo", category: "food-grocery", subCategory: "snacks", variant: "12x55g", description: "Bulk carton of Bingo Original Style Salted chips.", price: 199, originalPrice: 220, discount: 10, image: "/assets/products/IN-FG-ITC-040.jpg", affiliateUrl: "/go/IN-FG-ITC-040", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.0, reviewCount: 6800, tags: ["snacks", "itc", "bingo", "original-style", "salted", "bulk"], apiSource: "open-food-facts-free" },

  // B NATURAL & FABELLE BEVERAGES (041–050)
  { id: "IN-FG-ITC-041", name: "B Natural Mixed Fruit Juice 1L", brand: "ITC", subBrand: "B Natural", category: "food-grocery", subCategory: "beverages", variant: "1L", description: "100% Indian fruit juice with no added preservatives.", price: 99, originalPrice: 115, discount: 14, image: "/assets/products/IN-FG-ITC-041.jpg", affiliateUrl: "/go/IN-FG-ITC-041", affiliatePlatform: "bigbasket", affiliateSource: "static", inStock: true, rating: 4.2, reviewCount: 19800, tags: ["beverages", "itc", "b-natural", "mixed-fruit", "juice"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-ITC-042", name: "B Natural Mixed Fruit Juice 1L 2-Pack", brand: "ITC", subBrand: "B Natural", category: "food-grocery", subCategory: "beverages", variant: "2-Pack", description: "Twin pack of mixed fruit juice for the health-conscious household.", price: 189, originalPrice: 219, discount: 14, image: "/assets/products/IN-FG-ITC-042.jpg", affiliateUrl: "/go/IN-FG-ITC-042", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.2, reviewCount: 14500, tags: ["beverages", "itc", "b-natural", "mixed-fruit", "juice", "twin-pack"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-ITC-043", name: "B Natural Mixed Fruit Juice 1L 6-Pack", brand: "ITC", subBrand: "B Natural", category: "food-grocery", subCategory: "beverages", variant: "6-Pack", description: "Six-pack carton of B Natural Mixed Fruit for monthly supply.", price: 549, originalPrice: 639, discount: 14, image: "/assets/products/IN-FG-ITC-043.jpg", affiliateUrl: "/go/IN-FG-ITC-043", affiliatePlatform: "bigbasket", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 8900, tags: ["beverages", "itc", "b-natural", "mixed-fruit", "juice", "bulk"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-ITC-044", name: "B Natural Mixed Fruit Juice 200ml 6-Pack", brand: "ITC", subBrand: "B Natural", category: "food-grocery", subCategory: "beverages", variant: "200ml 6-Pack", description: "Convenient on-the-go packs of mixed fruit juice for kids.", price: 120, originalPrice: 139, discount: 14, image: "/assets/products/IN-FG-ITC-044.jpg", affiliateUrl: "/go/IN-FG-ITC-044", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.1, reviewCount: 12300, tags: ["beverages", "itc", "b-natural", "mixed-fruit", "juice", "mini-pack"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-ITC-045", name: "B Natural Mixed Fruit Juice 500ml", brand: "ITC", subBrand: "B Natural", category: "food-grocery", subCategory: "beverages", variant: "500ml", description: "Half-litre pack of refreshing mixed fruit juice blend.", price: 65, originalPrice: 75, discount: 13, image: "/assets/products/IN-FG-ITC-045.jpg", affiliateUrl: "/go/IN-FG-ITC-045", affiliatePlatform: "bigbasket", affiliateSource: "static", inStock: true, rating: 4.1, reviewCount: 16200, tags: ["beverages", "itc", "b-natural", "mixed-fruit", "juice"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-ITC-046", name: "B Natural Mango Juice 1L", brand: "ITC", subBrand: "B Natural", category: "food-grocery", subCategory: "beverages", variant: "1L", description: "Made from Totapuri and Alphonso mangoes with no added preservatives.", price: 99, originalPrice: 115, discount: 14, image: "/assets/products/IN-FG-ITC-046.jpg", affiliateUrl: "/go/IN-FG-ITC-046", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 22400, tags: ["beverages", "itc", "b-natural", "mango", "juice"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-ITC-047", name: "B Natural Mango Juice 1L 2-Pack", brand: "ITC", subBrand: "B Natural", category: "food-grocery", subCategory: "beverages", variant: "2-Pack", description: "Double pack of India's favourite mango juice brand.", price: 189, originalPrice: 219, discount: 14, image: "/assets/products/IN-FG-ITC-047.jpg", affiliateUrl: "/go/IN-FG-ITC-047", affiliatePlatform: "bigbasket", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 17600, tags: ["beverages", "itc", "b-natural", "mango", "juice", "twin-pack"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-ITC-048", name: "Fabelle Dark Chocolate Bar 55g", brand: "ITC", subBrand: "Fabelle", category: "food-grocery", subCategory: "beverages", variant: "55g Single", description: "Handcrafted luxury dark chocolate with 70% cocoa from ITC's master chocolatiers.", price: 150, originalPrice: 175, discount: 14, image: "/assets/products/IN-FG-ITC-048.jpg", affiliateUrl: "/go/IN-FG-ITC-048", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.5, reviewCount: 8700, tags: ["chocolate", "itc", "fabelle", "dark-chocolate", "premium"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-ITC-049", name: "Fabelle Dark Chocolate Bar 55g 3-Pack", brand: "ITC", subBrand: "Fabelle", category: "food-grocery", subCategory: "beverages", variant: "3-Pack", description: "Triple indulgence pack of Fabelle luxury dark chocolate bars.", price: 399, originalPrice: 465, discount: 14, image: "/assets/products/IN-FG-ITC-049.jpg", affiliateUrl: "/go/IN-FG-ITC-049", affiliatePlatform: "bigbasket", affiliateSource: "static", inStock: true, rating: 4.5, reviewCount: 5400, tags: ["chocolate", "itc", "fabelle", "dark-chocolate", "premium", "gift"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-ITC-050", name: "Fabelle Dark Chocolate Bar 55g 6-Pack", brand: "ITC", subBrand: "Fabelle", category: "food-grocery", subCategory: "beverages", variant: "6-Pack", description: "Premium gift box of six Fabelle dark chocolate bars.", price: 749, originalPrice: 869, discount: 14, image: "/assets/products/IN-FG-ITC-050.jpg", affiliateUrl: "/go/IN-FG-ITC-050", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.4, reviewCount: 3200, tags: ["chocolate", "itc", "fabelle", "dark-chocolate", "premium", "gift-box"], apiSource: "open-food-facts-free" },
]

// ===================================================================
// Britannia — 50 products (IN-FG-BRI-001 to IN-FG-BRI-050)
// Sub-categories: biscuits, breads-dairy, cakes-pastries, rusks-crackers, specialty
// ===================================================================
export const BRITANNIA_PRODUCTS: IndiaProduct[] = [
  // BISCUITS (001–010)
  { id: "IN-FG-BRI-001", name: "Britannia Good Day Butter Cookies 75g", brand: "Britannia", subBrand: "Good Day", category: "food-grocery", subCategory: "biscuits", variant: "75g", description: "Rich buttery cookies with a melt-in-your-mouth texture.", price: 25, originalPrice: 29, discount: 14, image: "/assets/products/IN-FG-BRI-001.jpg", affiliateUrl: "/go/IN-FG-BRI-001", affiliatePlatform: "bigbasket", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 42100, tags: ["biscuits", "britannia", "good-day", "butter-cookies"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-BRI-002", name: "Britannia Good Day Butter Cookies 150g", brand: "Britannia", subBrand: "Good Day", category: "food-grocery", subCategory: "biscuits", variant: "150g", description: "Delicious buttery biscuits perfect with tea or coffee.", price: 45, originalPrice: 52, discount: 13, image: "/assets/products/IN-FG-BRI-002.jpg", affiliateUrl: "/go/IN-FG-BRI-002", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 36800, tags: ["biscuits", "britannia", "good-day", "butter-cookies"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-BRI-003", name: "Britannia Good Day Butter Cookies 300g", brand: "Britannia", subBrand: "Good Day", category: "food-grocery", subCategory: "biscuits", variant: "300g", description: "Family sharing pack of crunchy butter cookies.", price: 85, originalPrice: 99, discount: 14, image: "/assets/products/IN-FG-BRI-003.jpg", affiliateUrl: "/go/IN-FG-BRI-003", affiliatePlatform: "bigbasket", affiliateSource: "static", inStock: true, rating: 4.2, reviewCount: 28400, tags: ["biscuits", "britannia", "good-day", "butter-cookies"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-BRI-004", name: "Britannia Good Day Butter Cookies 600g", brand: "Britannia", subBrand: "Good Day", category: "food-grocery", subCategory: "biscuits", variant: "600g", description: "Value pack of India's favourite buttery biscuit brand.", price: 160, originalPrice: 185, discount: 14, image: "/assets/products/IN-FG-BRI-004.jpg", affiliateUrl: "/go/IN-FG-BRI-004", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.2, reviewCount: 19700, tags: ["biscuits", "britannia", "good-day", "butter-cookies", "value-pack"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-BRI-005", name: "Britannia Good Day Butter Cookies 1kg", brand: "Britannia", subBrand: "Good Day", category: "food-grocery", subCategory: "biscuits", variant: "1kg", description: "Mega pack of Good Day Butter cookies for the whole family.", price: 249, originalPrice: 289, discount: 14, image: "/assets/products/IN-FG-BRI-005.jpg", affiliateUrl: "/go/IN-FG-BRI-005", affiliatePlatform: "bigbasket", affiliateSource: "static", inStock: true, rating: 4.4, reviewCount: 13200, tags: ["biscuits", "britannia", "good-day", "butter-cookies", "bulk"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-BRI-006", name: "Britannia Marie Gold Biscuits 75g", brand: "Britannia", subBrand: "Marie Gold", category: "food-grocery", subCategory: "biscuits", variant: "75g", description: "Light and crispy Marie biscuits enriched with vitamins.", price: 20, originalPrice: 23, discount: 13, image: "/assets/products/IN-FG-BRI-006.jpg", affiliateUrl: "/go/IN-FG-BRI-006", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.1, reviewCount: 38600, tags: ["biscuits", "britannia", "marie-gold", "light"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-BRI-007", name: "Britannia Marie Gold Biscuits 200g", brand: "Britannia", subBrand: "Marie Gold", category: "food-grocery", subCategory: "biscuits", variant: "200g", description: "The classic Indian Marie biscuit trusted for over 100 years.", price: 40, originalPrice: 46, discount: 13, image: "/assets/products/IN-FG-BRI-007.jpg", affiliateUrl: "/go/IN-FG-BRI-007", affiliatePlatform: "bigbasket", affiliateSource: "static", inStock: true, rating: 4.1, reviewCount: 32500, tags: ["biscuits", "britannia", "marie-gold", "classic"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-BRI-008", name: "Britannia Marie Gold Biscuits 400g", brand: "Britannia", subBrand: "Marie Gold", category: "food-grocery", subCategory: "biscuits", variant: "400g", description: "Wholesome Marie biscuits with zero trans-fat.", price: 75, originalPrice: 87, discount: 14, image: "/assets/products/IN-FG-BRI-008.jpg", affiliateUrl: "/go/IN-FG-BRI-008", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.0, reviewCount: 25300, tags: ["biscuits", "britannia", "marie-gold", "family-pack"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-BRI-009", name: "Britannia Marie Gold Biscuits 800g", brand: "Britannia", subBrand: "Marie Gold", category: "food-grocery", subCategory: "biscuits", variant: "800g", description: "Large family pack of crunchy Marie Gold biscuits.", price: 145, originalPrice: 169, discount: 14, image: "/assets/products/IN-FG-BRI-009.jpg", affiliateUrl: "/go/IN-FG-BRI-009", affiliatePlatform: "bigbasket", affiliateSource: "static", inStock: true, rating: 4.0, reviewCount: 17800, tags: ["biscuits", "britannia", "marie-gold", "value-pack"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-BRI-010", name: "Britannia Marie Gold Biscuits 1kg", brand: "Britannia", subBrand: "Marie Gold", category: "food-grocery", subCategory: "biscuits", variant: "1kg", description: "Jumbo pack of India's most popular Marie biscuit brand.", price: 175, originalPrice: 205, discount: 15, image: "/assets/products/IN-FG-BRI-010.jpg", affiliateUrl: "/go/IN-FG-BRI-010", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.1, reviewCount: 11600, tags: ["biscuits", "britannia", "marie-gold", "bulk"], apiSource: "open-food-facts-free" },

  // BREADS AND DAIRY (011–020)
  { id: "IN-FG-BRI-011", name: "Britannia 100% Whole Wheat Bread 400g", brand: "Britannia", subBrand: "Bread", category: "food-grocery", subCategory: "breads-dairy", variant: "400g", description: "Soft whole wheat bread with fibre for a healthy breakfast.", price: 55, originalPrice: 62, discount: 11, image: "/assets/products/IN-FG-BRI-011.jpg", affiliateUrl: "/go/IN-FG-BRI-011", affiliatePlatform: "bigbasket", affiliateSource: "static", inStock: true, rating: 4.0, reviewCount: 18900, tags: ["bread", "britannia", "whole-wheat", "breakfast"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-BRI-012", name: "Britannia 100% Whole Wheat Bread 500g", brand: "Britannia", subBrand: "Bread", category: "food-grocery", subCategory: "breads-dairy", variant: "500g", description: "Large loaf of nutritious whole wheat bread for the family.", price: 65, originalPrice: 73, discount: 11, image: "/assets/products/IN-FG-BRI-012.jpg", affiliateUrl: "/go/IN-FG-BRI-012", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.0, reviewCount: 15600, tags: ["bread", "britannia", "whole-wheat", "breakfast"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-BRI-013", name: "Britannia 100% Whole Wheat Bread 200g", brand: "Britannia", subBrand: "Bread", category: "food-grocery", subCategory: "breads-dairy", variant: "200g", description: "Compact bread pack ideal for small households.", price: 35, originalPrice: 39, discount: 10, image: "/assets/products/IN-FG-BRI-013.jpg", affiliateUrl: "/go/IN-FG-BRI-013", affiliatePlatform: "bigbasket", affiliateSource: "static", inStock: true, rating: 3.9, reviewCount: 12300, tags: ["bread", "britannia", "whole-wheat", "small-pack"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-BRI-014", name: "Britannia 100% Whole Wheat Bread 2x400g", brand: "Britannia", subBrand: "Bread", category: "food-grocery", subCategory: "breads-dairy", variant: "2x400g", description: "Twin-pack of whole wheat bread for weekly consumption.", price: 105, originalPrice: 118, discount: 11, image: "/assets/products/IN-FG-BRI-014.jpg", affiliateUrl: "/go/IN-FG-BRI-014", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.0, reviewCount: 8700, tags: ["bread", "britannia", "whole-wheat", "twin-pack"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-BRI-015", name: "Britannia Multigrain Bread 400g", brand: "Britannia", subBrand: "Bread", category: "food-grocery", subCategory: "breads-dairy", variant: "Multigrain 400g", description: "Multigrain bread with oats, ragi, and wheat for added nutrition.", price: 70, originalPrice: 79, discount: 11, image: "/assets/products/IN-FG-BRI-015.jpg", affiliateUrl: "/go/IN-FG-BRI-015", affiliatePlatform: "bigbasket", affiliateSource: "static", inStock: true, rating: 4.1, reviewCount: 9400, tags: ["bread", "britannia", "multigrain", "healthy"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-BRI-016", name: "Britannia Cheese Slices 200g", brand: "Britannia", subBrand: "Cheese", category: "food-grocery", subCategory: "breads-dairy", variant: "200g", description: "Creamy processed cheese slices perfect for sandwiches and burgers.", price: 115, originalPrice: 129, discount: 11, image: "/assets/products/IN-FG-BRI-016.jpg", affiliateUrl: "/go/IN-FG-BRI-016", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.2, reviewCount: 21500, tags: ["cheese", "britannia", "slices", "dairy"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-BRI-017", name: "Britannia Cheese Slices 400g", brand: "Britannia", subBrand: "Cheese", category: "food-grocery", subCategory: "breads-dairy", variant: "400g", description: "Family pack of smooth melting cheese slices.", price: 215, originalPrice: 241, discount: 11, image: "/assets/products/IN-FG-BRI-017.jpg", affiliateUrl: "/go/IN-FG-BRI-017", affiliatePlatform: "bigbasket", affiliateSource: "static", inStock: true, rating: 4.2, reviewCount: 16800, tags: ["cheese", "britannia", "slices", "dairy", "family-pack"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-BRI-018", name: "Britannia Cheese Slices 750g", brand: "Britannia", subBrand: "Cheese", category: "food-grocery", subCategory: "breads-dairy", variant: "750g", description: "Bulk pack of premium processed cheese slices for restaurants.", price: 385, originalPrice: 431, discount: 11, image: "/assets/products/IN-FG-BRI-018.jpg", affiliateUrl: "/go/IN-FG-BRI-018", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 9200, tags: ["cheese", "britannia", "slices", "dairy", "bulk"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-BRI-019", name: "Britannia Cheese Slices 100g", brand: "Britannia", subBrand: "Cheese", category: "food-grocery", subCategory: "breads-dairy", variant: "100g", description: "Handy small pack of cheese slices for quick snacks.", price: 65, originalPrice: 73, discount: 11, image: "/assets/products/IN-FG-BRI-019.jpg", affiliateUrl: "/go/IN-FG-BRI-019", affiliatePlatform: "bigbasket", affiliateSource: "static", inStock: true, rating: 4.1, reviewCount: 14300, tags: ["cheese", "britannia", "slices", "dairy", "small-pack"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-BRI-020", name: "Britannia Smoked Cheese Slices 200g", brand: "Britannia", subBrand: "Cheese", category: "food-grocery", subCategory: "breads-dairy", variant: "Smoked 200g", description: "Smoky flavoured cheese slices for gourmet sandwiches.", price: 135, originalPrice: 151, discount: 11, image: "/assets/products/IN-FG-BRI-020.jpg", affiliateUrl: "/go/IN-FG-BRI-020", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.0, reviewCount: 7600, tags: ["cheese", "britannia", "smoked", "slices", "dairy", "premium"], apiSource: "open-food-facts-free" },

  // CAKES (021–030)
  { id: "IN-FG-BRI-021", name: "Britannia Chocolate Layer Cake 55g", brand: "Britannia", subBrand: "Cakes", category: "food-grocery", subCategory: "cakes-pastries", variant: "55g Single", description: "Soft chocolate cake with creamy layers for a quick treat.", price: 20, originalPrice: 23, discount: 13, image: "/assets/products/IN-FG-BRI-021.jpg", affiliateUrl: "/go/IN-FG-BRI-021", affiliatePlatform: "bigbasket", affiliateSource: "static", inStock: true, rating: 4.1, reviewCount: 25600, tags: ["cake", "britannia", "chocolate", "snack-cake"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-BRI-022", name: "Britannia Chocolate Layer Cake 55g 6-Pack", brand: "Britannia", subBrand: "Cakes", category: "food-grocery", subCategory: "cakes-pastries", variant: "6-Pack", description: "Six-pack of chocolate cakes perfect for kids' lunchboxes.", price: 110, originalPrice: 129, discount: 15, image: "/assets/products/IN-FG-BRI-022.jpg", affiliateUrl: "/go/IN-FG-BRI-022", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.1, reviewCount: 18900, tags: ["cake", "britannia", "chocolate", "multi-pack"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-BRI-023", name: "Britannia Chocolate Layer Cake 55g 12-Pack", brand: "Britannia", subBrand: "Cakes", category: "food-grocery", subCategory: "cakes-pastries", variant: "12-Pack", description: "Dozen pack of soft chocolate layer cakes for parties.", price: 210, originalPrice: 245, discount: 14, image: "/assets/products/IN-FG-BRI-023.jpg", affiliateUrl: "/go/IN-FG-BRI-023", affiliatePlatform: "bigbasket", affiliateSource: "static", inStock: true, rating: 4.2, reviewCount: 12400, tags: ["cake", "britannia", "chocolate", "party-pack"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-BRI-024", name: "Britannia Chocolate Layer Cake 55g 24-Pack", brand: "Britannia", subBrand: "Cakes", category: "food-grocery", subCategory: "cakes-pastries", variant: "24-Pack", description: "Bulk carton of chocolate cakes for canteen and office supply.", price: 399, originalPrice: 465, discount: 14, image: "/assets/products/IN-FG-BRI-024.jpg", affiliateUrl: "/go/IN-FG-BRI-024", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.2, reviewCount: 7800, tags: ["cake", "britannia", "chocolate", "bulk"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-BRI-025", name: "Britannia Chocolate Layer Cake Combo Pack", brand: "Britannia", subBrand: "Cakes", category: "food-grocery", subCategory: "cakes-pastries", variant: "Combo Pack", description: "Assorted combo of chocolate and vanilla layer cakes.", price: 450, originalPrice: 525, discount: 14, image: "/assets/products/IN-FG-BRI-025.jpg", affiliateUrl: "/go/IN-FG-BRI-025", affiliatePlatform: "bigbasket", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 5400, tags: ["cake", "britannia", "chocolate", "vanilla", "combo"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-BRI-026", name: "Britannia Pure Magic Chocolate Chunk Cookies 75g", brand: "Britannia", subBrand: "Pure Magic", category: "food-grocery", subCategory: "cakes-pastries", variant: "75g", description: "Premium chocolate chunk cookies with rich cocoa flavour.", price: 30, originalPrice: 35, discount: 14, image: "/assets/products/IN-FG-BRI-026.jpg", affiliateUrl: "/go/IN-FG-BRI-026", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.2, reviewCount: 22100, tags: ["cookies", "britannia", "pure-magic", "chocolate-chunk"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-BRI-027", name: "Britannia Pure Magic Chocolate Chunk Cookies 150g", brand: "Britannia", subBrand: "Pure Magic", category: "food-grocery", subCategory: "cakes-pastries", variant: "150g", description: "Indulgent cookies loaded with real chocolate chunks.", price: 55, originalPrice: 65, discount: 15, image: "/assets/products/IN-FG-BRI-027.jpg", affiliateUrl: "/go/IN-FG-BRI-027", affiliatePlatform: "bigbasket", affiliateSource: "static", inStock: true, rating: 4.2, reviewCount: 17800, tags: ["cookies", "britannia", "pure-magic", "chocolate-chunk"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-BRI-028", name: "Britannia Pure Magic Chocolate Chunk Cookies 3-Pack", brand: "Britannia", subBrand: "Pure Magic", category: "food-grocery", subCategory: "cakes-pastries", variant: "3-Pack", description: "Triple pack of Pure Magic cookies for chocolate lovers.", price: 85, originalPrice: 99, discount: 14, image: "/assets/products/IN-FG-BRI-028.jpg", affiliateUrl: "/go/IN-FG-BRI-028", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.1, reviewCount: 13500, tags: ["cookies", "britannia", "pure-magic", "chocolate-chunk", "multi-pack"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-BRI-029", name: "Britannia Pure Magic Chocolate Chunk Cookies 6-Pack", brand: "Britannia", subBrand: "Pure Magic", category: "food-grocery", subCategory: "cakes-pastries", variant: "6-Pack", description: "Six-pack of premium chocolate chunk cookies.", price: 160, originalPrice: 185, discount: 14, image: "/assets/products/IN-FG-BRI-029.jpg", affiliateUrl: "/go/IN-FG-BRI-029", affiliatePlatform: "bigbasket", affiliateSource: "static", inStock: true, rating: 4.1, reviewCount: 9200, tags: ["cookies", "britannia", "pure-magic", "chocolate-chunk", "party-pack"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-BRI-030", name: "Britannia Pure Magic Chocolate Chunk Cookies 12-Pack", brand: "Britannia", subBrand: "Pure Magic", category: "food-grocery", subCategory: "cakes-pastries", variant: "12-Pack", description: "Bulk box of Pure Magic cookies for gifting or stocking.", price: 310, originalPrice: 359, discount: 14, image: "/assets/products/IN-FG-BRI-030.jpg", affiliateUrl: "/go/IN-FG-BRI-030", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 6100, tags: ["cookies", "britannia", "pure-magic", "chocolate-chunk", "bulk"], apiSource: "open-food-facts-free" },

  // RUSKS AND CRACKERS (031–040)
  { id: "IN-FG-BRI-031", name: "Britannia Toastea Plain Rusk 187g", brand: "Britannia", subBrand: "Toastea", category: "food-grocery", subCategory: "rusks-crackers", variant: "187g", description: "Crispy oven-baked rusk perfect for dipping in tea.", price: 35, originalPrice: 39, discount: 10, image: "/assets/products/IN-FG-BRI-031.jpg", affiliateUrl: "/go/IN-FG-BRI-031", affiliatePlatform: "bigbasket", affiliateSource: "static", inStock: true, rating: 4.0, reviewCount: 19800, tags: ["rusk", "britannia", "toastea", "plain", "tea-time"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-BRI-032", name: "Britannia Toastea Plain Rusk 350g", brand: "Britannia", subBrand: "Toastea", category: "food-grocery", subCategory: "rusks-crackers", variant: "350g", description: "Classic plain rusk baked to golden perfection.", price: 62, originalPrice: 69, discount: 10, image: "/assets/products/IN-FG-BRI-032.jpg", affiliateUrl: "/go/IN-FG-BRI-032", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.0, reviewCount: 16500, tags: ["rusk", "britannia", "toastea", "plain"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-BRI-033", name: "Britannia Toastea Plain Rusk 700g", brand: "Britannia", subBrand: "Toastea", category: "food-grocery", subCategory: "rusks-crackers", variant: "700g", description: "Large family pack of crunchy plain rusks.", price: 115, originalPrice: 129, discount: 11, image: "/assets/products/IN-FG-BRI-033.jpg", affiliateUrl: "/go/IN-FG-BRI-033", affiliatePlatform: "bigbasket", affiliateSource: "static", inStock: true, rating: 4.1, reviewCount: 11200, tags: ["rusk", "britannia", "toastea", "plain", "family-pack"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-BRI-034", name: "Britannia Toastea Plain Rusk 2x350g", brand: "Britannia", subBrand: "Toastea", category: "food-grocery", subCategory: "rusks-crackers", variant: "2x350g", description: "Twin-pack of Britannia Toastea rusks for weekly stock.", price: 120, originalPrice: 135, discount: 11, image: "/assets/products/IN-FG-BRI-034.jpg", affiliateUrl: "/go/IN-FG-BRI-034", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.0, reviewCount: 8400, tags: ["rusk", "britannia", "toastea", "plain", "twin-pack"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-BRI-035", name: "Britannia Toastea Plain Rusk 1kg", brand: "Britannia", subBrand: "Toastea", category: "food-grocery", subCategory: "rusks-crackers", variant: "1kg", description: "Bulk rusk pack for restaurants, hostels, and large families.", price: 159, originalPrice: 179, discount: 11, image: "/assets/products/IN-FG-BRI-035.jpg", affiliateUrl: "/go/IN-FG-BRI-035", affiliatePlatform: "bigbasket", affiliateSource: "static", inStock: true, rating: 4.1, reviewCount: 6700, tags: ["rusk", "britannia", "toastea", "plain", "bulk"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-BRI-036", name: "Britannia 50-50 Crackers 75g", brand: "Britannia", subBrand: "50-50", category: "food-grocery", subCategory: "rusks-crackers", variant: "75g", description: "Crispy sweet-and-salty crackers in a unique blend.", price: 20, originalPrice: 22, discount: 9, image: "/assets/products/IN-FG-BRI-036.jpg", affiliateUrl: "/go/IN-FG-BRI-036", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 3.9, reviewCount: 24500, tags: ["crackers", "britannia", "50-50", "sweet-salty"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-BRI-037", name: "Britannia 50-50 Crackers 200g", brand: "Britannia", subBrand: "50-50", category: "food-grocery", subCategory: "rusks-crackers", variant: "200g", description: "Popular 50-50 crackers with the perfect sweet-salty balance.", price: 45, originalPrice: 50, discount: 10, image: "/assets/products/IN-FG-BRI-037.jpg", affiliateUrl: "/go/IN-FG-BRI-037", affiliatePlatform: "bigbasket", affiliateSource: "static", inStock: true, rating: 3.9, reviewCount: 19300, tags: ["crackers", "britannia", "50-50", "sweet-salty"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-BRI-038", name: "Britannia 50-50 Crackers 400g", brand: "Britannia", subBrand: "50-50", category: "food-grocery", subCategory: "rusks-crackers", variant: "400g", description: "Family-size pack of crunchy 50-50 crackers.", price: 85, originalPrice: 95, discount: 11, image: "/assets/products/IN-FG-BRI-038.jpg", affiliateUrl: "/go/IN-FG-BRI-038", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 3.8, reviewCount: 14700, tags: ["crackers", "britannia", "50-50", "sweet-salty", "family-pack"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-BRI-039", name: "Britannia 50-50 Crackers 800g", brand: "Britannia", subBrand: "50-50", category: "food-grocery", subCategory: "rusks-crackers", variant: "800g", description: "Value pack of India's iconic sweet-and-salty crackers.", price: 160, originalPrice: 179, discount: 11, image: "/assets/products/IN-FG-BRI-039.jpg", affiliateUrl: "/go/IN-FG-BRI-039", affiliatePlatform: "bigbasket", affiliateSource: "static", inStock: true, rating: 3.8, reviewCount: 10200, tags: ["crackers", "britannia", "50-50", "sweet-salty", "value-pack"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-BRI-040", name: "Britannia 50-50 Crackers 1kg", brand: "Britannia", subBrand: "50-50", category: "food-grocery", subCategory: "rusks-crackers", variant: "1kg", description: "Jumbo pack of 50-50 crackers for offices and gatherings.", price: 195, originalPrice: 219, discount: 11, image: "/assets/products/IN-FG-BRI-040.jpg", affiliateUrl: "/go/IN-FG-BRI-040", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 3.9, reviewCount: 7500, tags: ["crackers", "britannia", "50-50", "sweet-salty", "bulk"], apiSource: "open-food-facts-free" },

  // SPECIALTY (041–050)
  { id: "IN-FG-BRI-041", name: "Britannia Little Hearts 26.8g", brand: "Britannia", subBrand: "Little Hearts", category: "food-grocery", subCategory: "specialty", variant: "26.8g", description: "Heart-shaped sugar-sprinkled puff pastry biscuits.", price: 10, originalPrice: 12, discount: 17, image: "/assets/products/IN-FG-BRI-041.jpg", affiliateUrl: "/go/IN-FG-BRI-041", affiliatePlatform: "bigbasket", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 35200, tags: ["biscuits", "britannia", "little-hearts", "puff-pastry"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-BRI-042", name: "Britannia Little Hearts 75g", brand: "Britannia", subBrand: "Little Hearts", category: "food-grocery", subCategory: "specialty", variant: "75g", description: "Flaky layered biscuits with a sweet sugar coating.", price: 25, originalPrice: 29, discount: 14, image: "/assets/products/IN-FG-BRI-042.jpg", affiliateUrl: "/go/IN-FG-BRI-042", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.3, reviewCount: 28600, tags: ["biscuits", "britannia", "little-hearts", "puff-pastry"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-BRI-043", name: "Britannia Little Hearts 3-Pack", brand: "Britannia", subBrand: "Little Hearts", category: "food-grocery", subCategory: "specialty", variant: "3-Pack", description: "Triple pack of crunchy heart-shaped biscuits.", price: 69, originalPrice: 80, discount: 14, image: "/assets/products/IN-FG-BRI-043.jpg", affiliateUrl: "/go/IN-FG-BRI-043", affiliatePlatform: "bigbasket", affiliateSource: "static", inStock: true, rating: 4.2, reviewCount: 19400, tags: ["biscuits", "britannia", "little-hearts", "multi-pack"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-BRI-044", name: "Britannia Little Hearts 6-Pack", brand: "Britannia", subBrand: "Little Hearts", category: "food-grocery", subCategory: "specialty", variant: "6-Pack", description: "Six-pack of India's most loved heart-shaped biscuits.", price: 130, originalPrice: 152, discount: 14, image: "/assets/products/IN-FG-BRI-044.jpg", affiliateUrl: "/go/IN-FG-BRI-044", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.2, reviewCount: 13100, tags: ["biscuits", "britannia", "little-hearts", "party-pack"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-BRI-045", name: "Britannia Little Hearts 12-Pack", brand: "Britannia", subBrand: "Little Hearts", category: "food-grocery", subCategory: "specialty", variant: "12-Pack", description: "Bulk dozen pack of Little Hearts for pantry stocking.", price: 249, originalPrice: 289, discount: 14, image: "/assets/products/IN-FG-BRI-045.jpg", affiliateUrl: "/go/IN-FG-BRI-045", affiliatePlatform: "bigbasket", affiliateSource: "static", inStock: true, rating: 4.4, reviewCount: 8500, tags: ["biscuits", "britannia", "little-hearts", "bulk"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-BRI-046", name: "Britannia Bourbon Cream Biscuits 60g", brand: "Britannia", subBrand: "Bourbon", category: "food-grocery", subCategory: "specialty", variant: "60g", description: "Classic chocolate cream sandwich biscuits.", price: 20, originalPrice: 23, discount: 13, image: "/assets/products/IN-FG-BRI-046.jpg", affiliateUrl: "/go/IN-FG-BRI-046", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.1, reviewCount: 29700, tags: ["biscuits", "britannia", "bourbon", "cream", "chocolate"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-BRI-047", name: "Britannia Bourbon Cream Biscuits 200g", brand: "Britannia", subBrand: "Bourbon", category: "food-grocery", subCategory: "specialty", variant: "200g", description: "Chocolate-flavoured cream sandwiched between cocoa biscuits.", price: 50, originalPrice: 58, discount: 14, image: "/assets/products/IN-FG-BRI-047.jpg", affiliateUrl: "/go/IN-FG-BRI-047", affiliatePlatform: "bigbasket", affiliateSource: "static", inStock: true, rating: 4.1, reviewCount: 23400, tags: ["biscuits", "britannia", "bourbon", "cream", "chocolate"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-BRI-048", name: "Britannia Bourbon Cream Biscuits 400g", brand: "Britannia", subBrand: "Bourbon", category: "food-grocery", subCategory: "specialty", variant: "400g", description: "Family pack of the beloved Bourbon chocolate cream biscuit.", price: 95, originalPrice: 110, discount: 14, image: "/assets/products/IN-FG-BRI-048.jpg", affiliateUrl: "/go/IN-FG-BRI-048", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.0, reviewCount: 17600, tags: ["biscuits", "britannia", "bourbon", "cream", "family-pack"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-BRI-049", name: "Britannia Bourbon Cream Biscuits 800g", brand: "Britannia", subBrand: "Bourbon", category: "food-grocery", subCategory: "specialty", variant: "800g", description: "Value pack of rich chocolate Bourbon cream biscuits.", price: 180, originalPrice: 209, discount: 14, image: "/assets/products/IN-FG-BRI-049.jpg", affiliateUrl: "/go/IN-FG-BRI-049", affiliatePlatform: "bigbasket", affiliateSource: "static", inStock: true, rating: 4.0, reviewCount: 11800, tags: ["biscuits", "britannia", "bourbon", "cream", "value-pack"], apiSource: "open-food-facts-free" },
  { id: "IN-FG-BRI-050", name: "Britannia Bourbon Cream Biscuits 1kg", brand: "Britannia", subBrand: "Bourbon", category: "food-grocery", subCategory: "specialty", variant: "1kg", description: "Jumbo 1kg pack of Bourbon cream biscuits for bulk buyers.", price: 220, originalPrice: 255, discount: 14, image: "/assets/products/IN-FG-BRI-050.jpg", affiliateUrl: "/go/IN-FG-BRI-050", affiliatePlatform: "amazon", affiliateSource: "static", inStock: true, rating: 4.1, reviewCount: 7200, tags: ["biscuits", "britannia", "bourbon", "cream", "bulk"], apiSource: "open-food-facts-free" },
]
