export interface Product {
  id: string
  name: string
  brand: string
  category: string
  subCategory: string
  price: number
  originalPrice: number
  priceRange: 'budget' | 'mid' | 'premium' | 'luxury'
  rating: number
  reviews: number
  image: string
  tags: string[]
  affiliatePlatform: 'amazon' | 'flipkart' | 'cj' | 'pod' | 'vcm'
  affiliateId: string
  badge?: string
  description: string
}

const CATALOG_SEEDS: Omit<Product, 'id'>[] = [
  { name: 'Samsung Galaxy S25 Ultra', brand: 'Samsung', category: 'smartphones', subCategory: 'flagship-android', price: 129999, originalPrice: 149999, priceRange: 'luxury', rating: 4.8, reviews: 8420, image: 'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=400', tags: ['tech', 'premium', 'gift', 'tier1', 'diwali', 'wedding_season', 'impulse_buy'], affiliatePlatform: 'amazon', affiliateId: 'B0CS4VHMGJ', badge: 'Lowest in 90 Days', description: 'AI-powered flagship with 200MP camera and titanium build' },
  { name: 'iPhone 16 Pro Max', brand: 'Apple', category: 'smartphones', subCategory: 'flagship-ios', price: 159900, originalPrice: 179900, priceRange: 'luxury', rating: 4.9, reviews: 12350, image: 'https://images.unsplash.com/photo-1592286927505-1def25115558?w=400', tags: ['tech', 'luxury', 'gift', 'tier1', 'diwali', 'christmas', 'impulse_buy'], affiliatePlatform: 'amazon', affiliateId: 'B0D3J5K7X2', badge: 'Bestseller', description: 'Apple Intelligence meets A18 Pro chip and ProRes video' },
  { name: 'MacBook Air M3', brand: 'Apple', category: 'laptops', subCategory: 'ultrabook-mac', price: 114900, originalPrice: 129900, priceRange: 'luxury', rating: 4.9, reviews: 7830, image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400', tags: ['tech', 'luxury', 'tier1', 'gift', 'exam_prep', 'back_to_college'], affiliatePlatform: 'amazon', affiliateId: 'B0CV7LM89J', badge: 'Top Pick', description: '18-hour battery, fanless design, M3 performance' },
  { name: 'HP Pavilion 15', brand: 'HP', category: 'laptops', subCategory: 'student-laptop', price: 49999, originalPrice: 59999, priceRange: 'mid', rating: 4.3, reviews: 12400, image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400', tags: ['tech', 'mid', 'tier2', 'school_opening', 'exam_prep', 'study_supplies'], affiliatePlatform: 'amazon', affiliateId: 'B0CS7KW4LM', badge: 'Student Pick', description: 'Intel Core i5, 16GB RAM, FHD anti-glare display' },
  { name: 'Sony WH-1000XM5', brand: 'Sony', category: 'audio', subCategory: 'noise-cancelling', price: 24990, originalPrice: 34990, priceRange: 'premium', rating: 4.8, reviews: 22100, image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400', tags: ['audio', 'premium', 'gift', 'tier1', 'christmas', 'diwali', 'winter'], affiliatePlatform: 'amazon', affiliateId: 'B09XS7JWHH', badge: 'Lowest in 90 Days', description: 'Industry-best ANC with 30-hour battery and Speak-to-Chat' },
  { name: 'boAt Airdopes 141', brand: 'boAt', category: 'audio', subCategory: 'tws-earbuds', price: 1299, originalPrice: 3990, priceRange: 'budget', rating: 4.2, reviews: 84500, image: 'https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?w=400', tags: ['audio', 'budget', 'tier3', 'bharat', 'gifting', 'exam_season'], affiliatePlatform: 'amazon', affiliateId: 'B09TQBRKDD', badge: 'Most Loved', description: 'Most loved Indian earbuds with 42hr total playback' },
  { name: 'Allen Solly Slim Fit Shirt', brand: 'Allen Solly', category: 'mens-fashion', subCategory: 'formal-shirts', price: 1299, originalPrice: 2499, priceRange: 'budget', rating: 4.4, reviews: 8920, image: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=400', tags: ['fashion', 'formal', 'tier2', 'wedding_season', 'office', 'winter'], affiliatePlatform: 'amazon', affiliateId: 'B09XKWM73P', badge: '48% Off', description: 'Wrinkle-free cotton blend, perfect for office and events' },
  { name: 'Fabindia Kurta Set', brand: 'Fabindia', category: 'mens-fashion', subCategory: 'ethnic-wear', price: 2499, originalPrice: 3999, priceRange: 'mid', rating: 4.6, reviews: 5670, image: 'https://images.unsplash.com/photo-1529391409740-59f2ce93de2e?w=400', tags: ['ethnic', 'festival_fashion', 'holi', 'diwali', 'navratri', 'wedding_season', 'south_india', 'north_india'], affiliatePlatform: 'amazon', affiliateId: 'B0CR5WLKM9', badge: 'Festive Pick', description: 'Handwoven cotton with traditional block print motifs' },
  { name: 'Kanjivaram Silk Saree', brand: 'Pothys', category: 'womens-fashion', subCategory: 'sarees-silk', price: 8999, originalPrice: 14999, priceRange: 'mid', rating: 4.7, reviews: 3450, image: 'https://images.unsplash.com/photo-1610189352649-c8c3d24b24e9?w=400', tags: ['ethnic', 'south_india', 'pongal', 'ugadi', 'onam', 'wedding_season', 'womens_fashion', 'festival_fashion'], affiliatePlatform: 'amazon', affiliateId: 'B0CWRTM54P', badge: 'Regional Pick', description: 'Authentic pure silk with gold zari border - temple collection' },
  { name: 'Anita Dongre Anarkali Suit', brand: 'Anita Dongre', category: 'womens-fashion', subCategory: 'salwar-kameez', price: 4999, originalPrice: 7999, priceRange: 'premium', rating: 4.5, reviews: 2310, image: 'https://images.unsplash.com/photo-1619086303291-0ef7699e4b31?w=400', tags: ['ethnic', 'festival_fashion', 'navratri', 'diwali', 'wedding_season', 'premium'], affiliatePlatform: 'amazon', affiliateId: 'B0CX4LT8R5', description: 'Floral chikankari work on georgette - festive collection 2026' },
  { name: 'LEGO Technic Bugatti', brand: 'LEGO', category: 'kids-toys', subCategory: 'building-sets', price: 12999, originalPrice: 17999, priceRange: 'premium', rating: 4.9, reviews: 4120, image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400', tags: ['toys', 'gift', 'christmas', 'childrens_day', 'premium', 'tier1', 'impulse_buy'], affiliatePlatform: 'amazon', affiliateId: 'B09KX7WNPQ', badge: 'Top Gift', description: '3,600 pieces, working V16 engine, Chiron Super Sport replica' },
  { name: 'Funskool Scrabble Junior', brand: 'Funskool', category: 'kids-toys', subCategory: 'board-games', price: 599, originalPrice: 999, priceRange: 'budget', rating: 4.3, reviews: 6780, image: 'https://images.unsplash.com/photo-1611996575749-79a3a250f948?w=400', tags: ['toys', 'education', 'budget', 'tier3', 'bharat', 'school_opening', 'school_holiday', 'exam_prep'], affiliatePlatform: 'amazon', affiliateId: 'B07FQKHRP2', description: 'Educational word game for 5+ years. Made in India.' },
  { name: 'Preethi Zodiac Mixer Grinder', brand: 'Preethi', category: 'home-kitchen', subCategory: 'kitchen-appliances', price: 3499, originalPrice: 5999, priceRange: 'budget', rating: 4.6, reviews: 34200, image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400', tags: ['kitchen', 'south_india', 'pongal', 'home', 'budget', 'tier2', 'tier3', 'bharat', 'gifting'], affiliatePlatform: 'amazon', affiliateId: 'B07V9WTRYL', badge: 'South India Favourite', description: '750W with 3 jars, ideal for South Indian grinding needs' },
  { name: 'Dyson V12 Detect Slim', brand: 'Dyson', category: 'home-kitchen', subCategory: 'vacuum-cleaners', price: 44900, originalPrice: 55900, priceRange: 'luxury', rating: 4.7, reviews: 2840, image: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=400', tags: ['home', 'luxury', 'tier1', 'metro', 'diwali', 'home_makeover', 'winter'], affiliatePlatform: 'amazon', affiliateId: 'B0C2JKHP8Q', description: 'Laser detection reveals microscopic dust with HEPA filtration' },
  { name: 'Forest Essentials Rose Water', brand: 'Forest Essentials', category: 'beauty', subCategory: 'skincare-natural', price: 895, originalPrice: 1295, priceRange: 'mid', rating: 4.5, reviews: 12400, image: 'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=400', tags: ['beauty', 'natural', 'gifting', 'valentines_day', 'mothers_day', 'summer', 'tier1', 'tier2'], affiliatePlatform: 'amazon', affiliateId: 'B07GZKWL98', description: 'Distilled from Kannauj roses - pure ayurvedic' },
  { name: 'Mamaearth Vitamin C Face Serum', brand: 'Mamaearth', category: 'beauty', subCategory: 'serums', price: 499, originalPrice: 899, priceRange: 'budget', rating: 4.3, reviews: 45600, image: 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=400', tags: ['beauty', 'budget', 'bharat', 'tier2', 'tier3', 'summer', 'gifting'], affiliatePlatform: 'flipkart', affiliateId: 'MAMVITCSER', badge: 'India Favourite', description: 'Toxin-free vitamin C with turmeric for natural glow' },
  { name: 'Yonex Arcsaber 11', brand: 'Yonex', category: 'sports', subCategory: 'racquet-sports', price: 7999, originalPrice: 11999, priceRange: 'premium', rating: 4.8, reviews: 3120, image: 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=400', tags: ['sports', 'premium', 'south_india', 'winter', 'fitness_goals', 'tier1'], affiliatePlatform: 'amazon', affiliateId: 'B09YXK8WQ3', description: 'Beloved by national champions - high-flex shaft for speed' },
  { name: 'Decathlon Domyos Yoga Mat', brand: 'Decathlon', category: 'sports', subCategory: 'yoga-fitness', price: 1299, originalPrice: 2999, priceRange: 'budget', rating: 4.5, reviews: 28900, image: 'https://images.unsplash.com/photo-1601925228335-ce3e46be9c15?w=400', tags: ['fitness', 'yoga', 'budget', 'new_year_resolutions', 'monsoon_indoor', 'stay_home', 'fitness_goals', 'bharat'], affiliatePlatform: 'amazon', affiliateId: 'B09KMXP7WL', description: 'Non-slip 5mm thick, eco-friendly, carry strap included' },
  { name: 'NCERT Class 12 Complete Set', brand: 'NCERT', category: 'books', subCategory: 'academic-textbooks', price: 2999, originalPrice: 4500, priceRange: 'budget', rating: 4.7, reviews: 56000, image: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400', tags: ['education', 'exam_prep', 'exam_season', 'school_opening', 'budget', 'tier3', 'bharat', 'study_supplies'], affiliatePlatform: 'amazon', affiliateId: 'B09KXWRP7M', badge: 'Exam Season Essential', description: 'Official NCERT 2025-26 complete reference pack' },
  { name: 'Atomic Habits', brand: 'Penguin', category: 'books', subCategory: 'self-development', price: 349, originalPrice: 699, priceRange: 'budget', rating: 4.8, reviews: 145000, image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400', tags: ['books', 'self_help', 'new_year_resolutions', 'fitness_goals', 'all_tier', 'gift', 'impulse_buy'], affiliatePlatform: 'amazon', affiliateId: 'B08GY3JJ7Q', badge: 'Bestseller', description: 'The definitive guide to building good habits' },
  { name: 'PlayStation 5 Slim', brand: 'Sony', category: 'gaming', subCategory: 'consoles', price: 49990, originalPrice: 54990, priceRange: 'luxury', rating: 4.9, reviews: 18700, image: 'https://images.unsplash.com/photo-1607016284318-d1a621edf6f0?w=400', tags: ['gaming', 'luxury', 'tier1', 'christmas', 'diwali', 'gift', 'impulse_buy', 'monsoon_indoor', 'winter'], affiliatePlatform: 'amazon', affiliateId: 'B0CMKB41BM', badge: '#1 Console', description: 'Next-gen gaming with 4K 120fps and haptic feedback' },
  { name: 'Acer Nitro Monitor 165Hz', brand: 'Acer', category: 'gaming', subCategory: 'gaming-monitors', price: 16999, originalPrice: 24999, priceRange: 'mid', rating: 4.5, reviews: 8940, image: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=400', tags: ['gaming', 'tech', 'mid', 'tier2', 'monsoon_indoor', 'exam_season'], affiliatePlatform: 'amazon', affiliateId: 'B09KXRM8P7', description: '23.8 inch FHD IPS with AMD FreeSync' },
  { name: 'Michelin Pilot Sport 5', brand: 'Michelin', category: 'automotive', subCategory: 'tyres', price: 8499, originalPrice: 11999, priceRange: 'premium', rating: 4.7, reviews: 2340, image: 'https://images.unsplash.com/photo-1493238792000-8113da705763?w=400', tags: ['automotive', 'premium', 'tier1', 'monsoon', 'monsoon_prep', 'safety'], affiliatePlatform: 'amazon', affiliateId: 'B09YXKP6T8', description: 'Exceptional wet braking for Indian monsoon roads' },
  { name: 'Omron Blood Pressure Monitor', brand: 'Omron', category: 'health', subCategory: 'medical-devices', price: 2999, originalPrice: 4999, priceRange: 'mid', rating: 4.6, reviews: 34500, image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=400', tags: ['health', 'gifting', 'parents_gift', 'diwali', 'all_tier'], affiliatePlatform: 'amazon', affiliateId: 'B09WK8PQ4M', badge: 'Gift for Parents', description: 'Clinically validated monitor for home BP checks' },
  { name: 'Staedtler Geometry Set', brand: 'Staedtler', category: 'office', subCategory: 'school-supplies', price: 299, originalPrice: 499, priceRange: 'budget', rating: 4.5, reviews: 45600, image: 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=400', tags: ['stationery', 'budget', 'school_opening', 'exam_prep', 'tier3', 'bharat', 'study_supplies'], affiliatePlatform: 'amazon', affiliateId: 'B07CXKWP9T', description: 'Precision geometry set trusted by students' },
  { name: 'Malabar Gold Spices Gift Set', brand: 'Malabar', category: 'food-gourmet', subCategory: 'gift-hampers', price: 1999, originalPrice: 3499, priceRange: 'mid', rating: 4.4, reviews: 6780, image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400', tags: ['food', 'gift', 'diwali', 'gifting', 'pongal', 'south_india', 'festival_gifting', 'corporate_gifting'], affiliatePlatform: 'amazon', affiliateId: 'B09KMW8PQ3', description: 'Pure Kerala spices festive gift box' },
  { name: 'American Tourister Twist Trolley', brand: 'American Tourister', category: 'travel', subCategory: 'trolley-bags', price: 3499, originalPrice: 6999, priceRange: 'mid', rating: 4.4, reviews: 23400, image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400', tags: ['travel', 'mid', 'summer_vacation', 'new_year', 'gifting', 'tier2'], affiliatePlatform: 'amazon', affiliateId: 'B09XLWP7M3', badge: 'Travel Season', description: 'Cabin-size trolley with TSA lock and spinner wheels' },
  { name: 'Chicco Baby Carrier Soft', brand: 'Chicco', category: 'baby', subCategory: 'baby-carriers', price: 2999, originalPrice: 5499, priceRange: 'mid', rating: 4.6, reviews: 8940, image: 'https://images.unsplash.com/photo-1555252333-9f8e92e65df9?w=400', tags: ['baby', 'gifting', 'mid', 'tier1', 'tier2', 'new_year_resolutions'], affiliatePlatform: 'amazon', affiliateId: 'B0CR4LWMT9', description: 'Ergonomic hip-healthy design for young parents' },
  { name: 'Royal Canin Maxi Adult', brand: 'Royal Canin', category: 'pets', subCategory: 'dog-food', price: 4299, originalPrice: 5999, priceRange: 'premium', rating: 4.7, reviews: 18400, image: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=400', tags: ['pets', 'premium', 'tier1', 'tier2', 'impulse_buy', 'monthly_essential'], affiliatePlatform: 'amazon', affiliateId: 'B09KXWQ8MT', description: 'Tailored nutrition for large breed dogs' },
  { name: 'Ugaoo Peace Lily Plant', brand: 'Ugaoo', category: 'gardening', subCategory: 'indoor-plants', price: 399, originalPrice: 699, priceRange: 'budget', rating: 4.5, reviews: 24500, image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400', tags: ['home', 'gifting', 'summer', 'monsoon', 'tier1', 'tier2', 'valentines_day', 'mothers_day', 'home_makeover'], affiliatePlatform: 'amazon', affiliateId: 'B09XKWM54T', badge: 'Air Purifier', description: 'Low-maintenance indoor plant for cleaner air' },
  { name: 'Custom Diwali Family Name Mug Set', brand: 'CloudBasket POD', category: 'pod', subCategory: 'festive-gifting', price: 799, originalPrice: 1499, priceRange: 'budget', rating: 4.8, reviews: 2340, image: 'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=400', tags: ['pod', 'diwali', 'gifting', 'festival_gifting', 'personalised', 'all_tier', 'corporate_gifting', 'impulse_buy'], affiliatePlatform: 'pod', affiliateId: 'pod-diwali-mug-001', badge: 'Personalised Gift', description: 'Add your family name - ceramic mug set of 4' },
  { name: 'Holi Colour T-Shirt Pack', brand: 'CloudBasket POD', category: 'pod', subCategory: 'festival-apparel', price: 599, originalPrice: 999, priceRange: 'budget', rating: 4.7, reviews: 1890, image: 'https://images.unsplash.com/photo-1529374255404-311a2a4f1fd9?w=400', tags: ['pod', 'holi', 'festival_fashion', 'spring', 'gifting', 'all_tier'], affiliatePlatform: 'pod', affiliateId: 'pod-holi-tshirt-001', badge: 'Holi Special', description: 'Vibrant pre-dyed Holi tee pack' },
  { name: 'Bride & Groom Squad Hoodies', brand: 'CloudBasket POD', category: 'pod', subCategory: 'wedding-merch', price: 1299, originalPrice: 2499, priceRange: 'mid', rating: 4.9, reviews: 3120, image: 'https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=400', tags: ['pod', 'wedding_season', 'gifting', 'winter', 'personalised', 'north_india', 'tier1', 'tier2'], affiliatePlatform: 'pod', affiliateId: 'pod-wedding-hoodie-001', badge: 'Wedding Season', description: 'Custom names - perfect wedding party gift' },
  { name: 'Kindle Paperwhite', brand: 'Amazon', category: 'ebooks', subCategory: 'readers', price: 14999, originalPrice: 17999, priceRange: 'premium', rating: 4.7, reviews: 20800, image: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400', tags: ['books', 'reading', 'tech', 'premium', 'tier1', 'exam_prep'], affiliatePlatform: 'amazon', affiliateId: 'KINDLEPW6', description: 'Glare-free e-ink reader with weeks-long battery' },
  { name: 'Canon EOS R50', brand: 'Canon', category: 'cameras', subCategory: 'mirrorless', price: 68999, originalPrice: 78999, priceRange: 'premium', rating: 4.7, reviews: 6400, image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=400', tags: ['camera', 'tech', 'premium', 'tier1', 'travel', 'wedding_season'], affiliatePlatform: 'amazon', affiliateId: 'CANONR50', description: 'Creator-focused mirrorless camera with 4K recording' },
  { name: 'Philips Air Fryer XL', brand: 'Philips', category: 'appliances', subCategory: 'air-fryers', price: 11999, originalPrice: 17999, priceRange: 'premium', rating: 4.6, reviews: 16600, image: 'https://images.unsplash.com/photo-1585515656973-6f29a3d6d4f2?w=400', tags: ['home', 'kitchen', 'premium', 'tier1', 'tier2', 'health'], affiliatePlatform: 'amazon', affiliateId: 'PHILIPSAFXL', description: 'Rapid Air Technology for low-oil cooking' },
  { name: 'Bose Soundbar 900', brand: 'Bose', category: 'home-audio', subCategory: 'soundbars', price: 79999, originalPrice: 99999, priceRange: 'luxury', rating: 4.8, reviews: 3200, image: 'https://images.unsplash.com/photo-1589003077984-894e133dabab?w=400', tags: ['audio', 'luxury', 'tier1', 'christmas', 'diwali', 'home_makeover'], affiliatePlatform: 'amazon', affiliateId: 'BOSESB900', description: 'Dolby Atmos premium soundbar for immersive cinema' },
  { name: 'Blue Star Inverter AC 1.5T', brand: 'Blue Star', category: 'cooling', subCategory: 'air-conditioners', price: 38999, originalPrice: 52999, priceRange: 'premium', rating: 4.4, reviews: 11200, image: 'https://images.unsplash.com/photo-1545259741-2ea3ebf61fa5?w=400', tags: ['summer', 'cooling_products', 'tier1', 'tier2', 'home'], affiliatePlatform: 'amazon', affiliateId: 'BLUESTAR15T', description: 'Energy-efficient AC with fast cooling and clean filters' },
  { name: 'Wildcraft Rain Jacket', brand: 'Wildcraft', category: 'outdoor', subCategory: 'rainwear', price: 2499, originalPrice: 3999, priceRange: 'mid', rating: 4.3, reviews: 9800, image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400', tags: ['monsoon', 'monsoon_gear', 'travel', 'tier2', 'tier3'], affiliatePlatform: 'flipkart', affiliateId: 'WILDRAINJKT', description: 'Waterproof and breathable jacket for heavy rain' },
  { name: 'Saregama Carvaan Mini', brand: 'Saregama', category: 'retro-audio', subCategory: 'portable-speakers', price: 2490, originalPrice: 4490, priceRange: 'mid', rating: 4.6, reviews: 22100, image: 'https://images.unsplash.com/photo-1471479917193-f00955256257?w=400', tags: ['gift', 'parents_gift', 'diwali', 'all_tier'], affiliatePlatform: 'amazon', affiliateId: 'CARVAANMINI', description: 'Portable retro speaker with 351 preloaded Hindi songs' },
  { name: 'Nike Air Zoom Pegasus', brand: 'Nike', category: 'footwear', subCategory: 'running-shoes', price: 7995, originalPrice: 11995, priceRange: 'premium', rating: 4.5, reviews: 15200, image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400', tags: ['sports', 'fitness', 'premium', 'tier1', 'tier2'], affiliatePlatform: 'amazon', affiliateId: 'NIKEPEGASUS', description: 'Daily trainer with responsive cushioning' },
  { name: 'Raymond Wedding Suit Fabric', brand: 'Raymond', category: 'mens-fashion', subCategory: 'suiting', price: 4599, originalPrice: 6999, priceRange: 'mid', rating: 4.4, reviews: 4300, image: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=400', tags: ['wedding_season', 'mens_fashion', 'tier1', 'tier2', 'gift'], affiliatePlatform: 'amazon', affiliateId: 'RAYMONDSUIT', description: 'Premium suiting fabric for custom tailoring' },
  { name: 'Nataraj Drawing Kit', brand: 'Nataraj', category: 'art-craft', subCategory: 'drawing-supplies', price: 349, originalPrice: 699, priceRange: 'budget', rating: 4.3, reviews: 8800, image: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400', tags: ['school_opening', 'children_play', 'education', 'budget', 'tier3'], affiliatePlatform: 'flipkart', affiliateId: 'NATDRAWKIT', description: 'Complete drawing starter kit for kids' },
  { name: 'Orient Electric Room Heater', brand: 'Orient', category: 'winter-care', subCategory: 'room-heaters', price: 2299, originalPrice: 3499, priceRange: 'budget', rating: 4.2, reviews: 12600, image: 'https://images.unsplash.com/photo-1616594039964-3f7a6f84aeb4?w=400', tags: ['winter', 'winter_essentials', 'home', 'tier2', 'tier3'], affiliatePlatform: 'amazon', affiliateId: 'ORIENTHEAT', description: 'Compact and safe room heater for winter comfort' },
  { name: 'Tata Sampann Dry Fruits Combo', brand: 'Tata', category: 'grocery', subCategory: 'dry-fruits', price: 899, originalPrice: 1499, priceRange: 'budget', rating: 4.4, reviews: 54000, image: 'https://images.unsplash.com/photo-1603048719539-9ecb4d178f56?w=400', tags: ['diwali', 'gifting', 'grocery', 'all_tier', 'festival_gifting'], affiliatePlatform: 'amazon', affiliateId: 'TATADRYCOMBO', description: 'Almond, cashew and raisins festival combo pack' },
  { name: 'Urban Ladder Sofa Set', brand: 'Urban Ladder', category: 'furniture', subCategory: 'living-room', price: 32999, originalPrice: 49999, priceRange: 'premium', rating: 4.3, reviews: 3900, image: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=400', tags: ['home_makeover', 'premium', 'tier1', 'tier2', 'wedding_season'], affiliatePlatform: 'amazon', affiliateId: 'ULSOFASET', description: 'Modern 3+1+1 sofa set with stain-resistant fabric' },
]

const TARGET_SIZE = 8000

function varyPrice(price: number, index: number): number {
  const multiplier = 1 + ((index % 7) - 3) * 0.02
  return Math.max(99, Math.round(price * multiplier))
}

function varyRating(rating: number, index: number): number {
  const next = rating + ((index % 5) - 2) * 0.03
  return Number(Math.max(3.8, Math.min(4.95, next)).toFixed(1))
}

function buildCatalog(size: number = TARGET_SIZE): Product[] {
  const products: Product[] = []
  let idCounter = 1

  while (products.length < size) {
    for (const seed of CATALOG_SEEDS) {
      if (products.length >= size) break
      const variant = Math.floor(products.length / CATALOG_SEEDS.length) + 1
      const id = `cb-${String(idCounter++).padStart(5, '0')}`
      const price = varyPrice(seed.price, variant)
      const originalPrice = Math.max(price + 50, varyPrice(seed.originalPrice, variant + 1))

      products.push({
        ...seed,
        id,
        name: variant > 1 ? `${seed.name} (${variant})` : seed.name,
        price,
        originalPrice,
        rating: varyRating(seed.rating, variant),
        reviews: seed.reviews + variant * 7,
        affiliateId: `${seed.affiliateId}-${variant}`,
      })
    }
  }

  return products
}

export const CATALOG: Product[] = buildCatalog()

export function getProductsByCategory(cat: string): Product[] {
  return CATALOG.filter((product) => product.category === cat)
}

export function getProductById(id: string): Product | undefined {
  return CATALOG.find((product) => product.id === id)
}

export function getAllCategories(): string[] {
  return [...new Set(CATALOG.map((product) => product.category))]
}
