import type { Deal } from '@/lib/types'

const inHours = (hours: number): string => {
  return new Date(Date.now() + hours * 60 * 60 * 1000).toISOString()
}

export const DEALS: Deal[] = [
  {
    id: 'flash-1',
    productId: 1,
    goId: 'amazon-B09N3XMZ5F',
    title: 'boAt Airdopes 141 Gen 2 — Flash Price',
    discount: 47,
    expiresAt: inHours(1),
    isFlash: true,
    badge: 'Flash Sale',
  },
  {
    id: 'flash-2',
    productId: 2,
    goId: 'amazon-B09CTWFV5W',
    title: 'Philips Air Fryer 4.1L — Flash Price',
    discount: 43,
    expiresAt: inHours(1),
    isFlash: true,
    badge: 'Flash Sale',
  },
  {
    id: 'flash-3',
    productId: 3,
    goId: 'amazon-B096VF5YYF',
    title: 'boAt Xtend Smartwatch — Flash Price',
    discount: 50,
    expiresAt: inHours(1),
    isFlash: true,
    badge: 'Flash Sale',
  },
  {
    id: 'flash-4',
    productId: 4,
    goId: 'amazon-B0DMDZWP7Q',
    title: 'boAt Wave Call 2 Plus — Flash Price',
    discount: 50,
    expiresAt: inHours(1),
    isFlash: true,
    badge: 'Flash Sale',
  },
  {
    id: 'deal-1',
    productId: 5,
    title: 'Samsung Galaxy S25 — Weekend Deal',
    discount: 15,
    expiresAt: inHours(24),
    isFlash: false,
    badge: 'Limited Time',
  },
  {
    id: 'deal-2',
    productId: 6,
    title: 'Apple MacBook Air M4 — Weekend Deal',
    discount: 18,
    expiresAt: inHours(24),
    isFlash: false,
    badge: 'Limited Time',
  },
  {
    id: 'deal-3',
    productId: 7,
    title: 'Nike Air Zoom — Weekend Deal',
    discount: 22,
    expiresAt: inHours(24),
    isFlash: false,
    badge: 'Limited Time',
  },
  {
    id: 'deal-4',
    productId: 8,
    title: 'Bosch Smart Mixer — Weekend Deal',
    discount: 12,
    expiresAt: inHours(24),
    isFlash: false,
    badge: 'Limited Time',
  },
  {
    id: 'cj-1',
    productId: 9,
    title: 'Global Tech — CJ Exclusive',
    discount: 40,
    expiresAt: inHours(48),
    isFlash: false,
    badge: 'CJ Exclusive',
  },
  {
    id: 'cj-2',
    productId: 10,
    title: 'Premium Fashion — CJ Exclusive',
    discount: 28,
    expiresAt: inHours(48),
    isFlash: false,
    badge: 'CJ Exclusive',
  },
  {
    id: 'cj-3',
    productId: 11,
    title: 'Lifestyle Picks — CJ Exclusive',
    discount: 33,
    expiresAt: inHours(48),
    isFlash: false,
    badge: 'CJ Exclusive',
  },
  {
    id: 'cj-4',
    productId: 12,
    title: 'Beauty Bundle — CJ Exclusive',
    discount: 45,
    expiresAt: inHours(48),
    isFlash: false,
    badge: 'CJ Exclusive',
  },
]

export const FLASH_DEALS: Deal[] = DEALS.filter((deal) => deal.isFlash)
