// ── Shared product catalogue ─────────────────────────────────────────────────
// Single source of truth for ProductsClient, /products/[id], compare, search
// No external calls — all data is static

export type Platform = 'Amazon' | 'Flipkart'

export type Category =
  | 'All'
  | 'Mobiles'
  | 'Laptops'
  | 'Fashion'
  | 'Home'
  | 'Cameras'
  | 'Gaming'
  | 'Electronics'
  | 'Footwear'
  | 'Books'
  | 'Beauty'
  | 'Sports'
  | 'Toys'

export interface Product {
  id: string
  name: string
  brand: string
  platform: Platform
  originalPrice: string
  discountedPrice: string
  priceValue: number          // numeric for sort/filter
  rating: number
  reviews: string
  discountPercent: number
  category: Category
  imageUrl: string
  description: string
  tags: string[]
  inStock: boolean
  affiliateUrl: string
}

export const CATEGORIES: readonly Category[] = [
  'All', 'Mobiles', 'Laptops', 'Fashion', 'Home', 'Cameras',
  'Gaming', 'Electronics', 'Footwear', 'Books', 'Beauty', 'Sports', 'Toys',
]

export const PRODUCTS: Product[] = [
  // ── Mobiles ────────────────────────────────────────────────────────────────
  {
    id: 'mob-1',
    name: 'Samsung Galaxy M35 5G',
    brand: 'Samsung',
    platform: 'Amazon',
    originalPrice: '₹24,999',
    discountedPrice: '₹18,999',
    priceValue: 18999,
    rating: 4.2,
    reviews: '12,450',
    discountPercent: 24,
    category: 'Mobiles',
    imageUrl: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=400&h=400&fit=crop',
    description: '6.6" Super AMOLED display, 50MP camera, 5000mAh battery, 6GB RAM. Best mid-range performer for 2026.',
    tags: ['5G', 'AMOLED', '50MP'],
    inStock: true,
    affiliateUrl: 'https://www.amazon.in',
  },
  {
    id: 'mob-2',
    name: 'iPhone 15 128GB',
    brand: 'Apple',
    platform: 'Amazon',
    originalPrice: '₹89,900',
    discountedPrice: '₹79,900',
    priceValue: 79900,
    rating: 4.8,
    reviews: '34,210',
    discountPercent: 11,
    category: 'Mobiles',
    imageUrl: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=400&h=400&fit=crop',
    description: 'A16 Bionic chip, 48MP main camera, Dynamic Island, USB-C charging. The benchmark smartphone experience.',
    tags: ['A16 Bionic', 'USB-C', 'Dynamic Island'],
    inStock: true,
    affiliateUrl: 'https://www.amazon.in',
  },
  {
    id: 'mob-3',
    name: 'Redmi Note 13 Pro 5G',
    brand: 'Xiaomi',
    platform: 'Amazon',
    originalPrice: '₹24,999',
    discountedPrice: '₹19,999',
    priceValue: 19999,
    rating: 4.4,
    reviews: '28,900',
    discountPercent: 20,
    category: 'Mobiles',
    imageUrl: 'https://images.unsplash.com/photo-1605236453806-6ff36851218e?w=400&h=400&fit=crop',
    description: '200MP camera, 67W turbo charging, Snapdragon 7s Gen 2. The camera king under ₹20,000.',
    tags: ['200MP', '5G', '67W Charging'],
    inStock: true,
    affiliateUrl: 'https://www.amazon.in',
  },
  {
    id: 'mob-4',
    name: 'Realme 12 Pro+ 5G',
    brand: 'Realme',
    platform: 'Flipkart',
    originalPrice: '₹27,999',
    discountedPrice: '₹21,999',
    priceValue: 21999,
    rating: 4.3,
    reviews: '9,870',
    discountPercent: 21,
    category: 'Mobiles',
    imageUrl: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400&h=400&fit=crop',
    description: 'Periscope zoom camera, 50MP Sony IMX890, 67W SUPERVOOC. Exceptional photography at mid-range price.',
    tags: ['Periscope Zoom', '5G', 'Sony Sensor'],
    inStock: true,
    affiliateUrl: 'https://www.flipkart.com',
  },
  {
    id: 'mob-5',
    name: 'Vivo V30e 5G',
    brand: 'Vivo',
    platform: 'Amazon',
    originalPrice: '₹29,999',
    discountedPrice: '₹24,499',
    priceValue: 24499,
    rating: 4.1,
    reviews: '5,340',
    discountPercent: 18,
    category: 'Mobiles',
    imageUrl: 'https://images.unsplash.com/photo-1574944985070-8f3ebc6b79d2?w=400&h=400&fit=crop',
    description: '50MP front camera with aura light, 80W flash charge, 6.78" AMOLED. Selfie-focused flagship killer.',
    tags: ['Selfie Camera', '5G', '80W Charging'],
    inStock: true,
    affiliateUrl: 'https://www.amazon.in',
  },

  // ── Laptops ────────────────────────────────────────────────────────────────
  {
    id: 'lap-1',
    name: 'HP Pavilion Laptop 15',
    brand: 'HP',
    platform: 'Flipkart',
    originalPrice: '₹62,000',
    discountedPrice: '₹45,990',
    priceValue: 45990,
    rating: 4.4,
    reviews: '7,120',
    discountPercent: 26,
    category: 'Laptops',
    imageUrl: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400&h=400&fit=crop',
    description: 'Intel Core i5-1335U, 16GB RAM, 512GB SSD, Full HD display. Best-in-class productivity laptop.',
    tags: ['Intel i5', '16GB RAM', 'SSD'],
    inStock: true,
    affiliateUrl: 'https://www.flipkart.com',
  },
  {
    id: 'lap-2',
    name: 'MacBook Air M3 13"',
    brand: 'Apple',
    platform: 'Amazon',
    originalPrice: '₹1,29,900',
    discountedPrice: '₹1,14,900',
    priceValue: 114900,
    rating: 4.9,
    reviews: '15,670',
    discountPercent: 12,
    category: 'Laptops',
    imageUrl: 'https://images.unsplash.com/photo-1611186871525-5a73d2f5d2c8?w=400&h=400&fit=crop',
    description: 'M3 chip, 18-hour battery, 13.6" Liquid Retina display, 8GB Unified Memory. Fanless, silent performance.',
    tags: ['M3 Chip', '18hr Battery', 'Retina'],
    inStock: true,
    affiliateUrl: 'https://www.amazon.in',
  },
  {
    id: 'lap-3',
    name: 'Dell Inspiron 15 3520',
    brand: 'Dell',
    platform: 'Flipkart',
    originalPrice: '₹55,990',
    discountedPrice: '₹44,999',
    priceValue: 44999,
    rating: 4.2,
    reviews: '11,300',
    discountPercent: 20,
    category: 'Laptops',
    imageUrl: 'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=400&h=400&fit=crop',
    description: 'Intel Core i5-1235U, 8GB RAM, 512GB SSD, 15.6" FHD. Reliable workhorse with excellent build quality.',
    tags: ['Intel i5', 'Dell', 'FHD'],
    inStock: true,
    affiliateUrl: 'https://www.flipkart.com',
  },
  {
    id: 'lap-4',
    name: 'ASUS VivoBook 15 OLED',
    brand: 'ASUS',
    platform: 'Amazon',
    originalPrice: '₹49,990',
    discountedPrice: '₹39,990',
    priceValue: 39990,
    rating: 4.5,
    reviews: '8,450',
    discountPercent: 20,
    category: 'Laptops',
    imageUrl: 'https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=400&h=400&fit=crop',
    description: 'Ryzen 5 7530U, 15.6" OLED 2.8K display, 16GB RAM, 512GB SSD. Stunning visuals for creators.',
    tags: ['OLED', 'Ryzen 5', '2.8K Display'],
    inStock: true,
    affiliateUrl: 'https://www.amazon.in',
  },
  {
    id: 'lap-5',
    name: 'Lenovo IdeaPad Slim 3',
    brand: 'Lenovo',
    platform: 'Flipkart',
    originalPrice: '₹42,990',
    discountedPrice: '₹35,990',
    priceValue: 35990,
    rating: 4.1,
    reviews: '19,800',
    discountPercent: 16,
    category: 'Laptops',
    imageUrl: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=400&h=400&fit=crop',
    description: 'Intel Core i3-1215U, 8GB RAM, 256GB SSD, 15.6" FHD. Budget-friendly for students and beginners.',
    tags: ['Budget', 'Student', 'Lenovo'],
    inStock: true,
    affiliateUrl: 'https://www.flipkart.com',
  },

  // ── Fashion ────────────────────────────────────────────────────────────────
  {
    id: 'fas-1',
    name: 'Titan Analog Watch',
    brand: 'Titan',
    platform: 'Flipkart',
    originalPrice: '₹3,500',
    discountedPrice: '₹2,495',
    priceValue: 2495,
    rating: 4.3,
    reviews: '6,780',
    discountPercent: 29,
    category: 'Fashion',
    imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop',
    description: 'Slim metal case, mineral crystal glass, water resistant to 30m. Classic Indian watchmaking at its finest.',
    tags: ['Analog', 'Water Resistant', 'Titan'],
    inStock: true,
    affiliateUrl: 'https://www.flipkart.com',
  },
  {
    id: 'fas-2',
    name: 'Peter England Polo T-Shirt',
    brand: 'Peter England',
    platform: 'Amazon',
    originalPrice: '₹1,299',
    discountedPrice: '₹649',
    priceValue: 649,
    rating: 4.0,
    reviews: '3,240',
    discountPercent: 50,
    category: 'Fashion',
    imageUrl: 'https://images.unsplash.com/photo-1523381294911-8d3cead13475?w=400&h=400&fit=crop',
    description: '100% cotton pique fabric, ribbed collar, regular fit. Versatile wardrobe essential for office and casual.',
    tags: ['Cotton', 'Regular Fit', 'Polo'],
    inStock: true,
    affiliateUrl: 'https://www.amazon.in',
  },
  {
    id: 'fas-3',
    name: 'BIBA Women\'s Kurta Set',
    brand: 'BIBA',
    platform: 'Flipkart',
    originalPrice: '₹2,499',
    discountedPrice: '₹1,299',
    priceValue: 1299,
    rating: 4.2,
    reviews: '2,190',
    discountPercent: 48,
    category: 'Fashion',
    imageUrl: 'https://images.unsplash.com/photo-1583391733956-6c78276477e2?w=400&h=400&fit=crop',
    description: 'Printed cotton kurta with palazzo pants, ethnic embroidery work. Festival-ready ethnic fashion.',
    tags: ['Ethnic', 'Cotton', 'Festival Wear'],
    inStock: true,
    affiliateUrl: 'https://www.flipkart.com',
  },
  {
    id: 'fas-4',
    name: 'Levi\'s 511 Slim Fit Jeans',
    brand: 'Levi\'s',
    platform: 'Amazon',
    originalPrice: '₹3,999',
    discountedPrice: '₹2,199',
    priceValue: 2199,
    rating: 4.4,
    reviews: '14,560',
    discountPercent: 45,
    category: 'Fashion',
    imageUrl: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=400&h=400&fit=crop',
    description: 'Stretch denim, slim fit through thigh and leg opening. The gold-standard everyday jean for men.',
    tags: ['Slim Fit', 'Stretch Denim', 'Levi\'s'],
    inStock: true,
    affiliateUrl: 'https://www.amazon.in',
  },
  {
    id: 'fas-5',
    name: 'Fastrack Oval Sunglasses',
    brand: 'Fastrack',
    platform: 'Flipkart',
    originalPrice: '₹1,495',
    discountedPrice: '₹895',
    priceValue: 895,
    rating: 4.1,
    reviews: '4,320',
    discountPercent: 40,
    category: 'Fashion',
    imageUrl: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=400&h=400&fit=crop',
    description: 'UV400 protection, polycarbonate lens, lightweight frame. Premium look at an accessible price.',
    tags: ['UV400', 'Lightweight', 'Oval Frame'],
    inStock: true,
    affiliateUrl: 'https://www.flipkart.com',
  },

  // ── Home ───────────────────────────────────────────────────────────────────
  {
    id: 'hom-1',
    name: 'Philips HD9270 Air Fryer',
    brand: 'Philips',
    platform: 'Amazon',
    originalPrice: '₹9,995',
    discountedPrice: '₹6,499',
    priceValue: 6499,
    rating: 4.5,
    reviews: '22,100',
    discountPercent: 35,
    category: 'Home',
    imageUrl: 'https://images.unsplash.com/photo-1585515320310-259814833e62?w=400&h=400&fit=crop',
    description: '6.2L capacity, Rapid Air Technology, 13 cooking presets. Fry, bake, grill and roast with 90% less fat.',
    tags: ['Air Fryer', '6.2L', 'Philips'],
    inStock: true,
    affiliateUrl: 'https://www.amazon.in',
  },
  {
    id: 'hom-2',
    name: 'Prestige PIC 20 Induction',
    brand: 'Prestige',
    platform: 'Flipkart',
    originalPrice: '₹2,800',
    discountedPrice: '₹1,799',
    priceValue: 1799,
    rating: 4.0,
    reviews: '31,450',
    discountPercent: 36,
    category: 'Home',
    imageUrl: 'https://images.unsplash.com/photo-1556911073-52527ac43761?w=400&h=400&fit=crop',
    description: '2000W power, feather touch controls, auto-off safety, 7 preset cooking menus. Smart cooking simplified.',
    tags: ['2000W', 'Auto-off', 'Induction'],
    inStock: true,
    affiliateUrl: 'https://www.flipkart.com',
  },
  {
    id: 'hom-3',
    name: 'Kent Grand Star RO Purifier',
    brand: 'Kent',
    platform: 'Amazon',
    originalPrice: '₹18,500',
    discountedPrice: '₹12,999',
    priceValue: 12999,
    rating: 4.3,
    reviews: '9,870',
    discountPercent: 30,
    category: 'Home',
    imageUrl: 'https://images.unsplash.com/photo-1548767797-d8c844163c4c?w=400&h=400&fit=crop',
    description: '8L storage, RO+UV+UF purification, TDS controller, 20L/hr flow. Hospital-grade purified water at home.',
    tags: ['RO+UV', '8L Tank', 'Kent'],
    inStock: true,
    affiliateUrl: 'https://www.amazon.in',
  },
  {
    id: 'hom-4',
    name: 'Orient Tornado Pedestal Fan',
    brand: 'Orient',
    platform: 'Flipkart',
    originalPrice: '₹4,299',
    discountedPrice: '₹2,999',
    priceValue: 2999,
    rating: 4.1,
    reviews: '5,600',
    discountPercent: 30,
    category: 'Home',
    imageUrl: 'https://images.unsplash.com/photo-1628177142898-93e36e4e3a50?w=400&h=400&fit=crop',
    description: '1200mm blade sweep, remote control, 100% copper motor, 5-speed settings. Powerful and whisper-quiet.',
    tags: ['Remote Control', 'Copper Motor', '5-Speed'],
    inStock: true,
    affiliateUrl: 'https://www.flipkart.com',
  },
  {
    id: 'hom-5',
    name: 'Story@Home 144TC Bedsheet Set',
    brand: 'Story@Home',
    platform: 'Amazon',
    originalPrice: '₹1,499',
    discountedPrice: '₹699',
    priceValue: 699,
    rating: 4.2,
    reviews: '18,900',
    discountPercent: 53,
    category: 'Home',
    imageUrl: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=400&h=400&fit=crop',
    description: '100% microfibre double bedsheet with 2 pillow covers, 144 thread count. Soft, fade-resistant comfort.',
    tags: ['Microfibre', 'Double Bed', '144TC'],
    inStock: true,
    affiliateUrl: 'https://www.amazon.in',
  },

  // ── Cameras ────────────────────────────────────────────────────────────────
  {
    id: 'cam-1',
    name: 'Canon EOS M200',
    brand: 'Canon',
    platform: 'Amazon',
    originalPrice: '₹44,995',
    discountedPrice: '₹32,999',
    priceValue: 32999,
    rating: 4.6,
    reviews: '3,450',
    discountPercent: 27,
    category: 'Cameras',
    imageUrl: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=400&h=400&fit=crop',
    description: '24.1MP APS-C sensor, 4K video, Dual Pixel autofocus, touchscreen. Perfect first mirrorless camera.',
    tags: ['24MP', '4K Video', 'Mirrorless'],
    inStock: true,
    affiliateUrl: 'https://www.amazon.in',
  },
  {
    id: 'cam-2',
    name: 'Sony ZV-E10 Mirrorless',
    brand: 'Sony',
    platform: 'Amazon',
    originalPrice: '₹59,990',
    discountedPrice: '₹49,990',
    priceValue: 49990,
    rating: 4.7,
    reviews: '2,180',
    discountPercent: 17,
    category: 'Cameras',
    imageUrl: 'https://images.unsplash.com/photo-1607462109225-6b64ae2dd3cb?w=400&h=400&fit=crop',
    description: '24.2MP APS-C, 4K 30fps, directional 3-capsule mic, fast hybrid AF. The vlogger\'s best friend.',
    tags: ['Vlogging', '4K', 'Sony'],
    inStock: true,
    affiliateUrl: 'https://www.amazon.in',
  },
  {
    id: 'cam-3',
    name: 'GoPro Hero 12 Black',
    brand: 'GoPro',
    platform: 'Amazon',
    originalPrice: '₹39,500',
    discountedPrice: '₹34,990',
    priceValue: 34990,
    rating: 4.5,
    reviews: '4,320',
    discountPercent: 11,
    category: 'Cameras',
    imageUrl: 'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=400&h=400&fit=crop',
    description: '5.3K60 video, HyperSmooth 6.0 stabilisation, 27MP photos, waterproof to 10m. Adventure-ready.',
    tags: ['5.3K', 'Waterproof', 'Action Cam'],
    inStock: true,
    affiliateUrl: 'https://www.amazon.in',
  },
  {
    id: 'cam-4',
    name: 'Digitek Portable Tripod 7ft',
    brand: 'Digitek',
    platform: 'Flipkart',
    originalPrice: '₹2,499',
    discountedPrice: '₹1,299',
    priceValue: 1299,
    rating: 4.0,
    reviews: '8,760',
    discountPercent: 48,
    category: 'Cameras',
    imageUrl: 'https://images.unsplash.com/photo-1531265726475-52ad60219627?w=400&h=400&fit=crop',
    description: '7ft max height, 4kg load capacity, universal mount, carry bag included. Studio quality at home.',
    tags: ['7ft', 'Portable', 'Universal Mount'],
    inStock: true,
    affiliateUrl: 'https://www.flipkart.com',
  },

  // ── Gaming ─────────────────────────────────────────────────────────────────
  {
    id: 'gam-1',
    name: 'Sony DualSense Controller',
    brand: 'Sony',
    platform: 'Amazon',
    originalPrice: '₹7,290',
    discountedPrice: '₹5,999',
    priceValue: 5999,
    rating: 4.7,
    reviews: '21,300',
    discountPercent: 18,
    category: 'Gaming',
    imageUrl: 'https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=400&h=400&fit=crop',
    description: 'Adaptive triggers, haptic feedback, built-in mic, USB-C charging. Next-gen feel for PS5 and PC.',
    tags: ['PS5', 'Haptic', 'Adaptive Triggers'],
    inStock: true,
    affiliateUrl: 'https://www.amazon.in',
  },
  {
    id: 'gam-2',
    name: 'Redgear MK851 Mech Keyboard',
    brand: 'Redgear',
    platform: 'Flipkart',
    originalPrice: '₹3,999',
    discountedPrice: '₹2,499',
    priceValue: 2499,
    rating: 4.2,
    reviews: '9,870',
    discountPercent: 38,
    category: 'Gaming',
    imageUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=400&h=400&fit=crop',
    description: 'Outemu Blue switches, full RGB backlighting, N-key rollover, metal plate. Best budget mech keyboard.',
    tags: ['Mechanical', 'RGB', 'N-Key Rollover'],
    inStock: true,
    affiliateUrl: 'https://www.flipkart.com',
  },
  {
    id: 'gam-3',
    name: 'Logitech G502 X Gaming Mouse',
    brand: 'Logitech',
    platform: 'Amazon',
    originalPrice: '₹5,995',
    discountedPrice: '₹4,495',
    priceValue: 4495,
    rating: 4.6,
    reviews: '6,540',
    discountPercent: 25,
    category: 'Gaming',
    imageUrl: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400&h=400&fit=crop',
    description: 'HERO 25K sensor, 13 programmable buttons, LIGHTFORCE switches, 89g. Precision for competitive gaming.',
    tags: ['25K DPI', '89g', 'HERO Sensor'],
    inStock: true,
    affiliateUrl: 'https://www.amazon.in',
  },
  {
    id: 'gam-4',
    name: 'HyperX Cloud II Gaming Headset',
    brand: 'HyperX',
    platform: 'Amazon',
    originalPrice: '₹7,999',
    discountedPrice: '₹5,499',
    priceValue: 5499,
    rating: 4.5,
    reviews: '14,230',
    discountPercent: 31,
    category: 'Gaming',
    imageUrl: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=400&h=400&fit=crop',
    description: '53mm drivers, virtual 7.1 surround, memory foam ear cups, detachable mic. Award-winning audio.',
    tags: ['7.1 Surround', '53mm Drivers', 'Memory Foam'],
    inStock: true,
    affiliateUrl: 'https://www.amazon.in',
  },
  {
    id: 'gam-5',
    name: 'Nintendo Switch OLED',
    brand: 'Nintendo',
    platform: 'Amazon',
    originalPrice: '₹35,999',
    discountedPrice: '₹33,999',
    priceValue: 33999,
    rating: 4.8,
    reviews: '8,900',
    discountPercent: 6,
    category: 'Gaming',
    imageUrl: 'https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?w=400&h=400&fit=crop',
    description: '7" OLED screen, enhanced audio, 64GB storage, wide adjustable stand. Play anywhere, anytime.',
    tags: ['OLED', 'Portable', 'Nintendo'],
    inStock: true,
    affiliateUrl: 'https://www.amazon.in',
  },

  // ── Electronics ────────────────────────────────────────────────────────────
  {
    id: 'ele-1',
    name: 'boAt Airdopes 141 TWS',
    brand: 'boAt',
    platform: 'Amazon',
    originalPrice: '₹2,990',
    discountedPrice: '₹999',
    priceValue: 999,
    rating: 4.1,
    reviews: '89,300',
    discountPercent: 67,
    category: 'Electronics',
    imageUrl: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400&h=400&fit=crop',
    description: '42H total playback, BEAST Mode low latency, ENx mic, IPX4 rated. India\'s most popular TWS earbuds.',
    tags: ['42H Battery', 'BEAST Mode', 'IPX4'],
    inStock: true,
    affiliateUrl: 'https://www.amazon.in',
  },
  {
    id: 'ele-2',
    name: 'Samsung 43" 4K Crystal UHD TV',
    brand: 'Samsung',
    platform: 'Amazon',
    originalPrice: '₹42,990',
    discountedPrice: '₹28,999',
    priceValue: 28999,
    rating: 4.3,
    reviews: '8,421',
    discountPercent: 33,
    category: 'Electronics',
    imageUrl: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829e1?w=400&h=400&fit=crop',
    description: 'Crystal Processor 4K, PurColor, HDR, Tizen OS, 3 HDMI ports. Vivid viewing on a budget.',
    tags: ['4K UHD', 'HDR', 'Smart TV'],
    inStock: true,
    affiliateUrl: 'https://www.amazon.in',
  },
  {
    id: 'ele-3',
    name: 'JBL Charge 5 Bluetooth Speaker',
    brand: 'JBL',
    platform: 'Amazon',
    originalPrice: '₹16,999',
    discountedPrice: '₹12,999',
    priceValue: 12999,
    rating: 4.6,
    reviews: '11,450',
    discountPercent: 24,
    category: 'Electronics',
    imageUrl: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=400&h=400&fit=crop',
    description: '20H playtime, IP67 waterproof, built-in power bank, PartyBoost. The party speaker built to last.',
    tags: ['20H Battery', 'IP67', 'Power Bank'],
    inStock: true,
    affiliateUrl: 'https://www.amazon.in',
  },
  {
    id: 'ele-4',
    name: 'Apple Watch SE (2nd Gen)',
    brand: 'Apple',
    platform: 'Flipkart',
    originalPrice: '₹32,900',
    discountedPrice: '₹26,900',
    priceValue: 26900,
    rating: 4.7,
    reviews: '19,870',
    discountPercent: 18,
    category: 'Electronics',
    imageUrl: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=400&h=400&fit=crop',
    description: 'S8 chip, crash detection, heart rate & SpO2 monitoring, swimproof. The essential Apple Watch.',
    tags: ['Health Tracking', 'Crash Detection', 'Swimproof'],
    inStock: true,
    affiliateUrl: 'https://www.flipkart.com',
  },
  {
    id: 'ele-5',
    name: 'Anker 523 PowerCore 20000',
    brand: 'Anker',
    platform: 'Amazon',
    originalPrice: '₹2,999',
    discountedPrice: '₹1,999',
    priceValue: 1999,
    rating: 4.4,
    reviews: '44,200',
    discountPercent: 33,
    category: 'Electronics',
    imageUrl: 'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=400&h=400&fit=crop',
    description: '20000mAh, dual USB-A + USB-C, 22.5W fast charge, PowerIQ 3.0. Charge 3 devices simultaneously.',
    tags: ['20000mAh', '22.5W Fast Charge', 'Anker'],
    inStock: true,
    affiliateUrl: 'https://www.amazon.in',
  },

  // ── Footwear ───────────────────────────────────────────────────────────────
  {
    id: 'foo-1',
    name: 'Nike Revolution 7 Running',
    brand: 'Nike',
    platform: 'Flipkart',
    originalPrice: '₹5,999',
    discountedPrice: '₹3,995',
    priceValue: 3995,
    rating: 4.2,
    reviews: '7,890',
    discountPercent: 33,
    category: 'Footwear',
    imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop',
    description: 'Foam midsole, rubber outsole for grip, breathable mesh upper. Everyday running made comfortable.',
    tags: ['Running', 'Foam Midsole', 'Breathable'],
    inStock: true,
    affiliateUrl: 'https://www.flipkart.com',
  },
  {
    id: 'foo-2',
    name: 'Bata Men\'s Formal Derby',
    brand: 'Bata',
    platform: 'Flipkart',
    originalPrice: '₹2,499',
    discountedPrice: '₹1,299',
    priceValue: 1299,
    rating: 4.0,
    reviews: '12,400',
    discountPercent: 48,
    category: 'Footwear',
    imageUrl: 'https://images.unsplash.com/photo-1449505278894-297fdb3edbc1?w=400&h=400&fit=crop',
    description: 'Genuine leather upper, cushioned insole, non-slip sole. Office-ready formal shoes at an unbeatable price.',
    tags: ['Formal', 'Leather', 'Office Wear'],
    inStock: true,
    affiliateUrl: 'https://www.flipkart.com',
  },
  {
    id: 'foo-3',
    name: 'Puma Cell Vive Sneakers',
    brand: 'Puma',
    platform: 'Amazon',
    originalPrice: '₹4,999',
    discountedPrice: '₹2,999',
    priceValue: 2999,
    rating: 4.3,
    reviews: '5,670',
    discountPercent: 40,
    category: 'Footwear',
    imageUrl: 'https://images.unsplash.com/photo-1556906781-9a412961d28b?w=400&h=400&fit=crop',
    description: 'CELL technology cushioning, breathable mesh upper, flexible outsole. Sport-casual hybrid for all day.',
    tags: ['CELL Cushioning', 'Casual', 'Puma'],
    inStock: true,
    affiliateUrl: 'https://www.amazon.in',
  },
  {
    id: 'foo-4',
    name: 'Crocs Classic Clog',
    brand: 'Crocs',
    platform: 'Amazon',
    originalPrice: '₹4,295',
    discountedPrice: '₹2,995',
    priceValue: 2995,
    rating: 4.5,
    reviews: '23,100',
    discountPercent: 30,
    category: 'Footwear',
    imageUrl: 'https://images.unsplash.com/photo-1515347619252-60a4bf4fff4f?w=400&h=400&fit=crop',
    description: 'Croslite foam construction, 13 ventilation ports, pivoting heel straps. Iconic comfort all day long.',
    tags: ['Croslite Foam', 'Ventilated', 'Iconic'],
    inStock: true,
    affiliateUrl: 'https://www.amazon.in',
  },

  // ── Books ──────────────────────────────────────────────────────────────────
  {
    id: 'boo-1',
    name: 'Atomic Habits — James Clear',
    brand: 'Penguin',
    platform: 'Amazon',
    originalPrice: '₹799',
    discountedPrice: '₹389',
    priceValue: 389,
    rating: 4.8,
    reviews: '1,23,400',
    discountPercent: 51,
    category: 'Books',
    imageUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&h=400&fit=crop',
    description: 'The #1 bestselling guide to building good habits and breaking bad ones. Over 10 million copies sold worldwide.',
    tags: ['Self-Help', 'Bestseller', 'Habits'],
    inStock: true,
    affiliateUrl: 'https://www.amazon.in',
  },
  {
    id: 'boo-2',
    name: 'The Alchemist — Paulo Coelho',
    brand: 'HarperCollins',
    platform: 'Amazon',
    originalPrice: '₹399',
    discountedPrice: '₹199',
    priceValue: 199,
    rating: 4.7,
    reviews: '89,700',
    discountPercent: 50,
    category: 'Books',
    imageUrl: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400&h=400&fit=crop',
    description: 'A magical story about following your dreams. Translated into 80 languages, 65 million copies sold.',
    tags: ['Fiction', 'Inspirational', 'Classic'],
    inStock: true,
    affiliateUrl: 'https://www.amazon.in',
  },
  {
    id: 'boo-3',
    name: 'Rich Dad Poor Dad — Robert Kiyosaki',
    brand: 'Plata Publishing',
    platform: 'Flipkart',
    originalPrice: '₹499',
    discountedPrice: '₹259',
    priceValue: 259,
    rating: 4.6,
    reviews: '67,200',
    discountPercent: 48,
    category: 'Books',
    imageUrl: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=400&h=400&fit=crop',
    description: 'The global bestseller on financial literacy, investing, and building wealth. A life-changing read.',
    tags: ['Finance', 'Investing', 'Bestseller'],
    inStock: true,
    affiliateUrl: 'https://www.flipkart.com',
  },
  {
    id: 'boo-4',
    name: 'Psychology of Money — Morgan Housel',
    brand: 'Harriman House',
    platform: 'Amazon',
    originalPrice: '₹699',
    discountedPrice: '₹349',
    priceValue: 349,
    rating: 4.7,
    reviews: '54,300',
    discountPercent: 50,
    category: 'Books',
    imageUrl: 'https://images.unsplash.com/photo-1457369804613-52c61a468e7d?w=400&h=400&fit=crop',
    description: '19 short stories exploring the strange ways people think about money. Essential personal finance reading.',
    tags: ['Finance', 'Psychology', 'Personal Finance'],
    inStock: true,
    affiliateUrl: 'https://www.amazon.in',
  },

  // ── Beauty ─────────────────────────────────────────────────────────────────
  {
    id: 'bea-1',
    name: 'Lakme CC Cream SPF 30',
    brand: 'Lakme',
    platform: 'Amazon',
    originalPrice: '₹599',
    discountedPrice: '₹299',
    priceValue: 299,
    rating: 4.1,
    reviews: '18,700',
    discountPercent: 50,
    category: 'Beauty',
    imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&h=400&fit=crop',
    description: 'SPF 30, 9-in-1 benefits, light-medium coverage, dermatologist tested. The everyday complexion corrector.',
    tags: ['SPF 30', 'CC Cream', 'Dermatologist Tested'],
    inStock: true,
    affiliateUrl: 'https://www.amazon.in',
  },
  {
    id: 'bea-2',
    name: 'Mamaearth Vitamin C Moisturiser',
    brand: 'Mamaearth',
    platform: 'Flipkart',
    originalPrice: '₹699',
    discountedPrice: '₹449',
    priceValue: 449,
    rating: 4.3,
    reviews: '32,400',
    discountPercent: 36,
    category: 'Beauty',
    imageUrl: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=400&h=400&fit=crop',
    description: 'Vitamin C & Turmeric, SPF 20, non-greasy formula, MadeSafe certified. Glowing skin all day.',
    tags: ['Vitamin C', 'SPF 20', 'Non-Greasy'],
    inStock: true,
    affiliateUrl: 'https://www.flipkart.com',
  },
  {
    id: 'bea-3',
    name: 'Vega Style Ion Hair Dryer',
    brand: 'Vega',
    platform: 'Amazon',
    originalPrice: '₹1,595',
    discountedPrice: '₹799',
    priceValue: 799,
    rating: 4.0,
    reviews: '24,900',
    discountPercent: 50,
    category: 'Beauty',
    imageUrl: 'https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=400&h=400&fit=crop',
    description: '1800W motor, 2 heat settings, cool shot button, ionic technology. Frizz-free blowout at home.',
    tags: ['1800W', 'Ionic', 'Cool Shot'],
    inStock: true,
    affiliateUrl: 'https://www.amazon.in',
  },
  {
    id: 'bea-4',
    name: 'Engage W1 Perfume Spray',
    brand: 'Engage',
    platform: 'Amazon',
    originalPrice: '₹799',
    discountedPrice: '₹399',
    priceValue: 399,
    rating: 4.2,
    reviews: '11,200',
    discountPercent: 50,
    category: 'Beauty',
    imageUrl: 'https://images.unsplash.com/photo-1547887538-047f3a8503f5?w=400&h=400&fit=crop',
    description: '150ml, long-lasting floral-woody fragrance, skin-friendly formula. All-day freshness for women.',
    tags: ['Floral', 'Long-Lasting', '150ml'],
    inStock: true,
    affiliateUrl: 'https://www.amazon.in',
  },

  // ── Sports ─────────────────────────────────────────────────────────────────
  {
    id: 'spo-1',
    name: 'Boldfit Premium Yoga Mat 6mm',
    brand: 'Boldfit',
    platform: 'Amazon',
    originalPrice: '₹1,299',
    discountedPrice: '₹699',
    priceValue: 699,
    rating: 4.3,
    reviews: '28,900',
    discountPercent: 46,
    category: 'Sports',
    imageUrl: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=400&h=400&fit=crop',
    description: '6mm thick TPE foam, anti-slip texture, carry strap, sweat-resistant. Perfect for yoga and home workouts.',
    tags: ['6mm', 'Anti-Slip', 'TPE Foam'],
    inStock: true,
    affiliateUrl: 'https://www.amazon.in',
  },
  {
    id: 'spo-2',
    name: 'PowerMax Hex Dumbbell Set 10kg',
    brand: 'PowerMax',
    platform: 'Flipkart',
    originalPrice: '₹2,499',
    discountedPrice: '₹1,499',
    priceValue: 1499,
    rating: 4.4,
    reviews: '9,340',
    discountPercent: 40,
    category: 'Sports',
    imageUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400&h=400&fit=crop',
    description: 'Rubber-coated hex design, anti-roll, chrome handle, pair of 5kg. Home gym essentials for beginners.',
    tags: ['Rubber Coated', 'Hex Design', 'Pair'],
    inStock: true,
    affiliateUrl: 'https://www.flipkart.com',
  },
  {
    id: 'spo-3',
    name: 'SG English Willow Cricket Bat',
    brand: 'SG',
    platform: 'Amazon',
    originalPrice: '₹2,999',
    discountedPrice: '₹1,899',
    priceValue: 1899,
    rating: 4.2,
    reviews: '6,780',
    discountPercent: 37,
    category: 'Sports',
    imageUrl: 'https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=400&h=400&fit=crop',
    description: 'Grade 3 English Willow, full cane handle, 2.7 lbs, short handle. Trusted by club cricketers.',
    tags: ['English Willow', 'Grade 3', 'SG'],
    inStock: true,
    affiliateUrl: 'https://www.amazon.in',
  },
  {
    id: 'spo-4',
    name: 'Yonex Muscle Power Badminton Racket',
    brand: 'Yonex',
    platform: 'Flipkart',
    originalPrice: '₹2,299',
    discountedPrice: '₹1,299',
    priceValue: 1299,
    rating: 4.3,
    reviews: '14,500',
    discountPercent: 43,
    category: 'Sports',
    imageUrl: 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=400&h=400&fit=crop',
    description: 'Graphite shaft, T-joint reinforcement, pre-strung, includes full cover. Ideal for recreational play.',
    tags: ['Graphite', 'Pre-strung', 'Yonex'],
    inStock: true,
    affiliateUrl: 'https://www.flipkart.com',
  },

  // ── Toys ───────────────────────────────────────────────────────────────────
  {
    id: 'toy-1',
    name: 'LEGO Classic Creative Bricks',
    brand: 'LEGO',
    platform: 'Amazon',
    originalPrice: '₹3,999',
    discountedPrice: '₹2,499',
    priceValue: 2499,
    rating: 4.8,
    reviews: '4,560',
    discountPercent: 38,
    category: 'Toys',
    imageUrl: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=400&h=400&fit=crop',
    description: '484 pieces, 33 LEGO colours, 9 base plates. Endless creative building for ages 4+.',
    tags: ['Ages 4+', '484 Pieces', 'Creative'],
    inStock: true,
    affiliateUrl: 'https://www.amazon.in',
  },
  {
    id: 'toy-2',
    name: 'Hot Wheels 20-Car Gift Pack',
    brand: 'Hot Wheels',
    platform: 'Flipkart',
    originalPrice: '₹1,999',
    discountedPrice: '₹1,299',
    priceValue: 1299,
    rating: 4.6,
    reviews: '11,200',
    discountPercent: 35,
    category: 'Toys',
    imageUrl: 'https://images.unsplash.com/photo-1594736797933-d0501ba2fe65?w=400&h=400&fit=crop',
    description: '20 die-cast vehicles, 1:64 scale, assorted designs. The perfect gift for little car enthusiasts.',
    tags: ['Die-Cast', '20 Cars', 'Ages 3+'],
    inStock: true,
    affiliateUrl: 'https://www.flipkart.com',
  },
  {
    id: 'toy-3',
    name: 'Barbie Dreamhouse Adventures',
    brand: 'Barbie',
    platform: 'Amazon',
    originalPrice: '₹7,999',
    discountedPrice: '₹4,999',
    priceValue: 4999,
    rating: 4.4,
    reviews: '3,890',
    discountPercent: 38,
    category: 'Toys',
    imageUrl: 'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=400&h=400&fit=crop',
    description: '3-storey, 7 play areas, 70+ accessories, colour-change features. Imagination-packed playset for ages 3+.',
    tags: ['Ages 3+', '70+ Accessories', 'Playset'],
    inStock: true,
    affiliateUrl: 'https://www.amazon.in',
  },
  {
    id: 'toy-4',
    name: 'Funskool Snakes & Ladders + Ludo',
    brand: 'Funskool',
    platform: 'Amazon',
    originalPrice: '₹999',
    discountedPrice: '₹599',
    priceValue: 599,
    rating: 4.5,
    reviews: '8,760',
    discountPercent: 40,
    category: 'Toys',
    imageUrl: 'https://images.unsplash.com/photo-1611996575749-79a3a250f948?w=400&h=400&fit=crop',
    description: '2-in-1 classic board game, vibrant printed board, 4 player tokens, dice. Family game night favourite.',
    tags: ['Board Game', '2-in-1', 'Family'],
    inStock: true,
    affiliateUrl: 'https://www.amazon.in',
  },

  // ── Mobiles (extra) ────────────────────────────────────────────────────────
  {
    id: 'mob-6',
    name: 'Poco X6 Pro 5G',
    brand: 'Poco',
    platform: 'Flipkart',
    originalPrice: '₹26,999',
    discountedPrice: '₹21,999',
    priceValue: 21999,
    rating: 4.4,
    reviews: '18,300',
    discountPercent: 19,
    category: 'Mobiles',
    imageUrl: 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=400&h=400&fit=crop',
    description: 'Dimensity 8300 Ultra, 6.67" 144Hz AMOLED, 67W fast charge, 64MP OIS camera. Performance powerhouse.',
    tags: ['Dimensity 8300', '144Hz', '67W Charge'],
    inStock: true,
    affiliateUrl: 'https://www.flipkart.com',
  },
  {
    id: 'mob-7',
    name: 'iQOO Z9s 5G',
    brand: 'iQOO',
    platform: 'Flipkart',
    originalPrice: '₹22,999',
    discountedPrice: '₹17,999',
    priceValue: 17999,
    rating: 4.3,
    reviews: '9,800',
    discountPercent: 22,
    category: 'Mobiles',
    imageUrl: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400&h=400&fit=crop',
    description: 'Snapdragon 7s Gen 3, 5000mAh battery, 50MP rear camera, IP54 rating. Reliable daily driver.',
    tags: ['Snapdragon 7s', 'IP54', '5000mAh'],
    inStock: true,
    affiliateUrl: 'https://www.flipkart.com',
  },

  // ── Laptops (extra) ────────────────────────────────────────────────────────
  {
    id: 'lap-6',
    name: 'HP Pavilion 14 Core i5',
    brand: 'HP',
    platform: 'Flipkart',
    originalPrice: '₹65,990',
    discountedPrice: '₹49,990',
    priceValue: 49990,
    rating: 4.2,
    reviews: '4,560',
    discountPercent: 24,
    category: 'Laptops',
    imageUrl: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400&h=400&fit=crop',
    description: '12th Gen Core i5, 16GB RAM, 512GB SSD, 14" FHD IPS, Win 11. Balanced performance for daily work.',
    tags: ['Core i5', '16GB RAM', 'FHD IPS'],
    inStock: true,
    affiliateUrl: 'https://www.flipkart.com',
  },
  {
    id: 'lap-7',
    name: 'Lenovo IdeaPad Slim 3',
    brand: 'Lenovo',
    platform: 'Amazon',
    originalPrice: '₹57,490',
    discountedPrice: '₹44,990',
    priceValue: 44990,
    rating: 4.1,
    reviews: '6,870',
    discountPercent: 22,
    category: 'Laptops',
    imageUrl: 'https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=400&h=400&fit=crop',
    description: 'Ryzen 5 7520U, 8GB RAM, 512GB SSD, 15.6" FHD, Win 11. Slim, lightweight everyday laptop.',
    tags: ['Ryzen 5', 'Slim', '512GB SSD'],
    inStock: true,
    affiliateUrl: 'https://www.amazon.in',
  },

  // ── Fashion (extra) ────────────────────────────────────────────────────────
  {
    id: 'fas-6',
    name: 'Allen Solly Men\'s Slim Fit Chinos',
    brand: 'Allen Solly',
    platform: 'Amazon',
    originalPrice: '₹2,999',
    discountedPrice: '₹1,499',
    priceValue: 1499,
    rating: 4.2,
    reviews: '14,500',
    discountPercent: 50,
    category: 'Fashion',
    imageUrl: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=400&h=400&fit=crop',
    description: 'Slim fit, stretch fabric, mid-rise waist, available in 8 colours. Office-to-weekend versatility.',
    tags: ['Slim Fit', 'Stretch', 'Chinos'],
    inStock: true,
    affiliateUrl: 'https://www.amazon.in',
  },
  {
    id: 'fas-7',
    name: 'W Women\'s A-Line Kurta',
    brand: 'W',
    platform: 'Myntra',
    originalPrice: '₹1,999',
    discountedPrice: '₹999',
    priceValue: 999,
    rating: 4.4,
    reviews: '22,300',
    discountPercent: 50,
    category: 'Fashion',
    imageUrl: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400&h=400&fit=crop',
    description: 'Cotton blend, block print, A-line silhouette, 3/4 sleeves. Effortless ethnic elegance for all occasions.',
    tags: ['Cotton', 'Block Print', 'A-Line'],
    inStock: true,
    affiliateUrl: 'https://www.flipkart.com',
  },

  // ── Home (extra) ──────────────────────────────────────────────────────────
  {
    id: 'hom-6',
    name: 'Pigeon Healthifry Digital Air Fryer 4.2L',
    brand: 'Pigeon',
    platform: 'Amazon',
    originalPrice: '₹5,999',
    discountedPrice: '₹3,299',
    priceValue: 3299,
    rating: 4.3,
    reviews: '19,800',
    discountPercent: 45,
    category: 'Home',
    imageUrl: 'https://images.unsplash.com/photo-1585515320310-259814833e62?w=400&h=400&fit=crop',
    description: '4.2L capacity, digital touch panel, 8 preset modes, 1400W, auto shut-off. Oil-free healthy cooking.',
    tags: ['4.2L', 'Digital', '1400W'],
    inStock: true,
    affiliateUrl: 'https://www.amazon.in',
  },
  {
    id: 'hom-7',
    name: 'Milton Thermosteel Flask 1L',
    brand: 'Milton',
    platform: 'Amazon',
    originalPrice: '₹1,299',
    discountedPrice: '₹699',
    priceValue: 699,
    rating: 4.5,
    reviews: '45,600',
    discountPercent: 46,
    category: 'Home',
    imageUrl: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400&h=400&fit=crop',
    description: '18/8 stainless steel, keeps hot 24hr/cold 48hr, 1L capacity, leak-proof lid. Essential hydration companion.',
    tags: ['24hr Hot', '48hr Cold', 'Leak-Proof'],
    inStock: true,
    affiliateUrl: 'https://www.amazon.in',
  },

  // ── Cameras (extra) ───────────────────────────────────────────────────────
  {
    id: 'cam-5',
    name: 'GoPro HERO12 Black',
    brand: 'GoPro',
    platform: 'Amazon',
    originalPrice: '₹44,000',
    discountedPrice: '₹34,990',
    priceValue: 34990,
    rating: 4.7,
    reviews: '2,890',
    discountPercent: 20,
    category: 'Cameras',
    imageUrl: 'https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=400&h=400&fit=crop',
    description: '5.3K60 video, 27MP photos, HyperSmooth 6.0, waterproof to 10m. The ultimate action camera.',
    tags: ['5.3K Video', 'HyperSmooth', 'Waterproof'],
    inStock: true,
    affiliateUrl: 'https://www.amazon.in',
  },
  {
    id: 'cam-6',
    name: 'Nikon Z30 Mirrorless Vlogger Kit',
    brand: 'Nikon',
    platform: 'Amazon',
    originalPrice: '₹72,995',
    discountedPrice: '₹59,995',
    priceValue: 59995,
    rating: 4.5,
    reviews: '1,340',
    discountPercent: 18,
    category: 'Cameras',
    imageUrl: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=400&h=400&fit=crop',
    description: '20.9MP APS-C, 4K UHD, flip touchscreen, no viewfinder — built for content creators on the go.',
    tags: ['4K UHD', 'Flip Screen', 'Vlogger'],
    inStock: true,
    affiliateUrl: 'https://www.amazon.in',
  },

  // ── Gaming (extra) ────────────────────────────────────────────────────────
  {
    id: 'gam-6',
    name: 'Razer BlackWidow V3 Keyboard',
    brand: 'Razer',
    platform: 'Amazon',
    originalPrice: '₹11,999',
    discountedPrice: '₹7,999',
    priceValue: 7999,
    rating: 4.6,
    reviews: '3,450',
    discountPercent: 33,
    category: 'Gaming',
    imageUrl: 'https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=400&h=400&fit=crop',
    description: 'Razer Green switches, Chroma RGB, titanium switch coating, multi-function roller. Tactile typing perfection.',
    tags: ['Green Switches', 'Chroma RGB', 'Mechanical'],
    inStock: true,
    affiliateUrl: 'https://www.amazon.in',
  },
  {
    id: 'gam-7',
    name: 'Sony DualSense PS5 Controller',
    brand: 'Sony',
    platform: 'Amazon',
    originalPrice: '₹7,990',
    discountedPrice: '₹5,990',
    priceValue: 5990,
    rating: 4.8,
    reviews: '12,700',
    discountPercent: 25,
    category: 'Gaming',
    imageUrl: 'https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?w=400&h=400&fit=crop',
    description: 'Adaptive triggers, haptic feedback, built-in mic, USB-C charging. Next-gen gaming feel.',
    tags: ['Adaptive Triggers', 'Haptic', 'PS5'],
    inStock: true,
    affiliateUrl: 'https://www.amazon.in',
  },

  // ── Electronics (extra) ───────────────────────────────────────────────────
  {
    id: 'ele-6',
    name: 'Xiaomi Smart Band 8 Pro',
    brand: 'Xiaomi',
    platform: 'Flipkart',
    originalPrice: '₹4,999',
    discountedPrice: '₹3,499',
    priceValue: 3499,
    rating: 4.4,
    reviews: '21,800',
    discountPercent: 30,
    category: 'Electronics',
    imageUrl: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=400&h=400&fit=crop',
    description: '1.74" AMOLED, GPS, SpO2, heart rate, 150+ sports modes, 14-day battery. Premium fitness tracking.',
    tags: ['AMOLED', 'GPS', '14-Day Battery'],
    inStock: true,
    affiliateUrl: 'https://www.flipkart.com',
  },
  {
    id: 'ele-7',
    name: 'Anker 65W GaN USB-C Charger',
    brand: 'Anker',
    platform: 'Amazon',
    originalPrice: '₹3,499',
    discountedPrice: '₹2,299',
    priceValue: 2299,
    rating: 4.6,
    reviews: '8,930',
    discountPercent: 34,
    category: 'Electronics',
    imageUrl: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=400&h=400&fit=crop',
    description: '65W GaN tech, 3-port (2C+1A), foldable plug, compact design. Charge laptop + phone + tablet at once.',
    tags: ['65W GaN', '3-Port', 'Compact'],
    inStock: true,
    affiliateUrl: 'https://www.amazon.in',
  },

  // ── Footwear (extra) ──────────────────────────────────────────────────────
  {
    id: 'foo-5',
    name: 'Sparx Men\'s Running Shoes',
    brand: 'Sparx',
    platform: 'Amazon',
    originalPrice: '₹2,499',
    discountedPrice: '₹1,099',
    priceValue: 1099,
    rating: 4.1,
    reviews: '32,400',
    discountPercent: 56,
    category: 'Footwear',
    imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop',
    description: 'EVA midsole, mesh upper, non-marking rubber sole. Lightweight and breathable for daily jogging.',
    tags: ['EVA Midsole', 'Mesh', 'Lightweight'],
    inStock: true,
    affiliateUrl: 'https://www.amazon.in',
  },
  {
    id: 'foo-6',
    name: 'Woodland Women\'s Casual Boots',
    brand: 'Woodland',
    platform: 'Flipkart',
    originalPrice: '₹4,999',
    discountedPrice: '₹2,999',
    priceValue: 2999,
    rating: 4.3,
    reviews: '7,200',
    discountPercent: 40,
    category: 'Footwear',
    imageUrl: 'https://images.unsplash.com/photo-1449505278894-297fdb3edbc1?w=400&h=400&fit=crop',
    description: 'Genuine leather upper, lace-up closure, rugged rubber sole, ankle height. Style meets durability.',
    tags: ['Leather', 'Ankle Boot', 'Woodland'],
    inStock: true,
    affiliateUrl: 'https://www.flipkart.com',
  },

  // ── Books (extra) ─────────────────────────────────────────────────────────
  {
    id: 'boo-5',
    name: 'Zero to One — Peter Thiel',
    brand: 'Crown Business',
    platform: 'Amazon',
    originalPrice: '₹599',
    discountedPrice: '₹289',
    priceValue: 289,
    rating: 4.5,
    reviews: '34,100',
    discountPercent: 52,
    category: 'Books',
    imageUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&h=400&fit=crop',
    description: 'Notes on startups and how to build the future. Essential reading for every entrepreneur and innovator.',
    tags: ['Startups', 'Business', 'Entrepreneurship'],
    inStock: true,
    affiliateUrl: 'https://www.amazon.in',
  },
  {
    id: 'boo-6',
    name: 'Deep Work — Cal Newport',
    brand: 'Grand Central',
    platform: 'Amazon',
    originalPrice: '₹599',
    discountedPrice: '₹299',
    priceValue: 299,
    rating: 4.6,
    reviews: '28,700',
    discountPercent: 50,
    category: 'Books',
    imageUrl: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400&h=400&fit=crop',
    description: 'Rules for focused success in a distracted world. How to achieve peak productivity and meaningful work.',
    tags: ['Productivity', 'Focus', 'Career'],
    inStock: true,
    affiliateUrl: 'https://www.amazon.in',
  },
  {
    id: 'boo-7',
    name: 'The Midnight Library — Matt Haig',
    brand: 'Canongate',
    platform: 'Flipkart',
    originalPrice: '₹499',
    discountedPrice: '₹249',
    priceValue: 249,
    rating: 4.5,
    reviews: '19,800',
    discountPercent: 50,
    category: 'Books',
    imageUrl: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=400&h=400&fit=crop',
    description: 'Between life and death is a library of infinite second chances. A heartwarming novel about choices.',
    tags: ['Fiction', 'Literary', 'Bestseller'],
    inStock: true,
    affiliateUrl: 'https://www.flipkart.com',
  },
  {
    id: 'boo-8',
    name: 'Sapiens — Yuval Noah Harari',
    brand: 'Harper',
    platform: 'Amazon',
    originalPrice: '₹799',
    discountedPrice: '₹399',
    priceValue: 399,
    rating: 4.7,
    reviews: '56,400',
    discountPercent: 50,
    category: 'Books',
    imageUrl: 'https://images.unsplash.com/photo-1457369804613-52c61a468e7d?w=400&h=400&fit=crop',
    description: 'A brief history of humankind. How Homo sapiens came to dominate Earth — a landmark work of history.',
    tags: ['History', 'Non-Fiction', 'Harari'],
    inStock: true,
    affiliateUrl: 'https://www.amazon.in',
  },
  {
    id: 'boo-9',
    name: 'The 5AM Club — Robin Sharma',
    brand: 'HarperCollins',
    platform: 'Flipkart',
    originalPrice: '₹499',
    discountedPrice: '₹239',
    priceValue: 239,
    rating: 4.3,
    reviews: '41,200',
    discountPercent: 52,
    category: 'Books',
    imageUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&h=400&fit=crop',
    description: 'Own your morning, elevate your life. A game-changing routine used by world-class performers.',
    tags: ['Productivity', 'Routine', 'Self-Help'],
    inStock: true,
    affiliateUrl: 'https://www.flipkart.com',
  },

  // ── Beauty (extra) ────────────────────────────────────────────────────────
  {
    id: 'bea-5',
    name: 'Nykaa Skinshield Sunscreen SPF 50',
    brand: 'Nykaa',
    platform: 'Flipkart',
    originalPrice: '₹899',
    discountedPrice: '₹449',
    priceValue: 449,
    rating: 4.2,
    reviews: '14,600',
    discountPercent: 50,
    category: 'Beauty',
    imageUrl: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=400&h=400&fit=crop',
    description: 'SPF 50 PA+++, matte finish, broad-spectrum UVA/UVB protection, dermatologist tested. Daily skin shield.',
    tags: ['SPF 50', 'Matte Finish', 'Broad Spectrum'],
    inStock: true,
    affiliateUrl: 'https://www.flipkart.com',
  },
  {
    id: 'bea-6',
    name: 'Biotique Bio Morning Nector Face Wash',
    brand: 'Biotique',
    platform: 'Amazon',
    originalPrice: '₹399',
    discountedPrice: '₹199',
    priceValue: 199,
    rating: 4.1,
    reviews: '29,400',
    discountPercent: 50,
    category: 'Beauty',
    imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&h=400&fit=crop',
    description: '100ml, honey and wheat germ, pH balanced, removes dirt without stripping natural oils. Gentle daily cleanser.',
    tags: ['Honey', 'pH Balanced', 'Gentle'],
    inStock: true,
    affiliateUrl: 'https://www.amazon.in',
  },
  {
    id: 'bea-7',
    name: 'L\'Oreal Paris Telescopic Mascara',
    brand: 'L\'Oreal',
    platform: 'Amazon',
    originalPrice: '₹1,099',
    discountedPrice: '₹649',
    priceValue: 649,
    rating: 4.3,
    reviews: '8,700',
    discountPercent: 41,
    category: 'Beauty',
    imageUrl: 'https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=400&h=400&fit=crop',
    description: 'Extends lashes up to 60%, separated & defined, smudge-proof formula. Long-lasting runway-ready lashes.',
    tags: ['Lengthening', 'Smudge-Proof', 'L\'Oreal'],
    inStock: true,
    affiliateUrl: 'https://www.amazon.in',
  },
  {
    id: 'bea-8',
    name: 'Dove Intense Repair Shampoo 650ml',
    brand: 'Dove',
    platform: 'Flipkart',
    originalPrice: '₹699',
    discountedPrice: '₹399',
    priceValue: 399,
    rating: 4.4,
    reviews: '33,200',
    discountPercent: 43,
    category: 'Beauty',
    imageUrl: 'https://images.unsplash.com/photo-1547887538-047f3a8503f5?w=400&h=400&fit=crop',
    description: 'Keratin actives, repairs damage, restores strength, for dry brittle hair. Salon-smooth hair at home.',
    tags: ['Keratin', 'Repair', '650ml'],
    inStock: true,
    affiliateUrl: 'https://www.flipkart.com',
  },
  {
    id: 'bea-9',
    name: 'MyGlamm Lip & Cheek Tint',
    brand: 'MyGlamm',
    platform: 'Amazon',
    originalPrice: '₹599',
    discountedPrice: '₹299',
    priceValue: 299,
    rating: 4.2,
    reviews: '6,400',
    discountPercent: 50,
    category: 'Beauty',
    imageUrl: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400&h=400&fit=crop',
    description: 'Water-based, buildable colour, 12-hour wear, dual-use for lips and cheeks. Dewy natural finish.',
    tags: ['Dual-Use', 'Buildable', '12-Hour Wear'],
    inStock: true,
    affiliateUrl: 'https://www.amazon.in',
  },

  // ── Sports (extra) ────────────────────────────────────────────────────────
  {
    id: 'spo-5',
    name: 'Cosco Challenger Football',
    brand: 'Cosco',
    platform: 'Amazon',
    originalPrice: '₹999',
    discountedPrice: '₹599',
    priceValue: 599,
    rating: 4.2,
    reviews: '21,300',
    discountPercent: 40,
    category: 'Sports',
    imageUrl: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=400&h=400&fit=crop',
    description: 'PVC outer casing, hand-stitched panels, size 5, machine-inflated. Durable all-weather football.',
    tags: ['Size 5', 'PVC', 'Hand-Stitched'],
    inStock: true,
    affiliateUrl: 'https://www.amazon.in',
  },
  {
    id: 'spo-6',
    name: 'Nivia Carbonite Basketball',
    brand: 'Nivia',
    platform: 'Flipkart',
    originalPrice: '₹1,299',
    discountedPrice: '₹799',
    priceValue: 799,
    rating: 4.3,
    reviews: '9,800',
    discountPercent: 38,
    category: 'Sports',
    imageUrl: 'https://images.unsplash.com/photo-1546519638405-a9f6b741f42b?w=400&h=400&fit=crop',
    description: 'Rubber composition, deep channel design, size 7, excellent grip. Ideal for outdoor courts.',
    tags: ['Rubber', 'Size 7', 'Outdoor'],
    inStock: true,
    affiliateUrl: 'https://www.flipkart.com',
  },
  {
    id: 'spo-7',
    name: 'Decathlon Domyos Resistance Bands Set',
    brand: 'Decathlon',
    platform: 'Amazon',
    originalPrice: '₹1,499',
    discountedPrice: '₹799',
    priceValue: 799,
    rating: 4.4,
    reviews: '18,600',
    discountPercent: 47,
    category: 'Sports',
    imageUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400&h=400&fit=crop',
    description: '5-band set, 10–50lb resistance levels, latex-free, includes carry bag. Full-body home gym solution.',
    tags: ['5-Band Set', 'Latex-Free', 'Home Gym'],
    inStock: true,
    affiliateUrl: 'https://www.amazon.in',
  },
  {
    id: 'spo-8',
    name: 'Yonex Mavis 350 Feather Shuttlecock (6 pack)',
    brand: 'Yonex',
    platform: 'Amazon',
    originalPrice: '₹999',
    discountedPrice: '₹699',
    priceValue: 699,
    rating: 4.5,
    reviews: '11,400',
    discountPercent: 30,
    category: 'Sports',
    imageUrl: 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=400&h=400&fit=crop',
    description: 'Nylon skirt, medium speed, pack of 6, suitable for indoor and outdoor play. Tournament-grade shuttlecock.',
    tags: ['Nylon', 'Pack of 6', 'Tournament'],
    inStock: true,
    affiliateUrl: 'https://www.amazon.in',
  },
  {
    id: 'spo-9',
    name: 'Nivia 8-in-1 Gym Gloves',
    brand: 'Nivia',
    platform: 'Flipkart',
    originalPrice: '₹799',
    discountedPrice: '₹449',
    priceValue: 449,
    rating: 4.1,
    reviews: '14,200',
    discountPercent: 44,
    category: 'Sports',
    imageUrl: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=400&h=400&fit=crop',
    description: 'Microfibre palm, wrist support, breathable mesh back, non-slip grip. Protect your hands during lifts.',
    tags: ['Wrist Support', 'Non-Slip', 'Microfibre'],
    inStock: true,
    affiliateUrl: 'https://www.flipkart.com',
  },

  // ── Toys (extra) ──────────────────────────────────────────────────────────
  {
    id: 'toy-5',
    name: 'Nerf Elite 2.0 Commander RD-6',
    brand: 'Nerf',
    platform: 'Amazon',
    originalPrice: '₹2,999',
    discountedPrice: '₹1,799',
    priceValue: 1799,
    rating: 4.5,
    reviews: '6,700',
    discountPercent: 40,
    category: 'Toys',
    imageUrl: 'https://images.unsplash.com/photo-1594736797933-d0501ba2fe65?w=400&h=400&fit=crop',
    description: '6-dart rotating drum, fires up to 27m, slam-fire action, includes 12 darts. Epic backyard battles.',
    tags: ['27m Range', '6-Dart Drum', 'Ages 8+'],
    inStock: true,
    affiliateUrl: 'https://www.amazon.in',
  },
  {
    id: 'toy-6',
    name: 'Skillmatics Educational Card Game',
    brand: 'Skillmatics',
    platform: 'Amazon',
    originalPrice: '₹899',
    discountedPrice: '₹499',
    priceValue: 499,
    rating: 4.6,
    reviews: '8,900',
    discountPercent: 44,
    category: 'Toys',
    imageUrl: 'https://images.unsplash.com/photo-1611996575749-79a3a250f948?w=400&h=400&fit=crop',
    description: 'Guess in 10 card game, 200 questions, ages 6+, 2–6 players. Boosts general knowledge and quick thinking.',
    tags: ['Educational', 'Ages 6+', '2-6 Players'],
    inStock: true,
    affiliateUrl: 'https://www.amazon.in',
  },
  {
    id: 'toy-7',
    name: 'Play-Doh Creativity Starter Kit',
    brand: 'Play-Doh',
    platform: 'Flipkart',
    originalPrice: '₹1,499',
    discountedPrice: '₹899',
    priceValue: 899,
    rating: 4.7,
    reviews: '12,300',
    discountPercent: 40,
    category: 'Toys',
    imageUrl: 'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=400&h=400&fit=crop',
    description: '10 non-toxic cans, 15 tools, step-by-step guide, ages 3+. Endless sculpting fun for little hands.',
    tags: ['Non-Toxic', '10 Cans', 'Ages 3+'],
    inStock: true,
    affiliateUrl: 'https://www.flipkart.com',
  },
  {
    id: 'toy-8',
    name: 'Meccano Junior Starter Set',
    brand: 'Meccano',
    platform: 'Amazon',
    originalPrice: '₹2,499',
    discountedPrice: '₹1,599',
    priceValue: 1599,
    rating: 4.4,
    reviews: '3,200',
    discountPercent: 36,
    category: 'Toys',
    imageUrl: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=400&h=400&fit=crop',
    description: '100+ parts, real metal pieces, builds 3 motorised models, includes tool. STEM learning through building.',
    tags: ['STEM', 'Metal Parts', 'Motorised'],
    inStock: true,
    affiliateUrl: 'https://www.amazon.in',
  },
  {
    id: 'toy-9',
    name: 'Rubik\'s Cube 3x3 Speed Cube',
    brand: 'Rubik\'s',
    platform: 'Amazon',
    originalPrice: '₹1,299',
    discountedPrice: '₹699',
    priceValue: 699,
    rating: 4.5,
    reviews: '24,100',
    discountPercent: 46,
    category: 'Toys',
    imageUrl: 'https://images.unsplash.com/photo-1611996575749-79a3a250f948?w=400&h=400&fit=crop',
    description: 'Original Rubik\'s brand, smooth rotation, vibrant stickers, ages 8+. The classic puzzle that started it all.',
    tags: ['Speed Cube', 'Ages 8+', 'Classic'],
    inStock: true,
    affiliateUrl: 'https://www.amazon.in',
  },
]

export function getProductById(id: string): Product | null {
  return PRODUCTS.find((p) => p.id === id) ?? null
}

export function getProductsByCategory(category: Category): Product[] {
  if (category === 'All') return PRODUCTS
  return PRODUCTS.filter((p) => p.category === category)
}

export function searchProducts(query: string): Product[] {
  const q = query.toLowerCase()
  return PRODUCTS.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.brand.toLowerCase().includes(q) ||
      p.category.toLowerCase().includes(q) ||
      p.tags.some((t) => t.toLowerCase().includes(q)),
  )
}
