// ── Shared product catalogue ─────────────────────────────────────────────────
// Single source of truth for ProductsClient, /products/[id], compare, search
// No external calls — all data is static

export type Platform = 'Amazon' | 'Flipkart' | 'Myntra' | 'AJIO'

export type Category =
  | 'All'
  | 'Mobiles'
  | 'Laptops'
  | 'Fashion'
  | 'Home'
  | 'Cameras'
  | 'Gaming'
  | 'Electronics'
  | 'Footwear'
  | 'Books'
  | 'Beauty'
  | 'Sports'
  | 'Toys'
  | 'Audio'
  | 'Furniture'

export interface Product {
  id: string
  name: string
  brand: string
  platform: Platform
  originalPrice: string
  discountedPrice: string
  priceValue: number          // numeric for sort/filter
  rating: number
  reviews: string
  discountPercent: number
  category: Category
  imageUrl: string
  description: string
  tags: string[]
  inStock: boolean
  affiliateUrl: string
}

export const CATEGORIES: readonly Category[] = [
  'All', 'Mobiles', 'Laptops', 'Fashion', 'Home', 'Cameras',
  'Gaming', 'Electronics', 'Footwear', 'Books', 'Beauty', 'Sports', 'Toys', 'Audio', 'Furniture',
]

function getCategoryImage(category: Category): string {
  let photoId = ''
  switch (category) {
    case 'Mobiles':     photoId = '1511707171634-5f897ff02aa9'; break
    case 'Laptops':     photoId = '1496181133206-80ce9b88a853'; break
    case 'Fashion':     photoId = '1483985988355-763728e1935b'; break
    case 'Home':        photoId = '1513519245088-0e12902e5a38'; break
    case 'Cameras':     photoId = '1516035069371-29a1b244cc32'; break
    case 'Gaming':      photoId = '1606144042614-b2417e99c4e3'; break
    case 'Electronics': photoId = '1593359677879-a4bb92f829e1'; break
    case 'Footwear':    photoId = '1542291026-7eec264c27ff'; break
    case 'Books':       photoId = '1544716278-ca5e3f4abd8c'; break
    case 'Beauty':      photoId = '1556228720-195a672e8a03'; break
    case 'Sports':      photoId = '1601925260368-ae2f83cf8b7f'; break
    case 'Toys':        photoId = '1587654780291-39c9404d746b'; break
    case 'Audio':       photoId = '1505740420928-5e560c06d30e'; break
    case 'Furniture':   photoId = '1555041469-a586c61ea9bc'; break
    default:            photoId = '1505740420928-5e560c06d30e'
  }
  return `https://images.unsplash.com/photo-${photoId}?w=400&h=400&fit=crop`
}

const RAW_PRODUCTS = [
  // ── Mobiles ────────────────────────────────────────────────────────────────
  {
    id: 'mob-1',
    name: 'Samsung Galaxy M35 5G',
    brand: 'Samsung',
    platform: 'Amazon',
    originalPrice: '₹24,999',
    discountedPrice: '₹18,999',
    priceValue: 18999,
    rating: 4.2,
    reviews: '12,450',
    discountPercent: 24,
    category: 'Mobiles',
    description: '6.6" Super AMOLED display, 50MP camera, 5000mAh battery, 6GB RAM. Best mid-range performer for 2026.',
    tags: ['5G', 'AMOLED', '50MP'],
    inStock: true,
    affiliateUrl: '/go/amazon-mob-1',
  },
  {
    id: 'mob-2',
    name: 'iPhone 15 128GB',
    brand: 'Apple',
    platform: 'Amazon',
    originalPrice: '₹89,900',
    discountedPrice: '₹79,900',
    priceValue: 79900,
    rating: 4.8,
    reviews: '34,210',
    discountPercent: 11,
    category: 'Mobiles',
    description: 'A16 Bionic chip, 48MP main camera, Dynamic Island, USB-C charging. The benchmark smartphone experience.',
    tags: ['A16 Bionic', 'USB-C', 'Dynamic Island'],
    inStock: true,
    affiliateUrl: '/go/amazon-mob-2',
  },
  {
    id: 'mob-3',
    name: 'Redmi Note 13 Pro 5G',
    brand: 'Xiaomi',
    platform: 'Amazon',
    originalPrice: '₹24,999',
    discountedPrice: '₹19,999',
    priceValue: 19999,
    rating: 4.4,
    reviews: '28,900',
    discountPercent: 20,
    category: 'Mobiles',
    description: '200MP camera, 67W turbo charging, Snapdragon 7s Gen 2. The camera king under ₹20,000.',
    tags: ['200MP', '5G', '67W Charging'],
    inStock: true,
    affiliateUrl: '/go/amazon-mob-3',
  },
  {
    id: 'mob-4',
    name: 'Realme 12 Pro+ 5G',
    brand: 'Realme',
    platform: 'Flipkart',
    originalPrice: '₹27,999',
    discountedPrice: '₹21,999',
    priceValue: 21999,
    rating: 4.3,
    reviews: '9,870',
    discountPercent: 21,
    category: 'Mobiles',
    description: 'Periscope zoom camera, 50MP Sony IMX890, 67W SUPERVOOC. Exceptional photography at mid-range price.',
    tags: ['Periscope Zoom', '5G', 'Sony Sensor'],
    inStock: true,
    affiliateUrl: '/go/flipkart-mob-4',
  },
  {
    id: 'mob-5',
    name: 'Vivo V30e 5G',
    brand: 'Vivo',
    platform: 'Amazon',
    originalPrice: '₹29,999',
    discountedPrice: '₹24,499',
    priceValue: 24499,
    rating: 4.1,
    reviews: '5,340',
    discountPercent: 18,
    category: 'Mobiles',
    description: '50MP front camera with aura light, 80W flash charge, 6.78" AMOLED. Selfie-focused flagship killer.',
    tags: ['Selfie Camera', '5G', '80W Charging'],
    inStock: true,
    affiliateUrl: '/go/amazon-mob-5',
  },

  // ── Laptops ────────────────────────────────────────────────────────────────
  {
    id: 'lap-1',
    name: 'HP Pavilion Laptop 15',
    brand: 'HP',
    platform: 'Flipkart',
    originalPrice: '₹62,000',
    discountedPrice: '₹45,990',
    priceValue: 45990,
    rating: 4.4,
    reviews: '7,120',
    discountPercent: 26,
    category: 'Laptops',
    description: 'Intel Core i5-1335U, 16GB RAM, 512GB SSD, Full HD display. Best-in-class productivity laptop.',
    tags: ['Intel i5', '16GB RAM', 'SSD'],
    inStock: true,
    affiliateUrl: '/go/flipkart-lap-1',
  },
  {
    id: 'lap-2',
    name: 'MacBook Air M3 13"',
    brand: 'Apple',
    platform: 'Amazon',
    originalPrice: '₹1,29,900',
    discountedPrice: '₹1,14,900',
    priceValue: 114900,
    rating: 4.9,
    reviews: '15,670',
    discountPercent: 12,
    category: 'Laptops',
    description: 'M3 chip, 18-hour battery, 13.6" Liquid Retina display, 8GB Unified Memory. Fanless, silent performance.',
    tags: ['M3 Chip', '18hr Battery', 'Retina'],
    inStock: true,
    affiliateUrl: '/go/amazon-lap-2',
  },
  {
    id: 'lap-3',
    name: 'Dell Inspiron 15 3520',
    brand: 'Dell',
    platform: 'Flipkart',
    originalPrice: '₹55,990',
    discountedPrice: '₹44,999',
    priceValue: 44999,
    rating: 4.2,
    reviews: '11,300',
    discountPercent: 20,
    category: 'Laptops',
    description: 'Intel Core i5-1235U, 8GB RAM, 512GB SSD, 15.6" FHD. Reliable workhorse with excellent build quality.',
    tags: ['Intel i5', 'Dell', 'FHD'],
    inStock: true,
    affiliateUrl: '/go/flipkart-lap-3',
  },
  {
    id: 'lap-4',
    name: 'ASUS VivoBook 15 OLED',
    brand: 'ASUS',
    platform: 'Amazon',
    originalPrice: '₹49,990',
    discountedPrice: '₹39,990',
    priceValue: 39990,
    rating: 4.5,
    reviews: '8,450',
    discountPercent: 20,
    category: 'Laptops',
    description: 'Ryzen 5 7530U, 15.6" OLED 2.8K display, 16GB RAM, 512GB SSD. Stunning visuals for creators.',
    tags: ['OLED', 'Ryzen 5', '2.8K Display'],
    inStock: true,
    affiliateUrl: '/go/amazon-lap-4',
  },
  {
    id: 'lap-5',
    name: 'Lenovo IdeaPad Slim 3',
    brand: 'Lenovo',
    platform: 'Flipkart',
    originalPrice: '₹42,990',
    discountedPrice: '₹35,990',
    priceValue: 35990,
    rating: 4.1,
    reviews: '19,800',
    discountPercent: 16,
    category: 'Laptops',
    description: 'Intel Core i3-1215U, 8GB RAM, 256GB SSD, 15.6" FHD. Budget-friendly for students and beginners.',
    tags: ['Budget', 'Student', 'Lenovo'],
    inStock: true,
    affiliateUrl: '/go/flipkart-lap-5',
  },

  // ── Fashion ────────────────────────────────────────────────────────────────
  {
    id: 'fas-1',
    name: 'Titan Analog Watch',
    brand: 'Titan',
    platform: 'Flipkart',
    originalPrice: '₹3,500',
    discountedPrice: '₹2,495',
    priceValue: 2495,
    rating: 4.3,
    reviews: '6,780',
    discountPercent: 29,
    category: 'Fashion',
    description: 'Slim metal case, mineral crystal glass, water resistant to 30m. Classic Indian watchmaking at its finest.',
    tags: ['Analog', 'Water Resistant', 'Titan'],
    inStock: true,
    affiliateUrl: '/go/flipkart-fas-1',
  },
  {
    id: 'fas-2',
    name: 'Peter England Polo T-Shirt',
    brand: 'Peter England',
    platform: 'Amazon',
    originalPrice: '₹1,299',
    discountedPrice: '₹649',
    priceValue: 649,
    rating: 4.0,
    reviews: '3,240',
    discountPercent: 50,
    category: 'Fashion',
    description: '100% cotton pique fabric, ribbed collar, regular fit. Versatile wardrobe essential for office and casual.',
    tags: ['Cotton', 'Regular Fit', 'Polo'],
    inStock: true,
    affiliateUrl: '/go/amazon-fas-2',
  },
  {
    id: 'fas-3',
    name: 'BIBA Women\'s Kurta Set',
    brand: 'BIBA',
    platform: 'Flipkart',
    originalPrice: '₹2,499',
    discountedPrice: '₹1,299',
    priceValue: 1299,
    rating: 4.2,
    reviews: '2,190',
    discountPercent: 48,
    category: 'Fashion',
    description: 'Printed cotton kurta with palazzo pants, ethnic embroidery work. Festival-ready ethnic fashion.',
    tags: ['Ethnic', 'Cotton', 'Festival Wear'],
    inStock: true,
    affiliateUrl: '/go/flipkart-fas-3',
  },
  {
    id: 'fas-4',
    name: 'Levi\'s 511 Slim Fit Jeans',
    brand: 'Levi\'s',
    platform: 'Amazon',
    originalPrice: '₹3,999',
    discountedPrice: '₹2,199',
    priceValue: 2199,
    rating: 4.4,
    reviews: '14,560',
    discountPercent: 45,
    category: 'Fashion',
    description: 'Stretch denim, slim fit through thigh and leg opening. The gold-standard everyday jean for men.',
    tags: ['Slim Fit', 'Stretch Denim', 'Levi\'s'],
    inStock: true,
    affiliateUrl: '/go/amazon-fas-4',
  },
  {
    id: 'fas-5',
    name: 'Fastrack Oval Sunglasses',
    brand: 'Fastrack',
    platform: 'Flipkart',
    originalPrice: '₹1,495',
    discountedPrice: '₹895',
    priceValue: 895,
    rating: 4.1,
    reviews: '4,320',
    discountPercent: 40,
    category: 'Fashion',
    description: 'UV400 protection, polycarbonate lens, lightweight frame. Premium look at an accessible price.',
    tags: ['UV400', 'Lightweight', 'Oval Frame'],
    inStock: true,
    affiliateUrl: '/go/flipkart-fas-5',
  },

  // ── Home ───────────────────────────────────────────────────────────────────
  {
    id: 'hom-1',
    name: 'Philips HD9270 Air Fryer',
    brand: 'Philips',
    platform: 'Amazon',
    originalPrice: '₹9,995',
    discountedPrice: '₹6,499',
    priceValue: 6499,
    rating: 4.5,
    reviews: '22,100',
    discountPercent: 35,
    category: 'Home',
    description: '6.2L capacity, Rapid Air Technology, 13 cooking presets. Fry, bake, grill and roast with 90% less fat.',
    tags: ['Air Fryer', '6.2L', 'Philips'],
    inStock: true,
    affiliateUrl: '/go/amazon-hom-1',
  },
  {
    id: 'hom-2',
    name: 'Prestige PIC 20 Induction',
    brand: 'Prestige',
    platform: 'Flipkart',
    originalPrice: '₹2,800',
    discountedPrice: '₹1,799',
    priceValue: 1799,
    rating: 4.0,
    reviews: '31,450',
    discountPercent: 36,
    category: 'Home',
    description: '2000W power, feather touch controls, auto-off safety, 7 preset cooking menus. Smart cooking simplified.',
    tags: ['2000W', 'Auto-off', 'Induction'],
    inStock: true,
    affiliateUrl: '/go/flipkart-hom-2',
  },
  {
    id: 'hom-3',
    name: 'Kent Grand Star RO Purifier',
    brand: 'Kent',
    platform: 'Amazon',
    originalPrice: '₹18,500',
    discountedPrice: '₹12,999',
    priceValue: 12999,
    rating: 4.3,
    reviews: '9,870',
    discountPercent: 30,
    category: 'Home',
    description: '8L storage, RO+UV+UF purification, TDS controller, 20L/hr flow. Hospital-grade purified water at home.',
    tags: ['RO+UV', '8L Tank', 'Kent'],
    inStock: true,
    affiliateUrl: '/go/amazon-hom-3',
  },
  {
    id: 'hom-4',
    name: 'Orient Tornado Pedestal Fan',
    brand: 'Orient',
    platform: 'Flipkart',
    originalPrice: '₹4,299',
    discountedPrice: '₹2,999',
    priceValue: 2999,
    rating: 4.1,
    reviews: '5,600',
    discountPercent: 30,
    category: 'Home',
    description: '1200mm blade sweep, remote control, 100% copper motor, 5-speed settings. Powerful and whisper-quiet.',
    tags: ['Remote Control', 'Copper Motor', '5-Speed'],
    inStock: true,
    affiliateUrl: '/go/flipkart-hom-4',
  },
  {
    id: 'hom-5',
    name: 'Story@Home 144TC Bedsheet Set',
    brand: 'Story@Home',
    platform: 'Amazon',
    originalPrice: '₹1,499',
    discountedPrice: '₹699',
    priceValue: 699,
    rating: 4.2,
    reviews: '18,900',
    discountPercent: 53,
    category: 'Home',
    description: '100% microfibre double bedsheet with 2 pillow covers, 144 thread count. Soft, fade-resistant comfort.',
    tags: ['Microfibre', 'Double Bed', '144TC'],
    inStock: true,
    affiliateUrl: '/go/amazon-hom-5',
  },

  // ── Cameras ────────────────────────────────────────────────────────────────
  {
    id: 'cam-1',
    name: 'Canon EOS M200',
    brand: 'Canon',
    platform: 'Amazon',
    originalPrice: '₹44,995',
    discountedPrice: '₹32,999',
    priceValue: 32999,
    rating: 4.6,
    reviews: '3,450',
    discountPercent: 27,
    category: 'Cameras',
    description: '24.1MP APS-C sensor, 4K video, Dual Pixel autofocus, touchscreen. Perfect first mirrorless camera.',
    tags: ['24MP', '4K Video', 'Mirrorless'],
    inStock: true,
    affiliateUrl: '/go/amazon-cam-1',
  },
  {
    id: 'cam-2',
    name: 'Sony ZV-E10 Mirrorless',
    brand: 'Sony',
    platform: 'Amazon',
    originalPrice: '₹59,990',
    discountedPrice: '₹49,990',
    priceValue: 49990,
    rating: 4.7,
    reviews: '2,180',
    discountPercent: 17,
    category: 'Cameras',
    description: '24.2MP APS-C, 4K 30fps, directional 3-capsule mic, fast hybrid AF. The vlogger\'s best friend.',
    tags: ['Vlogging', '4K', 'Sony'],
    inStock: true,
    affiliateUrl: '/go/amazon-cam-2',
  },
  {
    id: 'cam-3',
    name: 'GoPro Hero 12 Black',
    brand: 'GoPro',
    platform: 'Amazon',
    originalPrice: '₹39,500',
    discountedPrice: '₹34,990',
    priceValue: 34990,
    rating: 4.5,
    reviews: '4,320',
    discountPercent: 11,
    category: 'Cameras',
    description: '5.3K60 video, HyperSmooth 6.0 stabilisation, 27MP photos, waterproof to 10m. Adventure-ready.',
    tags: ['5.3K', 'Waterproof', 'Action Cam'],
    inStock: true,
    affiliateUrl: '/go/amazon-cam-3',
  },
  {
    id: 'cam-4',
    name: 'Digitek Portable Tripod 7ft',
    brand: 'Digitek',
    platform: 'Flipkart',
    originalPrice: '₹2,499',
    discountedPrice: '₹1,299',
    priceValue: 1299,
    rating: 4.0,
    reviews: '8,760',
    discountPercent: 48,
    category: 'Cameras',
    description: '7ft max height, 4kg load capacity, universal mount, carry bag included. Studio quality at home.',
    tags: ['7ft', 'Portable', 'Universal Mount'],
    inStock: true,
    affiliateUrl: '/go/flipkart-cam-4',
  },

  // ── Gaming ─────────────────────────────────────────────────────────────────
  {
    id: 'gam-1',
    name: 'Sony DualSense Controller',
    brand: 'Sony',
    platform: 'Amazon',
    originalPrice: '₹7,290',
    discountedPrice: '₹5,999',
    priceValue: 5999,
    rating: 4.7,
    reviews: '21,300',
    discountPercent: 18,
    category: 'Gaming',
    description: 'Adaptive triggers, haptic feedback, built-in mic, USB-C charging. Next-gen feel for PS5 and PC.',
    tags: ['PS5', 'Haptic', 'Adaptive Triggers'],
    inStock: true,
    affiliateUrl: '/go/amazon-gam-1',
  },
  {
    id: 'gam-2',
    name: 'Redgear MK851 Mech Keyboard',
    brand: 'Redgear',
    platform: 'Flipkart',
    originalPrice: '₹3,999',
    discountedPrice: '₹2,499',
    priceValue: 2499,
    rating: 4.2,
    reviews: '9,870',
    discountPercent: 38,
    category: 'Gaming',
    description: 'Outemu Blue switches, full RGB backlighting, N-key rollover, metal plate. Best budget mech keyboard.',
    tags: ['Mechanical', 'RGB', 'N-Key Rollover'],
    inStock: true,
    affiliateUrl: '/go/flipkart-gam-2',
  },
  {
    id: 'gam-3',
    name: 'Logitech G502 X Gaming Mouse',
    brand: 'Logitech',
    platform: 'Amazon',
    originalPrice: '₹5,995',
    discountedPrice: '₹4,495',
    priceValue: 4495,
    rating: 4.6,
    reviews: '6,540',
    discountPercent: 25,
    category: 'Gaming',
    description: 'HERO 25K sensor, 13 programmable buttons, LIGHTFORCE switches, 89g. Precision for competitive gaming.',
    tags: ['25K DPI', '89g', 'HERO Sensor'],
    inStock: true,
    affiliateUrl: '/go/amazon-gam-3',
  },
  {
    id: 'gam-4',
    name: 'HyperX Cloud II Gaming Headset',
    brand: 'HyperX',
    platform: 'Amazon',
    originalPrice: '₹7,999',
    discountedPrice: '₹5,499',
    priceValue: 5499,
    rating: 4.5,
    reviews: '14,230',
    discountPercent: 31,
    category: 'Gaming',
    description: '53mm drivers, virtual 7.1 surround, memory foam ear cups, detachable mic. Award-winning audio.',
    tags: ['7.1 Surround', '53mm Drivers', 'Memory Foam'],
    inStock: true,
    affiliateUrl: '/go/amazon-gam-4',
  },
  {
    id: 'gam-5',
    name: 'Nintendo Switch OLED',
    brand: 'Nintendo',
    platform: 'Amazon',
    originalPrice: '₹35,999',
    discountedPrice: '₹33,999',
    priceValue: 33999,
    rating: 4.8,
    reviews: '8,900',
    discountPercent: 6,
    category: 'Gaming',
    description: '7" OLED screen, enhanced audio, 64GB storage, wide adjustable stand. Play anywhere, anytime.',
    tags: ['OLED', 'Portable', 'Nintendo'],
    inStock: true,
    affiliateUrl: '/go/amazon-gam-5',
  },

  // ── Electronics ────────────────────────────────────────────────────────────
  {
    id: 'ele-1',
    name: 'boAt Airdopes 141 TWS',
    brand: 'boAt',
    platform: 'Amazon',
    originalPrice: '₹2,990',
    discountedPrice: '₹999',
    priceValue: 999,
    rating: 4.1,
    reviews: '89,300',
    discountPercent: 67,
    category: 'Electronics',
    description: '42H total playback, BEAST Mode low latency, ENx mic, IPX4 rated. India\'s most popular TWS earbuds.',
    tags: ['42H Battery', 'BEAST Mode', 'IPX4'],
    inStock: true,
    affiliateUrl: '/go/amazon-ele-1',
  },
  {
    id: 'ele-2',
    name: 'Samsung 43" 4K Crystal UHD TV',
    brand: 'Samsung',
    platform: 'Amazon',
    originalPrice: '₹42,990',
    discountedPrice: '₹28,999',
    priceValue: 28999,
    rating: 4.3,
    reviews: '8,421',
    discountPercent: 33,
    category: 'Electronics',
    description: 'Crystal Processor 4K, PurColor, HDR, Tizen OS, 3 HDMI ports. Vivid viewing on a budget.',
    tags: ['4K UHD', 'HDR', 'Smart TV'],
    inStock: true,
    affiliateUrl: '/go/amazon-ele-2',
  },
  {
    id: 'ele-3',
    name: 'JBL Charge 5 Bluetooth Speaker',
    brand: 'JBL',
    platform: 'Amazon',
    originalPrice: '₹16,999',
    discountedPrice: '₹12,999',
    priceValue: 12999,
    rating: 4.6,
    reviews: '11,450',
    discountPercent: 24,
    category: 'Electronics',
    description: '20H playtime, IP67 waterproof, built-in power bank, PartyBoost. The party speaker built to last.',
    tags: ['20H Battery', 'IP67', 'Power Bank'],
    inStock: true,
    affiliateUrl: '/go/amazon-ele-3',
  },
  {
    id: 'ele-4',
    name: 'Apple Watch SE (2nd Gen)',
    brand: 'Apple',
    platform: 'Flipkart',
    originalPrice: '₹32,900',
    discountedPrice: '₹26,900',
    priceValue: 26900,
    rating: 4.7,
    reviews: '19,870',
    discountPercent: 18,
    category: 'Electronics',
    description: 'S8 chip, crash detection, heart rate & SpO2 monitoring, swimproof. The essential Apple Watch.',
    tags: ['Health Tracking', 'Crash Detection', 'Swimproof'],
    inStock: true,
    affiliateUrl: '/go/flipkart-ele-4',
  },
  {
    id: 'ele-5',
    name: 'Anker 523 PowerCore 20000',
    brand: 'Anker',
    platform: 'Amazon',
    originalPrice: '₹2,999',
    discountedPrice: '₹1,999',
    priceValue: 1999,
    rating: 4.4,
    reviews: '44,200',
    discountPercent: 33,
    category: 'Electronics',
    description: '20000mAh, dual USB-A + USB-C, 22.5W fast charge, PowerIQ 3.0. Charge 3 devices simultaneously.',
    tags: ['20000mAh', '22.5W Fast Charge', 'Anker'],
    inStock: true,
    affiliateUrl: '/go/amazon-ele-5',
  },

  // ── Footwear ───────────────────────────────────────────────────────────────
  {
    id: 'foo-1',
    name: 'Nike Revolution 7 Running',
    brand: 'Nike',
    platform: 'Flipkart',
    originalPrice: '₹5,999',
    discountedPrice: '₹3,995',
    priceValue: 3995,
    rating: 4.2,
    reviews: '7,890',
    discountPercent: 33,
    category: 'Footwear',
    description: 'Foam midsole, rubber outsole for grip, breathable mesh upper. Everyday running made comfortable.',
    tags: ['Running', 'Foam Midsole', 'Breathable'],
    inStock: true,
    affiliateUrl: '/go/flipkart-foo-1',
  },
  {
    id: 'foo-2',
    name: 'Bata Men\'s Formal Derby',
    brand: 'Bata',
    platform: 'Flipkart',
    originalPrice: '₹2,499',
    discountedPrice: '₹1,299',
    priceValue: 1299,
    rating: 4.0,
    reviews: '12,400',
    discountPercent: 48,
    category: 'Footwear',
    description: 'Genuine leather upper, cushioned insole, non-slip sole. Office-ready formal shoes at an unbeatable price.',
    tags: ['Formal', 'Leather', 'Office Wear'],
    inStock: true,
    affiliateUrl: '/go/flipkart-foo-2',
  },
  {
    id: 'foo-3',
    name: 'Puma Cell Vive Sneakers',
    brand: 'Puma',
    platform: 'Amazon',
    originalPrice: '₹4,999',
    discountedPrice: '₹2,999',
    priceValue: 2999,
    rating: 4.3,
    reviews: '5,670',
    discountPercent: 40,
    category: 'Footwear',
    description: 'CELL technology cushioning, breathable mesh upper, flexible outsole. Sport-casual hybrid for all day.',
    tags: ['CELL Cushioning', 'Casual', 'Puma'],
    inStock: true,
    affiliateUrl: '/go/amazon-foo-3',
  },
  {
    id: 'foo-4',
    name: 'Crocs Classic Clog',
    brand: 'Crocs',
    platform: 'Amazon',
    originalPrice: '₹4,295',
    discountedPrice: '₹2,995',
    priceValue: 2995,
    rating: 4.5,
    reviews: '23,100',
    discountPercent: 30,
    category: 'Footwear',
    description: 'Croslite foam construction, 13 ventilation ports, pivoting heel straps. Iconic comfort all day long.',
    tags: ['Croslite Foam', 'Ventilated', 'Iconic'],
    inStock: true,
    affiliateUrl: '/go/amazon-foo-4',
  },

  // ── Books ──────────────────────────────────────────────────────────────────
  {
    id: 'boo-1',
    name: 'Atomic Habits — James Clear',
    brand: 'Penguin',
    platform: 'Amazon',
    originalPrice: '₹799',
    discountedPrice: '₹389',
    priceValue: 389,
    rating: 4.8,
    reviews: '1,23,400',
    discountPercent: 51,
    category: 'Books',
    description: 'The #1 bestselling guide to building good habits and breaking bad ones. Over 10 million copies sold worldwide.',
    tags: ['Self-Help', 'Bestseller', 'Habits'],
    inStock: true,
    affiliateUrl: '/go/amazon-boo-1',
  },
  {
    id: 'boo-2',
    name: 'The Alchemist — Paulo Coelho',
    brand: 'HarperCollins',
    platform: 'Amazon',
    originalPrice: '₹399',
    discountedPrice: '₹199',
    priceValue: 199,
    rating: 4.7,
    reviews: '89,700',
    discountPercent: 50,
    category: 'Books',
    description: 'A magical story about following your dreams. Translated into 80 languages, 65 million copies sold.',
    tags: ['Fiction', 'Inspirational', 'Classic'],
    inStock: true,
    affiliateUrl: '/go/amazon-boo-2',
  },
  {
    id: 'boo-3',
    name: 'Rich Dad Poor Dad — Robert Kiyosaki',
    brand: 'Plata Publishing',
    platform: 'Flipkart',
    originalPrice: '₹499',
    discountedPrice: '₹259',
    priceValue: 259,
    rating: 4.6,
    reviews: '67,200',
    discountPercent: 48,
    category: 'Books',
    description: 'The global bestseller on financial literacy, investing, and building wealth. A life-changing read.',
    tags: ['Finance', 'Investing', 'Bestseller'],
    inStock: true,
    affiliateUrl: '/go/flipkart-boo-3',
  },
  {
    id: 'boo-4',
    name: 'Psychology of Money — Morgan Housel',
    brand: 'Harriman House',
    platform: 'Amazon',
    originalPrice: '₹699',
    discountedPrice: '₹349',
    priceValue: 349,
    rating: 4.7,
    reviews: '54,300',
    discountPercent: 50,
    category: 'Books',
    description: '19 short stories exploring the strange ways people think about money. Essential personal finance reading.',
    tags: ['Finance', 'Psychology', 'Personal Finance'],
    inStock: true,
    affiliateUrl: '/go/amazon-boo-4',
  },

  // ── Beauty ─────────────────────────────────────────────────────────────────
  {
    id: 'bea-1',
    name: 'Lakme CC Cream SPF 30',
    brand: 'Lakme',
    platform: 'Amazon',
    originalPrice: '₹599',
    discountedPrice: '₹299',
    priceValue: 299,
    rating: 4.1,
    reviews: '18,700',
    discountPercent: 50,
    category: 'Beauty',
    description: 'SPF 30, 9-in-1 benefits, light-medium coverage, dermatologist tested. The everyday complexion corrector.',
    tags: ['SPF 30', 'CC Cream', 'Dermatologist Tested'],
    inStock: true,
    affiliateUrl: '/go/amazon-bea-1',
  },
  {
    id: 'bea-2',
    name: 'Mamaearth Vitamin C Moisturiser',
    brand: 'Mamaearth',
    platform: 'Flipkart',
    originalPrice: '₹699',
    discountedPrice: '₹449',
    priceValue: 449,
    rating: 4.3,
    reviews: '32,400',
    discountPercent: 36,
    category: 'Beauty',
    description: 'Vitamin C & Turmeric, SPF 20, non-greasy formula, MadeSafe certified. Glowing skin all day.',
    tags: ['Vitamin C', 'SPF 20', 'Non-Greasy'],
    inStock: true,
    affiliateUrl: '/go/flipkart-bea-2',
  },
  {
    id: 'bea-3',
    name: 'Vega Style Ion Hair Dryer',
    brand: 'Vega',
    platform: 'Amazon',
    originalPrice: '₹1,595',
    discountedPrice: '₹799',
    priceValue: 799,
    rating: 4.0,
    reviews: '24,900',
    discountPercent: 50,
    category: 'Beauty',
    description: '1800W motor, 2 heat settings, cool shot button, ionic technology. Frizz-free blowout at home.',
    tags: ['1800W', 'Ionic', 'Cool Shot'],
    inStock: true,
    affiliateUrl: '/go/amazon-bea-3',
  },
  {
    id: 'bea-4',
    name: 'Engage W1 Perfume Spray',
    brand: 'Engage',
    platform: 'Amazon',
    originalPrice: '₹799',
    discountedPrice: '₹399',
    priceValue: 399,
    rating: 4.2,
    reviews: '11,200',
    discountPercent: 50,
    category: 'Beauty',
    description: '150ml, long-lasting floral-woody fragrance, skin-friendly formula. All-day freshness for women.',
    tags: ['Floral', 'Long-Lasting', '150ml'],
    inStock: true,
    affiliateUrl: '/go/amazon-bea-4',
  },

  // ── Sports ─────────────────────────────────────────────────────────────────
  {
    id: 'spo-1',
    name: 'Boldfit Premium Yoga Mat 6mm',
    brand: 'Boldfit',
    platform: 'Amazon',
    originalPrice: '₹1,299',
    discountedPrice: '₹699',
    priceValue: 699,
    rating: 4.3,
    reviews: '28,900',
    discountPercent: 46,
    category: 'Sports',
    description: '6mm thick TPE foam, anti-slip texture, carry strap, sweat-resistant. Perfect for yoga and home workouts.',
    tags: ['6mm', 'Anti-Slip', 'TPE Foam'],
    inStock: true,
    affiliateUrl: '/go/amazon-spo-1',
  },
  {
    id: 'spo-2',
    name: 'PowerMax Hex Dumbbell Set 10kg',
    brand: 'PowerMax',
    platform: 'Flipkart',
    originalPrice: '₹2,499',
    discountedPrice: '₹1,499',
    priceValue: 1499,
    rating: 4.4,
    reviews: '9,340',
    discountPercent: 40,
    category: 'Sports',
    description: 'Rubber-coated hex design, anti-roll, chrome handle, pair of 5kg. Home gym essentials for beginners.',
    tags: ['Rubber Coated', 'Hex Design', 'Pair'],
    inStock: true,
    affiliateUrl: '/go/flipkart-spo-2',
  },
  {
    id: 'spo-3',
    name: 'SG English Willow Cricket Bat',
    brand: 'SG',
    platform: 'Amazon',
    originalPrice: '₹2,999',
    discountedPrice: '₹1,899',
    priceValue: 1899,
    rating: 4.2,
    reviews: '6,780',
    discountPercent: 37,
    category: 'Sports',
    description: 'Grade 3 English Willow, full cane handle, 2.7 lbs, short handle. Trusted by club cricketers.',
    tags: ['English Willow', 'Grade 3', 'SG'],
    inStock: true,
    affiliateUrl: '/go/amazon-spo-3',
  },
  {
    id: 'spo-4',
    name: 'Yonex Muscle Power Badminton Racket',
    brand: 'Yonex',
    platform: 'Flipkart',
    originalPrice: '₹2,299',
    discountedPrice: '₹1,299',
    priceValue: 1299,
    rating: 4.3,
    reviews: '14,500',
    discountPercent: 43,
    category: 'Sports',
    description: 'Graphite shaft, T-joint reinforcement, pre-strung, includes full cover. Ideal for recreational play.',
    tags: ['Graphite', 'Pre-strung', 'Yonex'],
    inStock: true,
    affiliateUrl: '/go/flipkart-spo-4',
  },

  // ── Toys ───────────────────────────────────────────────────────────────────
  {
    id: 'toy-1',
    name: 'LEGO Classic Creative Bricks',
    brand: 'LEGO',
    platform: 'Amazon',
    originalPrice: '₹3,999',
    discountedPrice: '₹2,499',
    priceValue: 2499,
    rating: 4.8,
    reviews: '4,560',
    discountPercent: 38,
    category: 'Toys',
    description: '484 pieces, 33 LEGO colours, 9 base plates. Endless creative building for ages 4+.',
    tags: ['Ages 4+', '484 Pieces', 'Creative'],
    inStock: true,
    affiliateUrl: '/go/amazon-toy-1',
  },
  {
    id: 'toy-2',
    name: 'Hot Wheels 20-Car Gift Pack',
    brand: 'Hot Wheels',
    platform: 'Flipkart',
    originalPrice: '₹1,999',
    discountedPrice: '₹1,299',
    priceValue: 1299,
    rating: 4.6,
    reviews: '11,200',
    discountPercent: 35,
    category: 'Toys',
    description: '20 die-cast vehicles, 1:64 scale, assorted designs. The perfect gift for little car enthusiasts.',
    tags: ['Die-Cast', '20 Cars', 'Ages 3+'],
    inStock: true,
    affiliateUrl: '/go/flipkart-toy-2',
  },
  {
    id: 'toy-3',
    name: 'Barbie Dreamhouse Adventures',
    brand: 'Barbie',
    platform: 'Amazon',
    originalPrice: '₹7,999',
    discountedPrice: '₹4,999',
    priceValue: 4999,
    rating: 4.4,
    reviews: '3,890',
    discountPercent: 38,
    category: 'Toys',
    description: '3-storey, 7 play areas, 70+ accessories, colour-change features. Imagination-packed playset for ages 3+.',
    tags: ['Ages 3+', '70+ Accessories', 'Playset'],
    inStock: true,
    affiliateUrl: '/go/amazon-toy-3',
  },
  {
    id: 'toy-4',
    name: 'Funskool Snakes & Ladders + Ludo',
    brand: 'Funskool',
    platform: 'Amazon',
    originalPrice: '₹999',
    discountedPrice: '₹599',
    priceValue: 599,
    rating: 4.5,
    reviews: '8,760',
    discountPercent: 40,
    category: 'Toys',
    description: '2-in-1 classic board game, vibrant printed board, 4 player tokens, dice. Family game night favourite.',
    tags: ['Board Game', '2-in-1', 'Family'],
    inStock: true,
    affiliateUrl: '/go/amazon-toy-4',
  },
]

export const PRODUCTS: Product[] = RAW_PRODUCTS.map(p => ({
  ...p,
  platform: p.platform as Platform,
  category: p.category as Category,
  imageUrl: getCategoryImage(p.category as Category)
}))

export function getProductById(id: string): Product | null {
  return PRODUCTS.find((p) => p.id === id) ?? null
}

export function getProductsByCategory(category: Category): Product[] {
  if (category === 'All') return PRODUCTS
  return PRODUCTS.filter((p) => p.category === category)
}

export function searchProducts(query: string): Product[] {
  const q = query.toLowerCase()
  return PRODUCTS.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.brand.toLowerCase().includes(q) ||
      p.category.toLowerCase().includes(q) ||
      p.tags.some((t) => t.toLowerCase().includes(q)),
  )
}
