// lib/india-catalog-2/fashion-personal.ts
// 70 products: Fashion (Levi's, Peter England, Van Heusen, Fabindia, H&M, Manyavar, Bata, Puma, Adidas, Woodland) + Beauty/Personal Care (Lakme, Mamaearth, WOW, Plum)
import type { IndiaProduct } from '@/lib/india-catalog/types'

// ─── LEVI'S (8) ──────────────────────────────────────────────────────────────

export const LEVIS: IndiaProduct[] = [
  { id: 'IN2-FA-LEV-001', name: "Levi's 511 Slim Fit Jeans — Blue 32W/32L", brand: "Levi's", subBrand: '511', category: 'fashion', subCategory: 'jeans', variant: 'Blue 32W/32L', description: "Levi's iconic 511 slim fit jeans in mid-blue wash. Made from stretch denim for all-day comfort. Machine washable.", price: 2799, originalPrice: 4999, discount: 44, image: '/assets/products/levis/511-slim-blue-32.jpg', affiliateUrl: '/go/IN2-FA-LEV-001', affiliatePlatform: 'myntra', affiliateSource: 'flipkart-affiliate-free', inStock: true, isFeatured: true, isTrending: true, rating: 4.4, reviewCount: 23400, tags: ['Slim Fit', 'Jeans', "Levi's", 'Denim', 'Men'], apiSource: 'static' },
  { id: 'IN2-FA-LEV-002', name: "Levi's 511 Slim Fit Jeans — Black 32W/32L", brand: "Levi's", subBrand: '511', category: 'fashion', subCategory: 'jeans', variant: 'Black 32W/32L', description: "Levi's 511 slim fit in jet black. Versatile stretch denim that takes you from office to evening.", price: 2799, originalPrice: 4999, discount: 44, image: '/assets/products/levis/511-slim-black-32.jpg', affiliateUrl: '/go/IN2-FA-LEV-002', affiliatePlatform: 'myntra', affiliateSource: 'flipkart-affiliate-free', inStock: true, isFeatured: false, isTrending: true, rating: 4.4, reviewCount: 18900, tags: ['Slim Fit', 'Black Jeans', "Levi's", 'Denim', 'Men'], apiSource: 'static' },
  { id: 'IN2-FA-LEV-003', name: "Levi's 501 Original Fit Jeans — Dark Blue 34W/32L", brand: "Levi's", subBrand: '501', category: 'fashion', subCategory: 'jeans', variant: 'Dark Blue 34W/32L', description: "The original Levi's 501. Straight leg, button fly, 100% cotton. A timeless wardrobe essential since 1873.", price: 3499, originalPrice: 5999, discount: 42, image: '/assets/products/levis/501-original-darkblue-34.jpg', affiliateUrl: '/go/IN2-FA-LEV-003', affiliatePlatform: 'myntra', affiliateSource: 'flipkart-affiliate-free', inStock: true, isFeatured: true, isTrending: false, rating: 4.5, reviewCount: 31200, tags: ['Straight Fit', '501', "Levi's", 'Original', 'Men'], apiSource: 'static' },
  { id: 'IN2-FA-LEV-004', name: "Levi's Original Logo T-Shirt — White M", brand: "Levi's", subBrand: 'Levi\'s Tees', category: 'fashion', subCategory: 't-shirts', variant: 'White M', description: 'Classic Levi\'s logo tee in 100% cotton jersey. Ribbed crew neck and relaxed fit. Essential casual wear.', price: 799, originalPrice: 1399, discount: 43, image: '/assets/products/levis/logo-tee-white-m.jpg', affiliateUrl: '/go/IN2-FA-LEV-004', affiliatePlatform: 'myntra', affiliateSource: 'flipkart-affiliate-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.2, reviewCount: 8760, tags: ['T-Shirt', 'Cotton', "Levi's", 'Casual', 'Men'], apiSource: 'static' },
  { id: 'IN2-FA-LEV-005', name: "Levi's Original Logo T-Shirt — Navy Blue M", brand: "Levi's", subBrand: "Levi's Tees", category: 'fashion', subCategory: 't-shirts', variant: 'Navy Blue M', description: "Levi's logo tee in navy. 100% cotton jersey with printed Levi's batwing logo on the chest.", price: 799, originalPrice: 1399, discount: 43, image: '/assets/products/levis/logo-tee-navy-m.jpg', affiliateUrl: '/go/IN2-FA-LEV-005', affiliatePlatform: 'myntra', affiliateSource: 'flipkart-affiliate-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.2, reviewCount: 7340, tags: ['T-Shirt', 'Cotton', "Levi's", 'Navy', 'Men'], apiSource: 'static' },
  { id: 'IN2-FA-LEV-006', name: "Levi's Men's Cotton Casual Shirt — Sky Blue L", brand: "Levi's", subBrand: "Levi's Shirts", category: 'fashion', subCategory: 'casual-shirts', variant: 'Sky Blue L', description: "Levi's casual shirt in breathable cotton. Classic collar, chest pocket and relaxed fit perfect for weekends.", price: 1499, originalPrice: 2799, discount: 46, image: '/assets/products/levis/casual-shirt-skyblue-l.jpg', affiliateUrl: '/go/IN2-FA-LEV-006', affiliatePlatform: 'myntra', affiliateSource: 'flipkart-affiliate-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.3, reviewCount: 5620, tags: ['Casual Shirt', 'Cotton', "Levi's", 'Men', 'Sky Blue'], apiSource: 'static' },
  { id: 'IN2-FA-LEV-007', name: "Levi's Women's 710 Super Skinny Jeans — Blue 28W", brand: "Levi's", subBrand: '710', category: 'fashion', subCategory: 'jeans', variant: 'Blue 28W', description: "Levi's 710 super skinny jeans for women. Slim through hip and thigh with a super skinny leg. Stretch denim.", price: 2999, originalPrice: 5499, discount: 45, image: '/assets/products/levis/710-super-skinny-blue-28.jpg', affiliateUrl: '/go/IN2-FA-LEV-007', affiliatePlatform: 'myntra', affiliateSource: 'flipkart-affiliate-free', inStock: true, isFeatured: true, isTrending: true, rating: 4.3, reviewCount: 12300, tags: ['Skinny Jeans', "Levi's", 'Women', 'Denim', '710'], apiSource: 'static' },
  { id: 'IN2-FA-LEV-008', name: "Levi's Ribcage Straight Jeans — Women White 27W", brand: "Levi's", subBrand: 'Ribcage', category: 'fashion', subCategory: 'jeans', variant: 'White 27W', description: "Levi's Ribcage high-rise straight fit jeans for women in white. Sits at the natural waist for a vintage silhouette.", price: 3499, originalPrice: 5999, discount: 42, image: '/assets/products/levis/ribcage-straight-white-27.jpg', affiliateUrl: '/go/IN2-FA-LEV-008', affiliatePlatform: 'myntra', affiliateSource: 'flipkart-affiliate-free', inStock: true, isFeatured: false, isTrending: true, rating: 4.4, reviewCount: 9870, tags: ['High Rise', 'Straight Jeans', "Levi's", 'Women', 'White'], apiSource: 'static' },
]

// ─── PETER ENGLAND (5) ───────────────────────────────────────────────────────

export const PETER_ENGLAND: IndiaProduct[] = [
  { id: 'IN2-FA-PE-001', name: 'Peter England Men Formal Shirt — White 40', brand: 'Peter England', subBrand: 'Peter England Classic', category: 'fashion', subCategory: 'formal-shirts', variant: 'White Size 40', description: 'Peter England regular fit formal shirt in white. 100% cotton with wrinkle-resistant finish. Perfect for office.', price: 899, originalPrice: 1599, discount: 44, image: '/assets/products/peter-england/formal-white-40.jpg', affiliateUrl: '/go/IN2-FA-PE-001', affiliatePlatform: 'myntra', affiliateSource: 'flipkart-affiliate-free', inStock: true, isFeatured: true, isTrending: false, rating: 4.2, reviewCount: 14500, tags: ['Formal Shirt', 'White', 'Peter England', 'Men', 'Office'], apiSource: 'static' },
  { id: 'IN2-FA-PE-002', name: 'Peter England Men Formal Shirt — Light Blue 40', brand: 'Peter England', subBrand: 'Peter England Classic', category: 'fashion', subCategory: 'formal-shirts', variant: 'Light Blue Size 40', description: 'Peter England slim fit formal shirt in light blue check. Spread collar, full placket. Professional look.', price: 949, originalPrice: 1699, discount: 44, image: '/assets/products/peter-england/formal-lightblue-40.jpg', affiliateUrl: '/go/IN2-FA-PE-002', affiliatePlatform: 'myntra', affiliateSource: 'flipkart-affiliate-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.2, reviewCount: 11200, tags: ['Formal Shirt', 'Blue', 'Peter England', 'Men', 'Slim Fit'], apiSource: 'static' },
  { id: 'IN2-FA-PE-003', name: 'Peter England Men Slim Fit Chinos — Khaki 32W', brand: 'Peter England', subBrand: 'Peter England Chinos', category: 'fashion', subCategory: 'chinos', variant: 'Khaki 32W', description: 'Peter England slim fit cotton chinos in khaki. Flat front, mid-rise. Smart casual for office or weekends.', price: 1299, originalPrice: 2299, discount: 43, image: '/assets/products/peter-england/chinos-khaki-32.jpg', affiliateUrl: '/go/IN2-FA-PE-003', affiliatePlatform: 'myntra', affiliateSource: 'flipkart-affiliate-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.1, reviewCount: 7890, tags: ['Chinos', 'Khaki', 'Peter England', 'Men', 'Smart Casual'], apiSource: 'static' },
  { id: 'IN2-FA-PE-004', name: "Peter England Men's Blazer — Navy Blue 40", brand: 'Peter England', subBrand: 'Peter England Elite', category: 'fashion', subCategory: 'blazers', variant: 'Navy Blue Size 40', description: 'Peter England single-breasted blazer in navy blue. Poly-viscose blend with notched lapel. Work or party ready.', price: 2499, originalPrice: 4499, discount: 44, image: '/assets/products/peter-england/blazer-navy-40.jpg', affiliateUrl: '/go/IN2-FA-PE-004', affiliatePlatform: 'myntra', affiliateSource: 'flipkart-affiliate-free', inStock: true, isFeatured: true, isTrending: false, rating: 4.3, reviewCount: 5430, tags: ['Blazer', 'Navy', 'Peter England', 'Men', 'Formal'], apiSource: 'static' },
  { id: 'IN2-FA-PE-005', name: "Peter England Men's Polo T-Shirt — Navy S", brand: 'Peter England', subBrand: 'Peter England Sports', category: 'fashion', subCategory: 'polo-t-shirts', variant: 'Navy S', description: 'Peter England pique polo in navy. Ribbed collar and cuffs, 2-button placket. Smart casual weekend wear.', price: 699, originalPrice: 1299, discount: 46, image: '/assets/products/peter-england/polo-navy-s.jpg', affiliateUrl: '/go/IN2-FA-PE-005', affiliatePlatform: 'myntra', affiliateSource: 'flipkart-affiliate-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.1, reviewCount: 6780, tags: ['Polo', 'Navy', 'Peter England', 'Men', 'Smart Casual'], apiSource: 'static' },
]

// ─── VAN HEUSEN (5) ──────────────────────────────────────────────────────────

export const VAN_HEUSEN: IndiaProduct[] = [
  { id: 'IN2-FA-VH-001', name: 'Van Heusen Slim Fit Formal Shirt — White 40', brand: 'Van Heusen', subBrand: 'Van Heusen Classic', category: 'fashion', subCategory: 'formal-shirts', variant: 'White Size 40', description: 'Van Heusen slim fit formal shirt in wrinkle-free cotton. Spread collar, machine washable. India office essential.', price: 1099, originalPrice: 1999, discount: 45, image: '/assets/products/van-heusen/formal-white-40.jpg', affiliateUrl: '/go/IN2-FA-VH-001', affiliatePlatform: 'myntra', affiliateSource: 'flipkart-affiliate-free', inStock: true, isFeatured: true, isTrending: false, rating: 4.3, reviewCount: 19600, tags: ['Formal Shirt', 'White', 'Van Heusen', 'Wrinkle Free', 'Slim Fit'], apiSource: 'static' },
  { id: 'IN2-FA-VH-002', name: 'Van Heusen Slim Fit Formal Shirt — Light Blue 40', brand: 'Van Heusen', subBrand: 'Van Heusen Classic', category: 'fashion', subCategory: 'formal-shirts', variant: 'Light Blue Size 40', description: 'Van Heusen slim fit shirt in light blue. Superior cotton with anti-static finish. Stays fresh through long workdays.', price: 1199, originalPrice: 2199, discount: 45, image: '/assets/products/van-heusen/formal-lightblue-40.jpg', affiliateUrl: '/go/IN2-FA-VH-002', affiliatePlatform: 'myntra', affiliateSource: 'flipkart-affiliate-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.3, reviewCount: 15400, tags: ['Formal Shirt', 'Blue', 'Van Heusen', 'Anti-Static', 'Men'], apiSource: 'static' },
  { id: 'IN2-FA-VH-003', name: 'Van Heusen Flex Stretch Formal Trousers — Black 32W', brand: 'Van Heusen', subBrand: 'Van Heusen Flex', category: 'fashion', subCategory: 'formal-trousers', variant: 'Black 32W', description: 'Van Heusen Flex formal trousers with 4-way stretch. Flat front, mid-rise. Moves with you through every meeting.', price: 1499, originalPrice: 2799, discount: 46, image: '/assets/products/van-heusen/flex-trousers-black-32.jpg', affiliateUrl: '/go/IN2-FA-VH-003', affiliatePlatform: 'myntra', affiliateSource: 'flipkart-affiliate-free', inStock: true, isFeatured: false, isTrending: true, rating: 4.4, reviewCount: 8970, tags: ['Formal Trousers', 'Black', 'Van Heusen', 'Stretch', 'Flat Front'], apiSource: 'static' },
  { id: 'IN2-FA-VH-004', name: "Van Heusen Women's Formal Shirt — White S", brand: 'Van Heusen', subBrand: "Van Heusen Woman", category: 'fashion', subCategory: 'formal-shirts', variant: 'White S', description: "Van Heusen women's slim fit formal shirt in white. Wrinkle-free cotton, mandarin collar. Boardroom to brunch.", price: 1199, originalPrice: 2199, discount: 45, image: '/assets/products/van-heusen/women-formal-white-s.jpg', affiliateUrl: '/go/IN2-FA-VH-004', affiliatePlatform: 'myntra', affiliateSource: 'flipkart-affiliate-free', inStock: true, isFeatured: true, isTrending: false, rating: 4.3, reviewCount: 7340, tags: ['Formal Shirt', 'Women', 'Van Heusen', 'White', 'Wrinkle Free'], apiSource: 'static' },
  { id: 'IN2-FA-VH-005', name: "Van Heusen Men's Casual Polo — Olive Green M", brand: 'Van Heusen', subBrand: 'Van Heusen Sport', category: 'fashion', subCategory: 'polo-t-shirts', variant: 'Olive Green M', description: 'Van Heusen Sport polo in olive green. Moisture-wicking fabric with antibacterial finish. Weekend casual done right.', price: 899, originalPrice: 1699, discount: 47, image: '/assets/products/van-heusen/polo-olive-m.jpg', affiliateUrl: '/go/IN2-FA-VH-005', affiliatePlatform: 'myntra', affiliateSource: 'flipkart-affiliate-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.2, reviewCount: 5980, tags: ['Polo', 'Olive', 'Van Heusen', 'Moisture Wicking', 'Men'], apiSource: 'static' },
]

// ─── FABINDIA (5) ────────────────────────────────────────────────────────────

export const FABINDIA: IndiaProduct[] = [
  { id: 'IN2-FA-FBI-001', name: "Fabindia Men's Cotton Kurta — Off White M", brand: 'Fabindia', subBrand: 'Fabindia Men', category: 'fashion', subCategory: 'kurtas', variant: 'Off White M', description: 'Fabindia handloom cotton kurta in off white. Straight cut with side slits. Artisan-crafted in India, festival ready.', price: 1299, originalPrice: 1999, discount: 35, image: '/assets/products/fabindia/kurta-offwhite-m.jpg', affiliateUrl: '/go/IN2-FA-FBI-001', affiliatePlatform: 'myntra', affiliateSource: 'flipkart-affiliate-free', inStock: true, isFeatured: true, isTrending: false, rating: 4.4, reviewCount: 8760, tags: ['Kurta', 'Cotton', 'Fabindia', 'Men', 'Handloom'], apiSource: 'static' },
  { id: 'IN2-FA-FBI-002', name: "Fabindia Women's Printed Kurta Set — Indigo Blue S", brand: 'Fabindia', subBrand: 'Fabindia Women', category: 'fashion', subCategory: 'kurta-sets', variant: 'Indigo Blue S', description: "Fabindia women's block-printed cotton kurta set with palazzo and dupatta. Indigo blue. Handcrafted artisan wear.", price: 2999, originalPrice: 4499, discount: 33, image: '/assets/products/fabindia/women-kurta-set-indigo-s.jpg', affiliateUrl: '/go/IN2-FA-FBI-002', affiliatePlatform: 'myntra', affiliateSource: 'flipkart-affiliate-free', inStock: true, isFeatured: true, isTrending: true, rating: 4.5, reviewCount: 12340, tags: ['Kurta Set', 'Block Print', 'Fabindia', 'Women', 'Handcraft'], apiSource: 'static' },
  { id: 'IN2-FA-FBI-003', name: "Fabindia Men's Cotton Shorts — Beige M", brand: 'Fabindia', subBrand: 'Fabindia Men', category: 'fashion', subCategory: 'shorts', variant: 'Beige M', description: 'Fabindia cotton shorts in beige. Drawstring waist, side and back pockets. Comfortable summer casuals.', price: 799, originalPrice: 1299, discount: 38, image: '/assets/products/fabindia/cotton-shorts-beige-m.jpg', affiliateUrl: '/go/IN2-FA-FBI-003', affiliatePlatform: 'myntra', affiliateSource: 'flipkart-affiliate-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.2, reviewCount: 4560, tags: ['Shorts', 'Cotton', 'Fabindia', 'Men', 'Summer'], apiSource: 'static' },
  { id: 'IN2-FA-FBI-004', name: "Fabindia Women's Cotton Saree — Red & Gold", brand: 'Fabindia', subBrand: 'Fabindia Sarees', category: 'fashion', subCategory: 'sarees', variant: 'Red & Gold', description: "Fabindia handwoven cotton saree in red with gold zari border. Comes with unstitched blouse piece. Wedding season must-have.", price: 3499, originalPrice: 5499, discount: 36, image: '/assets/products/fabindia/saree-red-gold.jpg', affiliateUrl: '/go/IN2-FA-FBI-004', affiliatePlatform: 'myntra', affiliateSource: 'flipkart-affiliate-free', inStock: true, isFeatured: true, isTrending: false, rating: 4.6, reviewCount: 6780, tags: ['Saree', 'Cotton', 'Fabindia', 'Women', 'Zari'], apiSource: 'static' },
  { id: 'IN2-FA-FBI-005', name: "Fabindia Men's Nehru Jacket — Navy Blue M", brand: 'Fabindia', subBrand: 'Fabindia Men', category: 'fashion', subCategory: 'ethnic-jackets', variant: 'Navy Blue M', description: "Fabindia Nehru jacket in handloom cotton. Mandarin collar, front buttons. Layer over kurta for festive occasions.", price: 1799, originalPrice: 2799, discount: 36, image: '/assets/products/fabindia/nehru-jacket-navy-m.jpg', affiliateUrl: '/go/IN2-FA-FBI-005', affiliatePlatform: 'myntra', affiliateSource: 'flipkart-affiliate-free', inStock: true, isFeatured: false, isTrending: true, rating: 4.3, reviewCount: 5670, tags: ['Nehru Jacket', 'Ethnic', 'Fabindia', 'Men', 'Navy'], apiSource: 'static' },
]

// ─── H&M (5) ─────────────────────────────────────────────────────────────────

export const HM: IndiaProduct[] = [
  { id: 'IN2-FA-HM-001', name: "H&M Women's Basic Cotton T-Shirt — White S", brand: 'H&M', subBrand: 'H&M Basics', category: 'fashion', subCategory: 't-shirts', variant: 'White S', description: "H&M basic cotton jersey t-shirt for women. Round neck, short sleeves. The everyday essential that goes with everything.", price: 499, originalPrice: 899, discount: 44, image: '/assets/products/hm/women-basic-tee-white-s.jpg', affiliateUrl: '/go/IN2-FA-HM-001', affiliatePlatform: 'myntra', affiliateSource: 'flipkart-affiliate-free', inStock: true, isFeatured: false, isTrending: true, rating: 4.1, reviewCount: 9870, tags: ['T-Shirt', 'Cotton', 'H&M', 'Women', 'Basic'], apiSource: 'static' },
  { id: 'IN2-FA-HM-002', name: "H&M Women's Straight-Leg Jeans — Blue 36", brand: 'H&M', subBrand: 'H&M Denim', category: 'fashion', subCategory: 'jeans', variant: 'Blue 36', description: "H&M straight-leg jeans for women. High waist, regular fit through hips and thighs. Classic blue denim wash.", price: 1999, originalPrice: 3499, discount: 43, image: '/assets/products/hm/women-straight-jeans-blue-36.jpg', affiliateUrl: '/go/IN2-FA-HM-002', affiliatePlatform: 'myntra', affiliateSource: 'flipkart-affiliate-free', inStock: true, isFeatured: false, isTrending: true, rating: 4.2, reviewCount: 7650, tags: ['Jeans', 'Straight Leg', 'H&M', 'Women', 'High Waist'], apiSource: 'static' },
  { id: 'IN2-FA-HM-003', name: "H&M Men's Regular Fit Oxford Shirt — White M", brand: 'H&M', subBrand: 'H&M Men', category: 'fashion', subCategory: 'casual-shirts', variant: 'White M', description: "H&M regular fit Oxford shirt for men. Button-down collar, chest pocket. Smart casual fabric that irons easily.", price: 1299, originalPrice: 2299, discount: 43, image: '/assets/products/hm/men-oxford-white-m.jpg', affiliateUrl: '/go/IN2-FA-HM-003', affiliatePlatform: 'myntra', affiliateSource: 'flipkart-affiliate-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.2, reviewCount: 6540, tags: ['Oxford Shirt', 'H&M', 'Men', 'Smart Casual', 'White'], apiSource: 'static' },
  { id: 'IN2-FA-HM-004', name: "H&M Women's Floral Wrap Dress — Red Floral S", brand: 'H&M', subBrand: 'H&M Women', category: 'fashion', subCategory: 'dresses', variant: 'Red Floral S', description: "H&M women's V-neck wrap dress in floral print chiffon. Tie waist, flutter sleeves. Summer occasion wear.", price: 1499, originalPrice: 2799, discount: 46, image: '/assets/products/hm/women-wrap-dress-red-floral-s.jpg', affiliateUrl: '/go/IN2-FA-HM-004', affiliatePlatform: 'myntra', affiliateSource: 'flipkart-affiliate-free', inStock: true, isFeatured: true, isTrending: true, rating: 4.3, reviewCount: 11230, tags: ['Dress', 'Floral', 'H&M', 'Women', 'Wrap'], apiSource: 'static' },
  { id: 'IN2-FA-HM-005', name: "H&M Men's Slim Fit Chinos — Beige 32W", brand: 'H&M', subBrand: 'H&M Men', category: 'fashion', subCategory: 'chinos', variant: 'Beige 32W', description: "H&M slim fit chinos for men in beige. Cotton blend, mid-rise. Pair with a shirt for effortless smart casual.", price: 1499, originalPrice: 2699, discount: 44, image: '/assets/products/hm/men-slim-chinos-beige-32.jpg', affiliateUrl: '/go/IN2-FA-HM-005', affiliatePlatform: 'myntra', affiliateSource: 'flipkart-affiliate-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.2, reviewCount: 8760, tags: ['Chinos', 'Slim Fit', 'H&M', 'Men', 'Beige'], apiSource: 'static' },
]

// ─── MANYAVAR (4) ────────────────────────────────────────────────────────────

export const MANYAVAR: IndiaProduct[] = [
  { id: 'IN2-FA-MBA-001', name: "Manyavar Men's Embroidered Kurta — Royal Blue M", brand: 'Manyavar', subBrand: 'Manyavar Core', category: 'fashion', subCategory: 'kurtas', variant: 'Royal Blue M', description: "Manyavar festive kurta with subtle chikankari embroidery in royal blue. Mandarin collar, straight cut. Eid and Diwali perfect.", price: 2999, originalPrice: 4999, discount: 40, image: '/assets/products/manyavar/kurta-royal-blue-m.jpg', affiliateUrl: '/go/IN2-FA-MBA-001', affiliatePlatform: 'myntra', affiliateSource: 'flipkart-affiliate-free', inStock: true, isFeatured: true, isTrending: true, rating: 4.5, reviewCount: 8970, tags: ['Kurta', 'Embroidered', 'Manyavar', 'Men', 'Festive'], apiSource: 'static' },
  { id: 'IN2-FA-MBA-002', name: "Manyavar Men's Sherwani — Cream 40", brand: 'Manyavar', subBrand: 'Manyavar Wedding', category: 'fashion', subCategory: 'sherwanis', variant: 'Cream Size 40', description: "Manyavar wedding sherwani in cream with gold zardozi work. Comes with matching churidar. The groom's choice.", price: 12999, originalPrice: 19999, discount: 35, image: '/assets/products/manyavar/sherwani-cream-40.jpg', affiliateUrl: '/go/IN2-FA-MBA-002', affiliatePlatform: 'myntra', affiliateSource: 'flipkart-affiliate-free', inStock: true, isFeatured: true, isTrending: false, rating: 4.6, reviewCount: 3450, tags: ['Sherwani', 'Wedding', 'Manyavar', 'Men', 'Groom'], apiSource: 'static' },
  { id: 'IN2-FA-MBA-003', name: "Manyavar Men's Indo-Western Set — Maroon M", brand: 'Manyavar', subBrand: 'Mohey by Manyavar', category: 'fashion', subCategory: 'indo-western', variant: 'Maroon M', description: "Manyavar Indo-Western set with jacket and straight pants in maroon. Perfect sangeet and reception look.", price: 5999, originalPrice: 9999, discount: 40, image: '/assets/products/manyavar/indo-western-maroon-m.jpg', affiliateUrl: '/go/IN2-FA-MBA-003', affiliatePlatform: 'myntra', affiliateSource: 'flipkart-affiliate-free', inStock: true, isFeatured: false, isTrending: true, rating: 4.4, reviewCount: 5670, tags: ['Indo Western', 'Festive', 'Manyavar', 'Men', 'Sangeet'], apiSource: 'static' },
  { id: 'IN2-FA-MBA-004', name: "Manyavar Men's Nehru Jacket Set — Navy Blue M", brand: 'Manyavar', subBrand: 'Manyavar Core', category: 'fashion', subCategory: 'ethnic-jackets', variant: 'Navy Blue M', description: "Manyavar Nehru jacket with matching kurta in navy blue. Subtle texture, gold buttons. Smart ethnic casual.", price: 3499, originalPrice: 5999, discount: 42, image: '/assets/products/manyavar/nehru-jacket-set-navy-m.jpg', affiliateUrl: '/go/IN2-FA-MBA-004', affiliatePlatform: 'myntra', affiliateSource: 'flipkart-affiliate-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.4, reviewCount: 6780, tags: ['Nehru Jacket', 'Ethnic', 'Manyavar', 'Men', 'Festive'], apiSource: 'static' },
]

// ─── BATA FOOTWEAR (5) ───────────────────────────────────────────────────────

export const BATA: IndiaProduct[] = [
  { id: 'IN2-FW-BAT-001', name: "Bata Men's Power Sneakers — Black UK9", brand: 'Bata', subBrand: 'Power', category: 'fashion', subCategory: 'sneakers', variant: 'Black UK9', description: "Bata Power canvas sneakers in black. Lightweight EVA sole, lace-up design. Comfortable everyday footwear.", price: 1299, originalPrice: 2199, discount: 41, image: '/assets/products/bata/power-sneakers-black-9.jpg', affiliateUrl: '/go/IN2-FW-BAT-001', affiliatePlatform: 'flipkart', affiliateSource: 'flipkart-affiliate-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.1, reviewCount: 12300, tags: ['Sneakers', 'Black', 'Bata', 'Men', 'Casual'], apiSource: 'static' },
  { id: 'IN2-FW-BAT-002', name: "Bata Men's Formal Leather Shoes — Dark Brown UK9", brand: 'Bata', subBrand: 'Bata Classic', category: 'fashion', subCategory: 'formal-shoes', variant: 'Dark Brown UK9', description: "Bata men's lace-up formal shoes in dark brown leather. Cushioned insole, genuine leather upper. Office essentials.", price: 1799, originalPrice: 2999, discount: 40, image: '/assets/products/bata/formal-darkbrown-9.jpg', affiliateUrl: '/go/IN2-FW-BAT-002', affiliatePlatform: 'flipkart', affiliateSource: 'flipkart-affiliate-free', inStock: true, isFeatured: true, isTrending: false, rating: 4.2, reviewCount: 18900, tags: ['Formal Shoes', 'Leather', 'Bata', 'Men', 'Dark Brown'], apiSource: 'static' },
  { id: 'IN2-FW-BAT-003', name: "Bata Women's Block Heels — Nude UK5", brand: 'Bata', subBrand: 'Bata Comfit', category: 'fashion', subCategory: 'heels', variant: 'Nude UK5', description: "Bata women's block-heel sandals in nude. Adjustable ankle strap, cushioned footbed. Party and office wear.", price: 1499, originalPrice: 2499, discount: 40, image: '/assets/products/bata/women-heels-nude-5.jpg', affiliateUrl: '/go/IN2-FW-BAT-003', affiliatePlatform: 'myntra', affiliateSource: 'flipkart-affiliate-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.0, reviewCount: 6540, tags: ['Heels', 'Block Heel', 'Bata', 'Women', 'Nude'], apiSource: 'static' },
  { id: 'IN2-FW-BAT-004', name: "Bata Men's Casual Floaters — Tan UK9", brand: 'Bata', subBrand: 'Bata Comfit', category: 'fashion', subCategory: 'sandals', variant: 'Tan UK9', description: "Bata men's slip-on floaters in tan. Velcro closure, cushioned footbed. Perfect for casual summer outings.", price: 999, originalPrice: 1699, discount: 41, image: '/assets/products/bata/floaters-tan-9.jpg', affiliateUrl: '/go/IN2-FW-BAT-004', affiliatePlatform: 'flipkart', affiliateSource: 'flipkart-affiliate-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.0, reviewCount: 9870, tags: ['Floaters', 'Tan', 'Bata', 'Men', 'Summer'], apiSource: 'static' },
  { id: 'IN2-FW-BAT-005', name: "Bata Women's Ballet Flats — Black UK5", brand: 'Bata', subBrand: 'Bata Comfit', category: 'fashion', subCategory: 'flats', variant: 'Black UK5', description: "Bata women's ballet flats in black faux leather. Flexible sole, cushioned insole. Comfortable all-day wear.", price: 999, originalPrice: 1699, discount: 41, image: '/assets/products/bata/women-ballet-black-5.jpg', affiliateUrl: '/go/IN2-FW-BAT-005', affiliatePlatform: 'myntra', affiliateSource: 'flipkart-affiliate-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.1, reviewCount: 8760, tags: ['Ballet Flats', 'Black', 'Bata', 'Women', 'Comfortable'], apiSource: 'static' },
]

// ─── PUMA (5) ────────────────────────────────────────────────────────────────

export const PUMA: IndiaProduct[] = [
  { id: 'IN2-FW-PUM-001', name: "Puma Softride Premier Men's Running Shoes — White/Black UK9", brand: 'Puma', subBrand: 'Softride', category: 'fashion', subCategory: 'running-shoes', variant: 'White/Black UK9', description: 'Puma Softride Premier running shoes with SOFTRIDE foam for superior cushioning. Lightweight mesh upper. Daily run ready.', price: 4999, originalPrice: 7999, discount: 38, image: '/assets/products/puma/softride-premier-white-9.jpg', affiliateUrl: '/go/IN2-FW-PUM-001', affiliatePlatform: 'myntra', affiliateSource: 'flipkart-affiliate-free', inStock: true, isFeatured: true, isTrending: true, rating: 4.4, reviewCount: 14500, tags: ['Running Shoes', 'Puma', 'Softride', 'Men', 'Cushioning'], apiSource: 'static' },
  { id: 'IN2-FW-PUM-002', name: "Puma RS-X3 Puzzle Sneakers — Black UK9", brand: 'Puma', subBrand: 'RS-X', category: 'fashion', subCategory: 'sneakers', variant: 'Black UK9', description: "Puma RS-X3 retro-inspired chunky sneakers. RS foam cushioning, multi-layered upper. Street style statement.", price: 6999, originalPrice: 11999, discount: 42, image: '/assets/products/puma/rs-x3-black-9.jpg', affiliateUrl: '/go/IN2-FW-PUM-002', affiliatePlatform: 'myntra', affiliateSource: 'flipkart-affiliate-free', inStock: true, isFeatured: false, isTrending: true, rating: 4.3, reviewCount: 9870, tags: ['Chunky Sneakers', 'RS-X', 'Puma', 'Streetwear', 'Men'], apiSource: 'static' },
  { id: 'IN2-FW-PUM-003', name: "Puma Women's Flyer Runner Shoes — Pink/White UK6", brand: 'Puma', subBrand: 'Flyer Runner', category: 'fashion', subCategory: 'running-shoes', variant: 'Pink/White UK6', description: "Puma Flyer Runner for women. Lightweight mesh with SOFTFOAM+ insole. Vibrant pink for morning runs.", price: 3999, originalPrice: 6499, discount: 38, image: '/assets/products/puma/flyer-runner-pink-6.jpg', affiliateUrl: '/go/IN2-FW-PUM-003', affiliatePlatform: 'myntra', affiliateSource: 'flipkart-affiliate-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.3, reviewCount: 7650, tags: ['Running Shoes', 'Puma', 'Women', 'Pink', 'Lightweight'], apiSource: 'static' },
  { id: 'IN2-FW-PUM-004', name: "Puma Essentials Track Pants — Black M", brand: 'Puma', subBrand: 'Puma Essentials', category: 'fashion', subCategory: 'track-pants', variant: 'Black M', description: 'Puma Essentials track pants in black. Elastic waistband with drawcord, side pockets. Gym to street wear.', price: 1999, originalPrice: 3499, discount: 43, image: '/assets/products/puma/essentials-track-pants-black-m.jpg', affiliateUrl: '/go/IN2-FW-PUM-004', affiliatePlatform: 'myntra', affiliateSource: 'flipkart-affiliate-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.2, reviewCount: 11200, tags: ['Track Pants', 'Black', 'Puma', 'Men', 'Gym'], apiSource: 'static' },
  { id: 'IN2-FW-PUM-005', name: "Puma Small Logo T-Shirt — White M", brand: 'Puma', subBrand: 'Puma Essentials', category: 'fashion', subCategory: 't-shirts', variant: 'White M', description: "Puma classic small logo t-shirt in white. 100% cotton jersey, ribbed crew neck. The everyday gym and casual tee.", price: 1499, originalPrice: 2499, discount: 40, image: '/assets/products/puma/small-logo-tee-white-m.jpg', affiliateUrl: '/go/IN2-FW-PUM-005', affiliatePlatform: 'myntra', affiliateSource: 'flipkart-affiliate-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.2, reviewCount: 8760, tags: ['T-Shirt', 'Cotton', 'Puma', 'Men', 'Casual'], apiSource: 'static' },
]

// ─── ADIDAS (5) ──────────────────────────────────────────────────────────────

export const ADIDAS_FASHION: IndiaProduct[] = [
  { id: 'IN2-FW-ADI-001', name: "Adidas Ultraboost 22 Running Shoes — Black/White UK9", brand: 'Adidas', subBrand: 'Ultraboost', category: 'fashion', subCategory: 'running-shoes', variant: 'Black/White UK9', description: 'Adidas Ultraboost 22 with Boost midsole for incredible energy return. Primeknit+ upper wraps the foot. For serious runners.', price: 10999, originalPrice: 17999, discount: 39, image: '/assets/products/adidas/ultraboost-22-black-9.jpg', affiliateUrl: '/go/IN2-FW-ADI-001', affiliatePlatform: 'myntra', affiliateSource: 'flipkart-affiliate-free', inStock: true, isFeatured: true, isTrending: true, rating: 4.6, reviewCount: 18900, tags: ['Ultraboost', 'Running Shoes', 'Adidas', 'Men', 'Boost'], apiSource: 'static' },
  { id: 'IN2-FW-ADI-002', name: "Adidas Stan Smith Sneakers — White/Green UK9", brand: 'Adidas', subBrand: 'Stan Smith', category: 'fashion', subCategory: 'sneakers', variant: 'White/Green UK9', description: "Adidas Stan Smith — the timeless tennis shoe turned style icon. Perforated 3-Stripes, leather upper, green heel tab.", price: 7999, originalPrice: 12999, discount: 38, image: '/assets/products/adidas/stan-smith-white-green-9.jpg', affiliateUrl: '/go/IN2-FW-ADI-002', affiliatePlatform: 'myntra', affiliateSource: 'flipkart-affiliate-free', inStock: true, isFeatured: true, isTrending: true, rating: 4.5, reviewCount: 34500, tags: ['Stan Smith', 'Adidas', 'Sneakers', 'Classic', 'Men'], apiSource: 'static' },
  { id: 'IN2-FW-ADI-003', name: "Adidas Tiro 23 Track Pants — Black M", brand: 'Adidas', subBrand: 'Tiro', category: 'fashion', subCategory: 'track-pants', variant: 'Black M', description: "Adidas Tiro 23 football-inspired track pants. Moisture-absorbing AEROREADY fabric. Zip pockets, tapered fit.", price: 2999, originalPrice: 4999, discount: 40, image: '/assets/products/adidas/tiro-23-track-black-m.jpg', affiliateUrl: '/go/IN2-FW-ADI-003', affiliatePlatform: 'myntra', affiliateSource: 'flipkart-affiliate-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.4, reviewCount: 12300, tags: ['Track Pants', 'Tiro', 'Adidas', 'Men', 'AEROREADY'], apiSource: 'static' },
  { id: 'IN2-FW-ADI-004', name: "Adidas Trefoil Pullover Hoodie — Grey M", brand: 'Adidas', subBrand: 'Adidas Originals', category: 'fashion', subCategory: 'hoodies', variant: 'Grey M', description: 'Adidas Originals Trefoil hoodie in grey melange. French terry cotton, kangaroo pocket. Classic streetwear icon.', price: 3999, originalPrice: 6999, discount: 43, image: '/assets/products/adidas/trefoil-hoodie-grey-m.jpg', affiliateUrl: '/go/IN2-FW-ADI-004', affiliatePlatform: 'myntra', affiliateSource: 'flipkart-affiliate-free', inStock: true, isFeatured: false, isTrending: true, rating: 4.4, reviewCount: 9870, tags: ['Hoodie', 'Trefoil', 'Adidas', 'Originals', 'Streetwear'], apiSource: 'static' },
  { id: 'IN2-FW-ADI-005', name: "Adidas Women's Puremotion Running Shoes — White/Pink UK6", brand: 'Adidas', subBrand: 'Puremotion', category: 'fashion', subCategory: 'running-shoes', variant: 'White/Pink UK6', description: "Adidas Puremotion for women. Lightweight mesh upper, cloudfoam cushioning. Perfect for morning jogs and gym.", price: 4999, originalPrice: 7999, discount: 38, image: '/assets/products/adidas/puremotion-white-pink-6.jpg', affiliateUrl: '/go/IN2-FW-ADI-005', affiliatePlatform: 'myntra', affiliateSource: 'flipkart-affiliate-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.3, reviewCount: 8760, tags: ['Running Shoes', 'Adidas', 'Women', 'Cloudfoam', 'Pink'], apiSource: 'static' },
]

// ─── WOODLAND (4) ────────────────────────────────────────────────────────────

export const WOODLAND: IndiaProduct[] = [
  { id: 'IN2-FW-WDL-001', name: "Woodland Men's Leather Trekking Shoes — Dark Brown UK9", brand: 'Woodland', subBrand: 'Woodland Pro', category: 'fashion', subCategory: 'trekking-shoes', variant: 'Dark Brown UK9', description: "Woodland leather trekking shoes with anti-skid rubber sole. Waterproof treated upper, padded collar. Built for Indian trails.", price: 3999, originalPrice: 6499, discount: 38, image: '/assets/products/woodland/trekking-darkbrown-9.jpg', affiliateUrl: '/go/IN2-FW-WDL-001', affiliatePlatform: 'flipkart', affiliateSource: 'flipkart-affiliate-free', inStock: true, isFeatured: true, isTrending: false, rating: 4.4, reviewCount: 23400, tags: ['Trekking Shoes', 'Leather', 'Woodland', 'Men', 'Waterproof'], apiSource: 'static' },
  { id: 'IN2-FW-WDL-002', name: "Woodland Men's Casual Leather Shoes — Camel UK9", brand: 'Woodland', subBrand: 'Woodland Classic', category: 'fashion', subCategory: 'casual-shoes', variant: 'Camel UK9', description: 'Woodland casual shoes in camel leather. Lace-up, thick rubber sole. Rugged style for everyday and outdoor casual wear.', price: 2999, originalPrice: 4999, discount: 40, image: '/assets/products/woodland/casual-camel-9.jpg', affiliateUrl: '/go/IN2-FW-WDL-002', affiliatePlatform: 'flipkart', affiliateSource: 'flipkart-affiliate-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.3, reviewCount: 18900, tags: ['Casual Shoes', 'Leather', 'Woodland', 'Men', 'Rugged'], apiSource: 'static' },
  { id: 'IN2-FW-WDL-003', name: "Woodland Men's Leather Ankle Boots — Dark Brown UK9", brand: 'Woodland', subBrand: 'Woodland Boots', category: 'fashion', subCategory: 'boots', variant: 'Dark Brown UK9', description: 'Woodland ankle boots in full-grain leather. Side zip, cushioned footbed. Style for winter and monsoon season.', price: 4499, originalPrice: 7499, discount: 40, image: '/assets/products/woodland/ankle-boots-darkbrown-9.jpg', affiliateUrl: '/go/IN2-FW-WDL-003', affiliatePlatform: 'flipkart', affiliateSource: 'flipkart-affiliate-free', inStock: true, isFeatured: false, isTrending: true, rating: 4.4, reviewCount: 9870, tags: ['Ankle Boots', 'Leather', 'Woodland', 'Men', 'Winter'], apiSource: 'static' },
  { id: 'IN2-FW-WDL-004', name: "Woodland Men's Boat Shoes — Rust Brown UK9", brand: 'Woodland', subBrand: 'Woodland Classic', category: 'fashion', subCategory: 'boat-shoes', variant: 'Rust Brown UK9', description: "Woodland boat shoes in rust brown leather. Non-marking siped outsole. Smart casual for college and weekend outings.", price: 2499, originalPrice: 4199, discount: 41, image: '/assets/products/woodland/boat-shoes-rust-9.jpg', affiliateUrl: '/go/IN2-FW-WDL-004', affiliatePlatform: 'flipkart', affiliateSource: 'flipkart-affiliate-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.2, reviewCount: 7650, tags: ['Boat Shoes', 'Rust', 'Woodland', 'Men', 'Casual'], apiSource: 'static' },
]

// ─── LAKME (5) ───────────────────────────────────────────────────────────────

export const LAKME: IndiaProduct[] = [
  { id: 'IN2-BE-LAK-001', name: 'Lakme 9 to 5 Flawless Matte Foundation — Shell', brand: 'Lakme', subBrand: '9 to 5', category: 'personal-care', subCategory: 'foundation', variant: 'Shell', description: "Lakme 9 to 5 foundation with flawless matte finish. SPF 8. Light, buildable coverage lasting up to 16 hours. India's #1.", price: 599, originalPrice: 799, discount: 25, image: '/assets/products/lakme/9to5-matte-foundation-shell.jpg', affiliateUrl: '/go/IN2-BE-LAK-001', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: true, isTrending: true, rating: 4.3, reviewCount: 45600, tags: ['Foundation', 'Matte', 'Lakme', '9 to 5', 'SPF 8'], apiSource: 'static' },
  { id: 'IN2-BE-LAK-002', name: 'Lakme Absolute Matte Lip Color — Red Fantasy', brand: 'Lakme', subBrand: 'Absolute', category: 'personal-care', subCategory: 'lipstick', variant: 'Red Fantasy', description: "Lakme Absolute matte lipstick in bold Red Fantasy. Creamy texture with matte finish. Long-lasting up to 8 hours.", price: 399, originalPrice: 549, discount: 27, image: '/assets/products/lakme/absolute-matte-lip-red.jpg', affiliateUrl: '/go/IN2-BE-LAK-002', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: false, isTrending: true, rating: 4.2, reviewCount: 34500, tags: ['Lipstick', 'Red', 'Matte', 'Lakme', 'Absolute'], apiSource: 'static' },
  { id: 'IN2-BE-LAK-003', name: 'Lakme Eyeconic Kajal — Black', brand: 'Lakme', subBrand: 'Eyeconic', category: 'personal-care', subCategory: 'eye-makeup', variant: 'Black', description: "Lakme Eyeconic kajal in jet black. Smudge-proof formula, lasts 24 hours. Waterproof. India's best-selling kajal.", price: 199, originalPrice: 279, discount: 29, image: '/assets/products/lakme/eyeconic-kajal-black.jpg', affiliateUrl: '/go/IN2-BE-LAK-003', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: true, isTrending: true, rating: 4.5, reviewCount: 87600, tags: ['Kajal', 'Black', 'Smudge Proof', 'Lakme', 'Waterproof'], apiSource: 'static' },
  { id: 'IN2-BE-LAK-004', name: 'Lakme Perfect Radiance Brightening Face Wash — 100ml', brand: 'Lakme', subBrand: 'Perfect Radiance', category: 'personal-care', subCategory: 'face-wash', variant: '100ml', description: "Lakme Perfect Radiance brightening face wash with micro-crystals. Reveals fresh, glowing skin. Paraben-free.", price: 199, originalPrice: 269, discount: 26, image: '/assets/products/lakme/perfect-radiance-facewash-100ml.jpg', affiliateUrl: '/go/IN2-BE-LAK-004', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.2, reviewCount: 23400, tags: ['Face Wash', 'Brightening', 'Lakme', 'Paraben Free', 'Skin Care'], apiSource: 'static' },
  { id: 'IN2-BE-LAK-005', name: 'Lakme Salon Expert Hair Serum — Damage Repair 100ml', brand: 'Lakme', subBrand: 'Salon Expert', category: 'personal-care', subCategory: 'hair-care', variant: 'Damage Repair 100ml', description: "Lakme Salon Expert hair serum for damaged hair. Protein-enriched formula reduces breakage. Salon-like finish at home.", price: 299, originalPrice: 399, discount: 25, image: '/assets/products/lakme/salon-expert-serum-100ml.jpg', affiliateUrl: '/go/IN2-BE-LAK-005', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.1, reviewCount: 18900, tags: ['Hair Serum', 'Damage Repair', 'Lakme', 'Protein', 'Salon'], apiSource: 'static' },
]

// ─── MAMAEARTH (5) ───────────────────────────────────────────────────────────

export const MAMAEARTH: IndiaProduct[] = [
  { id: 'IN2-BE-MAM-001', name: 'Mamaearth Vitamin C Face Wash — 100ml', brand: 'Mamaearth', subBrand: 'Vitamin C', category: 'personal-care', subCategory: 'face-wash', variant: '100ml', description: 'Mamaearth Vitamin C face wash with turmeric for radiant skin. Free from sulphates, parabens and SLS. Safe for daily use.', price: 249, originalPrice: 349, discount: 29, image: '/assets/products/mamaearth/vitc-facewash-100ml.jpg', affiliateUrl: '/go/IN2-BE-MAM-001', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: true, isTrending: true, rating: 4.3, reviewCount: 67800, tags: ['Vitamin C', 'Face Wash', 'Mamaearth', 'Turmeric', 'Sulphate Free'], apiSource: 'static' },
  { id: 'IN2-BE-MAM-002', name: 'Mamaearth Onion Hair Oil — 250ml', brand: 'Mamaearth', subBrand: 'Onion Range', category: 'personal-care', subCategory: 'hair-care', variant: '250ml', description: 'Mamaearth Onion hair oil with redensyl to control hair fall. Nourishes scalp and strengthens roots. Dermatologist tested.', price: 349, originalPrice: 499, discount: 30, image: '/assets/products/mamaearth/onion-hair-oil-250ml.jpg', affiliateUrl: '/go/IN2-BE-MAM-002', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: true, isTrending: true, rating: 4.3, reviewCount: 89000, tags: ['Hair Oil', 'Onion', 'Hair Fall', 'Mamaearth', 'Redensyl'], apiSource: 'static' },
  { id: 'IN2-BE-MAM-003', name: 'Mamaearth Ubtan Face Wash — 100ml', brand: 'Mamaearth', subBrand: 'Ubtan', category: 'personal-care', subCategory: 'face-wash', variant: '100ml', description: 'Mamaearth Ubtan face wash with turmeric and saffron. Brightens and exfoliates naturally. Ancient Ayurveda for modern skin.', price: 249, originalPrice: 349, discount: 29, image: '/assets/products/mamaearth/ubtan-facewash-100ml.jpg', affiliateUrl: '/go/IN2-BE-MAM-003', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.4, reviewCount: 54300, tags: ['Ubtan', 'Face Wash', 'Turmeric', 'Mamaearth', 'Ayurveda'], apiSource: 'static' },
  { id: 'IN2-BE-MAM-004', name: 'Mamaearth Onion Shampoo — 250ml', brand: 'Mamaearth', subBrand: 'Onion Range', category: 'personal-care', subCategory: 'shampoo', variant: '250ml', description: 'Mamaearth Onion shampoo with plant keratin for hair fall control. Free from sulphates and parabens. For all hair types.', price: 349, originalPrice: 499, discount: 30, image: '/assets/products/mamaearth/onion-shampoo-250ml.jpg', affiliateUrl: '/go/IN2-BE-MAM-004', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: false, isTrending: true, rating: 4.3, reviewCount: 76500, tags: ['Shampoo', 'Onion', 'Hair Fall', 'Mamaearth', 'Keratin'], apiSource: 'static' },
  { id: 'IN2-BE-MAM-005', name: 'Mamaearth Tea Tree Face Cream — 50g', brand: 'Mamaearth', subBrand: 'Tea Tree', category: 'personal-care', subCategory: 'moisturizer', variant: '50g', description: 'Mamaearth Tea Tree face cream for acne-prone skin. Niacinamide and tea tree extract fight breakouts. Oil-free, non-comedogenic.', price: 299, originalPrice: 399, discount: 25, image: '/assets/products/mamaearth/tea-tree-cream-50g.jpg', affiliateUrl: '/go/IN2-BE-MAM-005', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.2, reviewCount: 34500, tags: ['Tea Tree', 'Moisturizer', 'Acne', 'Mamaearth', 'Niacinamide'], apiSource: 'static' },
]

// ─── WOW SKIN SCIENCE (4) ────────────────────────────────────────────────────

export const WOW: IndiaProduct[] = [
  { id: 'IN2-BE-WOW-001', name: 'WOW Apple Cider Vinegar Shampoo — 300ml', brand: 'WOW Skin Science', subBrand: 'Apple Cider Vinegar', category: 'personal-care', subCategory: 'shampoo', variant: '300ml', description: 'WOW ACV shampoo with Himalayan apple cider vinegar. Balances scalp pH, removes build-up, enhances shine. Sulphate free.', price: 549, originalPrice: 799, discount: 31, image: '/assets/products/wow/acv-shampoo-300ml.jpg', affiliateUrl: '/go/IN2-BE-WOW-001', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: true, isTrending: true, rating: 4.3, reviewCount: 56700, tags: ['ACV', 'Shampoo', 'WOW', 'Sulphate Free', 'Scalp Health'], apiSource: 'static' },
  { id: 'IN2-BE-WOW-002', name: 'WOW Activated Charcoal Face Wash — 100ml', brand: 'WOW Skin Science', subBrand: 'Activated Charcoal', category: 'personal-care', subCategory: 'face-wash', variant: '100ml', description: 'WOW charcoal face wash pulls out deep-seated impurities. Kaolin clay, salicylic acid. Deep cleansing for oily skin.', price: 299, originalPrice: 449, discount: 33, image: '/assets/products/wow/charcoal-facewash-100ml.jpg', affiliateUrl: '/go/IN2-BE-WOW-002', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.2, reviewCount: 43200, tags: ['Charcoal', 'Face Wash', 'WOW', 'Deep Cleanse', 'Oily Skin'], apiSource: 'static' },
  { id: 'IN2-BE-WOW-003', name: 'WOW Red Onion Black Seed Oil Conditioner — 300ml', brand: 'WOW Skin Science', subBrand: 'Red Onion', category: 'personal-care', subCategory: 'hair-care', variant: '300ml', description: 'WOW Red Onion conditioner with black seed oil and argan oil. Detangles, hydrates and reduces hair fall. No harmful chemicals.', price: 599, originalPrice: 849, discount: 29, image: '/assets/products/wow/red-onion-conditioner-300ml.jpg', affiliateUrl: '/go/IN2-BE-WOW-003', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.3, reviewCount: 38900, tags: ['Conditioner', 'Red Onion', 'WOW', 'Hair Fall', 'Argan Oil'], apiSource: 'static' },
  { id: 'IN2-BE-WOW-004', name: 'WOW Vitamin C Foaming Face Wash — 100ml', brand: 'WOW Skin Science', subBrand: 'Vitamin C', category: 'personal-care', subCategory: 'face-wash', variant: '100ml', description: 'WOW Vitamin C foaming face wash with niacinamide and hyaluronic acid. Brightens, cleanses and hydrates in one step.', price: 349, originalPrice: 499, discount: 30, image: '/assets/products/wow/vitc-foaming-facewash-100ml.jpg', affiliateUrl: '/go/IN2-BE-WOW-004', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: false, isTrending: true, rating: 4.3, reviewCount: 29800, tags: ['Vitamin C', 'Face Wash', 'WOW', 'Niacinamide', 'Brightening'], apiSource: 'static' },
]

// ─── PLUM (5) ────────────────────────────────────────────────────────────────

export const PLUM: IndiaProduct[] = [
  { id: 'IN2-BE-PLM-001', name: 'Plum Green Tea Renewed Clarity Night Gel — 50ml', brand: 'Plum', subBrand: 'Green Tea', category: 'personal-care', subCategory: 'moisturizer', variant: '50ml', description: "Plum Green Tea night gel with glycolic acid and niacinamide. Exfoliates while you sleep. Vegan, 100% cruelty-free.", price: 499, originalPrice: 699, discount: 29, image: '/assets/products/plum/green-tea-night-gel-50ml.jpg', affiliateUrl: '/go/IN2-BE-PLM-001', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: true, isTrending: true, rating: 4.4, reviewCount: 23400, tags: ['Night Gel', 'Green Tea', 'Plum', 'Glycolic Acid', 'Vegan'], apiSource: 'static' },
  { id: 'IN2-BE-PLM-002', name: 'Plum Bright Years Cell Renewal Serum — 30ml', brand: 'Plum', subBrand: 'Bright Years', category: 'personal-care', subCategory: 'serum', variant: '30ml', description: 'Plum Bright Years serum with retinol and vitamin C. Reduces fine lines and dark spots. Suitable for 30+ skin. Vegan.', price: 799, originalPrice: 1099, discount: 27, image: '/assets/products/plum/bright-years-serum-30ml.jpg', affiliateUrl: '/go/IN2-BE-PLM-002', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.4, reviewCount: 12300, tags: ['Serum', 'Retinol', 'Vitamin C', 'Plum', 'Anti-Aging'], apiSource: 'static' },
  { id: 'IN2-BE-PLM-003', name: 'Plum Wild Cherries & Vitamin C Face Wash — 100ml', brand: 'Plum', subBrand: 'Wild Cherries', category: 'personal-care', subCategory: 'face-wash', variant: '100ml', description: 'Plum face wash with wild cherry and Vitamin C. Brightens dull skin, gentle daily use. SLS-free, 100% vegan.', price: 299, originalPrice: 399, discount: 25, image: '/assets/products/plum/wild-cherries-vitc-facewash-100ml.jpg', affiliateUrl: '/go/IN2-BE-PLM-003', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.3, reviewCount: 18900, tags: ['Face Wash', 'Vitamin C', 'Plum', 'Brightening', 'SLS Free'], apiSource: 'static' },
  { id: 'IN2-BE-PLM-004', name: 'Plum Green Tea Mattifying Moisturizer SPF 35 — 75ml', brand: 'Plum', subBrand: 'Green Tea', category: 'personal-care', subCategory: 'moisturizer', variant: '75ml SPF 35', description: 'Plum Green Tea moisturizer with SPF 35 PA+++. Controls shine, lightweight formula. Perfect daily sunscreen-moisturizer for oily skin.', price: 549, originalPrice: 749, discount: 27, image: '/assets/products/plum/green-tea-moisturizer-spf35-75ml.jpg', affiliateUrl: '/go/IN2-BE-PLM-004', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: true, isTrending: true, rating: 4.4, reviewCount: 34500, tags: ['Moisturizer', 'SPF 35', 'Green Tea', 'Plum', 'Oily Skin'], apiSource: 'static' },
  { id: 'IN2-BE-PLM-005', name: 'Plum BodyLovin Vanilla Shea Body Butter — 250g', brand: 'Plum', subBrand: 'BodyLovin', category: 'personal-care', subCategory: 'body-care', variant: '250g', description: 'Plum BodyLovin body butter with shea butter and vanilla. Deep hydration lasting 24 hours. Non-greasy, vegan formula.', price: 549, originalPrice: 749, discount: 27, image: '/assets/products/plum/bodylovin-vanilla-shea-250g.jpg', affiliateUrl: '/go/IN2-BE-PLM-005', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.5, reviewCount: 9870, tags: ['Body Butter', 'Shea', 'Vanilla', 'Plum', 'Hydrating'], apiSource: 'static' },
]
