// lib/india-catalog-2/home-gadgets.ts
// 65 products: Home/Kitchen (Pigeon, Prestige, Milton, Borosil, Hawkins, Cello), Cameras (Canon, Sony), Tablets (Samsung, Lenovo), Smart TVs (Samsung, LG), Gaming (PlayStation), Sports (Nivia, Adidas), Baby (Pampers)
import type { IndiaProduct } from '@/lib/india-catalog/types'

// ─── PIGEON KITCHEN (5) ──────────────────────────────────────────────────────

export const PIGEON: IndiaProduct[] = [
  { id: 'IN2-HK-PIG-001', name: 'Pigeon Stainless Steel Pressure Cooker — 3 Litre', brand: 'Pigeon', subBrand: 'Pigeon Pressure Cookers', category: 'home-appliances', subCategory: 'pressure-cookers', variant: '3 Litre', description: 'Pigeon stainless steel pressure cooker with induction base. ISI certified, 5-year warranty. Healthy cooking with less oil.', price: 1299, originalPrice: 2199, discount: 41, image: '/assets/products/pigeon/ss-pressure-cooker-3l.jpg', affiliateUrl: '/go/IN2-HK-PIG-001', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: true, isTrending: false, rating: 4.3, reviewCount: 23400, tags: ['Pressure Cooker', 'Stainless Steel', 'Pigeon', 'Induction', 'ISI'], apiSource: 'static' },
  { id: 'IN2-HK-PIG-002', name: 'Pigeon By Stovekraft Hot Kettle 1.5L Electric', brand: 'Pigeon', subBrand: 'Pigeon Appliances', category: 'home-appliances', subCategory: 'kettles', variant: '1.5 Litre', description: 'Pigeon electric kettle 1.5L, 1500W, stainless steel interior. Auto shut-off, boil-dry protection. Perfect for chai and Maggi.', price: 699, originalPrice: 1199, discount: 42, image: '/assets/products/pigeon/hot-kettle-1.5l.jpg', affiliateUrl: '/go/IN2-HK-PIG-002', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: false, isTrending: true, rating: 4.2, reviewCount: 56700, tags: ['Kettle', 'Electric', 'Pigeon', '1500W', 'Auto Shut-Off'], apiSource: 'static' },
  { id: 'IN2-HK-PIG-003', name: 'Pigeon Sheen Non-Stick Kadai — 24cm with Lid', brand: 'Pigeon', subBrand: 'Pigeon Non-Stick', category: 'home-appliances', subCategory: 'cookware', variant: '24cm with Glass Lid', description: "Pigeon Sheen non-stick kadai with glass lid. PFOA-free coating, induction compatible. Easy to clean, even heat distribution.", price: 849, originalPrice: 1499, discount: 43, image: '/assets/products/pigeon/sheen-kadai-24cm.jpg', affiliateUrl: '/go/IN2-HK-PIG-003', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.1, reviewCount: 34500, tags: ['Kadai', 'Non-Stick', 'Pigeon', 'PFOA Free', 'Induction'], apiSource: 'static' },
  { id: 'IN2-HK-PIG-004', name: 'Pigeon Polypropylene Hand Blender 300W — White', brand: 'Pigeon', subBrand: 'Pigeon Appliances', category: 'home-appliances', subCategory: 'blenders', variant: 'White 300W', description: 'Pigeon 300W hand blender for soups, smoothies and milkshakes. Detachable blending shaft, easy cleaning. Compact design.', price: 799, originalPrice: 1499, discount: 47, image: '/assets/products/pigeon/hand-blender-300w-white.jpg', affiliateUrl: '/go/IN2-HK-PIG-004', affiliatePlatform: 'flipkart', affiliateSource: 'flipkart-affiliate-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.0, reviewCount: 18900, tags: ['Hand Blender', '300W', 'Pigeon', 'Smoothie', 'Compact'], apiSource: 'static' },
  { id: 'IN2-HK-PIG-005', name: 'Pigeon Non-Stick Flat Tawa — 27cm', brand: 'Pigeon', subBrand: 'Pigeon Non-Stick', category: 'home-appliances', subCategory: 'cookware', variant: '27cm', description: "Pigeon flat non-stick tawa for rotis and dosas. PFOA-free, induction and gas compatible. Bakelite handle stays cool.", price: 499, originalPrice: 899, discount: 44, image: '/assets/products/pigeon/non-stick-tawa-27cm.jpg', affiliateUrl: '/go/IN2-HK-PIG-005', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.1, reviewCount: 45600, tags: ['Tawa', 'Non-Stick', 'Pigeon', 'Roti', 'Induction'], apiSource: 'static' },
]

// ─── PRESTIGE (5) ────────────────────────────────────────────────────────────

export const PRESTIGE: IndiaProduct[] = [
  { id: 'IN2-HK-PRE-001', name: 'Prestige Deluxe Plus Aluminium Pressure Cooker — 5 Litre', brand: 'Prestige', subBrand: 'Prestige Deluxe Plus', category: 'home-appliances', subCategory: 'pressure-cookers', variant: '5 Litre Aluminium', description: 'Prestige Deluxe Plus pressure cooker with metallic safety plug. Gasket release system, hard anodised. ISI marked.', price: 1599, originalPrice: 2799, discount: 43, image: '/assets/products/prestige/deluxe-plus-5l.jpg', affiliateUrl: '/go/IN2-HK-PRE-001', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: true, isTrending: false, rating: 4.4, reviewCount: 45600, tags: ['Pressure Cooker', 'Aluminium', 'Prestige', 'ISI', '5 Litre'], apiSource: 'static' },
  { id: 'IN2-HK-PRE-002', name: 'Prestige Iris Induction Cooktop 1600W — Black', brand: 'Prestige', subBrand: 'Prestige Iris', category: 'home-appliances', subCategory: 'induction-cooktops', variant: 'Black 1600W', description: 'Prestige Iris induction cooktop with 8 pre-set menus. Glass ceramic plate, auto voltage regulator. BIS certified.', price: 2799, originalPrice: 4499, discount: 38, image: '/assets/products/prestige/iris-induction-1600w.jpg', affiliateUrl: '/go/IN2-HK-PRE-002', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: true, isTrending: true, rating: 4.3, reviewCount: 34500, tags: ['Induction Cooktop', '1600W', 'Prestige', 'BIS', '8 Menus'], apiSource: 'static' },
  { id: 'IN2-HK-PRE-003', name: 'Prestige Clip-On Stainless Steel Pressure Cooker — 5 Litre', brand: 'Prestige', subBrand: 'Prestige Clip-On', category: 'home-appliances', subCategory: 'pressure-cookers', variant: '5 Litre Stainless Steel', description: 'Prestige Clip-On pressure cooker with tri-ply base. Induction compatible, sturdy clip-on lid mechanism. ISI certified.', price: 3499, originalPrice: 5999, discount: 42, image: '/assets/products/prestige/clip-on-ss-5l.jpg', affiliateUrl: '/go/IN2-HK-PRE-003', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.5, reviewCount: 23400, tags: ['Pressure Cooker', 'Stainless Steel', 'Prestige', 'Clip-On', 'Induction'], apiSource: 'static' },
  { id: 'IN2-HK-PRE-004', name: 'Prestige PGMFD Mixer Grinder 750W — 3 Jars', brand: 'Prestige', subBrand: 'Prestige Mixer', category: 'home-appliances', subCategory: 'mixer-grinders', variant: '750W 3 Jars', description: 'Prestige 750W mixer grinder with 3 SS jars. Copper motor, powerful blending and grinding. 5-year motor warranty.', price: 3299, originalPrice: 5499, discount: 40, image: '/assets/products/prestige/mixer-750w-3jar.jpg', affiliateUrl: '/go/IN2-HK-PRE-004', affiliatePlatform: 'flipkart', affiliateSource: 'flipkart-affiliate-free', inStock: true, isFeatured: true, isTrending: false, rating: 4.3, reviewCount: 67800, tags: ['Mixer Grinder', '750W', 'Prestige', '3 Jars', 'Copper Motor'], apiSource: 'static' },
  { id: 'IN2-HK-PRE-005', name: 'Prestige Dura Non-Stick Kadai 25cm — Black', brand: 'Prestige', subBrand: 'Prestige Dura', category: 'home-appliances', subCategory: 'cookware', variant: '25cm Black', description: 'Prestige Dura hard anodised kadai with 3-layer non-stick coating. Induction base, scratch-resistant. Superior durability.', price: 1399, originalPrice: 2499, discount: 44, image: '/assets/products/prestige/dura-kadai-25cm.jpg', affiliateUrl: '/go/IN2-HK-PRE-005', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.4, reviewCount: 18900, tags: ['Kadai', 'Hard Anodised', 'Prestige', 'Dura', 'Induction'], apiSource: 'static' },
]

// ─── MILTON (5) ──────────────────────────────────────────────────────────────

export const MILTON: IndiaProduct[] = [
  { id: 'IN2-HK-MIL-001', name: 'Milton Thermosteel Flip Lid Bottle 500ml — Silver', brand: 'Milton', subBrand: 'Thermosteel', category: 'home-appliances', subCategory: 'water-bottles', variant: 'Silver 500ml', description: 'Milton Thermosteel bottle keeps hot 24 hours and cold 48 hours. SS 304 inner, no plastic contact. Leak-proof flip lid.', price: 699, originalPrice: 1199, discount: 42, image: '/assets/products/milton/thermosteel-flip-500ml-silver.jpg', affiliateUrl: '/go/IN2-HK-MIL-001', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: true, isTrending: true, rating: 4.5, reviewCount: 89000, tags: ['Water Bottle', 'Thermosteel', 'Milton', 'Insulated', '24 Hours Hot'], apiSource: 'static' },
  { id: 'IN2-HK-MIL-002', name: 'Milton Thermosteel 24 Hrs Bottle 1 Litre — Blue', brand: 'Milton', subBrand: 'Thermosteel', category: 'home-appliances', subCategory: 'water-bottles', variant: 'Blue 1 Litre', description: 'Milton 1L Thermosteel bottle for all-day hydration. Hot 24h, cold 48h. SS 304 inner, wide mouth for ice cubes.', price: 999, originalPrice: 1699, discount: 41, image: '/assets/products/milton/thermosteel-1l-blue.jpg', affiliateUrl: '/go/IN2-HK-MIL-002', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: false, isTrending: true, rating: 4.5, reviewCount: 56700, tags: ['Water Bottle', 'Thermosteel', '1 Litre', 'Milton', 'Wide Mouth'], apiSource: 'static' },
  { id: 'IN2-HK-MIL-003', name: 'Milton Cube 900 Lunch Box — 3 Containers', brand: 'Milton', subBrand: 'Milton Lunch Box', category: 'home-appliances', subCategory: 'lunch-boxes', variant: '3 Containers', description: 'Milton Cube insulated lunch box with 3 steel containers. Keeps food hot up to 3 hours. BPA-free outer shell.', price: 899, originalPrice: 1499, discount: 40, image: '/assets/products/milton/cube-900-lunch-3container.jpg', affiliateUrl: '/go/IN2-HK-MIL-003', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.3, reviewCount: 34500, tags: ['Lunch Box', 'Insulated', 'Milton', '3 Containers', 'BPA Free'], apiSource: 'static' },
  { id: 'IN2-HK-MIL-004', name: 'Milton Steel Lunch Box Executive — 3 Container', brand: 'Milton', subBrand: 'Milton Steel', category: 'home-appliances', subCategory: 'lunch-boxes', variant: '3 Container Steel', description: 'Milton stainless steel lunch box with 3 containers. Leakproof, microwave safe (without lid). Office and school carry.', price: 699, originalPrice: 1199, discount: 42, image: '/assets/products/milton/steel-lunch-3container.jpg', affiliateUrl: '/go/IN2-HK-MIL-004', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.2, reviewCount: 23400, tags: ['Lunch Box', 'Stainless Steel', 'Milton', 'Leakproof', 'Office'], apiSource: 'static' },
  { id: 'IN2-HK-MIL-005', name: 'Milton Casserole Dish 1500ml — Red', brand: 'Milton', subBrand: 'Milton Casserole', category: 'home-appliances', subCategory: 'casseroles', variant: 'Red 1500ml', description: 'Milton insulated casserole with SS inner pot. Keeps food hot for 6 hours. Ideal for dals, curries and rice.', price: 599, originalPrice: 999, discount: 40, image: '/assets/products/milton/casserole-1500ml-red.jpg', affiliateUrl: '/go/IN2-HK-MIL-005', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.2, reviewCount: 18900, tags: ['Casserole', 'Insulated', 'Milton', '6 Hours Hot', 'Steel'], apiSource: 'static' },
]

// ─── BOROSIL (5) ─────────────────────────────────────────────────────────────

export const BOROSIL: IndiaProduct[] = [
  { id: 'IN2-HK-BOR-001', name: 'Borosil Vision Glass Straight 205ml — Set of 6', brand: 'Borosil', subBrand: 'Vision Glass', category: 'home-appliances', subCategory: 'glassware', variant: 'Set of 6 205ml', description: 'Borosil Vision glasses made from high-quality borosilicate glass. Microwave and dishwasher safe. Shock resistant.', price: 499, originalPrice: 849, discount: 41, image: '/assets/products/borosil/vision-glass-205ml-6pc.jpg', affiliateUrl: '/go/IN2-HK-BOR-001', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: true, isTrending: false, rating: 4.5, reviewCount: 67800, tags: ['Glasses', 'Borosilicate', 'Borosil', 'Microwave Safe', 'Set of 6'], apiSource: 'static' },
  { id: 'IN2-HK-BOR-002', name: 'Borosil Microwaveable Glass Mixing Bowl 500ml', brand: 'Borosil', subBrand: 'Borosil Mixing Bowls', category: 'home-appliances', subCategory: 'cookware', variant: '500ml', description: 'Borosil borosilicate glass mixing bowl. Microwave, oven and freezer safe. Ideal for baking, mixing and serving.', price: 349, originalPrice: 599, discount: 42, image: '/assets/products/borosil/mixing-bowl-500ml.jpg', affiliateUrl: '/go/IN2-HK-BOR-002', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.4, reviewCount: 34500, tags: ['Mixing Bowl', 'Glass', 'Borosil', 'Microwave Safe', 'Baking'], apiSource: 'static' },
  { id: 'IN2-HK-BOR-003', name: 'Borosil Stainless Steel Lunch Box — 3 Tier', brand: 'Borosil', subBrand: 'Borosil Carry Fresh', category: 'home-appliances', subCategory: 'lunch-boxes', variant: '3 Tier', description: 'Borosil 3-tier steel lunch box with insulated bag. Keeps food hot for 2.5 hours. Leakproof, airtight containers.', price: 1299, originalPrice: 2199, discount: 41, image: '/assets/products/borosil/steel-lunch-3tier.jpg', affiliateUrl: '/go/IN2-HK-BOR-003', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.3, reviewCount: 18900, tags: ['Lunch Box', 'Stainless Steel', 'Borosil', '3 Tier', 'Insulated'], apiSource: 'static' },
  { id: 'IN2-HK-BOR-004', name: 'Borosil Krystal Glass Storage Jar 1000ml — Clear', brand: 'Borosil', subBrand: 'Krystal', category: 'home-appliances', subCategory: 'storage', variant: '1000ml Clear', description: "Borosil Krystal glass jar with airtight metal lid. Borosilicate glass, safe for refrigerator. Perfect for spices and grains.", price: 299, originalPrice: 499, discount: 40, image: '/assets/products/borosil/krystal-jar-1000ml.jpg', affiliateUrl: '/go/IN2-HK-BOR-004', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.4, reviewCount: 23400, tags: ['Storage Jar', 'Glass', 'Borosil', 'Airtight', 'Fridge Safe'], apiSource: 'static' },
  { id: 'IN2-HK-BOR-005', name: 'Borosil Classic Casserole 1500ml — Blue', brand: 'Borosil', subBrand: 'Borosil Classic', category: 'home-appliances', subCategory: 'casseroles', variant: 'Blue 1500ml', description: 'Borosil insulated casserole with SS inner container. Keeps food hot for 4 hours. Suitable for dal, sabzi, biriyani.', price: 799, originalPrice: 1299, discount: 38, image: '/assets/products/borosil/classic-casserole-1500ml-blue.jpg', affiliateUrl: '/go/IN2-HK-BOR-005', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.3, reviewCount: 12300, tags: ['Casserole', 'Insulated', 'Borosil', 'Blue', 'Hot Food'], apiSource: 'static' },
]

// ─── HAWKINS (5) ─────────────────────────────────────────────────────────────

export const HAWKINS: IndiaProduct[] = [
  { id: 'IN2-HK-HAW-001', name: 'Hawkins Contura Pressure Cooker — 5 Litre', brand: 'Hawkins', subBrand: 'Hawkins Contura', category: 'home-appliances', subCategory: 'pressure-cookers', variant: '5 Litre', description: 'Hawkins Contura aluminium pressure cooker with unique curved body for easier washing. Metallic safety plug, ISI marked.', price: 2299, originalPrice: 3799, discount: 39, image: '/assets/products/hawkins/contura-5l.jpg', affiliateUrl: '/go/IN2-HK-HAW-001', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: true, isTrending: false, rating: 4.5, reviewCount: 34500, tags: ['Pressure Cooker', 'Hawkins', 'Contura', 'ISI', '5 Litre'], apiSource: 'static' },
  { id: 'IN2-HK-HAW-002', name: 'Hawkins Classic Aluminium Pressure Cooker — 3 Litre', brand: 'Hawkins', subBrand: 'Hawkins Classic', category: 'home-appliances', subCategory: 'pressure-cookers', variant: '3 Litre Aluminium', description: 'Hawkins Classic pressure cooker since 1959. Hard body aluminium, extra thick base, gasket release system.', price: 1399, originalPrice: 2299, discount: 39, image: '/assets/products/hawkins/classic-3l.jpg', affiliateUrl: '/go/IN2-HK-HAW-002', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.5, reviewCount: 56700, tags: ['Pressure Cooker', 'Hawkins', 'Classic', 'Aluminium', '3 Litre'], apiSource: 'static' },
  { id: 'IN2-HK-HAW-003', name: 'Hawkins Stainless Steel Pressure Cooker — 5 Litre', brand: 'Hawkins', subBrand: 'Hawkins Stainless', category: 'home-appliances', subCategory: 'pressure-cookers', variant: '5 Litre Stainless Steel', description: 'Hawkins SS pressure cooker with induction base. Mirror finish, easy to clean. Pressure regulator and safety valve.', price: 3999, originalPrice: 6499, discount: 38, image: '/assets/products/hawkins/stainless-5l.jpg', affiliateUrl: '/go/IN2-HK-HAW-003', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.5, reviewCount: 23400, tags: ['Pressure Cooker', 'Stainless Steel', 'Hawkins', 'Induction', 'Mirror Finish'], apiSource: 'static' },
  { id: 'IN2-HK-HAW-004', name: 'Hawkins Futura Non-Stick Frying Pan 26cm', brand: 'Hawkins', subBrand: 'Futura', category: 'home-appliances', subCategory: 'cookware', variant: '26cm Non-Stick', description: "Hawkins Futura hard anodised non-stick frying pan. PFOA-free, scratch-resistant. Even heat distribution, induction compatible.", price: 1299, originalPrice: 2199, discount: 41, image: '/assets/products/hawkins/futura-frying-pan-26cm.jpg', affiliateUrl: '/go/IN2-HK-HAW-004', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.4, reviewCount: 18900, tags: ['Frying Pan', 'Non-Stick', 'Hawkins', 'Futura', 'Induction'], apiSource: 'static' },
  { id: 'IN2-HK-HAW-005', name: "Hawkins Miss Mary Aluminium Pressure Cooker — 3 Litre", brand: 'Hawkins', subBrand: 'Miss Mary', category: 'home-appliances', subCategory: 'pressure-cookers', variant: '3 Litre', description: "Hawkins Miss Mary small pressure cooker for 1-2 persons. Polished aluminium, safety plug. Quick cooking, easy to carry.", price: 1099, originalPrice: 1799, discount: 39, image: '/assets/products/hawkins/miss-mary-3l.jpg', affiliateUrl: '/go/IN2-HK-HAW-005', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.4, reviewCount: 23400, tags: ['Pressure Cooker', 'Miss Mary', 'Hawkins', 'Small', 'Aluminium'], apiSource: 'static' },
]

// ─── CELLO (5) ───────────────────────────────────────────────────────────────

export const CELLO: IndiaProduct[] = [
  { id: 'IN2-HK-CEL-001', name: 'Cello Max Fresh Whirl Lunch Box — 3 Containers', brand: 'Cello', subBrand: 'Max Fresh', category: 'home-appliances', subCategory: 'lunch-boxes', variant: '3 Containers', description: 'Cello Max Fresh 3-container lunch box with twist-lock lids. BPA-free plastic, microwave safe. Keeps food fresh and leak-proof.', price: 399, originalPrice: 699, discount: 43, image: '/assets/products/cello/max-fresh-whirl-3container.jpg', affiliateUrl: '/go/IN2-HK-CEL-001', affiliatePlatform: 'flipkart', affiliateSource: 'flipkart-affiliate-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.1, reviewCount: 34500, tags: ['Lunch Box', 'BPA Free', 'Cello', 'Microwave Safe', 'Leakproof'], apiSource: 'static' },
  { id: 'IN2-HK-CEL-002', name: 'Cello Opalware Dazzle Soup Bowl — Set of 6', brand: 'Cello', subBrand: 'Opalware Dazzle', category: 'home-appliances', subCategory: 'glassware', variant: 'Set of 6', description: 'Cello Opalware soup bowls in white with elegant design. Microwave safe, scratch-resistant. Dishwasher-friendly.', price: 499, originalPrice: 899, discount: 44, image: '/assets/products/cello/opalware-soup-bowl-6pc.jpg', affiliateUrl: '/go/IN2-HK-CEL-002', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.2, reviewCount: 18900, tags: ['Soup Bowl', 'Opalware', 'Cello', 'Set of 6', 'Microwave Safe'], apiSource: 'static' },
  { id: 'IN2-HK-CEL-003', name: 'Cello Plastic Airtight Storage Container Set — 6 Piece', brand: 'Cello', subBrand: 'Cello Fresh', category: 'home-appliances', subCategory: 'storage', variant: '6-Piece Set', description: 'Cello airtight storage containers in assorted sizes. BPA-free, click-lock lids. For dal, atta, rice and kitchen storage.', price: 449, originalPrice: 799, discount: 44, image: '/assets/products/cello/airtight-storage-6pc.jpg', affiliateUrl: '/go/IN2-HK-CEL-003', affiliatePlatform: 'flipkart', affiliateSource: 'flipkart-affiliate-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.1, reviewCount: 23400, tags: ['Storage Container', 'Airtight', 'Cello', 'BPA Free', 'Kitchen'], apiSource: 'static' },
  { id: 'IN2-HK-CEL-004', name: 'Cello Stainless Steel Water Bottle 1L — Blue', brand: 'Cello', subBrand: 'Cello Homeware', category: 'home-appliances', subCategory: 'water-bottles', variant: 'Blue 1 Litre', description: 'Cello stainless steel water bottle, BPA-free, rust-resistant. Wide mouth, easy to clean. Suitable for school and gym.', price: 349, originalPrice: 599, discount: 42, image: '/assets/products/cello/ss-water-bottle-1l-blue.jpg', affiliateUrl: '/go/IN2-HK-CEL-004', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.1, reviewCount: 12300, tags: ['Water Bottle', 'Stainless Steel', 'Cello', 'Blue', 'School'], apiSource: 'static' },
  { id: 'IN2-HK-CEL-005', name: 'Cello Plastic Airtight Storage Jars — Set of 3', brand: 'Cello', subBrand: 'Cello Checkers', category: 'home-appliances', subCategory: 'storage', variant: 'Set of 3', description: 'Cello transparent storage jars with airtight lids. See-through body to identify contents. Fridge and pantry safe.', price: 249, originalPrice: 449, discount: 44, image: '/assets/products/cello/airtight-jars-3pc.jpg', affiliateUrl: '/go/IN2-HK-CEL-005', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.0, reviewCount: 9870, tags: ['Storage Jars', 'Transparent', 'Cello', 'Airtight', 'Fridge Safe'], apiSource: 'static' },
]

// ─── CANON CAMERAS (4) ───────────────────────────────────────────────────────

export const CANON: IndiaProduct[] = [
  { id: 'IN2-CAM-CAN-001', name: 'Canon EOS 1500D DSLR Camera — 18-55mm Lens Kit', brand: 'Canon', subBrand: 'EOS', category: 'electronics', subCategory: 'cameras', variant: '18-55mm Lens Kit', description: "Canon EOS 1500D 24.1MP DSLR with 18-55mm IS II lens. Wi-Fi and NFC enabled. Perfect entry-level DSLR for India's beginners.", price: 29999, originalPrice: 44999, discount: 33, image: '/assets/products/canon/eos-1500d-kit-18-55.jpg', affiliateUrl: '/go/IN2-CAM-CAN-001', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: true, isTrending: true, rating: 4.5, reviewCount: 23400, tags: ['DSLR', 'Canon', 'EOS', '24MP', 'Wi-Fi'], apiSource: 'static' },
  { id: 'IN2-CAM-CAN-002', name: 'Canon PowerShot SX430 IS Digital Camera — Black', brand: 'Canon', subBrand: 'PowerShot', category: 'electronics', subCategory: 'cameras', variant: 'Black', description: 'Canon PowerShot SX430 IS with 45x optical zoom, 20MP sensor. Shoot from ultra-wide to super-telephoto. Built-in Wi-Fi.', price: 19999, originalPrice: 29999, discount: 33, image: '/assets/products/canon/powershot-sx430-black.jpg', affiliateUrl: '/go/IN2-CAM-CAN-002', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.3, reviewCount: 12300, tags: ['Point & Shoot', 'Canon', '45x Zoom', '20MP', 'Wi-Fi'], apiSource: 'static' },
  { id: 'IN2-CAM-CAN-003', name: 'Canon EOS M50 Mark II Mirrorless Camera — Body', brand: 'Canon', subBrand: 'EOS M', category: 'electronics', subCategory: 'cameras', variant: 'Body Only Black', description: 'Canon EOS M50 Mark II mirrorless camera with 24.1MP APS-C sensor. 4K video, Eye Detect AF, vertical video. Compact mirrorless.', price: 49999, originalPrice: 69999, discount: 29, image: '/assets/products/canon/eos-m50-mark2-black.jpg', affiliateUrl: '/go/IN2-CAM-CAN-003', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: true, isTrending: false, rating: 4.5, reviewCount: 9870, tags: ['Mirrorless', 'Canon', 'M50', '4K', 'APS-C'], apiSource: 'static' },
  { id: 'IN2-CAM-CAN-004', name: 'Canon IXUS 185 Point & Shoot Camera — Red', brand: 'Canon', subBrand: 'IXUS', category: 'electronics', subCategory: 'cameras', variant: 'Red', description: 'Canon IXUS 185 with 20MP CCD sensor and 8x optical zoom. Simple, affordable point-and-shoot. Perfect for beginners and travel.', price: 9999, originalPrice: 14999, discount: 33, image: '/assets/products/canon/ixus-185-red.jpg', affiliateUrl: '/go/IN2-CAM-CAN-004', affiliatePlatform: 'flipkart', affiliateSource: 'flipkart-affiliate-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.2, reviewCount: 7650, tags: ['Point & Shoot', 'IXUS', 'Canon', '20MP', 'Travel'], apiSource: 'static' },
]

// ─── SONY CAMERAS (4) ────────────────────────────────────────────────────────

export const SONY_CAMERAS: IndiaProduct[] = [
  { id: 'IN2-CAM-SON-001', name: 'Sony Alpha ZV-E10 Mirrorless Camera — 16-50mm Kit', brand: 'Sony', subBrand: 'Alpha ZV', category: 'electronics', subCategory: 'cameras', variant: '16-50mm Kit Black', description: "Sony ZV-E10 APS-C vlogging camera with 24.2MP sensor. Interchangeable lens, 4K video, product showcase mode. YouTuber's choice.", price: 54990, originalPrice: 79990, discount: 31, image: '/assets/products/sony/zv-e10-black-kit.jpg', affiliateUrl: '/go/IN2-CAM-SON-001', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: true, isTrending: true, rating: 4.6, reviewCount: 12300, tags: ['Mirrorless', 'Sony', 'ZV-E10', 'Vlog', '4K'], apiSource: 'static' },
  { id: 'IN2-CAM-SON-002', name: 'Sony Cyber-shot DSC-W830 Point & Shoot — Silver', brand: 'Sony', subBrand: 'Cyber-shot', category: 'electronics', subCategory: 'cameras', variant: 'Silver', description: 'Sony Cyber-shot W830 with 20.1MP CCD and 8x optical zoom. Super HAD CCD sensor, SteadyShot stabilization. Slim and lightweight.', price: 9490, originalPrice: 13490, discount: 30, image: '/assets/products/sony/cybershot-w830-silver.jpg', affiliateUrl: '/go/IN2-CAM-SON-002', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.2, reviewCount: 8760, tags: ['Point & Shoot', 'Sony', 'Cyber-shot', '20MP', 'SteadyShot'], apiSource: 'static' },
  { id: 'IN2-CAM-SON-003', name: 'Sony Alpha ILCE-6400 APS-C Mirrorless — Body', brand: 'Sony', subBrand: 'Alpha', category: 'electronics', subCategory: 'cameras', variant: 'Body Only Black', description: 'Sony a6400 with world-fastest 0.02s AF, 24.2MP APS-C sensor, 4K HDR video. Real-time tracking, Eye AF. Pro mirrorless.', price: 79990, originalPrice: 109990, discount: 27, image: '/assets/products/sony/a6400-body-black.jpg', affiliateUrl: '/go/IN2-CAM-SON-003', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: true, isTrending: false, rating: 4.7, reviewCount: 9870, tags: ['Mirrorless', 'Sony', 'a6400', 'Eye AF', '4K HDR'], apiSource: 'static' },
  { id: 'IN2-CAM-SON-004', name: 'Sony Action Cam HDR-AS50 Full HD — Black', brand: 'Sony', subBrand: 'Action Cam', category: 'electronics', subCategory: 'cameras', variant: 'Black', description: 'Sony HDR-AS50 action cam with ZEISS Tessar lens, 11.1MP, 1080p 60fps. SteadyShot image stabilization. Waterproof with housing.', price: 14990, originalPrice: 21990, discount: 32, image: '/assets/products/sony/hdr-as50-black.jpg', affiliateUrl: '/go/IN2-CAM-SON-004', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.3, reviewCount: 6540, tags: ['Action Cam', 'Sony', 'Full HD', 'ZEISS', 'Waterproof'], apiSource: 'static' },
]

// ─── SAMSUNG TABLETS (4) ─────────────────────────────────────────────────────

export const SAMSUNG_TABLETS: IndiaProduct[] = [
  { id: 'IN2-TAB-SAM-001', name: 'Samsung Galaxy Tab A8 10.5" 64GB — Grey', brand: 'Samsung', subBrand: 'Galaxy Tab A', category: 'electronics', subCategory: 'tablets', variant: 'Grey 64GB Wi-Fi', description: "Samsung Galaxy Tab A8 with 10.5'' TFT display, Unisoc T618 processor, 64GB storage. Multi-window, Dolby Atmos audio.", price: 17999, originalPrice: 24999, discount: 28, image: '/assets/products/samsung/tab-a8-grey-64gb.jpg', affiliateUrl: '/go/IN2-TAB-SAM-001', affiliatePlatform: 'flipkart', affiliateSource: 'flipkart-affiliate-free', inStock: true, isFeatured: true, isTrending: true, rating: 4.3, reviewCount: 18900, tags: ['Tablet', 'Samsung', 'Tab A8', '64GB', 'Dolby Atmos'], apiSource: 'static' },
  { id: 'IN2-TAB-SAM-002', name: 'Samsung Galaxy Tab S6 Lite 10.4" 64GB — Oxford Gray', brand: 'Samsung', subBrand: 'Galaxy Tab S', category: 'electronics', subCategory: 'tablets', variant: 'Oxford Gray 64GB', description: "Samsung Galaxy Tab S6 Lite with S Pen included. 10.4'' LCD, Exynos 9611, 4GB RAM. For notes, sketching and entertainment.", price: 24999, originalPrice: 36999, discount: 32, image: '/assets/products/samsung/tab-s6-lite-gray.jpg', affiliateUrl: '/go/IN2-TAB-SAM-002', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: true, isTrending: false, rating: 4.4, reviewCount: 14500, tags: ['Tablet', 'Samsung', 'Tab S6 Lite', 'S Pen', 'Exynos'], apiSource: 'static' },
  { id: 'IN2-TAB-SAM-003', name: 'Samsung Galaxy Tab A7 Lite 8.7" 32GB — Grey', brand: 'Samsung', subBrand: 'Galaxy Tab A', category: 'electronics', subCategory: 'tablets', variant: 'Grey 32GB LTE', description: "Samsung Galaxy Tab A7 Lite with 8.7'' display and LTE connectivity. MediaTek Helio P22T, metal body. Kids and travel tablet.", price: 13999, originalPrice: 19999, discount: 30, image: '/assets/products/samsung/tab-a7-lite-grey.jpg', affiliateUrl: '/go/IN2-TAB-SAM-003', affiliatePlatform: 'flipkart', affiliateSource: 'flipkart-affiliate-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.2, reviewCount: 9870, tags: ['Tablet', 'Samsung', 'Tab A7 Lite', 'LTE', 'Kids'], apiSource: 'static' },
  { id: 'IN2-TAB-SAM-004', name: 'Samsung Galaxy Tab S9 FE 10.9" 128GB — Gray', brand: 'Samsung', subBrand: 'Galaxy Tab S', category: 'electronics', subCategory: 'tablets', variant: 'Gray 128GB Wi-Fi', description: "Samsung Tab S9 FE with 10.9'' 90Hz display, IP68 water resistance, 128GB, Exynos 1380. S Pen included. Premium mid-range.", price: 36999, originalPrice: 54999, discount: 33, image: '/assets/products/samsung/tab-s9-fe-gray.jpg', affiliateUrl: '/go/IN2-TAB-SAM-004', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: true, isTrending: true, rating: 4.5, reviewCount: 8760, tags: ['Tablet', 'Samsung', 'Tab S9 FE', 'IP68', 'S Pen', '90Hz'], apiSource: 'static' },
]

// ─── LENOVO TABLETS (3) ──────────────────────────────────────────────────────

export const LENOVO_TABLETS: IndiaProduct[] = [
  { id: 'IN2-TAB-LEN-001', name: 'Lenovo Tab M10 Plus FHD 10.3" 64GB — Grey', brand: 'Lenovo', subBrand: 'Tab M', category: 'electronics', subCategory: 'tablets', variant: 'Grey 64GB Wi-Fi', description: "Lenovo Tab M10 Plus with 10.3'' FHD display, Helio P22T, 4GB RAM, 64GB storage. Dual speakers. Budget family tablet.", price: 14999, originalPrice: 21999, discount: 32, image: '/assets/products/lenovo/tab-m10-plus-grey.jpg', affiliateUrl: '/go/IN2-TAB-LEN-001', affiliatePlatform: 'flipkart', affiliateSource: 'flipkart-affiliate-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.2, reviewCount: 12300, tags: ['Tablet', 'Lenovo', 'Tab M10', '64GB', 'FHD'], apiSource: 'static' },
  { id: 'IN2-TAB-LEN-002', name: 'Lenovo Tab P11 2nd Gen 11.5" 128GB — Storm Grey', brand: 'Lenovo', subBrand: 'Tab P', category: 'electronics', subCategory: 'tablets', variant: 'Storm Grey 128GB', description: "Lenovo Tab P11 Gen 2 with 11.5'' 2K display, MediaTek Helio G99, 128GB. Quad JBL speakers. Best value productivity tablet.", price: 22999, originalPrice: 34999, discount: 34, image: '/assets/products/lenovo/tab-p11-gen2-grey.jpg', affiliateUrl: '/go/IN2-TAB-LEN-002', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: true, isTrending: false, rating: 4.4, reviewCount: 7650, tags: ['Tablet', 'Lenovo', 'Tab P11', '2K', 'JBL', '128GB'], apiSource: 'static' },
  { id: 'IN2-TAB-LEN-003', name: 'Lenovo IdeaPad Duet Chromebook 10.1" — 4GB/64GB', brand: 'Lenovo', subBrand: 'IdeaPad Duet', category: 'electronics', subCategory: 'tablets', variant: '4GB+64GB Chrome OS', description: "Lenovo Duet Chromebook with detachable keyboard and kickstand cover. 10.1'' FHD IPS, MediaTek Helio P60T. 2-in-1 student device.", price: 27990, originalPrice: 39990, discount: 30, image: '/assets/products/lenovo/ideapad-duet-chromebook.jpg', affiliateUrl: '/go/IN2-TAB-LEN-003', affiliatePlatform: 'flipkart', affiliateSource: 'flipkart-affiliate-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.3, reviewCount: 5670, tags: ['Chromebook', 'Lenovo', 'Duet', '2-in-1', 'Chrome OS', 'Student'], apiSource: 'static' },
]

// ─── SAMSUNG SMART TVs (4) ───────────────────────────────────────────────────

export const SAMSUNG_TVS: IndiaProduct[] = [
  { id: 'IN2-TV-SAM-001', name: 'Samsung 43" Crystal 4K UHD Smart TV 2024 — Black', brand: 'Samsung', subBrand: 'Crystal 4K', category: 'electronics', subCategory: 'smart-tvs', variant: '43 inch 4K', description: "Samsung 43'' Crystal 4K UHD TV with HDR10+, Crystal Processor 4K, PurColor technology. Tizen OS, built-in Alexa.", price: 29999, originalPrice: 44999, discount: 33, image: '/assets/products/samsung/crystal-4k-43-2024.jpg', affiliateUrl: '/go/IN2-TV-SAM-001', affiliatePlatform: 'flipkart', affiliateSource: 'flipkart-affiliate-free', inStock: true, isFeatured: true, isTrending: true, rating: 4.4, reviewCount: 23400, tags: ['Smart TV', 'Samsung', '43 inch', '4K UHD', 'Alexa', 'HDR10+'], apiSource: 'static' },
  { id: 'IN2-TV-SAM-002', name: 'Samsung 55" Crystal 4K UHD Smart TV 2024 — Black', brand: 'Samsung', subBrand: 'Crystal 4K', category: 'electronics', subCategory: 'smart-tvs', variant: '55 inch 4K', description: "Samsung 55'' Crystal 4K UHD with Object Tracking Sound Lite, Motion Xcelerator, 3 HDMI ports. Tizen smart platform.", price: 44999, originalPrice: 69999, discount: 36, image: '/assets/products/samsung/crystal-4k-55-2024.jpg', affiliateUrl: '/go/IN2-TV-SAM-002', affiliatePlatform: 'flipkart', affiliateSource: 'flipkart-affiliate-free', inStock: true, isFeatured: true, isTrending: false, rating: 4.5, reviewCount: 18900, tags: ['Smart TV', 'Samsung', '55 inch', '4K UHD', 'Motion Xcelerator', 'Tizen'], apiSource: 'static' },
  { id: 'IN2-TV-SAM-003', name: 'Samsung 32" HD Smart TV 2024 — Black', brand: 'Samsung', subBrand: 'Samsung Smart TV', category: 'electronics', subCategory: 'smart-tvs', variant: '32 inch HD', description: "Samsung 32'' HD Ready Smart TV with 1.5GB RAM and 8GB storage. PurColor display, Tizen OS. Perfect for bedroom.", price: 15999, originalPrice: 24999, discount: 36, image: '/assets/products/samsung/hd-smart-32-2024.jpg', affiliateUrl: '/go/IN2-TV-SAM-003', affiliatePlatform: 'flipkart', affiliateSource: 'flipkart-affiliate-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.2, reviewCount: 34500, tags: ['Smart TV', 'Samsung', '32 inch', 'HD Ready', 'Tizen', 'Bedroom TV'], apiSource: 'static' },
  { id: 'IN2-TV-SAM-004', name: 'Samsung 50" BU8000 Crystal UHD 4K Smart TV — Black', brand: 'Samsung', subBrand: 'BU8000', category: 'electronics', subCategory: 'smart-tvs', variant: '50 inch 4K', description: "Samsung BU8000 50'' 4K Crystal UHD with AirSlim design, Dynamic Crystal Color, Supreme UHD Dimming. Gaming-ready 2 HDMI 2.0.", price: 38999, originalPrice: 59999, discount: 35, image: '/assets/products/samsung/bu8000-50.jpg', affiliateUrl: '/go/IN2-TV-SAM-004', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: false, isTrending: true, rating: 4.4, reviewCount: 12300, tags: ['Smart TV', 'Samsung', '50 inch', '4K', 'AirSlim', 'Gaming'], apiSource: 'static' },
]

// ─── LG SMART TVs (3) ────────────────────────────────────────────────────────

export const LG_TVS: IndiaProduct[] = [
  { id: 'IN2-TV-LG-001', name: 'LG 43" 4K UHD Smart TV with AI ThinQ — Black', brand: 'LG', subBrand: 'LG UHD', category: 'electronics', subCategory: 'smart-tvs', variant: '43 inch 4K', description: "LG 43'' UHD 4K Smart TV with AI ThinQ, HDR10 Pro, α5 Gen5 AI Processor. webOS 22, built-in Google Assistant and Alexa.", price: 32999, originalPrice: 49999, discount: 34, image: '/assets/products/lg/4k-uq75-43.jpg', affiliateUrl: '/go/IN2-TV-LG-001', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: true, isTrending: false, rating: 4.4, reviewCount: 18900, tags: ['Smart TV', 'LG', '43 inch', '4K UHD', 'AI ThinQ', 'webOS'], apiSource: 'static' },
  { id: 'IN2-TV-LG-002', name: 'LG 32" HD Ready Smart TV — Black', brand: 'LG', subBrand: 'LG Smart TV', category: 'electronics', subCategory: 'smart-tvs', variant: '32 inch HD Ready', description: "LG 32'' HD Ready Smart TV with webOS 22. Built-in Alexa, HDR10, Magic Remote compatible. Compact smart TV for bedroom or kitchen.", price: 17999, originalPrice: 27999, discount: 36, image: '/assets/products/lg/hd-smart-32.jpg', affiliateUrl: '/go/IN2-TV-LG-002', affiliatePlatform: 'flipkart', affiliateSource: 'flipkart-affiliate-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.3, reviewCount: 23400, tags: ['Smart TV', 'LG', '32 inch', 'HD Ready', 'webOS', 'Alexa'], apiSource: 'static' },
  { id: 'IN2-TV-LG-003', name: 'LG 55" 4K UHD Smart TV NanoCell — Black', brand: 'LG', subBrand: 'LG NanoCell', category: 'electronics', subCategory: 'smart-tvs', variant: '55 inch 4K NanoCell', description: "LG 55'' NanoCell 4K Smart TV with Nano Color technology for more vivid colors. α7 Gen5 AI Processor, FILMMAKER MODE.", price: 54999, originalPrice: 84999, discount: 35, image: '/assets/products/lg/nanocell-55.jpg', affiliateUrl: '/go/IN2-TV-LG-003', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: true, isTrending: true, rating: 4.5, reviewCount: 12300, tags: ['Smart TV', 'LG', '55 inch', 'NanoCell', '4K', 'FILMMAKER'], apiSource: 'static' },
]

// ─── PLAYSTATION GAMING (3) ──────────────────────────────────────────────────

export const PLAYSTATION: IndiaProduct[] = [
  { id: 'IN2-GAM-SON-001', name: 'Sony DualSense Wireless Controller — White', brand: 'Sony', subBrand: 'DualSense', category: 'electronics', subCategory: 'gaming', variant: 'White', description: "Sony DualSense controller for PS5. Haptic feedback and adaptive triggers for immersive gaming. Built-in microphone, 12h battery.", price: 5999, originalPrice: 7490, discount: 20, image: '/assets/products/sony/dualsense-white.jpg', affiliateUrl: '/go/IN2-GAM-SON-001', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: true, isTrending: true, rating: 4.7, reviewCount: 23400, tags: ['Controller', 'PS5', 'DualSense', 'Haptic', 'Sony', 'Gaming'], apiSource: 'static' },
  { id: 'IN2-GAM-SON-002', name: 'Sony DualSense Wireless Controller — Midnight Black', brand: 'Sony', subBrand: 'DualSense', category: 'electronics', subCategory: 'gaming', variant: 'Midnight Black', description: 'Sony DualSense controller in Midnight Black. Haptic feedback, adaptive triggers, and built-in speaker. For PS5.', price: 5999, originalPrice: 7490, discount: 20, image: '/assets/products/sony/dualsense-midnight-black.jpg', affiliateUrl: '/go/IN2-GAM-SON-002', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: false, isTrending: true, rating: 4.7, reviewCount: 18900, tags: ['Controller', 'PS5', 'DualSense', 'Black', 'Sony', 'Haptic'], apiSource: 'static' },
  { id: 'IN2-GAM-SON-003', name: 'Sony PlayStation DualSense Charging Station — White', brand: 'Sony', subBrand: 'PlayStation Accessories', category: 'electronics', subCategory: 'gaming', variant: 'White', description: 'Official Sony PS5 DualSense charging station. Charge 2 controllers simultaneously. LED indicator, compact design.', price: 2490, originalPrice: 3490, discount: 29, image: '/assets/products/sony/dualsense-charging-station.jpg', affiliateUrl: '/go/IN2-GAM-SON-003', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.6, reviewCount: 9870, tags: ['Charging Station', 'PS5', 'DualSense', 'Sony', 'Dual Charge'], apiSource: 'static' },
]

// ─── NIVIA SPORTS (4) ────────────────────────────────────────────────────────

export const NIVIA: IndiaProduct[] = [
  { id: 'IN2-SPO-NIV-001', name: 'Nivia Carbonite Web Football — Size 5', brand: 'Nivia', subBrand: 'Carbonite', category: 'sports', subCategory: 'footballs', variant: 'Size 5', description: "Nivia Carbonite Web football, Size 5. PU synthetic outer, machine stitched. FIFA approved size and weight for match use.", price: 699, originalPrice: 1199, discount: 42, image: '/assets/products/nivia/carbonite-football-size5.jpg', affiliateUrl: '/go/IN2-SPO-NIV-001', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.2, reviewCount: 12300, tags: ['Football', 'Size 5', 'Nivia', 'Carbonite', 'Match Ball'], apiSource: 'static' },
  { id: 'IN2-SPO-NIV-002', name: 'Nivia Storm Cricket Bat — Kashmir Willow Short Handle', brand: 'Nivia', subBrand: 'Storm', category: 'sports', subCategory: 'cricket', variant: 'Kashmir Willow Short Handle', description: "Nivia Storm cricket bat made from Grade A Kashmir Willow. Full cane handle with anti-slip grip. Excellent for club cricket.", price: 799, originalPrice: 1399, discount: 43, image: '/assets/products/nivia/storm-cricket-bat.jpg', affiliateUrl: '/go/IN2-SPO-NIV-002', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: false, isTrending: true, rating: 4.2, reviewCount: 8760, tags: ['Cricket Bat', 'Kashmir Willow', 'Nivia', 'Club Cricket', 'Short Handle'], apiSource: 'static' },
  { id: 'IN2-SPO-NIV-003', name: 'Nivia Marathon Men Running Shoes — Black UK9', brand: 'Nivia', subBrand: 'Marathon', category: 'sports', subCategory: 'running-shoes', variant: 'Black UK9', description: "Nivia Marathon running shoes with mesh upper and EVA midsole. Anti-skid outsole, breathable lining. Budget training shoes.", price: 999, originalPrice: 1799, discount: 44, image: '/assets/products/nivia/marathon-running-black-9.jpg', affiliateUrl: '/go/IN2-SPO-NIV-003', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.0, reviewCount: 9870, tags: ['Running Shoes', 'Nivia', 'Marathon', 'EVA', 'Budget Training'], apiSource: 'static' },
  { id: 'IN2-SPO-NIV-004', name: 'Nivia Carbonite Basketball — Size 7', brand: 'Nivia', subBrand: 'Carbonite', category: 'sports', subCategory: 'basketball', variant: 'Size 7', description: 'Nivia Carbonite basketball, Size 7. High-quality rubber surface with deep channel design for better grip. Outdoor use.', price: 899, originalPrice: 1499, discount: 40, image: '/assets/products/nivia/carbonite-basketball-size7.jpg', affiliateUrl: '/go/IN2-SPO-NIV-004', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.1, reviewCount: 6540, tags: ['Basketball', 'Size 7', 'Nivia', 'Carbonite', 'Outdoor'], apiSource: 'static' },
]

// ─── ADIDAS SPORTS (3) ───────────────────────────────────────────────────────

export const ADIDAS_SPORTS: IndiaProduct[] = [
  { id: 'IN2-SPO-ADI-001', name: 'Adidas Performance Water Bottle 750ml — Black', brand: 'Adidas', subBrand: 'Adidas Performance', category: 'sports', subCategory: 'sports-accessories', variant: 'Black 750ml', description: 'Adidas 750ml water bottle with squeeze valve. BPA-free plastic, lightweight. Fits most cage holders. For gym and training.', price: 599, originalPrice: 999, discount: 40, image: '/assets/products/adidas/performance-bottle-750ml-black.jpg', affiliateUrl: '/go/IN2-SPO-ADI-001', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.2, reviewCount: 7650, tags: ['Water Bottle', 'Adidas', '750ml', 'BPA Free', 'Gym'], apiSource: 'static' },
  { id: 'IN2-SPO-ADI-002', name: 'Adidas Predator Training Gloves — Black S/M', brand: 'Adidas', subBrand: 'Predator', category: 'sports', subCategory: 'sports-accessories', variant: 'Black S/M', description: 'Adidas Predator training goalkeeper gloves. Non-slip palm coating, elastic wristband. Perfect for training sessions.', price: 999, originalPrice: 1799, discount: 44, image: '/assets/products/adidas/predator-training-gloves-sm.jpg', affiliateUrl: '/go/IN2-SPO-ADI-002', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.1, reviewCount: 4560, tags: ['Goalkeeper Gloves', 'Adidas', 'Predator', 'Training', 'Non-Slip'], apiSource: 'static' },
  { id: 'IN2-SPO-ADI-003', name: 'Adidas Team Speed Backpack — Black/White', brand: 'Adidas', subBrand: 'Adidas Team', category: 'sports', subCategory: 'sports-accessories', variant: 'Black/White', description: "Adidas Team Speed backpack with dedicated shoe compartment. 26-litre capacity, shoulder straps with padding. Gym and training bag.", price: 1999, originalPrice: 3499, discount: 43, image: '/assets/products/adidas/team-speed-backpack-black.jpg', affiliateUrl: '/go/IN2-SPO-ADI-003', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.3, reviewCount: 8760, tags: ['Backpack', 'Adidas', 'Team Speed', 'Gym Bag', '26 Litre'], apiSource: 'static' },
]

// ─── PAMPERS BABY (3) ────────────────────────────────────────────────────────

export const PAMPERS: IndiaProduct[] = [
  { id: 'IN2-BAB-PAM-001', name: 'Pampers Baby Dry Diapers Size M — Pack of 62', brand: 'Pampers', subBrand: 'Baby Dry', category: 'personal-care', subCategory: 'baby-care', variant: 'Medium Pack of 62', description: "Pampers Baby Dry diapers Size M (6-11kg). Triple leakguard protection, stays dry up to 12 hours. India's #1 diaper brand.", price: 1099, originalPrice: 1599, discount: 31, image: '/assets/products/pampers/baby-dry-m-62.jpg', affiliateUrl: '/go/IN2-BAB-PAM-001', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: true, isTrending: false, rating: 4.5, reviewCount: 56700, tags: ['Diapers', 'Pampers', 'Baby Dry', 'Size M', '12 Hours'], apiSource: 'static' },
  { id: 'IN2-BAB-PAM-002', name: 'Pampers New Baby Sensitive Wipes — Pack of 288', brand: 'Pampers', subBrand: 'New Baby', category: 'personal-care', subCategory: 'baby-care', variant: 'Pack of 288 (3×96)', description: "Pampers New Baby Sensitive wet wipes. Alcohol-free, dermatologist tested. Gentle on newborn skin. Bulk pack of 288.", price: 699, originalPrice: 999, discount: 30, image: '/assets/products/pampers/sensitive-wipes-288.jpg', affiliateUrl: '/go/IN2-BAB-PAM-002', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: false, isTrending: false, rating: 4.5, reviewCount: 34500, tags: ['Baby Wipes', 'Pampers', 'Sensitive', 'Newborn', 'Alcohol Free'], apiSource: 'static' },
  { id: 'IN2-BAB-PAM-003', name: 'Pampers Premium Care Pants Size M — Pack of 42', brand: 'Pampers', subBrand: 'Premium Care', category: 'personal-care', subCategory: 'baby-care', variant: 'Medium Pants Pack of 42', description: "Pampers Premium Care pant-style diapers Size M. Breathable outer cover, cotton-soft top layer. Easy pull-up and pull-down.", price: 999, originalPrice: 1399, discount: 29, image: '/assets/products/pampers/premium-care-pants-m-42.jpg', affiliateUrl: '/go/IN2-BAB-PAM-003', affiliatePlatform: 'amazon', affiliateSource: 'amazon-pa-api-free', inStock: true, isFeatured: false, isTrending: true, rating: 4.5, reviewCount: 43200, tags: ['Diaper Pants', 'Pampers', 'Premium Care', 'Size M', 'Breathable'], apiSource: 'static' },
]
