// lib/india-catalog-2/india-brands.ts
// 50 products: Smartphones, Laptops, Headphones, Smartwatches, Home Appliances
import type { IndiaProduct } from '@/lib/india-catalog/types'

// ─── SMARTPHONES (10) ────────────────────────────────────────────────────────

export const SMARTPHONES: IndiaProduct[] = [
  {
    id: 'IN2-SP-RM-001',
    name: 'Realme Narzo 60x 5G — Nebula Purple 128GB',
    brand: 'Realme',
    subBrand: 'Narzo',
    category: 'electronics',
    subCategory: 'smartphones',
    variant: 'Nebula Purple 128GB',
    description: '5G smartphone with Dimensity 6100+ chipset, 50MP AI camera, 5000mAh battery and 33W SUPERVOOC charging. Great value for budget segment.',
    price: 11999,
    originalPrice: 15999,
    discount: 25,
    image: '/assets/products/realme/narzo-60x-5g-purple.jpg',
    affiliateUrl: '/go/IN2-SP-RM-001',
    affiliatePlatform: 'flipkart',
    affiliateSource: 'flipkart-affiliate-free',
    inStock: true,
    isFeatured: true,
    isTrending: true,
    rating: 4.2,
    reviewCount: 14300,
    tags: ['5G', 'Realme', 'Budget', 'Narzo', '128GB'],
    apiSource: 'static',
  },
  {
    id: 'IN2-SP-RM-002',
    name: 'Realme 12 Pro+ 5G — Navigator Beige 256GB',
    brand: 'Realme',
    subBrand: 'Realme 12',
    category: 'electronics',
    subCategory: 'smartphones',
    variant: 'Navigator Beige 256GB',
    description: 'Periscope telephoto with 3x optical zoom, Sony IMX890 50MP primary, curved AMOLED display and 67W SUPERVOOC. Mid-range champion.',
    price: 28999,
    originalPrice: 34999,
    discount: 17,
    image: '/assets/products/realme/realme-12-pro-plus-beige.jpg',
    affiliateUrl: '/go/IN2-SP-RM-002',
    affiliatePlatform: 'flipkart',
    affiliateSource: 'flipkart-affiliate-free',
    inStock: true,
    isFeatured: true,
    isTrending: false,
    rating: 4.4,
    reviewCount: 9870,
    tags: ['5G', 'Periscope Zoom', 'AMOLED', '67W Charging', '256GB'],
    apiSource: 'static',
  },
  {
    id: 'IN2-SP-PC-001',
    name: 'Poco M6 Pro 5G — Popcorn Blue 128GB',
    brand: 'Poco',
    subBrand: 'Poco M',
    category: 'electronics',
    subCategory: 'smartphones',
    variant: 'Popcorn Blue 128GB',
    description: 'Dimensity 6080 5G processor, 50MP AI triple camera, 5000mAh with 33W fast charging. Best-in-class performance under ₹14k.',
    price: 13499,
    originalPrice: 17999,
    discount: 25,
    image: '/assets/products/poco/poco-m6-pro-blue.jpg',
    affiliateUrl: '/go/IN2-SP-PC-001',
    affiliatePlatform: 'flipkart',
    affiliateSource: 'flipkart-affiliate-free',
    inStock: true,
    isFeatured: false,
    isTrending: true,
    rating: 4.2,
    reviewCount: 18650,
    tags: ['5G', 'Poco', 'Budget', '33W Charging', 'Dimensity'],
    apiSource: 'static',
  },
  {
    id: 'IN2-SP-PC-002',
    name: 'Poco X6 Pro 5G — Yellow 256GB',
    brand: 'Poco',
    subBrand: 'Poco X',
    category: 'electronics',
    subCategory: 'smartphones',
    variant: 'Yellow 256GB',
    description: 'Dimensity 8300-Ultra, 144Hz Flow AMOLED, 67W turbo charging. Gaming-grade performance at mid-range pricing.',
    price: 24999,
    originalPrice: 29999,
    discount: 17,
    image: '/assets/products/poco/poco-x6-pro-yellow.jpg',
    affiliateUrl: '/go/IN2-SP-PC-002',
    affiliatePlatform: 'flipkart',
    affiliateSource: 'flipkart-affiliate-free',
    inStock: true,
    isFeatured: true,
    isTrending: true,
    rating: 4.5,
    reviewCount: 22400,
    tags: ['5G', '144Hz AMOLED', '67W Charging', 'Gaming', 'Dimensity 8300'],
    apiSource: 'static',
  },
  {
    id: 'IN2-SP-IQ-001',
    name: 'iQOO Z9 5G — Brushed Green 128GB',
    brand: 'iQOO',
    subBrand: 'iQOO Z',
    category: 'electronics',
    subCategory: 'smartphones',
    variant: 'Brushed Green 128GB',
    description: 'Dimensity 7200 with 44W FlashCharge, 64MP OIS camera and 120Hz AMOLED. Flagship-grade optics at mid-range price.',
    price: 19999,
    originalPrice: 24999,
    discount: 20,
    image: '/assets/products/iqoo/iqoo-z9-5g-green.jpg',
    affiliateUrl: '/go/IN2-SP-IQ-001',
    affiliatePlatform: 'flipkart',
    affiliateSource: 'flipkart-affiliate-free',
    inStock: true,
    isFeatured: false,
    isTrending: true,
    rating: 4.3,
    reviewCount: 11200,
    tags: ['5G', 'OIS Camera', 'AMOLED', '44W Charging', 'Dimensity 7200'],
    apiSource: 'static',
  },
  {
    id: 'IN2-SP-IQ-002',
    name: 'iQOO Neo 9 Pro 5G — Fiery Red 256GB',
    brand: 'iQOO',
    subBrand: 'iQOO Neo',
    category: 'electronics',
    subCategory: 'smartphones',
    variant: 'Fiery Red 256GB',
    description: 'Snapdragon 8 Gen 2 with 120W FlashCharge, 50MP Sony IMX920 and 6.78" LTPO AMOLED. Near-flagship for under ₹35k.',
    price: 34999,
    originalPrice: 42999,
    discount: 19,
    image: '/assets/products/iqoo/iqoo-neo-9-pro-red.jpg',
    affiliateUrl: '/go/IN2-SP-IQ-002',
    affiliatePlatform: 'flipkart',
    affiliateSource: 'flipkart-affiliate-free',
    inStock: true,
    isFeatured: true,
    isTrending: false,
    rating: 4.6,
    reviewCount: 8750,
    tags: ['5G', 'Snapdragon 8 Gen 2', '120W Charging', 'LTPO AMOLED', 'Flagship'],
    apiSource: 'static',
  },
  {
    id: 'IN2-SP-OP-001',
    name: 'OnePlus Nord CE 4 Lite 5G — Super Silver 128GB',
    brand: 'OnePlus',
    subBrand: 'Nord CE',
    category: 'electronics',
    subCategory: 'smartphones',
    variant: 'Super Silver 128GB',
    description: 'Snapdragon 695 5G, 50MP main camera, 5110mAh with 80W SUPERVOOC — all-day battery with fast top-up.',
    price: 17999,
    originalPrice: 22999,
    discount: 22,
    image: '/assets/products/oneplus/nord-ce-4-lite-silver.jpg',
    affiliateUrl: '/go/IN2-SP-OP-001',
    affiliatePlatform: 'amazon',
    affiliateSource: 'amazon-pa-api-free',
    inStock: true,
    isFeatured: false,
    isTrending: true,
    rating: 4.2,
    reviewCount: 16300,
    tags: ['5G', 'OnePlus', '80W Charging', 'Nord', 'Snapdragon 695'],
    apiSource: 'static',
  },
  {
    id: 'IN2-SP-OP-002',
    name: 'OnePlus 12R 5G — Iron Gray 128GB',
    brand: 'OnePlus',
    subBrand: 'OnePlus 12',
    category: 'electronics',
    subCategory: 'smartphones',
    variant: 'Iron Gray 128GB',
    description: 'Snapdragon 8 Gen 2, ProXDR AMOLED, 100W SUPERVOOC — charges 0-100% in 26 minutes. Flagship killer returns.',
    price: 39999,
    originalPrice: 44999,
    discount: 11,
    image: '/assets/products/oneplus/oneplus-12r-iron-gray.jpg',
    affiliateUrl: '/go/IN2-SP-OP-002',
    affiliatePlatform: 'amazon',
    affiliateSource: 'amazon-pa-api-free',
    inStock: true,
    isFeatured: true,
    isTrending: true,
    rating: 4.5,
    reviewCount: 7620,
    tags: ['5G', 'Snapdragon 8 Gen 2', '100W Charging', 'OnePlus', 'AMOLED'],
    apiSource: 'static',
  },
  {
    id: 'IN2-SP-RM-003',
    name: 'Realme GT 6T 5G — Fluid Silver 256GB',
    brand: 'Realme',
    subBrand: 'Realme GT',
    category: 'electronics',
    subCategory: 'smartphones',
    variant: 'Fluid Silver 256GB',
    description: 'Snapdragon 7s Gen 3, 6.78" 120Hz AMOLED, 5500mAh with 120W SUPERVOOC. Performance flagship under ₹36k.',
    price: 35999,
    originalPrice: 42999,
    discount: 16,
    image: '/assets/products/realme/realme-gt-6t-silver.jpg',
    affiliateUrl: '/go/IN2-SP-RM-003',
    affiliatePlatform: 'flipkart',
    affiliateSource: 'flipkart-affiliate-free',
    inStock: true,
    isFeatured: true,
    isTrending: false,
    rating: 4.4,
    reviewCount: 6200,
    tags: ['5G', 'Snapdragon 7s Gen 3', '120W Charging', 'GT Series', 'AMOLED'],
    apiSource: 'static',
  },
  {
    id: 'IN2-SP-PC-003',
    name: 'Poco F6 5G — Titanium Silver 256GB',
    brand: 'Poco',
    subBrand: 'Poco F',
    category: 'electronics',
    subCategory: 'smartphones',
    variant: 'Titanium Silver 256GB',
    description: 'Snapdragon 8s Gen 3 with 90W HyperCharge, 6.67" 120Hz AMOLED, 50MP Sony LYT-600 camera. True flagship-killer.',
    price: 29999,
    originalPrice: 34999,
    discount: 14,
    image: '/assets/products/poco/poco-f6-silver.jpg',
    affiliateUrl: '/go/IN2-SP-PC-003',
    affiliatePlatform: 'flipkart',
    affiliateSource: 'flipkart-affiliate-free',
    inStock: true,
    isFeatured: true,
    isTrending: true,
    rating: 4.6,
    reviewCount: 19800,
    tags: ['5G', 'Snapdragon 8s Gen 3', '90W Charging', 'Flagship Killer', '256GB'],
    apiSource: 'static',
  },
]

// ─── LAPTOPS (10) ─────────────────────────────────────────────────────────────

export const LAPTOPS: IndiaProduct[] = [
  {
    id: 'IN2-LT-LN-001',
    name: 'Lenovo IdeaPad Slim 3 — Core i5 8GB 512GB SSD',
    brand: 'Lenovo',
    subBrand: 'IdeaPad',
    category: 'electronics',
    subCategory: 'laptops',
    variant: 'Arctic Grey i5 8GB 512GB',
    description: '13th Gen Intel Core i5-1335U, 8GB DDR5, 512GB SSD, 15.6" FHD IPS anti-glare. Perfect everyday productivity laptop.',
    price: 44990,
    originalPrice: 55990,
    discount: 20,
    image: '/assets/products/lenovo/ideapad-slim-3-grey.jpg',
    affiliateUrl: '/go/IN2-LT-LN-001',
    affiliatePlatform: 'amazon',
    affiliateSource: 'amazon-pa-api-free',
    inStock: true,
    isFeatured: true,
    isTrending: true,
    rating: 4.3,
    reviewCount: 8920,
    tags: ['Laptop', 'Core i5', '512GB SSD', 'IdeaPad', 'Lenovo'],
    apiSource: 'static',
  },
  {
    id: 'IN2-LT-LN-002',
    name: 'Lenovo ThinkPad E14 Gen 5 — Core i5 16GB 512GB',
    brand: 'Lenovo',
    subBrand: 'ThinkPad',
    category: 'electronics',
    subCategory: 'laptops',
    variant: 'Black i5 16GB 512GB',
    description: '13th Gen Intel Core i5, 16GB RAM, 512GB SSD, MIL-STD-810H certified. Business-grade durability with fingerprint reader.',
    price: 59990,
    originalPrice: 74990,
    discount: 20,
    image: '/assets/products/lenovo/thinkpad-e14-black.jpg',
    affiliateUrl: '/go/IN2-LT-LN-002',
    affiliatePlatform: 'amazon',
    affiliateSource: 'amazon-pa-api-free',
    inStock: true,
    isFeatured: false,
    isTrending: false,
    rating: 4.5,
    reviewCount: 5640,
    tags: ['Laptop', 'ThinkPad', 'Business', 'MIL-STD', 'Core i5 16GB'],
    apiSource: 'static',
  },
  {
    id: 'IN2-LT-HP-001',
    name: 'HP Laptop 15 — Core i5 8GB 512GB SSD',
    brand: 'HP',
    subBrand: 'HP Laptop',
    category: 'electronics',
    subCategory: 'laptops',
    variant: 'Natural Silver i5 8GB 512GB',
    description: '12th Gen Intel Core i5-1235U, 8GB DDR4, 512GB SSD, 15.6" FHD micro-edge display with backlit keyboard.',
    price: 47490,
    originalPrice: 57490,
    discount: 17,
    image: '/assets/products/hp/hp-laptop-15-silver.jpg',
    affiliateUrl: '/go/IN2-LT-HP-001',
    affiliatePlatform: 'amazon',
    affiliateSource: 'amazon-pa-api-free',
    inStock: true,
    isFeatured: true,
    isTrending: false,
    rating: 4.2,
    reviewCount: 12300,
    tags: ['Laptop', 'HP', 'Core i5', '512GB SSD', 'Backlit Keyboard'],
    apiSource: 'static',
  },
  {
    id: 'IN2-LT-HP-002',
    name: 'HP Victus 15 — Ryzen 5 8GB 512GB GTX 1650',
    brand: 'HP',
    subBrand: 'Victus',
    category: 'electronics',
    subCategory: 'laptops',
    variant: 'Mica Silver Ryzen 5 GTX 1650',
    description: 'AMD Ryzen 5 5600H, 8GB RAM, 512GB SSD, NVIDIA GTX 1650 4GB, 144Hz FHD IPS — entry gaming laptop with HP build quality.',
    price: 57990,
    originalPrice: 69990,
    discount: 17,
    image: '/assets/products/hp/hp-victus-15-silver.jpg',
    affiliateUrl: '/go/IN2-LT-HP-002',
    affiliatePlatform: 'flipkart',
    affiliateSource: 'flipkart-affiliate-free',
    inStock: true,
    isFeatured: true,
    isTrending: true,
    rating: 4.3,
    reviewCount: 7820,
    tags: ['Gaming Laptop', 'HP Victus', 'GTX 1650', 'Ryzen 5', '144Hz'],
    apiSource: 'static',
  },
  {
    id: 'IN2-LT-AS-001',
    name: 'Asus VivoBook 15 — Core i5 16GB 512GB',
    brand: 'Asus',
    subBrand: 'VivoBook',
    category: 'electronics',
    subCategory: 'laptops',
    variant: 'Indie Black i5 16GB 512GB',
    description: '13th Gen Core i5-13500H, 16GB DDR4, 512GB NVMe SSD, OLED FHD display with 600 nit brightness. Creator-focused laptop.',
    price: 52990,
    originalPrice: 64990,
    discount: 18,
    image: '/assets/products/asus/vivobook-15-black.jpg',
    affiliateUrl: '/go/IN2-LT-AS-001',
    affiliatePlatform: 'amazon',
    affiliateSource: 'amazon-pa-api-free',
    inStock: true,
    isFeatured: false,
    isTrending: true,
    rating: 4.4,
    reviewCount: 6540,
    tags: ['Laptop', 'Asus', 'OLED', 'Core i5', '16GB RAM'],
    apiSource: 'static',
  },
  {
    id: 'IN2-LT-AS-002',
    name: 'Asus TUF Gaming A15 — Ryzen 5 16GB 512GB RTX 3050',
    brand: 'Asus',
    subBrand: 'TUF Gaming',
    category: 'electronics',
    subCategory: 'laptops',
    variant: 'Mecha Gray Ryzen 5 RTX 3050',
    description: 'AMD Ryzen 5 7535HS, 16GB DDR5, 512GB NVMe, RTX 3050 6GB, 144Hz FHD — MIL-STD-810H chassis built for gaming marathons.',
    price: 74990,
    originalPrice: 89990,
    discount: 17,
    image: '/assets/products/asus/tuf-gaming-a15-gray.jpg',
    affiliateUrl: '/go/IN2-LT-AS-002',
    affiliatePlatform: 'amazon',
    affiliateSource: 'amazon-pa-api-free',
    inStock: true,
    isFeatured: true,
    isTrending: true,
    rating: 4.5,
    reviewCount: 11200,
    tags: ['Gaming Laptop', 'TUF', 'RTX 3050', 'Ryzen 5', '144Hz DDR5'],
    apiSource: 'static',
  },
  {
    id: 'IN2-LT-AC-001',
    name: 'Acer Aspire 3 — Core i3 8GB 256GB SSD',
    brand: 'Acer',
    subBrand: 'Aspire',
    category: 'electronics',
    subCategory: 'laptops',
    variant: 'Steel Gray i3 8GB 256GB',
    description: '12th Gen Intel Core i3-1215U, 8GB RAM, 256GB SSD, 15.6" FHD IPS. Best entry-level laptop for students and home use.',
    price: 32990,
    originalPrice: 42990,
    discount: 23,
    image: '/assets/products/acer/aspire-3-gray.jpg',
    affiliateUrl: '/go/IN2-LT-AC-001',
    affiliatePlatform: 'flipkart',
    affiliateSource: 'flipkart-affiliate-free',
    inStock: true,
    isFeatured: false,
    isTrending: false,
    rating: 4.1,
    reviewCount: 16700,
    tags: ['Laptop', 'Acer', 'Budget', 'Core i3', 'Student'],
    apiSource: 'static',
  },
  {
    id: 'IN2-LT-AC-002',
    name: 'Acer Nitro 5 — Ryzen 5 16GB 512GB RTX 4050',
    brand: 'Acer',
    subBrand: 'Nitro',
    category: 'electronics',
    subCategory: 'laptops',
    variant: 'Black Ryzen 5 RTX 4050',
    description: 'AMD Ryzen 5 7535HS, 16GB DDR5, 512GB SSD, RTX 4050 6GB, 165Hz FHD — serious gaming performance with IPS-level display.',
    price: 79990,
    originalPrice: 94990,
    discount: 16,
    image: '/assets/products/acer/nitro-5-rtx4050-black.jpg',
    affiliateUrl: '/go/IN2-LT-AC-002',
    affiliatePlatform: 'amazon',
    affiliateSource: 'amazon-pa-api-free',
    inStock: true,
    isFeatured: true,
    isTrending: true,
    rating: 4.4,
    reviewCount: 9340,
    tags: ['Gaming Laptop', 'Nitro', 'RTX 4050', 'Ryzen 5', '165Hz'],
    apiSource: 'static',
  },
  {
    id: 'IN2-LT-LN-003',
    name: 'Lenovo IdeaPad Gaming 3 — Ryzen 5 16GB 512GB RTX 3050',
    brand: 'Lenovo',
    subBrand: 'IdeaPad Gaming',
    category: 'electronics',
    subCategory: 'laptops',
    variant: 'Onyx Grey Ryzen 5 RTX 3050',
    description: 'AMD Ryzen 5 7535HS, 16GB RAM, 512GB SSD, RTX 3050 6GB, 120Hz FHD — Lenovo build quality meets gaming performance.',
    price: 69990,
    originalPrice: 84990,
    discount: 18,
    image: '/assets/products/lenovo/ideapad-gaming-3-grey.jpg',
    affiliateUrl: '/go/IN2-LT-LN-003',
    affiliatePlatform: 'flipkart',
    affiliateSource: 'flipkart-affiliate-free',
    inStock: true,
    isFeatured: false,
    isTrending: false,
    rating: 4.3,
    reviewCount: 7430,
    tags: ['Gaming Laptop', 'Lenovo', 'RTX 3050', 'Ryzen 5', '120Hz'],
    apiSource: 'static',
  },
  {
    id: 'IN2-LT-HP-003',
    name: 'HP Envy x360 — Core i7 16GB 1TB SSD',
    brand: 'HP',
    subBrand: 'Envy',
    category: 'electronics',
    subCategory: 'laptops',
    variant: 'Natural Silver i7 16GB 1TB',
    description: '13th Gen Core i7-1355U, 16GB LPDDR4x, 1TB NVMe SSD, 15.6" OLED touch 2.8K 120Hz, 360-degree hinge. Premium 2-in-1.',
    price: 89990,
    originalPrice: 104990,
    discount: 14,
    image: '/assets/products/hp/hp-envy-x360-silver.jpg',
    affiliateUrl: '/go/IN2-LT-HP-003',
    affiliatePlatform: 'amazon',
    affiliateSource: 'amazon-pa-api-free',
    inStock: true,
    isFeatured: true,
    isTrending: false,
    rating: 4.6,
    reviewCount: 4210,
    tags: ['2-in-1 Laptop', 'OLED Touch', 'Core i7', '1TB SSD', 'HP Envy'],
    apiSource: 'static',
  },
]

// ─── HEADPHONES (10) ──────────────────────────────────────────────────────────

export const HEADPHONES: IndiaProduct[] = [
  {
    id: 'IN2-HP-BT-001',
    name: 'boAt Rockerz 450 Bluetooth Headphone — Black',
    brand: 'boAt',
    subBrand: 'Rockerz',
    category: 'electronics',
    subCategory: 'headphones',
    variant: 'Luscious Black',
    description: '40mm dynamic drivers, 15H playback, foldable on-ear design with soft earpads. Powerful bass for commutes and workouts.',
    price: 1299,
    originalPrice: 2990,
    discount: 57,
    image: '/assets/products/boat/rockerz-450-black.jpg',
    affiliateUrl: '/go/IN2-HP-BT-001',
    affiliatePlatform: 'amazon',
    affiliateSource: 'amazon-pa-api-free',
    inStock: true,
    isFeatured: true,
    isTrending: true,
    rating: 4.1,
    reviewCount: 48200,
    tags: ['Bluetooth', 'On-Ear', 'boAt', 'Rockerz', 'Bass'],
    apiSource: 'static',
  },
  {
    id: 'IN2-HP-BT-002',
    name: 'boAt Airdopes 141 TWS Earbuds — Bold Black',
    brand: 'boAt',
    subBrand: 'Airdopes',
    category: 'electronics',
    subCategory: 'headphones',
    variant: 'Bold Black',
    description: '8mm drivers with IWS+ Bluetooth 5.1, 42H total playtime, BEAST mode for gaming, IPX4 splash-resistant.',
    price: 799,
    originalPrice: 2990,
    discount: 73,
    image: '/assets/products/boat/airdopes-141-black.jpg',
    affiliateUrl: '/go/IN2-HP-BT-002',
    affiliatePlatform: 'flipkart',
    affiliateSource: 'flipkart-affiliate-free',
    inStock: true,
    isFeatured: true,
    isTrending: true,
    rating: 4.0,
    reviewCount: 1,
    tags: ['TWS', 'Earbuds', 'boAt', '42H Battery', 'IPX4'],
    apiSource: 'static',
  },
  {
    id: 'IN2-HP-JB-001',
    name: 'JBL Tune 520BT On-Ear Headphone — Black',
    brand: 'JBL',
    subBrand: 'Tune',
    category: 'electronics',
    subCategory: 'headphones',
    variant: 'Black',
    description: '40mm drivers with Pure Bass Sound, 57H battery, Speed Charge (10 min = 3H), USB-C charging. Industry-standard mid-range.',
    price: 2999,
    originalPrice: 4999,
    discount: 40,
    image: '/assets/products/jbl/tune-520bt-black.jpg',
    affiliateUrl: '/go/IN2-HP-JB-001',
    affiliatePlatform: 'amazon',
    affiliateSource: 'amazon-pa-api-free',
    inStock: true,
    isFeatured: true,
    isTrending: false,
    rating: 4.3,
    reviewCount: 21400,
    tags: ['JBL', 'On-Ear', 'Pure Bass', '57H Battery', 'USB-C'],
    apiSource: 'static',
  },
  {
    id: 'IN2-HP-JB-002',
    name: 'JBL Wave Beam TWS — Deep Sea Blue',
    brand: 'JBL',
    subBrand: 'Wave',
    category: 'electronics',
    subCategory: 'headphones',
    variant: 'Deep Sea Blue',
    description: '12.4mm drivers, Deep Bass Sound, 32H total playtime, IPX2, Voice Assistant support. Everyday earbuds by JBL.',
    price: 2499,
    originalPrice: 3999,
    discount: 38,
    image: '/assets/products/jbl/wave-beam-blue.jpg',
    affiliateUrl: '/go/IN2-HP-JB-002',
    affiliatePlatform: 'amazon',
    affiliateSource: 'amazon-pa-api-free',
    inStock: true,
    isFeatured: false,
    isTrending: true,
    rating: 4.2,
    reviewCount: 13600,
    tags: ['TWS', 'JBL', 'Deep Bass', '32H Battery', 'IPX2'],
    apiSource: 'static',
  },
  {
    id: 'IN2-HP-SN-001',
    name: 'Sony WH-1000XM5 ANC Headphone — Black',
    brand: 'Sony',
    subBrand: 'WH-1000X',
    category: 'electronics',
    subCategory: 'headphones',
    variant: 'Black',
    description: 'Industry-leading ANC with 8 microphones, 30H battery, Multipoint connection, 360 Reality Audio, USB-C quick charge.',
    price: 26990,
    originalPrice: 32990,
    discount: 18,
    image: '/assets/products/sony/wh-1000xm5-black.jpg',
    affiliateUrl: '/go/IN2-HP-SN-001',
    affiliatePlatform: 'amazon',
    affiliateSource: 'amazon-pa-api-free',
    inStock: true,
    isFeatured: true,
    isTrending: true,
    rating: 4.7,
    reviewCount: 34500,
    tags: ['ANC', 'Sony', 'Premium', '30H Battery', 'Multipoint'],
    apiSource: 'static',
  },
  {
    id: 'IN2-HP-SN-002',
    name: 'Sony WF-1000XM5 TWS — Silver',
    brand: 'Sony',
    subBrand: 'WF-1000X',
    category: 'electronics',
    subCategory: 'headphones',
    variant: 'Platinum Silver',
    description: 'Best-in-class ANC in a TWS form factor, V2 processor, 24H total, LDAC Hi-Res Audio, IPX4. Top-tier earbuds.',
    price: 19990,
    originalPrice: 24990,
    discount: 20,
    image: '/assets/products/sony/wf-1000xm5-silver.jpg',
    affiliateUrl: '/go/IN2-HP-SN-002',
    affiliatePlatform: 'amazon',
    affiliateSource: 'amazon-pa-api-free',
    inStock: true,
    isFeatured: true,
    isTrending: false,
    rating: 4.6,
    reviewCount: 18900,
    tags: ['ANC TWS', 'Sony', 'LDAC', 'Hi-Res Audio', 'Premium'],
    apiSource: 'static',
  },
  {
    id: 'IN2-HP-SE-001',
    name: 'Sennheiser Momentum 4 Wireless — Black',
    brand: 'Sennheiser',
    subBrand: 'Momentum',
    category: 'electronics',
    subCategory: 'headphones',
    variant: 'Black',
    description: '60H battery with ANC, adaptable acoustics, USB-C, multi-device connection and Sennheiser sound signature. Audiophile-grade comfort.',
    price: 29990,
    originalPrice: 39990,
    discount: 25,
    image: '/assets/products/sennheiser/momentum-4-black.jpg',
    affiliateUrl: '/go/IN2-HP-SE-001',
    affiliatePlatform: 'amazon',
    affiliateSource: 'amazon-pa-api-free',
    inStock: true,
    isFeatured: true,
    isTrending: false,
    rating: 4.6,
    reviewCount: 9800,
    tags: ['ANC', 'Sennheiser', '60H Battery', 'Audiophile', 'Premium'],
    apiSource: 'static',
  },
  {
    id: 'IN2-HP-BT-003',
    name: 'boAt Bassheads 100 Wired Earphone — Black',
    brand: 'boAt',
    subBrand: 'Bassheads',
    category: 'electronics',
    subCategory: 'headphones',
    variant: 'Furious Black',
    description: 'Dynamic 10mm drivers, in-line mic, tangle-free cable, universal 3.5mm jack. Best entry-level wired earphone under ₹400.',
    price: 399,
    originalPrice: 1290,
    discount: 69,
    image: '/assets/products/boat/bassheads-100-black.jpg',
    affiliateUrl: '/go/IN2-HP-BT-003',
    affiliatePlatform: 'amazon',
    affiliateSource: 'amazon-pa-api-free',
    inStock: true,
    isFeatured: false,
    isTrending: false,
    rating: 4.0,
    reviewCount: 82400,
    tags: ['Wired', 'boAt', 'Budget', 'Earphones', '3.5mm'],
    apiSource: 'static',
  },
  {
    id: 'IN2-HP-JB-003',
    name: 'JBL Endurance Peak 3 TWS — Black',
    brand: 'JBL',
    subBrand: 'Endurance',
    category: 'electronics',
    subCategory: 'headphones',
    variant: 'Black',
    description: 'TwistLock sport earbuds, IP68 dustproof & waterproof, 10H playtime + 40H case, JBL Pure Bass. Built for runners.',
    price: 5999,
    originalPrice: 8999,
    discount: 33,
    image: '/assets/products/jbl/endurance-peak-3-black.jpg',
    affiliateUrl: '/go/IN2-HP-JB-003',
    affiliatePlatform: 'amazon',
    affiliateSource: 'amazon-pa-api-free',
    inStock: true,
    isFeatured: false,
    isTrending: true,
    rating: 4.4,
    reviewCount: 11200,
    tags: ['TWS', 'Sport', 'IP68', 'JBL', 'Running'],
    apiSource: 'static',
  },
  {
    id: 'IN2-HP-SN-003',
    name: 'Sony MDR-XB55AP Extra Bass Earphone — Black',
    brand: 'Sony',
    subBrand: 'MDR-XB',
    category: 'electronics',
    subCategory: 'headphones',
    variant: 'Black',
    description: '12mm Extra Bass driver with integrated mic, powerful bass extension and ergonomic arc-supporter. Sony quality under ₹2k.',
    price: 1999,
    originalPrice: 2990,
    discount: 33,
    image: '/assets/products/sony/mdr-xb55ap-black.jpg',
    affiliateUrl: '/go/IN2-HP-SN-003',
    affiliatePlatform: 'amazon',
    affiliateSource: 'amazon-pa-api-free',
    inStock: true,
    isFeatured: false,
    isTrending: false,
    rating: 4.3,
    reviewCount: 29600,
    tags: ['Wired', 'Sony', 'Extra Bass', 'In-Ear', 'Mic'],
    apiSource: 'static',
  },
]

// ─── SMARTWATCHES (10) ────────────────────────────────────────────────────────

export const SMARTWATCHES: IndiaProduct[] = [
  {
    id: 'IN2-SW-NS-001',
    name: 'Noise ColorFit Pro 5 — Jet Black',
    brand: 'Noise',
    subBrand: 'ColorFit',
    category: 'electronics',
    subCategory: 'smartwatches',
    variant: 'Jet Black',
    description: '1.85" AMOLED display, 100+ sports modes, Bluetooth calling, SpO2, HR monitor, 7-day battery. Best-selling smartwatch in India.',
    price: 2499,
    originalPrice: 4999,
    discount: 50,
    image: '/assets/products/noise/colorfit-pro-5-black.jpg',
    affiliateUrl: '/go/IN2-SW-NS-001',
    affiliatePlatform: 'amazon',
    affiliateSource: 'amazon-pa-api-free',
    inStock: true,
    isFeatured: true,
    isTrending: true,
    rating: 4.2,
    reviewCount: 43200,
    tags: ['Smartwatch', 'Noise', 'AMOLED', 'Bluetooth Calling', '100+ Sports'],
    apiSource: 'static',
  },
  {
    id: 'IN2-SW-NS-002',
    name: 'Noise ColorFit Ultra 3 — Midnight Blue',
    brand: 'Noise',
    subBrand: 'ColorFit Ultra',
    category: 'electronics',
    subCategory: 'smartwatches',
    variant: 'Midnight Blue',
    description: '1.96" AMOLED, BT calling, AI Voice, metal build, always-on display, 100+ watch faces. Premium flagship from Noise.',
    price: 3999,
    originalPrice: 7999,
    discount: 50,
    image: '/assets/products/noise/colorfit-ultra-3-blue.jpg',
    affiliateUrl: '/go/IN2-SW-NS-002',
    affiliatePlatform: 'amazon',
    affiliateSource: 'amazon-pa-api-free',
    inStock: true,
    isFeatured: false,
    isTrending: true,
    rating: 4.3,
    reviewCount: 21800,
    tags: ['Smartwatch', 'Noise', 'AMOLED', 'Metal Build', 'Always-On'],
    apiSource: 'static',
  },
  {
    id: 'IN2-SW-FB-001',
    name: 'Fire-Boltt Phoenix Ultra — Black',
    brand: 'Fire-Boltt',
    subBrand: 'Phoenix',
    category: 'electronics',
    subCategory: 'smartwatches',
    variant: 'Black',
    description: '1.43" AMOLED round dial, Bluetooth calling, health suite, 100+ sports modes, IP67 water resistant. Classic round smartwatch.',
    price: 1799,
    originalPrice: 4999,
    discount: 64,
    image: '/assets/products/fire-boltt/phoenix-ultra-black.jpg',
    affiliateUrl: '/go/IN2-SW-FB-001',
    affiliatePlatform: 'amazon',
    affiliateSource: 'amazon-pa-api-free',
    inStock: true,
    isFeatured: true,
    isTrending: true,
    rating: 4.1,
    reviewCount: 37600,
    tags: ['Smartwatch', 'Fire-Boltt', 'Round Dial', 'BT Calling', 'Budget'],
    apiSource: 'static',
  },
  {
    id: 'IN2-SW-FB-002',
    name: 'Fire-Boltt Infinite — Black',
    brand: 'Fire-Boltt',
    subBrand: 'Infinite',
    category: 'electronics',
    subCategory: 'smartwatches',
    variant: 'Black',
    description: '1.85" HD display with Bluetooth calling, Crown navigation, 120+ watch faces, SpO2 and stress monitor. Feature-packed under ₹3.5k.',
    price: 3499,
    originalPrice: 6999,
    discount: 50,
    image: '/assets/products/fire-boltt/infinite-black.jpg',
    affiliateUrl: '/go/IN2-SW-FB-002',
    affiliatePlatform: 'flipkart',
    affiliateSource: 'flipkart-affiliate-free',
    inStock: true,
    isFeatured: false,
    isTrending: false,
    rating: 4.2,
    reviewCount: 19400,
    tags: ['Smartwatch', 'Fire-Boltt', 'BT Calling', 'Crown Navigation', 'SpO2'],
    apiSource: 'static',
  },
  {
    id: 'IN2-SW-AM-001',
    name: 'Amazfit Bip 5 — Cream White',
    brand: 'Amazfit',
    subBrand: 'Bip',
    category: 'electronics',
    subCategory: 'smartwatches',
    variant: 'Cream White',
    description: '1.91" HD display, Bluetooth calling, GPS, 10-day battery, Amazon Alexa built-in. Lightweight at just 33.5g.',
    price: 5999,
    originalPrice: 8999,
    discount: 33,
    image: '/assets/products/amazfit/bip-5-cream.jpg',
    affiliateUrl: '/go/IN2-SW-AM-001',
    affiliatePlatform: 'amazon',
    affiliateSource: 'amazon-pa-api-free',
    inStock: true,
    isFeatured: true,
    isTrending: false,
    rating: 4.3,
    reviewCount: 12400,
    tags: ['Smartwatch', 'Amazfit', 'GPS', 'Alexa', '10-Day Battery'],
    apiSource: 'static',
  },
  {
    id: 'IN2-SW-AM-002',
    name: 'Amazfit GTR 4 — Superspeed Black',
    brand: 'Amazfit',
    subBrand: 'GTR',
    category: 'electronics',
    subCategory: 'smartwatches',
    variant: 'Superspeed Black',
    description: '1.43" AMOLED round, dual-band GPS, Zepp OS 2.0, 150+ sport modes, 14-day battery, BT phone calls. Premium sports watch.',
    price: 14999,
    originalPrice: 19999,
    discount: 25,
    image: '/assets/products/amazfit/gtr-4-black.jpg',
    affiliateUrl: '/go/IN2-SW-AM-002',
    affiliatePlatform: 'amazon',
    affiliateSource: 'amazon-pa-api-free',
    inStock: true,
    isFeatured: true,
    isTrending: true,
    rating: 4.5,
    reviewCount: 8700,
    tags: ['Smartwatch', 'Amazfit', 'Dual-Band GPS', 'AMOLED', '150+ Sports'],
    apiSource: 'static',
  },
  {
    id: 'IN2-SW-NS-003',
    name: 'Noise Twist Go — Teal Green',
    brand: 'Noise',
    subBrand: 'Twist',
    category: 'electronics',
    subCategory: 'smartwatches',
    variant: 'Teal Green',
    description: 'Budget smartwatch with 1.69" TFT display, BT calling, IP68, SpO2 and HR tracking. Entry-level Noise for first-time buyers.',
    price: 1499,
    originalPrice: 2999,
    discount: 50,
    image: '/assets/products/noise/twist-go-teal.jpg',
    affiliateUrl: '/go/IN2-SW-NS-003',
    affiliatePlatform: 'flipkart',
    affiliateSource: 'flipkart-affiliate-free',
    inStock: true,
    isFeatured: false,
    isTrending: false,
    rating: 4.0,
    reviewCount: 28700,
    tags: ['Smartwatch', 'Noise', 'Budget', 'BT Calling', 'IP68'],
    apiSource: 'static',
  },
  {
    id: 'IN2-SW-FB-003',
    name: 'Fire-Boltt Dagger 3 — Black',
    brand: 'Fire-Boltt',
    subBrand: 'Dagger',
    category: 'electronics',
    subCategory: 'smartwatches',
    variant: 'Black',
    description: '1.96" AMOLED, rotating crown, BT calling, metal case, 100+ sports modes, AI Voice assistant. Best AMOLED under ₹2.5k.',
    price: 2299,
    originalPrice: 5999,
    discount: 62,
    image: '/assets/products/fire-boltt/dagger-3-black.jpg',
    affiliateUrl: '/go/IN2-SW-FB-003',
    affiliatePlatform: 'amazon',
    affiliateSource: 'amazon-pa-api-free',
    inStock: true,
    isFeatured: false,
    isTrending: true,
    rating: 4.1,
    reviewCount: 24100,
    tags: ['Smartwatch', 'Fire-Boltt', 'AMOLED', 'Metal Case', 'Budget'],
    apiSource: 'static',
  },
  {
    id: 'IN2-SW-AM-003',
    name: 'Amazfit Band 7 — Black',
    brand: 'Amazfit',
    subBrand: 'Band',
    category: 'electronics',
    subCategory: 'smartwatches',
    variant: 'Black',
    description: '1.47" AMOLED smart band, Amazon Alexa, 18-day battery, SpO2, PAI health score, 120+ sport modes. Slim band with big features.',
    price: 3499,
    originalPrice: 4999,
    discount: 30,
    image: '/assets/products/amazfit/band-7-black.jpg',
    affiliateUrl: '/go/IN2-SW-AM-003',
    affiliatePlatform: 'amazon',
    affiliateSource: 'amazon-pa-api-free',
    inStock: true,
    isFeatured: false,
    isTrending: false,
    rating: 4.4,
    reviewCount: 16500,
    tags: ['Smart Band', 'Amazfit', 'Alexa', '18-Day Battery', 'AMOLED'],
    apiSource: 'static',
  },
  {
    id: 'IN2-SW-NS-004',
    name: 'Noise Icon 3 — Rose Pink',
    brand: 'Noise',
    subBrand: 'Icon',
    category: 'electronics',
    subCategory: 'smartwatches',
    variant: 'Rose Pink',
    description: '1.8" HD display, BT calling, 100+ watch faces, Health suite with period tracker, IP68. Popular women-first smartwatch.',
    price: 1799,
    originalPrice: 3499,
    discount: 49,
    image: '/assets/products/noise/icon-3-pink.jpg',
    affiliateUrl: '/go/IN2-SW-NS-004',
    affiliatePlatform: 'amazon',
    affiliateSource: 'amazon-pa-api-free',
    inStock: true,
    isFeatured: false,
    isTrending: true,
    rating: 4.2,
    reviewCount: 31200,
    tags: ['Smartwatch', 'Noise', 'Women', 'BT Calling', 'Period Tracker'],
    apiSource: 'static',
  },
]

// ─── HOME APPLIANCES (10) ─────────────────────────────────────────────────────

export const HOME_APPLIANCES: IndiaProduct[] = [
  {
    id: 'IN2-HA-HV-001',
    name: 'Havells Sprint 390mm Pedestal Fan — Black',
    brand: 'Havells',
    subBrand: 'Sprint',
    category: 'home-appliances',
    subCategory: 'fans',
    variant: 'Black 390mm',
    description: '65W powerful motor, 3-speed control, aerodynamic blades, thermal overload protection. Ideal for living rooms and offices.',
    price: 3290,
    originalPrice: 4290,
    discount: 23,
    image: '/assets/products/havells/sprint-pedestal-fan-black.jpg',
    affiliateUrl: '/go/IN2-HA-HV-001',
    affiliatePlatform: 'amazon',
    affiliateSource: 'amazon-pa-api-free',
    inStock: true,
    isFeatured: false,
    isTrending: true,
    rating: 4.3,
    reviewCount: 14500,
    tags: ['Fan', 'Havells', 'Pedestal', '390mm', '65W'],
    apiSource: 'static',
  },
  {
    id: 'IN2-HA-HV-002',
    name: 'Havells Fabio 1200mm Ceiling Fan — Pearl White',
    brand: 'Havells',
    subBrand: 'Fabio',
    category: 'home-appliances',
    subCategory: 'fans',
    variant: 'Pearl White 1200mm',
    description: 'BEE 5-star rated 1200mm ceiling fan with 50W motor, anti-dust powder coating and balanced blades for silent operation.',
    price: 2490,
    originalPrice: 3290,
    discount: 24,
    image: '/assets/products/havells/fabio-ceiling-fan-white.jpg',
    affiliateUrl: '/go/IN2-HA-HV-002',
    affiliatePlatform: 'amazon',
    affiliateSource: 'amazon-pa-api-free',
    inStock: true,
    isFeatured: true,
    isTrending: false,
    rating: 4.4,
    reviewCount: 22100,
    tags: ['Ceiling Fan', 'Havells', '1200mm', '5-Star', 'Silent'],
    apiSource: 'static',
  },
  {
    id: 'IN2-HA-CR-001',
    name: 'Crompton Aura Prime 1200mm Ceiling Fan — Ivory',
    brand: 'Crompton',
    subBrand: 'Aura Prime',
    category: 'home-appliances',
    subCategory: 'fans',
    variant: 'Ivory 1200mm',
    description: 'High-speed 390 RPM, 72W motor, double ball bearing for long life and silent operation. Best-value ceiling fan from Crompton.',
    price: 1999,
    originalPrice: 2999,
    discount: 33,
    image: '/assets/products/crompton/aura-prime-ceiling-ivory.jpg',
    affiliateUrl: '/go/IN2-HA-CR-001',
    affiliatePlatform: 'flipkart',
    affiliateSource: 'flipkart-affiliate-free',
    inStock: true,
    isFeatured: false,
    isTrending: false,
    rating: 4.2,
    reviewCount: 31400,
    tags: ['Ceiling Fan', 'Crompton', '1200mm', 'Ball Bearing', 'Budget'],
    apiSource: 'static',
  },
  {
    id: 'IN2-HA-CR-002',
    name: 'Crompton SureBake 38L OTG Oven — Grey',
    brand: 'Crompton',
    subBrand: 'SureBake',
    category: 'home-appliances',
    subCategory: 'ovens',
    variant: 'Grey 38L',
    description: '38L capacity with 6 heating modes, motorized rotisserie, convection + grill, 90-min timer. Best OTG for Indian baking.',
    price: 5999,
    originalPrice: 8999,
    discount: 33,
    image: '/assets/products/crompton/surebake-38l-otg-grey.jpg',
    affiliateUrl: '/go/IN2-HA-CR-002',
    affiliatePlatform: 'amazon',
    affiliateSource: 'amazon-pa-api-free',
    inStock: true,
    isFeatured: true,
    isTrending: true,
    rating: 4.3,
    reviewCount: 8200,
    tags: ['OTG', 'Crompton', '38L', 'Convection', 'Rotisserie'],
    apiSource: 'static',
  },
  {
    id: 'IN2-HA-PH-001',
    name: 'Philips HD3030 Rice Cooker 1.8L — White',
    brand: 'Philips',
    subBrand: 'Daily Collection',
    category: 'home-appliances',
    subCategory: 'kitchen-appliances',
    variant: 'White 1.8L',
    description: '700W, 1.8L capacity, non-stick bowl, automatic keep-warm function. Cooks white rice, brown rice and steam vegetables.',
    price: 2499,
    originalPrice: 3499,
    discount: 29,
    image: '/assets/products/philips/hd3030-rice-cooker-white.jpg',
    affiliateUrl: '/go/IN2-HA-PH-001',
    affiliatePlatform: 'amazon',
    affiliateSource: 'amazon-pa-api-free',
    inStock: true,
    isFeatured: false,
    isTrending: false,
    rating: 4.4,
    reviewCount: 19800,
    tags: ['Rice Cooker', 'Philips', '1.8L', 'Non-Stick', 'Auto Keep-Warm'],
    apiSource: 'static',
  },
  {
    id: 'IN2-HA-PH-002',
    name: 'Philips Air Purifier AC1215 — White',
    brand: 'Philips',
    subBrand: 'Series 1000',
    category: 'home-appliances',
    subCategory: 'air-purifiers',
    variant: 'White AC1215',
    description: 'HEPA + Active Carbon filter, 333 m³/h CADR, IAQI sensor with auto mode. Covers 333 sq ft room. BIS certified for India.',
    price: 8999,
    originalPrice: 12999,
    discount: 31,
    image: '/assets/products/philips/ac1215-air-purifier-white.jpg',
    affiliateUrl: '/go/IN2-HA-PH-002',
    affiliatePlatform: 'amazon',
    affiliateSource: 'amazon-pa-api-free',
    inStock: true,
    isFeatured: true,
    isTrending: true,
    rating: 4.5,
    reviewCount: 11600,
    tags: ['Air Purifier', 'Philips', 'HEPA', 'IAQI Sensor', 'Auto Mode'],
    apiSource: 'static',
  },
  {
    id: 'IN2-HA-HV-003',
    name: 'Havells I-Cool 85L Desert Air Cooler — White',
    brand: 'Havells',
    subBrand: 'I-Cool',
    category: 'home-appliances',
    subCategory: 'air-coolers',
    variant: 'White 85L',
    description: '85L large tank, Turbo Cool technology, honeycomb pads, 4-way air deflection, castor wheels for mobility. Covers up to 400 sq ft.',
    price: 9490,
    originalPrice: 12490,
    discount: 24,
    image: '/assets/products/havells/i-cool-85l-white.jpg',
    affiliateUrl: '/go/IN2-HA-HV-003',
    affiliatePlatform: 'flipkart',
    affiliateSource: 'flipkart-affiliate-free',
    inStock: true,
    isFeatured: true,
    isTrending: true,
    rating: 4.2,
    reviewCount: 16300,
    tags: ['Air Cooler', 'Havells', '85L', 'Honeycomb Pad', 'Turbo Cool'],
    apiSource: 'static',
  },
  {
    id: 'IN2-HA-CR-003',
    name: 'Crompton Greaves 25L Instant Water Heater — White',
    brand: 'Crompton',
    subBrand: 'Greaves',
    category: 'home-appliances',
    subCategory: 'water-heaters',
    variant: 'White 25L',
    description: '2000W, 25L storage, 5-star BEE rating, anti-rust inner tank, adjustable thermostat, ISI marked. Reliable family-size geyser.',
    price: 4999,
    originalPrice: 6999,
    discount: 29,
    image: '/assets/products/crompton/25l-water-heater-white.jpg',
    affiliateUrl: '/go/IN2-HA-CR-003',
    affiliatePlatform: 'amazon',
    affiliateSource: 'amazon-pa-api-free',
    inStock: true,
    isFeatured: false,
    isTrending: false,
    rating: 4.3,
    reviewCount: 12400,
    tags: ['Geyser', 'Crompton', '25L', '5-Star', 'Anti-Rust'],
    apiSource: 'static',
  },
  {
    id: 'IN2-HA-PH-003',
    name: 'Philips HL7756 Mixer Grinder 550W — Blue',
    brand: 'Philips',
    subBrand: 'Daily Collection',
    category: 'home-appliances',
    subCategory: 'kitchen-appliances',
    variant: 'Vivid Blue 550W',
    description: '550W motor, 3 stainless steel jars (1.5L + 1L + 0.4L), 3-speed + pulse, overload protection. Kitchen workhorse by Philips.',
    price: 2999,
    originalPrice: 4499,
    discount: 33,
    image: '/assets/products/philips/hl7756-mixer-grinder-blue.jpg',
    affiliateUrl: '/go/IN2-HA-PH-003',
    affiliatePlatform: 'amazon',
    affiliateSource: 'amazon-pa-api-free',
    inStock: true,
    isFeatured: false,
    isTrending: true,
    rating: 4.4,
    reviewCount: 27800,
    tags: ['Mixer Grinder', 'Philips', '550W', '3 Jars', 'Kitchen'],
    apiSource: 'static',
  },
  {
    id: 'IN2-HA-HV-004',
    name: 'Havells Gracia 1.5 Ton 3-Star Inverter AC — White',
    brand: 'Havells',
    subBrand: 'Gracia',
    category: 'home-appliances',
    subCategory: 'air-conditioners',
    variant: 'White 1.5 Ton 3-Star',
    description: '1.5 Ton 3-star BEE rated inverter split AC, PM 2.5 filter, auto clean, Wi-Fi ready, ISEER 3.6. Suitable for rooms up to 150 sq ft.',
    price: 34990,
    originalPrice: 44990,
    discount: 22,
    image: '/assets/products/havells/gracia-1-5-ton-ac-white.jpg',
    affiliateUrl: '/go/IN2-HA-HV-004',
    affiliatePlatform: 'flipkart',
    affiliateSource: 'flipkart-affiliate-free',
    inStock: true,
    isFeatured: true,
    isTrending: true,
    rating: 4.3,
    reviewCount: 5900,
    tags: ['AC', 'Havells', 'Inverter', '1.5 Ton', '3-Star BEE'],
    apiSource: 'static',
  },
]
