import { IndiaProduct } from "../types"

// ──────────────────────────────────────────────
// BAJAJ ELECTRICALS — 50 products (IN-HA-BAJ-001 → 050)
// ──────────────────────────────────────────────

export const BAJAJ_PRODUCTS: IndiaProduct[] = [
  // ── FANS (001–010) ──────────────────────────
  {
    id: "IN-HA-BAJ-001",
    name: "Bajaj Kassels 1200mm Ceiling Fan — White",
    brand: "Bajaj Electricals",
    subBrand: "Kassels",
    category: "home-appliances",
    subCategory: "fans",
    variant: "White",
    description: "Bajaj Kassels 1200mm ceiling fan with aerodynamic blade design for high air delivery.",
    price: 1549,
    originalPrice: 1799,
    discount: 14,
    image: "/assets/products/IN-HA-BAJ-001.jpg",
    affiliateUrl: "/go/IN-HA-BAJ-001",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.2,
    reviewCount: 12400,
    tags: ["home-appliances", "bajaj", "Kassels", "ceiling-fan", "fan"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-BAJ-002",
    name: "Bajaj Kassels 1200mm Ceiling Fan — Brown",
    brand: "Bajaj Electricals",
    subBrand: "Kassels",
    category: "home-appliances",
    subCategory: "fans",
    variant: "Brown",
    description: "Bajaj Kassels 1200mm ceiling fan with aerodynamic blade design for high air delivery.",
    price: 1549,
    originalPrice: 1799,
    discount: 14,
    image: "/assets/products/IN-HA-BAJ-002.jpg",
    affiliateUrl: "/go/IN-HA-BAJ-002",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.2,
    reviewCount: 11800,
    tags: ["home-appliances", "bajaj", "Kassels", "ceiling-fan", "fan"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-BAJ-003",
    name: "Bajaj Esteem 1200mm Ceiling Fan — White",
    brand: "Bajaj Electricals",
    subBrand: "Esteem",
    category: "home-appliances",
    subCategory: "fans",
    variant: "White",
    description: "Bajaj Esteem 1200mm ceiling fan with double ball bearing motor for silent operation.",
    price: 1699,
    originalPrice: 1999,
    discount: 15,
    image: "/assets/products/IN-HA-BAJ-003.jpg",
    affiliateUrl: "/go/IN-HA-BAJ-003",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.3,
    reviewCount: 9800,
    tags: ["home-appliances", "bajaj", "Esteem", "ceiling-fan", "fan"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-BAJ-004",
    name: "Bajaj Esteem 1200mm Ceiling Fan — Pearl White",
    brand: "Bajaj Electricals",
    subBrand: "Esteem",
    category: "home-appliances",
    subCategory: "fans",
    variant: "Pearl White",
    description: "Bajaj Esteem 1200mm ceiling fan with double ball bearing motor for silent operation.",
    price: 1749,
    originalPrice: 1999,
    discount: 13,
    image: "/assets/products/IN-HA-BAJ-004.jpg",
    affiliateUrl: "/go/IN-HA-BAJ-004",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.3,
    reviewCount: 8500,
    tags: ["home-appliances", "bajaj", "Esteem", "ceiling-fan", "fan"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-BAJ-005",
    name: "Bajaj Midea 400mm Wall Fan — White",
    brand: "Bajaj Electricals",
    subBrand: "Midea",
    category: "home-appliances",
    subCategory: "fans",
    variant: "White",
    description: "Bajaj Midea 400mm wall fan with powerful motor and 3-speed control.",
    price: 2199,
    originalPrice: 2599,
    discount: 15,
    image: "/assets/products/IN-HA-BAJ-005.jpg",
    affiliateUrl: "/go/IN-HA-BAJ-005",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.1,
    reviewCount: 6700,
    tags: ["home-appliances", "bajaj", "Midea", "wall-fan", "fan"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-BAJ-006",
    name: "Bajaj Midea 400mm Wall Fan — Blue",
    brand: "Bajaj Electricals",
    subBrand: "Midea",
    category: "home-appliances",
    subCategory: "fans",
    variant: "Blue",
    description: "Bajaj Midea 400mm wall fan with powerful motor and 3-speed control.",
    price: 2199,
    originalPrice: 2599,
    discount: 15,
    image: "/assets/products/IN-HA-BAJ-006.jpg",
    affiliateUrl: "/go/IN-HA-BAJ-006",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.1,
    reviewCount: 5900,
    tags: ["home-appliances", "bajaj", "Midea", "wall-fan", "fan"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-BAJ-007",
    name: "Bajaj Grace 1200mm Ceiling Fan — Ivory",
    brand: "Bajaj Electricals",
    subBrand: "Grace",
    category: "home-appliances",
    subCategory: "fans",
    variant: "Ivory",
    description: "Bajaj Grace 1200mm ceiling fan with elegant design and energy-efficient motor.",
    price: 1399,
    originalPrice: 1649,
    discount: 15,
    image: "/assets/products/IN-HA-BAJ-007.jpg",
    affiliateUrl: "/go/IN-HA-BAJ-007",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.0,
    reviewCount: 7200,
    tags: ["home-appliances", "bajaj", "Grace", "ceiling-fan", "fan"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-BAJ-008",
    name: "Bajaj Grace 1200mm Ceiling Fan — Ivory Brown",
    brand: "Bajaj Electricals",
    subBrand: "Grace",
    category: "home-appliances",
    subCategory: "fans",
    variant: "Ivory Brown",
    description: "Bajaj Grace 1200mm ceiling fan with elegant design and energy-efficient motor.",
    price: 1399,
    originalPrice: 1649,
    discount: 15,
    image: "/assets/products/IN-HA-BAJ-008.jpg",
    affiliateUrl: "/go/IN-HA-BAJ-008",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.0,
    reviewCount: 6100,
    tags: ["home-appliances", "bajaj", "Grace", "ceiling-fan", "fan"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-BAJ-009",
    name: "Bajaj Euro 50W Pedestal Fan — White",
    brand: "Bajaj Electricals",
    subBrand: "Euro",
    category: "home-appliances",
    subCategory: "fans",
    variant: "White",
    description: "Bajaj Euro 50W pedestal fan with adjustable height and tilt mechanism.",
    price: 2799,
    originalPrice: 3299,
    discount: 15,
    image: "/assets/products/IN-HA-BAJ-009.jpg",
    affiliateUrl: "/go/IN-HA-BAJ-009",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.2,
    reviewCount: 5400,
    tags: ["home-appliances", "bajaj", "Euro", "pedestal-fan", "fan"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-BAJ-010",
    name: "Bajaj Euro 50W Pedestal Fan — Blue",
    brand: "Bajaj Electricals",
    subBrand: "Euro",
    category: "home-appliances",
    subCategory: "fans",
    variant: "Blue",
    description: "Bajaj Euro 50W pedestal fan with adjustable height and tilt mechanism.",
    price: 2799,
    originalPrice: 3299,
    discount: 15,
    image: "/assets/products/IN-HA-BAJ-010.jpg",
    affiliateUrl: "/go/IN-HA-BAJ-010",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.2,
    reviewCount: 4800,
    tags: ["home-appliances", "bajaj", "Euro", "pedestal-fan", "fan"],
    apiSource: "amazon-pa-api-free"
  },

  // ── IRONS (011–020) ────────────────────────
  {
    id: "IN-HA-BAJ-011",
    name: "Bajaj MX 15 1000W Dry Iron — Purple Orchid",
    brand: "Bajaj Electricals",
    subBrand: "MX",
    category: "home-appliances",
    subCategory: "irons",
    variant: "Purple Orchid",
    description: "Bajaj MX 15 1000W dry iron with non-stick coated soleplate for smooth gliding.",
    price: 549,
    originalPrice: 699,
    discount: 21,
    image: "/assets/products/IN-HA-BAJ-011.jpg",
    affiliateUrl: "/go/IN-HA-BAJ-011",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.1,
    reviewCount: 18200,
    tags: ["home-appliances", "bajaj", "MX", "dry-iron", "iron"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-BAJ-012",
    name: "Bajaj MX 15 1000W Dry Iron — Crimson",
    brand: "Bajaj Electricals",
    subBrand: "MX",
    category: "home-appliances",
    subCategory: "irons",
    variant: "Crimson",
    description: "Bajaj MX 15 1000W dry iron with non-stick coated soleplate for smooth gliding.",
    price: 549,
    originalPrice: 699,
    discount: 21,
    image: "/assets/products/IN-HA-BAJ-012.jpg",
    affiliateUrl: "/go/IN-HA-BAJ-012",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.1,
    reviewCount: 16500,
    tags: ["home-appliances", "bajaj", "MX", "dry-iron", "iron"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-BAJ-013",
    name: "Bajaj Majesty DX 7 1000W Dry Iron — Blue White",
    brand: "Bajaj Electricals",
    subBrand: "Majesty",
    category: "home-appliances",
    subCategory: "irons",
    variant: "Blue White",
    description: "Bajaj Majesty DX 7 1000W dry iron with temperature control dial and indicator light.",
    price: 599,
    originalPrice: 749,
    discount: 20,
    image: "/assets/products/IN-HA-BAJ-013.jpg",
    affiliateUrl: "/go/IN-HA-BAJ-013",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.2,
    reviewCount: 14300,
    tags: ["home-appliances", "bajaj", "Majesty", "dry-iron", "iron"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-BAJ-014",
    name: "Bajaj Majesty DX 7 1000W Dry Iron — Pink White",
    brand: "Bajaj Electricals",
    subBrand: "Majesty",
    category: "home-appliances",
    subCategory: "irons",
    variant: "Pink White",
    description: "Bajaj Majesty DX 7 1000W dry iron with temperature control dial and indicator light.",
    price: 599,
    originalPrice: 749,
    discount: 20,
    image: "/assets/products/IN-HA-BAJ-014.jpg",
    affiliateUrl: "/go/IN-HA-BAJ-014",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.2,
    reviewCount: 12800,
    tags: ["home-appliances", "bajaj", "Majesty", "dry-iron", "iron"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-BAJ-015",
    name: "Bajaj Nova NX4 1200W Dry Iron — Blue",
    brand: "Bajaj Electricals",
    subBrand: "Nova",
    category: "home-appliances",
    subCategory: "irons",
    variant: "Blue",
    description: "Bajaj Nova NX4 1200W dry iron with powerful heating element and lightweight design.",
    price: 699,
    originalPrice: 849,
    discount: 18,
    image: "/assets/products/IN-HA-BAJ-015.jpg",
    affiliateUrl: "/go/IN-HA-BAJ-015",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.0,
    reviewCount: 9600,
    tags: ["home-appliances", "bajaj", "Nova", "dry-iron", "iron"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-BAJ-016",
    name: "Bajaj Nova NX4 1200W Dry Iron — Purple",
    brand: "Bajaj Electricals",
    subBrand: "Nova",
    category: "home-appliances",
    subCategory: "irons",
    variant: "Purple",
    description: "Bajaj Nova NX4 1200W dry iron with powerful heating element and lightweight design.",
    price: 699,
    originalPrice: 849,
    discount: 18,
    image: "/assets/products/IN-HA-BAJ-016.jpg",
    affiliateUrl: "/go/IN-HA-BAJ-016",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.0,
    reviewCount: 8200,
    tags: ["home-appliances", "bajaj", "Nova", "dry-iron", "iron"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-BAJ-017",
    name: "Bajaj Majesty SX7 2000W Steam Iron — Blue White",
    brand: "Bajaj Electricals",
    subBrand: "Majesty",
    category: "home-appliances",
    subCategory: "irons",
    variant: "Blue White",
    description: "Bajaj Majesty SX7 2000W steam iron with vertical steam and self-cleaning function.",
    price: 1299,
    originalPrice: 1599,
    discount: 19,
    image: "/assets/products/IN-HA-BAJ-017.jpg",
    affiliateUrl: "/go/IN-HA-BAJ-017",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.3,
    reviewCount: 11200,
    tags: ["home-appliances", "bajaj", "Majesty", "steam-iron", "iron"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-BAJ-018",
    name: "Bajaj Majesty SX7 2000W Steam Iron — Silver",
    brand: "Bajaj Electricals",
    subBrand: "Majesty",
    category: "home-appliances",
    subCategory: "irons",
    variant: "Silver",
    description: "Bajaj Majesty SX7 2000W steam iron with vertical steam and self-cleaning function.",
    price: 1299,
    originalPrice: 1599,
    discount: 19,
    image: "/assets/products/IN-HA-BAJ-018.jpg",
    affiliateUrl: "/go/IN-HA-BAJ-018",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.3,
    reviewCount: 10100,
    tags: ["home-appliances", "bajaj", "Majesty", "steam-iron", "iron"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-BAJ-019",
    name: "Bajaj Majesty SX11 2200W Steam Iron — Blue",
    brand: "Bajaj Electricals",
    subBrand: "Majesty",
    category: "home-appliances",
    subCategory: "irons",
    variant: "Blue",
    description: "Bajaj Majesty SX11 2200W steam iron with ceramic soleplate and anti-drip system.",
    price: 1599,
    originalPrice: 1899,
    discount: 16,
    image: "/assets/products/IN-HA-BAJ-019.jpg",
    affiliateUrl: "/go/IN-HA-BAJ-019",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.4,
    reviewCount: 8700,
    tags: ["home-appliances", "bajaj", "Majesty", "steam-iron", "iron"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-BAJ-020",
    name: "Bajaj Majesty SX11 2200W Steam Iron — Purple",
    brand: "Bajaj Electricals",
    subBrand: "Majesty",
    category: "home-appliances",
    subCategory: "irons",
    variant: "Purple",
    description: "Bajaj Majesty SX11 2200W steam iron with ceramic soleplate and anti-drip system.",
    price: 1599,
    originalPrice: 1899,
    discount: 16,
    image: "/assets/products/IN-HA-BAJ-020.jpg",
    affiliateUrl: "/go/IN-HA-BAJ-020",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.4,
    reviewCount: 7900,
    tags: ["home-appliances", "bajaj", "Majesty", "steam-iron", "iron"],
    apiSource: "amazon-pa-api-free"
  },

  // ── MIXER GRINDERS (021–030) ────────────────
  {
    id: "IN-HA-BAJ-021",
    name: "Bajaj GX3 500W Mixer Grinder 3 Jars — White",
    brand: "Bajaj Electricals",
    subBrand: "GX",
    category: "home-appliances",
    subCategory: "mixer-grinders",
    variant: "White",
    description: "Bajaj GX3 500W mixer grinder with 3 stainless steel jars and multi-purpose blades.",
    price: 2149,
    originalPrice: 2599,
    discount: 17,
    image: "/assets/products/IN-HA-BAJ-021.jpg",
    affiliateUrl: "/go/IN-HA-BAJ-021",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.2,
    reviewCount: 22100,
    tags: ["home-appliances", "bajaj", "GX", "mixer-grinder", "kitchen"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-BAJ-022",
    name: "Bajaj GX3 500W Mixer Grinder 3 Jars — Red",
    brand: "Bajaj Electricals",
    subBrand: "GX",
    category: "home-appliances",
    subCategory: "mixer-grinders",
    variant: "Red",
    description: "Bajaj GX3 500W mixer grinder with 3 stainless steel jars and multi-purpose blades.",
    price: 2149,
    originalPrice: 2599,
    discount: 17,
    image: "/assets/products/IN-HA-BAJ-022.jpg",
    affiliateUrl: "/go/IN-HA-BAJ-022",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.2,
    reviewCount: 19800,
    tags: ["home-appliances", "bajaj", "GX", "mixer-grinder", "kitchen"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-BAJ-023",
    name: "Bajaj GX8 800W Mixer Grinder 3 Jars — White",
    brand: "Bajaj Electricals",
    subBrand: "GX",
    category: "home-appliances",
    subCategory: "mixer-grinders",
    variant: "White",
    description: "Bajaj GX8 800W mixer grinder with 3 jars and powerful motor for heavy-duty grinding.",
    price: 3299,
    originalPrice: 3899,
    discount: 15,
    image: "/assets/products/IN-HA-BAJ-023.jpg",
    affiliateUrl: "/go/IN-HA-BAJ-023",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.3,
    reviewCount: 15600,
    tags: ["home-appliances", "bajaj", "GX", "mixer-grinder", "kitchen"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-BAJ-024",
    name: "Bajaj GX8 800W Mixer Grinder 3 Jars — Blue",
    brand: "Bajaj Electricals",
    subBrand: "GX",
    category: "home-appliances",
    subCategory: "mixer-grinders",
    variant: "Blue",
    description: "Bajaj GX8 800W mixer grinder with 3 jars and powerful motor for heavy-duty grinding.",
    price: 3299,
    originalPrice: 3899,
    discount: 15,
    image: "/assets/products/IN-HA-BAJ-024.jpg",
    affiliateUrl: "/go/IN-HA-BAJ-024",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.3,
    reviewCount: 14200,
    tags: ["home-appliances", "bajaj", "GX", "mixer-grinder", "kitchen"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-BAJ-025",
    name: "Bajaj Platini PX55 600W Mixer Grinder — White",
    brand: "Bajaj Electricals",
    subBrand: "Platini",
    category: "home-appliances",
    subCategory: "mixer-grinders",
    variant: "White",
    description: "Bajaj Platini PX55 600W mixer grinder with 3 jars and overload protection.",
    price: 2699,
    originalPrice: 3199,
    discount: 16,
    image: "/assets/products/IN-HA-BAJ-025.jpg",
    affiliateUrl: "/go/IN-HA-BAJ-025",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.1,
    reviewCount: 10400,
    tags: ["home-appliances", "bajaj", "Platini", "mixer-grinder", "kitchen"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-BAJ-026",
    name: "Bajaj Platini PX55 600W Mixer Grinder — Black",
    brand: "Bajaj Electricals",
    subBrand: "Platini",
    category: "home-appliances",
    subCategory: "mixer-grinders",
    variant: "Black",
    description: "Bajaj Platini PX55 600W mixer grinder with 3 jars and overload protection.",
    price: 2699,
    originalPrice: 3199,
    discount: 16,
    image: "/assets/products/IN-HA-BAJ-026.jpg",
    affiliateUrl: "/go/IN-HA-BAJ-026",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.1,
    reviewCount: 9100,
    tags: ["home-appliances", "bajaj", "Platini", "mixer-grinder", "kitchen"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-BAJ-027",
    name: "Bajaj Classic 500W Mixer 3 Jar — White",
    brand: "Bajaj Electricals",
    subBrand: "Classic",
    category: "home-appliances",
    subCategory: "mixer-grinders",
    variant: "White",
    description: "Bajaj Classic 500W mixer grinder with 3 stainless steel jars for everyday kitchen needs.",
    price: 1999,
    originalPrice: 2399,
    discount: 17,
    image: "/assets/products/IN-HA-BAJ-027.jpg",
    affiliateUrl: "/go/IN-HA-BAJ-027",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.0,
    reviewCount: 17800,
    tags: ["home-appliances", "bajaj", "Classic", "mixer-grinder", "kitchen"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-BAJ-028",
    name: "Bajaj Classic 500W Mixer 3 Jar — Silver",
    brand: "Bajaj Electricals",
    subBrand: "Classic",
    category: "home-appliances",
    subCategory: "mixer-grinders",
    variant: "Silver",
    description: "Bajaj Classic 500W mixer grinder with 3 stainless steel jars for everyday kitchen needs.",
    price: 1999,
    originalPrice: 2399,
    discount: 17,
    image: "/assets/products/IN-HA-BAJ-028.jpg",
    affiliateUrl: "/go/IN-HA-BAJ-028",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.0,
    reviewCount: 15200,
    tags: ["home-appliances", "bajaj", "Classic", "mixer-grinder", "kitchen"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-BAJ-029",
    name: "Bajaj Rex 500W Mixer 3 Jar — White",
    brand: "Bajaj Electricals",
    subBrand: "Rex",
    category: "home-appliances",
    subCategory: "mixer-grinders",
    variant: "White",
    description: "Bajaj Rex 500W mixer grinder with 3 jars and motor overload protector.",
    price: 1849,
    originalPrice: 2249,
    discount: 18,
    image: "/assets/products/IN-HA-BAJ-029.jpg",
    affiliateUrl: "/go/IN-HA-BAJ-029",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.1,
    reviewCount: 24500,
    tags: ["home-appliances", "bajaj", "Rex", "mixer-grinder", "kitchen"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-BAJ-030",
    name: "Bajaj Rex 500W Mixer 3 Jar — Black",
    brand: "Bajaj Electricals",
    subBrand: "Rex",
    category: "home-appliances",
    subCategory: "mixer-grinders",
    variant: "Black",
    description: "Bajaj Rex 500W mixer grinder with 3 jars and motor overload protector.",
    price: 1849,
    originalPrice: 2249,
    discount: 18,
    image: "/assets/products/IN-HA-BAJ-030.jpg",
    affiliateUrl: "/go/IN-HA-BAJ-030",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.1,
    reviewCount: 21300,
    tags: ["home-appliances", "bajaj", "Rex", "mixer-grinder", "kitchen"],
    apiSource: "amazon-pa-api-free"
  },

  // ── WATER HEATERS (031–040) ─────────────────
  {
    id: "IN-HA-BAJ-031",
    name: "Bajaj New Shakti Storage 10L Water Heater — White",
    brand: "Bajaj Electricals",
    subBrand: "New Shakti",
    category: "home-appliances",
    subCategory: "water-heaters",
    variant: "White / 10L",
    description: "Bajaj New Shakti 10L storage water heater with glass-lined tank and titanium armour.",
    price: 5499,
    originalPrice: 6499,
    discount: 15,
    image: "/assets/products/IN-HA-BAJ-031.jpg",
    affiliateUrl: "/go/IN-HA-BAJ-031",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.2,
    reviewCount: 19700,
    tags: ["home-appliances", "bajaj", "New Shakti", "water-heater", "geyser"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-BAJ-032",
    name: "Bajaj New Shakti Storage 10L Water Heater — Blue Grey",
    brand: "Bajaj Electricals",
    subBrand: "New Shakti",
    category: "home-appliances",
    subCategory: "water-heaters",
    variant: "Blue Grey / 10L",
    description: "Bajaj New Shakti 10L storage water heater with glass-lined tank and titanium armour.",
    price: 5499,
    originalPrice: 6499,
    discount: 15,
    image: "/assets/products/IN-HA-BAJ-032.jpg",
    affiliateUrl: "/go/IN-HA-BAJ-032",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.2,
    reviewCount: 17400,
    tags: ["home-appliances", "bajaj", "New Shakti", "water-heater", "geyser"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-BAJ-033",
    name: "Bajaj New Shakti Storage 15L Water Heater — White",
    brand: "Bajaj Electricals",
    subBrand: "New Shakti",
    category: "home-appliances",
    subCategory: "water-heaters",
    variant: "White / 15L",
    description: "Bajaj New Shakti 15L storage water heater with swirl flow technology.",
    price: 6499,
    originalPrice: 7699,
    discount: 16,
    image: "/assets/products/IN-HA-BAJ-033.jpg",
    affiliateUrl: "/go/IN-HA-BAJ-033",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.3,
    reviewCount: 16200,
    tags: ["home-appliances", "bajaj", "New Shakti", "water-heater", "geyser"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-BAJ-034",
    name: "Bajaj New Shakti Storage 15L Water Heater — Ivory",
    brand: "Bajaj Electricals",
    subBrand: "New Shakti",
    category: "home-appliances",
    subCategory: "water-heaters",
    variant: "Ivory / 15L",
    description: "Bajaj New Shakti 15L storage water heater with swirl flow technology.",
    price: 6499,
    originalPrice: 7699,
    discount: 16,
    image: "/assets/products/IN-HA-BAJ-034.jpg",
    affiliateUrl: "/go/IN-HA-BAJ-034",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.3,
    reviewCount: 14800,
    tags: ["home-appliances", "bajaj", "New Shakti", "water-heater", "geyser"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-BAJ-035",
    name: "Bajaj New Shakti Storage 25L Water Heater — White",
    brand: "Bajaj Electricals",
    subBrand: "New Shakti",
    category: "home-appliances",
    subCategory: "water-heaters",
    variant: "White / 25L",
    description: "Bajaj New Shakti 25L storage water heater with high-density PUF insulation.",
    price: 7999,
    originalPrice: 9499,
    discount: 16,
    image: "/assets/products/IN-HA-BAJ-035.jpg",
    affiliateUrl: "/go/IN-HA-BAJ-035",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.3,
    reviewCount: 13500,
    tags: ["home-appliances", "bajaj", "New Shakti", "water-heater", "geyser"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-BAJ-036",
    name: "Bajaj New Shakti Storage 25L Water Heater — Steel",
    brand: "Bajaj Electricals",
    subBrand: "New Shakti",
    category: "home-appliances",
    subCategory: "water-heaters",
    variant: "Steel / 25L",
    description: "Bajaj New Shakti 25L storage water heater with high-density PUF insulation.",
    price: 7999,
    originalPrice: 9499,
    discount: 16,
    image: "/assets/products/IN-HA-BAJ-036.jpg",
    affiliateUrl: "/go/IN-HA-BAJ-036",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.3,
    reviewCount: 11900,
    tags: ["home-appliances", "bajaj", "New Shakti", "water-heater", "geyser"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-BAJ-037",
    name: "Bajaj Calenta Storage 10L Water Heater — White Silver",
    brand: "Bajaj Electricals",
    subBrand: "Calenta",
    category: "home-appliances",
    subCategory: "water-heaters",
    variant: "White Silver / 10L",
    description: "Bajaj Calenta 10L storage water heater with child safety mode and LED indicators.",
    price: 7499,
    originalPrice: 8999,
    discount: 17,
    image: "/assets/products/IN-HA-BAJ-037.jpg",
    affiliateUrl: "/go/IN-HA-BAJ-037",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.4,
    reviewCount: 8600,
    tags: ["home-appliances", "bajaj", "Calenta", "water-heater", "geyser"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-BAJ-038",
    name: "Bajaj Calenta Storage 10L Water Heater — Blue",
    brand: "Bajaj Electricals",
    subBrand: "Calenta",
    category: "home-appliances",
    subCategory: "water-heaters",
    variant: "Blue / 10L",
    description: "Bajaj Calenta 10L storage water heater with child safety mode and LED indicators.",
    price: 7499,
    originalPrice: 8999,
    discount: 17,
    image: "/assets/products/IN-HA-BAJ-038.jpg",
    affiliateUrl: "/go/IN-HA-BAJ-038",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.4,
    reviewCount: 7200,
    tags: ["home-appliances", "bajaj", "Calenta", "water-heater", "geyser"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-BAJ-039",
    name: "Bajaj Juvel 3L Instant Water Heater — White",
    brand: "Bajaj Electricals",
    subBrand: "Juvel",
    category: "home-appliances",
    subCategory: "water-heaters",
    variant: "White / 3L",
    description: "Bajaj Juvel 3L instant water heater with ISI mark and fire retardant cable.",
    price: 3299,
    originalPrice: 3999,
    discount: 18,
    image: "/assets/products/IN-HA-BAJ-039.jpg",
    affiliateUrl: "/go/IN-HA-BAJ-039",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.1,
    reviewCount: 14300,
    tags: ["home-appliances", "bajaj", "Juvel", "instant-water-heater", "geyser"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-BAJ-040",
    name: "Bajaj Juvel 3L Instant Water Heater — Ivory",
    brand: "Bajaj Electricals",
    subBrand: "Juvel",
    category: "home-appliances",
    subCategory: "water-heaters",
    variant: "Ivory / 3L",
    description: "Bajaj Juvel 3L instant water heater with ISI mark and fire retardant cable.",
    price: 3299,
    originalPrice: 3999,
    discount: 18,
    image: "/assets/products/IN-HA-BAJ-040.jpg",
    affiliateUrl: "/go/IN-HA-BAJ-040",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.1,
    reviewCount: 12600,
    tags: ["home-appliances", "bajaj", "Juvel", "instant-water-heater", "geyser"],
    apiSource: "amazon-pa-api-free"
  },

  // ── JUICERS AND BLENDERS (041–050) ──────────
  {
    id: "IN-HA-BAJ-041",
    name: "Bajaj JX5 25W Citrus Juicer — White",
    brand: "Bajaj Electricals",
    subBrand: "JX",
    category: "home-appliances",
    subCategory: "juicers-blenders",
    variant: "White",
    description: "Bajaj JX5 25W citrus juicer with dual-direction rotation for maximum extraction.",
    price: 749,
    originalPrice: 899,
    discount: 17,
    image: "/assets/products/IN-HA-BAJ-041.jpg",
    affiliateUrl: "/go/IN-HA-BAJ-041",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 3.9,
    reviewCount: 8200,
    tags: ["home-appliances", "bajaj", "JX", "citrus-juicer", "juicer"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-BAJ-042",
    name: "Bajaj JX5 25W Citrus Juicer — Orange",
    brand: "Bajaj Electricals",
    subBrand: "JX",
    category: "home-appliances",
    subCategory: "juicers-blenders",
    variant: "Orange",
    description: "Bajaj JX5 25W citrus juicer with dual-direction rotation for maximum extraction.",
    price: 749,
    originalPrice: 899,
    discount: 17,
    image: "/assets/products/IN-HA-BAJ-042.jpg",
    affiliateUrl: "/go/IN-HA-BAJ-042",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 3.9,
    reviewCount: 7100,
    tags: ["home-appliances", "bajaj", "JX", "citrus-juicer", "juicer"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-BAJ-043",
    name: "Bajaj Rex Blender 400W — White",
    brand: "Bajaj Electricals",
    subBrand: "Rex",
    category: "home-appliances",
    subCategory: "juicers-blenders",
    variant: "White",
    description: "Bajaj Rex 400W blender with sturdy 1.5L jar and 3-speed control.",
    price: 1599,
    originalPrice: 1899,
    discount: 16,
    image: "/assets/products/IN-HA-BAJ-043.jpg",
    affiliateUrl: "/go/IN-HA-BAJ-043",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.0,
    reviewCount: 6500,
    tags: ["home-appliances", "bajaj", "Rex", "blender", "kitchen"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-BAJ-044",
    name: "Bajaj Rex Blender 400W — Red",
    brand: "Bajaj Electricals",
    subBrand: "Rex",
    category: "home-appliances",
    subCategory: "juicers-blenders",
    variant: "Red",
    description: "Bajaj Rex 400W blender with sturdy 1.5L jar and 3-speed control.",
    price: 1599,
    originalPrice: 1899,
    discount: 16,
    image: "/assets/products/IN-HA-BAJ-044.jpg",
    affiliateUrl: "/go/IN-HA-BAJ-044",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.0,
    reviewCount: 5800,
    tags: ["home-appliances", "bajaj", "Rex", "blender", "kitchen"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-BAJ-045",
    name: "Bajaj Ninja 350W Personal Blender — Black",
    brand: "Bajaj Electricals",
    subBrand: "Ninja",
    category: "home-appliances",
    subCategory: "juicers-blenders",
    variant: "Black",
    description: "Bajaj Ninja 350W personal blender with portable travel jar and one-touch operation.",
    price: 1299,
    originalPrice: 1549,
    discount: 16,
    image: "/assets/products/IN-HA-BAJ-045.jpg",
    affiliateUrl: "/go/IN-HA-BAJ-045",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.1,
    reviewCount: 4900,
    tags: ["home-appliances", "bajaj", "Ninja", "personal-blender", "blender"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-BAJ-046",
    name: "Bajaj Ninja 350W Personal Blender — Silver",
    brand: "Bajaj Electricals",
    subBrand: "Ninja",
    category: "home-appliances",
    subCategory: "juicers-blenders",
    variant: "Silver",
    description: "Bajaj Ninja 350W personal blender with portable travel jar and one-touch operation.",
    price: 1299,
    originalPrice: 1549,
    discount: 16,
    image: "/assets/products/IN-HA-BAJ-046.jpg",
    affiliateUrl: "/go/IN-HA-BAJ-046",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.1,
    reviewCount: 4200,
    tags: ["home-appliances", "bajaj", "Ninja", "personal-blender", "blender"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-BAJ-047",
    name: "Bajaj Fruity 250W Citrus Juicer — Yellow",
    brand: "Bajaj Electricals",
    subBrand: "Fruity",
    category: "home-appliances",
    subCategory: "juicers-blenders",
    variant: "Yellow",
    description: "Bajaj Fruity 250W citrus juicer with transparent container and pulp regulator.",
    price: 999,
    originalPrice: 1199,
    discount: 17,
    image: "/assets/products/IN-HA-BAJ-047.jpg",
    affiliateUrl: "/go/IN-HA-BAJ-047",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.0,
    reviewCount: 5600,
    tags: ["home-appliances", "bajaj", "Fruity", "citrus-juicer", "juicer"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-BAJ-048",
    name: "Bajaj Fruity 250W Citrus Juicer — Lime",
    brand: "Bajaj Electricals",
    subBrand: "Fruity",
    category: "home-appliances",
    subCategory: "juicers-blenders",
    variant: "Lime",
    description: "Bajaj Fruity 250W citrus juicer with transparent container and pulp regulator.",
    price: 999,
    originalPrice: 1199,
    discount: 17,
    image: "/assets/products/IN-HA-BAJ-048.jpg",
    affiliateUrl: "/go/IN-HA-BAJ-048",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.0,
    reviewCount: 4800,
    tags: ["home-appliances", "bajaj", "Fruity", "citrus-juicer", "juicer"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-BAJ-049",
    name: "Bajaj Classic 100W Hand Blender — White",
    brand: "Bajaj Electricals",
    subBrand: "Classic",
    category: "home-appliances",
    subCategory: "juicers-blenders",
    variant: "White",
    description: "Bajaj Classic 100W hand blender with stainless steel blade and ergonomic grip.",
    price: 649,
    originalPrice: 799,
    discount: 19,
    image: "/assets/products/IN-HA-BAJ-049.jpg",
    affiliateUrl: "/go/IN-HA-BAJ-049",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 3.9,
    reviewCount: 7300,
    tags: ["home-appliances", "bajaj", "Classic", "hand-blender", "blender"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-BAJ-050",
    name: "Bajaj Classic 100W Hand Blender — Black",
    brand: "Bajaj Electricals",
    subBrand: "Classic",
    category: "home-appliances",
    subCategory: "juicers-blenders",
    variant: "Black",
    description: "Bajaj Classic 100W hand blender with stainless steel blade and ergonomic grip.",
    price: 649,
    originalPrice: 799,
    discount: 19,
    image: "/assets/products/IN-HA-BAJ-050.jpg",
    affiliateUrl: "/go/IN-HA-BAJ-050",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 3.9,
    reviewCount: 6400,
    tags: ["home-appliances", "bajaj", "Classic", "hand-blender", "blender"],
    apiSource: "amazon-pa-api-free"
  }
]

// ──────────────────────────────────────────────
// HAVELLS — 50 products (IN-HA-HAV-001 → 050)
// ──────────────────────────────────────────────

export const HAVELLS_PRODUCTS: IndiaProduct[] = [
  // ── FANS (001–010) ──────────────────────────
  {
    id: "IN-HA-HAV-001",
    name: "Havells Stealth Air 1200mm BLDC Ceiling Fan — Pearl White",
    brand: "Havells",
    subBrand: "Stealth Air",
    category: "home-appliances",
    subCategory: "fans",
    variant: "Pearl White",
    description: "Havells Stealth Air 1200mm BLDC ceiling fan with remote control and energy-saving motor.",
    price: 3999,
    originalPrice: 4799,
    discount: 17,
    image: "/assets/products/IN-HA-HAV-001.jpg",
    affiliateUrl: "/go/IN-HA-HAV-001",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.5,
    reviewCount: 18400,
    tags: ["home-appliances", "havells", "Stealth Air", "ceiling-fan", "BLDC", "fan"],
    isTrending: true,
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-HAV-002",
    name: "Havells Stealth Air 1200mm BLDC Ceiling Fan — Matt Black",
    brand: "Havells",
    subBrand: "Stealth Air",
    category: "home-appliances",
    subCategory: "fans",
    variant: "Matt Black",
    description: "Havells Stealth Air 1200mm BLDC ceiling fan with remote control and energy-saving motor.",
    price: 3999,
    originalPrice: 4799,
    discount: 17,
    image: "/assets/products/IN-HA-HAV-002.jpg",
    affiliateUrl: "/go/IN-HA-HAV-002",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.5,
    reviewCount: 16200,
    tags: ["home-appliances", "havells", "Stealth Air", "ceiling-fan", "BLDC", "fan"],
    isTrending: true,
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-HAV-003",
    name: "Havells Ambrose 1200mm Ceiling Fan — Pearl White",
    brand: "Havells",
    subBrand: "Ambrose",
    category: "home-appliances",
    subCategory: "fans",
    variant: "Pearl White",
    description: "Havells Ambrose 1200mm decorative ceiling fan with dust-resistant finish.",
    price: 2499,
    originalPrice: 2999,
    discount: 17,
    image: "/assets/products/IN-HA-HAV-003.jpg",
    affiliateUrl: "/go/IN-HA-HAV-003",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.3,
    reviewCount: 14100,
    tags: ["home-appliances", "havells", "Ambrose", "ceiling-fan", "fan"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-HAV-004",
    name: "Havells Ambrose 1200mm Ceiling Fan — Antique Copper",
    brand: "Havells",
    subBrand: "Ambrose",
    category: "home-appliances",
    subCategory: "fans",
    variant: "Antique Copper",
    description: "Havells Ambrose 1200mm decorative ceiling fan with dust-resistant finish.",
    price: 2549,
    originalPrice: 2999,
    discount: 15,
    image: "/assets/products/IN-HA-HAV-004.jpg",
    affiliateUrl: "/go/IN-HA-HAV-004",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.3,
    reviewCount: 12500,
    tags: ["home-appliances", "havells", "Ambrose", "ceiling-fan", "fan"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-HAV-005",
    name: "Havells Troika 1320mm Ceiling Fan — Pearl White",
    brand: "Havells",
    subBrand: "Troika",
    category: "home-appliances",
    subCategory: "fans",
    variant: "Pearl White",
    description: "Havells Troika 1320mm premium ceiling fan with aerodynamic blades for maximum air thrust.",
    price: 2999,
    originalPrice: 3599,
    discount: 17,
    image: "/assets/products/IN-HA-HAV-005.jpg",
    affiliateUrl: "/go/IN-HA-HAV-005",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.4,
    reviewCount: 11200,
    tags: ["home-appliances", "havells", "Troika", "ceiling-fan", "fan"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-HAV-006",
    name: "Havells Troika 1320mm Ceiling Fan — Elegant Maroon",
    brand: "Havells",
    subBrand: "Troika",
    category: "home-appliances",
    subCategory: "fans",
    variant: "Elegant Maroon",
    description: "Havells Troika 1320mm premium ceiling fan with aerodynamic blades for maximum air thrust.",
    price: 2999,
    originalPrice: 3599,
    discount: 17,
    image: "/assets/products/IN-HA-HAV-006.jpg",
    affiliateUrl: "/go/IN-HA-HAV-006",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.4,
    reviewCount: 9800,
    tags: ["home-appliances", "havells", "Troika", "ceiling-fan", "fan"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-HAV-007",
    name: "Havells Sprint Lite 400mm Pedestal Fan — White",
    brand: "Havells",
    subBrand: "Sprint Lite",
    category: "home-appliances",
    subCategory: "fans",
    variant: "White",
    description: "Havells Sprint Lite 400mm pedestal fan with adjustable height and tilt.",
    price: 3299,
    originalPrice: 3899,
    discount: 15,
    image: "/assets/products/IN-HA-HAV-007.jpg",
    affiliateUrl: "/go/IN-HA-HAV-007",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.2,
    reviewCount: 7600,
    tags: ["home-appliances", "havells", "Sprint Lite", "pedestal-fan", "fan"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-HAV-008",
    name: "Havells Sprint Lite 400mm Pedestal Fan — Blue",
    brand: "Havells",
    subBrand: "Sprint Lite",
    category: "home-appliances",
    subCategory: "fans",
    variant: "Blue",
    description: "Havells Sprint Lite 400mm pedestal fan with adjustable height and tilt.",
    price: 3299,
    originalPrice: 3899,
    discount: 15,
    image: "/assets/products/IN-HA-HAV-008.jpg",
    affiliateUrl: "/go/IN-HA-HAV-008",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.2,
    reviewCount: 6400,
    tags: ["home-appliances", "havells", "Sprint Lite", "pedestal-fan", "fan"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-HAV-009",
    name: "Havells Alstorm 400mm Wall Fan — White",
    brand: "Havells",
    subBrand: "Alstorm",
    category: "home-appliances",
    subCategory: "fans",
    variant: "White",
    description: "Havells Alstorm 400mm wall fan with 100% copper winding motor.",
    price: 2799,
    originalPrice: 3299,
    discount: 15,
    image: "/assets/products/IN-HA-HAV-009.jpg",
    affiliateUrl: "/go/IN-HA-HAV-009",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.1,
    reviewCount: 8200,
    tags: ["home-appliances", "havells", "Alstorm", "wall-fan", "fan"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-HAV-010",
    name: "Havells Alstorm 400mm Wall Fan — Black",
    brand: "Havells",
    subBrand: "Alstorm",
    category: "home-appliances",
    subCategory: "fans",
    variant: "Black",
    description: "Havells Alstorm 400mm wall fan with 100% copper winding motor.",
    price: 2799,
    originalPrice: 3299,
    discount: 15,
    image: "/assets/products/IN-HA-HAV-010.jpg",
    affiliateUrl: "/go/IN-HA-HAV-010",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.1,
    reviewCount: 7100,
    tags: ["home-appliances", "havells", "Alstorm", "wall-fan", "fan"],
    apiSource: "amazon-pa-api-free"
  },

  // ── LIGHTING (011–020) ──────────────────────
  {
    id: "IN-HA-HAV-011",
    name: "Havells Adore 10W LED Bulb — Warm White 3000K",
    brand: "Havells",
    subBrand: "Adore",
    category: "home-appliances",
    subCategory: "lighting",
    variant: "Warm White 3000K",
    description: "Havells Adore 10W LED bulb with wide beam angle and 25000 hours lifespan.",
    price: 129,
    originalPrice: 175,
    discount: 26,
    image: "/assets/products/IN-HA-HAV-011.jpg",
    affiliateUrl: "/go/IN-HA-HAV-011",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.3,
    reviewCount: 32100,
    tags: ["home-appliances", "havells", "Adore", "LED-bulb", "lighting"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-HAV-012",
    name: "Havells Adore 10W LED Bulb — Cool Day Light 6500K",
    brand: "Havells",
    subBrand: "Adore",
    category: "home-appliances",
    subCategory: "lighting",
    variant: "Cool Day Light 6500K",
    description: "Havells Adore 10W LED bulb with wide beam angle and 25000 hours lifespan.",
    price: 129,
    originalPrice: 175,
    discount: 26,
    image: "/assets/products/IN-HA-HAV-012.jpg",
    affiliateUrl: "/go/IN-HA-HAV-012",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.3,
    reviewCount: 29800,
    tags: ["home-appliances", "havells", "Adore", "LED-bulb", "lighting"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-HAV-013",
    name: "Havells Lumeno 12W Panel Light — White",
    brand: "Havells",
    subBrand: "Lumeno",
    category: "home-appliances",
    subCategory: "lighting",
    variant: "White",
    description: "Havells Lumeno 12W slim LED panel light with uniform light distribution.",
    price: 449,
    originalPrice: 599,
    discount: 25,
    image: "/assets/products/IN-HA-HAV-013.jpg",
    affiliateUrl: "/go/IN-HA-HAV-013",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.2,
    reviewCount: 14600,
    tags: ["home-appliances", "havells", "Lumeno", "panel-light", "lighting"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-HAV-014",
    name: "Havells Lumeno 12W Panel Light — Pack of 2",
    brand: "Havells",
    subBrand: "Lumeno",
    category: "home-appliances",
    subCategory: "lighting",
    variant: "Pack of 2",
    description: "Havells Lumeno 12W slim LED panel light with uniform light distribution — value pack.",
    price: 849,
    originalPrice: 1198,
    discount: 29,
    image: "/assets/products/IN-HA-HAV-014.jpg",
    affiliateUrl: "/go/IN-HA-HAV-014",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.2,
    reviewCount: 11200,
    tags: ["home-appliances", "havells", "Lumeno", "panel-light", "lighting", "combo"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-HAV-015",
    name: "Havells Retrofit LED Tube 18W — Cool Day Light",
    brand: "Havells",
    subBrand: "Retrofit",
    category: "home-appliances",
    subCategory: "lighting",
    variant: "Cool Day Light",
    description: "Havells Retrofit 18W LED tube light — direct replacement for fluorescent tubes.",
    price: 199,
    originalPrice: 275,
    discount: 28,
    image: "/assets/products/IN-HA-HAV-015.jpg",
    affiliateUrl: "/go/IN-HA-HAV-015",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.1,
    reviewCount: 18900,
    tags: ["home-appliances", "havells", "Retrofit", "LED-tube", "lighting"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-HAV-016",
    name: "Havells Retrofit LED Tube 18W — Pack of 4",
    brand: "Havells",
    subBrand: "Retrofit",
    category: "home-appliances",
    subCategory: "lighting",
    variant: "Pack of 4",
    description: "Havells Retrofit 18W LED tube light — value pack of 4 for whole-home replacement.",
    price: 749,
    originalPrice: 1100,
    discount: 32,
    image: "/assets/products/IN-HA-HAV-016.jpg",
    affiliateUrl: "/go/IN-HA-HAV-016",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.1,
    reviewCount: 14500,
    tags: ["home-appliances", "havells", "Retrofit", "LED-tube", "lighting", "combo"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-HAV-017",
    name: "Havells Stigi 15W LED Downlight — White",
    brand: "Havells",
    subBrand: "Stigi",
    category: "home-appliances",
    subCategory: "lighting",
    variant: "White",
    description: "Havells Stigi 15W recessed LED downlight with high lumen output.",
    price: 399,
    originalPrice: 549,
    discount: 27,
    image: "/assets/products/IN-HA-HAV-017.jpg",
    affiliateUrl: "/go/IN-HA-HAV-017",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.2,
    reviewCount: 9800,
    tags: ["home-appliances", "havells", "Stigi", "downlight", "lighting"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-HAV-018",
    name: "Havells Stigi 15W LED Downlight — Pack of 2",
    brand: "Havells",
    subBrand: "Stigi",
    category: "home-appliances",
    subCategory: "lighting",
    variant: "Pack of 2",
    description: "Havells Stigi 15W recessed LED downlight — value pack of 2.",
    price: 749,
    originalPrice: 1098,
    discount: 32,
    image: "/assets/products/IN-HA-HAV-018.jpg",
    affiliateUrl: "/go/IN-HA-HAV-018",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.2,
    reviewCount: 7500,
    tags: ["home-appliances", "havells", "Stigi", "downlight", "lighting", "combo"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-HAV-019",
    name: "Havells Colour Changing LED Strip — 5m RGB",
    brand: "Havells",
    subBrand: "LED Strip",
    category: "home-appliances",
    subCategory: "lighting",
    variant: "5m RGB",
    description: "Havells 5m RGB colour changing LED strip with remote control and multiple modes.",
    price: 1299,
    originalPrice: 1699,
    discount: 24,
    image: "/assets/products/IN-HA-HAV-019.jpg",
    affiliateUrl: "/go/IN-HA-HAV-019",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.0,
    reviewCount: 6200,
    tags: ["home-appliances", "havells", "LED Strip", "RGB", "lighting"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-HAV-020",
    name: "Havells Colour Changing LED Strip — Starter Kit",
    brand: "Havells",
    subBrand: "LED Strip",
    category: "home-appliances",
    subCategory: "lighting",
    variant: "Starter Kit",
    description: "Havells LED strip starter kit with controller, adapter, and 5m strip included.",
    price: 1799,
    originalPrice: 2299,
    discount: 22,
    image: "/assets/products/IN-HA-HAV-020.jpg",
    affiliateUrl: "/go/IN-HA-HAV-020",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.0,
    reviewCount: 4800,
    tags: ["home-appliances", "havells", "LED Strip", "RGB", "lighting", "starter-kit"],
    apiSource: "amazon-pa-api-free"
  },

  // ── SWITCHES (021–030) ──────────────────────
  {
    id: "IN-HA-HAV-021",
    name: "Havells Crabtree Thames 6A 1-Way Switch — White",
    brand: "Havells",
    subBrand: "Crabtree Thames",
    category: "home-appliances",
    subCategory: "switches",
    variant: "White",
    description: "Havells Crabtree Thames 6A modular 1-way switch with durable polycarbonate body.",
    price: 49,
    originalPrice: 65,
    discount: 25,
    image: "/assets/products/IN-HA-HAV-021.jpg",
    affiliateUrl: "/go/IN-HA-HAV-021",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.4,
    reviewCount: 28900,
    tags: ["home-appliances", "havells", "Crabtree", "switch", "modular-switch"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-HAV-022",
    name: "Havells Crabtree Thames 6A 1-Way Switch — Graphite",
    brand: "Havells",
    subBrand: "Crabtree Thames",
    category: "home-appliances",
    subCategory: "switches",
    variant: "Graphite",
    description: "Havells Crabtree Thames 6A modular 1-way switch with durable polycarbonate body.",
    price: 59,
    originalPrice: 75,
    discount: 21,
    image: "/assets/products/IN-HA-HAV-022.jpg",
    affiliateUrl: "/go/IN-HA-HAV-022",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.4,
    reviewCount: 24200,
    tags: ["home-appliances", "havells", "Crabtree", "switch", "modular-switch"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-HAV-023",
    name: "Havells Crabtree 16A 2-Way Switch — White",
    brand: "Havells",
    subBrand: "Crabtree",
    category: "home-appliances",
    subCategory: "switches",
    variant: "White",
    description: "Havells Crabtree 16A modular 2-way switch for heavy-duty appliance control.",
    price: 89,
    originalPrice: 115,
    discount: 23,
    image: "/assets/products/IN-HA-HAV-023.jpg",
    affiliateUrl: "/go/IN-HA-HAV-023",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.3,
    reviewCount: 19600,
    tags: ["home-appliances", "havells", "Crabtree", "switch", "2-way-switch"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-HAV-024",
    name: "Havells Crabtree 16A 2-Way Switch — Champagne",
    brand: "Havells",
    subBrand: "Crabtree",
    category: "home-appliances",
    subCategory: "switches",
    variant: "Champagne",
    description: "Havells Crabtree 16A modular 2-way switch for heavy-duty appliance control.",
    price: 99,
    originalPrice: 125,
    discount: 21,
    image: "/assets/products/IN-HA-HAV-024.jpg",
    affiliateUrl: "/go/IN-HA-HAV-024",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.3,
    reviewCount: 16800,
    tags: ["home-appliances", "havells", "Crabtree", "switch", "2-way-switch"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-HAV-025",
    name: "Havells Signia 16A Modular Switch — White Silver",
    brand: "Havells",
    subBrand: "Signia",
    category: "home-appliances",
    subCategory: "switches",
    variant: "White Silver",
    description: "Havells Signia premium 16A modular switch with silver trim and click feedback.",
    price: 149,
    originalPrice: 199,
    discount: 25,
    image: "/assets/products/IN-HA-HAV-025.jpg",
    affiliateUrl: "/go/IN-HA-HAV-025",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.5,
    reviewCount: 12400,
    tags: ["home-appliances", "havells", "Signia", "switch", "premium-switch"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-HAV-026",
    name: "Havells Signia 16A Modular Switch — Black",
    brand: "Havells",
    subBrand: "Signia",
    category: "home-appliances",
    subCategory: "switches",
    variant: "Black",
    description: "Havells Signia premium 16A modular switch with silver trim and click feedback.",
    price: 149,
    originalPrice: 199,
    discount: 25,
    image: "/assets/products/IN-HA-HAV-026.jpg",
    affiliateUrl: "/go/IN-HA-HAV-026",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.5,
    reviewCount: 10800,
    tags: ["home-appliances", "havells", "Signia", "switch", "premium-switch"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-HAV-027",
    name: "Havells Oro 16A Switch Socket Combo — White",
    brand: "Havells",
    subBrand: "Oro",
    category: "home-appliances",
    subCategory: "switches",
    variant: "White",
    description: "Havells Oro 16A modular switch and socket combo with shuttered socket.",
    price: 179,
    originalPrice: 235,
    discount: 24,
    image: "/assets/products/IN-HA-HAV-027.jpg",
    affiliateUrl: "/go/IN-HA-HAV-027",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.2,
    reviewCount: 15200,
    tags: ["home-appliances", "havells", "Oro", "switch-socket", "combo"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-HAV-028",
    name: "Havells Oro 16A Switch Socket Combo — Chrome Black",
    brand: "Havells",
    subBrand: "Oro",
    category: "home-appliances",
    subCategory: "switches",
    variant: "Chrome Black",
    description: "Havells Oro 16A modular switch and socket combo with shuttered socket.",
    price: 199,
    originalPrice: 260,
    discount: 23,
    image: "/assets/products/IN-HA-HAV-028.jpg",
    affiliateUrl: "/go/IN-HA-HAV-028",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.2,
    reviewCount: 13100,
    tags: ["home-appliances", "havells", "Oro", "switch-socket", "combo"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-HAV-029",
    name: "Havells Reo 16A Switch — White",
    brand: "Havells",
    subBrand: "Reo",
    category: "home-appliances",
    subCategory: "switches",
    variant: "White",
    description: "Havells Reo 16A modular switch — affordable and reliable for everyday use.",
    price: 35,
    originalPrice: 45,
    discount: 22,
    image: "/assets/products/IN-HA-HAV-029.jpg",
    affiliateUrl: "/go/IN-HA-HAV-029",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.1,
    reviewCount: 34500,
    tags: ["home-appliances", "havells", "Reo", "switch", "modular-switch"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-HAV-030",
    name: "Havells Reo 16A Switch — Black",
    brand: "Havells",
    subBrand: "Reo",
    category: "home-appliances",
    subCategory: "switches",
    variant: "Black",
    description: "Havells Reo 16A modular switch — affordable and reliable for everyday use.",
    price: 39,
    originalPrice: 50,
    discount: 22,
    image: "/assets/products/IN-HA-HAV-030.jpg",
    affiliateUrl: "/go/IN-HA-HAV-030",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.1,
    reviewCount: 31200,
    tags: ["home-appliances", "havells", "Reo", "switch", "modular-switch"],
    apiSource: "amazon-pa-api-free"
  },

  // ── WATER HEATERS (031–040) ─────────────────
  {
    id: "IN-HA-HAV-031",
    name: "Havells Instanio Prime 3L Instant Geyser — White Blue",
    brand: "Havells",
    subBrand: "Instanio Prime",
    category: "home-appliances",
    subCategory: "water-heaters",
    variant: "White Blue / 3L",
    description: "Havells Instanio Prime 3L instant water heater with colour-changing LED temperature indicator.",
    price: 4499,
    originalPrice: 5499,
    discount: 18,
    image: "/assets/products/IN-HA-HAV-031.jpg",
    affiliateUrl: "/go/IN-HA-HAV-031",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.3,
    reviewCount: 16800,
    tags: ["home-appliances", "havells", "Instanio Prime", "instant-geyser", "water-heater"],
    isFeatured: true,
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-HAV-032",
    name: "Havells Instanio Prime 3L Instant Geyser — Grey",
    brand: "Havells",
    subBrand: "Instanio Prime",
    category: "home-appliances",
    subCategory: "water-heaters",
    variant: "Grey / 3L",
    description: "Havells Instanio Prime 3L instant water heater with colour-changing LED temperature indicator.",
    price: 4499,
    originalPrice: 5499,
    discount: 18,
    image: "/assets/products/IN-HA-HAV-032.jpg",
    affiliateUrl: "/go/IN-HA-HAV-032",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.3,
    reviewCount: 14200,
    tags: ["home-appliances", "havells", "Instanio Prime", "instant-geyser", "water-heater"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-HAV-033",
    name: "Havells Monza EC 10L Storage Water Heater — Ivory",
    brand: "Havells",
    subBrand: "Monza EC",
    category: "home-appliances",
    subCategory: "water-heaters",
    variant: "Ivory / 10L",
    description: "Havells Monza EC 10L storage water heater with feroglas-coated inner tank.",
    price: 6999,
    originalPrice: 8499,
    discount: 18,
    image: "/assets/products/IN-HA-HAV-033.jpg",
    affiliateUrl: "/go/IN-HA-HAV-033",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.4,
    reviewCount: 12100,
    tags: ["home-appliances", "havells", "Monza EC", "storage-geyser", "water-heater"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-HAV-034",
    name: "Havells Monza EC 10L Storage Water Heater — Blue",
    brand: "Havells",
    subBrand: "Monza EC",
    category: "home-appliances",
    subCategory: "water-heaters",
    variant: "Blue / 10L",
    description: "Havells Monza EC 10L storage water heater with feroglas-coated inner tank.",
    price: 6999,
    originalPrice: 8499,
    discount: 18,
    image: "/assets/products/IN-HA-HAV-034.jpg",
    affiliateUrl: "/go/IN-HA-HAV-034",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.4,
    reviewCount: 10500,
    tags: ["home-appliances", "havells", "Monza EC", "storage-geyser", "water-heater"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-HAV-035",
    name: "Havells Monza EC 15L Storage Water Heater — Ivory",
    brand: "Havells",
    subBrand: "Monza EC",
    category: "home-appliances",
    subCategory: "water-heaters",
    variant: "Ivory / 15L",
    description: "Havells Monza EC 15L storage water heater with whirlflow technology for faster heating.",
    price: 8499,
    originalPrice: 9999,
    discount: 15,
    image: "/assets/products/IN-HA-HAV-035.jpg",
    affiliateUrl: "/go/IN-HA-HAV-035",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.4,
    reviewCount: 9800,
    tags: ["home-appliances", "havells", "Monza EC", "storage-geyser", "water-heater"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-HAV-036",
    name: "Havells Monza EC 15L Storage Water Heater — Silver",
    brand: "Havells",
    subBrand: "Monza EC",
    category: "home-appliances",
    subCategory: "water-heaters",
    variant: "Silver / 15L",
    description: "Havells Monza EC 15L storage water heater with whirlflow technology for faster heating.",
    price: 8499,
    originalPrice: 9999,
    discount: 15,
    image: "/assets/products/IN-HA-HAV-036.jpg",
    affiliateUrl: "/go/IN-HA-HAV-036",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.4,
    reviewCount: 8200,
    tags: ["home-appliances", "havells", "Monza EC", "storage-geyser", "water-heater"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-HAV-037",
    name: "Havells Monza EC 25L Storage Water Heater — Ivory",
    brand: "Havells",
    subBrand: "Monza EC",
    category: "home-appliances",
    subCategory: "water-heaters",
    variant: "Ivory / 25L",
    description: "Havells Monza EC 25L storage water heater with heavy-duty anode rod for corrosion resistance.",
    price: 9999,
    originalPrice: 11999,
    discount: 17,
    image: "/assets/products/IN-HA-HAV-037.jpg",
    affiliateUrl: "/go/IN-HA-HAV-037",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.3,
    reviewCount: 7600,
    tags: ["home-appliances", "havells", "Monza EC", "storage-geyser", "water-heater"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-HAV-038",
    name: "Havells Monza EC 25L Storage Water Heater — Blue",
    brand: "Havells",
    subBrand: "Monza EC",
    category: "home-appliances",
    subCategory: "water-heaters",
    variant: "Blue / 25L",
    description: "Havells Monza EC 25L storage water heater with heavy-duty anode rod for corrosion resistance.",
    price: 9999,
    originalPrice: 11999,
    discount: 17,
    image: "/assets/products/IN-HA-HAV-038.jpg",
    affiliateUrl: "/go/IN-HA-HAV-038",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.3,
    reviewCount: 6400,
    tags: ["home-appliances", "havells", "Monza EC", "storage-geyser", "water-heater"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-HAV-039",
    name: "Havells Adonia I 25L Storage Vertical Water Heater — White",
    brand: "Havells",
    subBrand: "Adonia",
    category: "home-appliances",
    subCategory: "water-heaters",
    variant: "White / 25L",
    description: "Havells Adonia I 25L vertical storage water heater with digital temperature display.",
    price: 12499,
    originalPrice: 14999,
    discount: 17,
    image: "/assets/products/IN-HA-HAV-039.jpg",
    affiliateUrl: "/go/IN-HA-HAV-039",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.5,
    reviewCount: 5800,
    tags: ["home-appliances", "havells", "Adonia", "storage-geyser", "water-heater", "digital"],
    isFeatured: true,
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-HAV-040",
    name: "Havells Adonia I 25L Storage Vertical Water Heater — Silver Blue",
    brand: "Havells",
    subBrand: "Adonia",
    category: "home-appliances",
    subCategory: "water-heaters",
    variant: "Silver Blue / 25L",
    description: "Havells Adonia I 25L vertical storage water heater with digital temperature display.",
    price: 12499,
    originalPrice: 14999,
    discount: 17,
    image: "/assets/products/IN-HA-HAV-040.jpg",
    affiliateUrl: "/go/IN-HA-HAV-040",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.5,
    reviewCount: 4900,
    tags: ["home-appliances", "havells", "Adonia", "storage-geyser", "water-heater", "digital"],
    apiSource: "amazon-pa-api-free"
  },

  // ── SMALL APPLIANCES (041–050) ──────────────
  {
    id: "IN-HA-HAV-041",
    name: "Havells Cista 600W Mixer Grinder 3 Jar — White",
    brand: "Havells",
    subBrand: "Cista",
    category: "home-appliances",
    subCategory: "small-appliances",
    variant: "White",
    description: "Havells Cista 600W mixer grinder with 3 stainless steel jars and overload protector.",
    price: 2999,
    originalPrice: 3599,
    discount: 17,
    image: "/assets/products/IN-HA-HAV-041.jpg",
    affiliateUrl: "/go/IN-HA-HAV-041",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.2,
    reviewCount: 11400,
    tags: ["home-appliances", "havells", "Cista", "mixer-grinder", "kitchen"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-HAV-042",
    name: "Havells Cista 600W Mixer Grinder 3 Jar — Red",
    brand: "Havells",
    subBrand: "Cista",
    category: "home-appliances",
    subCategory: "small-appliances",
    variant: "Red",
    description: "Havells Cista 600W mixer grinder with 3 stainless steel jars and overload protector.",
    price: 2999,
    originalPrice: 3599,
    discount: 17,
    image: "/assets/products/IN-HA-HAV-042.jpg",
    affiliateUrl: "/go/IN-HA-HAV-042",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.2,
    reviewCount: 9800,
    tags: ["home-appliances", "havells", "Cista", "mixer-grinder", "kitchen"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-HAV-043",
    name: "Havells Vibro 500W Mixer 3 Jar — White Red",
    brand: "Havells",
    subBrand: "Vibro",
    category: "home-appliances",
    subCategory: "small-appliances",
    variant: "White Red",
    description: "Havells Vibro 500W mixer grinder with 3 jars and high-quality stainless steel blades.",
    price: 2499,
    originalPrice: 2999,
    discount: 17,
    image: "/assets/products/IN-HA-HAV-043.jpg",
    affiliateUrl: "/go/IN-HA-HAV-043",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.1,
    reviewCount: 13600,
    tags: ["home-appliances", "havells", "Vibro", "mixer-grinder", "kitchen"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-HAV-044",
    name: "Havells Vibro 500W Mixer 3 Jar — Black",
    brand: "Havells",
    subBrand: "Vibro",
    category: "home-appliances",
    subCategory: "small-appliances",
    variant: "Black",
    description: "Havells Vibro 500W mixer grinder with 3 jars and high-quality stainless steel blades.",
    price: 2499,
    originalPrice: 2999,
    discount: 17,
    image: "/assets/products/IN-HA-HAV-044.jpg",
    affiliateUrl: "/go/IN-HA-HAV-044",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.1,
    reviewCount: 11200,
    tags: ["home-appliances", "havells", "Vibro", "mixer-grinder", "kitchen"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-HAV-045",
    name: "Havells Prolife Flouro 750W Mixer Grinder — White",
    brand: "Havells",
    subBrand: "Prolife",
    category: "home-appliances",
    subCategory: "small-appliances",
    variant: "White",
    description: "Havells Prolife Flouro 750W mixer grinder with 3 jars and multi-function blades.",
    price: 3499,
    originalPrice: 4199,
    discount: 17,
    image: "/assets/products/IN-HA-HAV-045.jpg",
    affiliateUrl: "/go/IN-HA-HAV-045",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.3,
    reviewCount: 8900,
    tags: ["home-appliances", "havells", "Prolife", "mixer-grinder", "kitchen"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-HAV-046",
    name: "Havells Prolife Flouro 750W Mixer Grinder — Black",
    brand: "Havells",
    subBrand: "Prolife",
    category: "home-appliances",
    subCategory: "small-appliances",
    variant: "Black",
    description: "Havells Prolife Flouro 750W mixer grinder with 3 jars and multi-function blades.",
    price: 3499,
    originalPrice: 4199,
    discount: 17,
    image: "/assets/products/IN-HA-HAV-046.jpg",
    affiliateUrl: "/go/IN-HA-HAV-046",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.3,
    reviewCount: 7400,
    tags: ["home-appliances", "havells", "Prolife", "mixer-grinder", "kitchen"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-HAV-047",
    name: "Havells Supermix 500W Hand Blender — White",
    brand: "Havells",
    subBrand: "Supermix",
    category: "home-appliances",
    subCategory: "small-appliances",
    variant: "White",
    description: "Havells Supermix 500W hand blender with stainless steel blade and detachable foot.",
    price: 1299,
    originalPrice: 1599,
    discount: 19,
    image: "/assets/products/IN-HA-HAV-047.jpg",
    affiliateUrl: "/go/IN-HA-HAV-047",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.1,
    reviewCount: 7800,
    tags: ["home-appliances", "havells", "Supermix", "hand-blender", "kitchen"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-HAV-048",
    name: "Havells Supermix 500W Hand Blender — Purple",
    brand: "Havells",
    subBrand: "Supermix",
    category: "home-appliances",
    subCategory: "small-appliances",
    variant: "Purple",
    description: "Havells Supermix 500W hand blender with stainless steel blade and detachable foot.",
    price: 1299,
    originalPrice: 1599,
    discount: 19,
    image: "/assets/products/IN-HA-HAV-048.jpg",
    affiliateUrl: "/go/IN-HA-HAV-048",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.1,
    reviewCount: 6500,
    tags: ["home-appliances", "havells", "Supermix", "hand-blender", "kitchen"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-HAV-049",
    name: "Havells 1500W Pop Up Toaster 2 Slice — White",
    brand: "Havells",
    subBrand: "Havells",
    category: "home-appliances",
    subCategory: "small-appliances",
    variant: "White",
    description: "Havells 1500W pop-up toaster with 7 browning levels and crumb tray.",
    price: 1799,
    originalPrice: 2199,
    discount: 18,
    image: "/assets/products/IN-HA-HAV-049.jpg",
    affiliateUrl: "/go/IN-HA-HAV-049",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.2,
    reviewCount: 9200,
    tags: ["home-appliances", "havells", "toaster", "pop-up-toaster", "kitchen"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-HAV-050",
    name: "Havells 1500W Pop Up Toaster 2 Slice — Silver",
    brand: "Havells",
    subBrand: "Havells",
    category: "home-appliances",
    subCategory: "small-appliances",
    variant: "Silver",
    description: "Havells 1500W pop-up toaster with 7 browning levels and crumb tray.",
    price: 1799,
    originalPrice: 2199,
    discount: 18,
    image: "/assets/products/IN-HA-HAV-050.jpg",
    affiliateUrl: "/go/IN-HA-HAV-050",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.2,
    reviewCount: 8100,
    tags: ["home-appliances", "havells", "toaster", "pop-up-toaster", "kitchen"],
    apiSource: "amazon-pa-api-free"
  }
]
