import { IndiaProduct } from "../types"

// ──────────────────────────────────────────────
// PHILIPS INDIA — 50 products (IN-HA-PHI-001 → 050)
// ──────────────────────────────────────────────

export const PHILIPS_PRODUCTS: IndiaProduct[] = [
  // ── AIR FRYERS (001–010) ────────────────────
  {
    id: "IN-HA-PHI-001",
    name: "Philips NA120/00 Airfryer 4.1L — Black",
    brand: "Philips",
    subBrand: "Airfryer",
    category: "home-appliances",
    subCategory: "air-fryers",
    variant: "Black",
    description: "Philips NA120/00 4.1L airfryer with rapid air technology for oil-free frying.",
    price: 6999,
    originalPrice: 8499,
    discount: 18,
    image: "/assets/products/IN-HA-PHI-001.jpg",
    affiliateUrl: "/go/IN-HA-PHI-001",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.4,
    reviewCount: 18200,
    tags: ["home-appliances", "philips", "Airfryer", "air-fryer", "kitchen"],
    isTrending: true,
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PHI-002",
    name: "Philips NA120/00 Airfryer 4.1L — White",
    brand: "Philips",
    subBrand: "Airfryer",
    category: "home-appliances",
    subCategory: "air-fryers",
    variant: "White",
    description: "Philips NA120/00 4.1L airfryer with rapid air technology for oil-free frying.",
    price: 6999,
    originalPrice: 8499,
    discount: 18,
    image: "/assets/products/IN-HA-PHI-002.jpg",
    affiliateUrl: "/go/IN-HA-PHI-002",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.4,
    reviewCount: 16500,
    tags: ["home-appliances", "philips", "Airfryer", "air-fryer", "kitchen"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PHI-003",
    name: "Philips HD9200/90 Airfryer 3L — Black",
    brand: "Philips",
    subBrand: "Airfryer",
    category: "home-appliances",
    subCategory: "air-fryers",
    variant: "Black",
    description: "Philips HD9200/90 compact 3L airfryer with starfish design for even cooking.",
    price: 5499,
    originalPrice: 6799,
    discount: 19,
    image: "/assets/products/IN-HA-PHI-003.jpg",
    affiliateUrl: "/go/IN-HA-PHI-003",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.3,
    reviewCount: 24100,
    tags: ["home-appliances", "philips", "Airfryer", "air-fryer", "kitchen", "compact"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PHI-004",
    name: "Philips HD9200/90 Airfryer 3L — Red",
    brand: "Philips",
    subBrand: "Airfryer",
    category: "home-appliances",
    subCategory: "air-fryers",
    variant: "Red",
    description: "Philips HD9200/90 compact 3L airfryer with starfish design for even cooking.",
    price: 5499,
    originalPrice: 6799,
    discount: 19,
    image: "/assets/products/IN-HA-PHI-004.jpg",
    affiliateUrl: "/go/IN-HA-PHI-004",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.3,
    reviewCount: 21400,
    tags: ["home-appliances", "philips", "Airfryer", "air-fryer", "kitchen", "compact"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PHI-005",
    name: "Philips HD9252/90 Airfryer XXL 6.2L — Black",
    brand: "Philips",
    subBrand: "Airfryer XXL",
    category: "home-appliances",
    subCategory: "air-fryers",
    variant: "Black",
    description: "Philips HD9252/90 XXL 6.2L airfryer with fat removal technology and digital display.",
    price: 12999,
    originalPrice: 15999,
    discount: 19,
    image: "/assets/products/IN-HA-PHI-005.jpg",
    affiliateUrl: "/go/IN-HA-PHI-005",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.5,
    reviewCount: 14800,
    tags: ["home-appliances", "philips", "Airfryer XXL", "air-fryer", "kitchen", "family-size"],
    isFeatured: true,
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PHI-006",
    name: "Philips HD9252/90 Airfryer XXL 6.2L — White",
    brand: "Philips",
    subBrand: "Airfryer XXL",
    category: "home-appliances",
    subCategory: "air-fryers",
    variant: "White",
    description: "Philips HD9252/90 XXL 6.2L airfryer with fat removal technology and digital display.",
    price: 12999,
    originalPrice: 15999,
    discount: 19,
    image: "/assets/products/IN-HA-PHI-006.jpg",
    affiliateUrl: "/go/IN-HA-PHI-006",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.5,
    reviewCount: 12600,
    tags: ["home-appliances", "philips", "Airfryer XXL", "air-fryer", "kitchen", "family-size"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PHI-007",
    name: "Philips HD9270/90 Airfryer XXL TurboStar — Black",
    brand: "Philips",
    subBrand: "Airfryer XXL TurboStar",
    category: "home-appliances",
    subCategory: "air-fryers",
    variant: "Black",
    description: "Philips HD9270/90 XXL TurboStar airfryer with twin turbostar technology for even results.",
    price: 14999,
    originalPrice: 17999,
    discount: 17,
    image: "/assets/products/IN-HA-PHI-007.jpg",
    affiliateUrl: "/go/IN-HA-PHI-007",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.5,
    reviewCount: 9800,
    tags: ["home-appliances", "philips", "Airfryer XXL", "TurboStar", "air-fryer", "kitchen"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PHI-008",
    name: "Philips HD9270/90 Airfryer XXL TurboStar — Matt Black",
    brand: "Philips",
    subBrand: "Airfryer XXL TurboStar",
    category: "home-appliances",
    subCategory: "air-fryers",
    variant: "Matt Black",
    description: "Philips HD9270/90 XXL TurboStar airfryer with twin turbostar technology for even results.",
    price: 14999,
    originalPrice: 17999,
    discount: 17,
    image: "/assets/products/IN-HA-PHI-008.jpg",
    affiliateUrl: "/go/IN-HA-PHI-008",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.5,
    reviewCount: 8400,
    tags: ["home-appliances", "philips", "Airfryer XXL", "TurboStar", "air-fryer", "kitchen"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PHI-009",
    name: "Philips HD9860/90 Smart Airfryer XXL — Black",
    brand: "Philips",
    subBrand: "Smart Airfryer XXL",
    category: "home-appliances",
    subCategory: "air-fryers",
    variant: "Black",
    description: "Philips HD9860/90 Smart XXL airfryer with NutriU app connectivity and smart sensing.",
    price: 19999,
    originalPrice: 23999,
    discount: 17,
    image: "/assets/products/IN-HA-PHI-009.jpg",
    affiliateUrl: "/go/IN-HA-PHI-009",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.6,
    reviewCount: 6200,
    tags: ["home-appliances", "philips", "Smart Airfryer", "air-fryer", "kitchen", "smart", "wifi"],
    isFeatured: true,
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PHI-010",
    name: "Philips HD9860/90 Smart Airfryer XXL — Silver",
    brand: "Philips",
    subBrand: "Smart Airfryer XXL",
    category: "home-appliances",
    subCategory: "air-fryers",
    variant: "Silver",
    description: "Philips HD9860/90 Smart XXL airfryer with NutriU app connectivity and smart sensing.",
    price: 19999,
    originalPrice: 23999,
    discount: 17,
    image: "/assets/products/IN-HA-PHI-010.jpg",
    affiliateUrl: "/go/IN-HA-PHI-010",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.6,
    reviewCount: 5100,
    tags: ["home-appliances", "philips", "Smart Airfryer", "air-fryer", "kitchen", "smart", "wifi"],
    apiSource: "amazon-pa-api-free"
  },

  // ── PERSONAL CARE APPLIANCES (011–020) ──────
  {
    id: "IN-HA-PHI-011",
    name: "Philips BHB662/00 Hair Straightener 230C — Black",
    brand: "Philips",
    subBrand: "Philips Beauty",
    category: "home-appliances",
    subCategory: "personal-care-appliances",
    variant: "Black",
    description: "Philips BHB662/00 hair straightener with keratin ceramic plates and 230°C max temp.",
    price: 2499,
    originalPrice: 2999,
    discount: 17,
    image: "/assets/products/IN-HA-PHI-011.jpg",
    affiliateUrl: "/go/IN-HA-PHI-011",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.3,
    reviewCount: 21400,
    tags: ["home-appliances", "philips", "Beauty", "hair-straightener", "personal-care"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PHI-012",
    name: "Philips BHB662/00 Hair Straightener 230C — Rose Gold",
    brand: "Philips",
    subBrand: "Philips Beauty",
    category: "home-appliances",
    subCategory: "personal-care-appliances",
    variant: "Rose Gold",
    description: "Philips BHB662/00 hair straightener with keratin ceramic plates and 230°C max temp.",
    price: 2499,
    originalPrice: 2999,
    discount: 17,
    image: "/assets/products/IN-HA-PHI-012.jpg",
    affiliateUrl: "/go/IN-HA-PHI-012",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.3,
    reviewCount: 19200,
    tags: ["home-appliances", "philips", "Beauty", "hair-straightener", "personal-care"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PHI-013",
    name: "Philips HP8302/06 3-in-1 Styler — Black Pink",
    brand: "Philips",
    subBrand: "Philips Beauty",
    category: "home-appliances",
    subCategory: "personal-care-appliances",
    variant: "Black Pink",
    description: "Philips HP8302/06 3-in-1 multi-styler — straighten, curl, and crimp in one device.",
    price: 1799,
    originalPrice: 2199,
    discount: 18,
    image: "/assets/products/IN-HA-PHI-013.jpg",
    affiliateUrl: "/go/IN-HA-PHI-013",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.1,
    reviewCount: 15600,
    tags: ["home-appliances", "philips", "Beauty", "styler", "personal-care"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PHI-014",
    name: "Philips HP8302/06 3-in-1 Styler — Gold",
    brand: "Philips",
    subBrand: "Philips Beauty",
    category: "home-appliances",
    subCategory: "personal-care-appliances",
    variant: "Gold",
    description: "Philips HP8302/06 3-in-1 multi-styler — straighten, curl, and crimp in one device.",
    price: 1799,
    originalPrice: 2199,
    discount: 18,
    image: "/assets/products/IN-HA-PHI-014.jpg",
    affiliateUrl: "/go/IN-HA-PHI-014",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.1,
    reviewCount: 13800,
    tags: ["home-appliances", "philips", "Beauty", "styler", "personal-care"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PHI-015",
    name: "Philips BHH777/00 Hair Straightener — Black",
    brand: "Philips",
    subBrand: "Philips Beauty",
    category: "home-appliances",
    subCategory: "personal-care-appliances",
    variant: "Black",
    description: "Philips BHH777/00 advanced hair straightener with SilkProtect coating.",
    price: 2999,
    originalPrice: 3599,
    discount: 17,
    image: "/assets/products/IN-HA-PHI-015.jpg",
    affiliateUrl: "/go/IN-HA-PHI-015",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.4,
    reviewCount: 12300,
    tags: ["home-appliances", "philips", "Beauty", "hair-straightener", "personal-care"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PHI-016",
    name: "Philips BHH777/00 Hair Straightener — Purple",
    brand: "Philips",
    subBrand: "Philips Beauty",
    category: "home-appliances",
    subCategory: "personal-care-appliances",
    variant: "Purple",
    description: "Philips BHH777/00 advanced hair straightener with SilkProtect coating.",
    price: 2999,
    originalPrice: 3599,
    discount: 17,
    image: "/assets/products/IN-HA-PHI-016.jpg",
    affiliateUrl: "/go/IN-HA-PHI-016",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.4,
    reviewCount: 10700,
    tags: ["home-appliances", "philips", "Beauty", "hair-straightener", "personal-care"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PHI-017",
    name: "Philips MG7940/15 Multigroom 9-in-1 — Black",
    brand: "Philips",
    subBrand: "Multigroom",
    category: "home-appliances",
    subCategory: "personal-care-appliances",
    variant: "Black",
    description: "Philips MG7940/15 all-in-one 9-in-1 grooming kit with DualCut blades.",
    price: 3999,
    originalPrice: 4799,
    discount: 17,
    image: "/assets/products/IN-HA-PHI-017.jpg",
    affiliateUrl: "/go/IN-HA-PHI-017",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.5,
    reviewCount: 19800,
    tags: ["home-appliances", "philips", "Multigroom", "grooming-kit", "trimmer"],
    isTrending: true,
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PHI-018",
    name: "Philips MG7940/15 Multigroom 9-in-1 — Titanium",
    brand: "Philips",
    subBrand: "Multigroom",
    category: "home-appliances",
    subCategory: "personal-care-appliances",
    variant: "Titanium",
    description: "Philips MG7940/15 all-in-one 9-in-1 grooming kit with DualCut blades.",
    price: 3999,
    originalPrice: 4799,
    discount: 17,
    image: "/assets/products/IN-HA-PHI-018.jpg",
    affiliateUrl: "/go/IN-HA-PHI-018",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.5,
    reviewCount: 17200,
    tags: ["home-appliances", "philips", "Multigroom", "grooming-kit", "trimmer"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PHI-019",
    name: "Philips AT899/16 Aquatouch Wet Dry Shaver — Black Blue",
    brand: "Philips",
    subBrand: "AquaTouch",
    category: "home-appliances",
    subCategory: "personal-care-appliances",
    variant: "Black Blue",
    description: "Philips AT899/16 AquaTouch wet and dry electric shaver with aquatec seal.",
    price: 4499,
    originalPrice: 5499,
    discount: 18,
    image: "/assets/products/IN-HA-PHI-019.jpg",
    affiliateUrl: "/go/IN-HA-PHI-019",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.3,
    reviewCount: 14600,
    tags: ["home-appliances", "philips", "AquaTouch", "shaver", "electric-shaver"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PHI-020",
    name: "Philips AT899/16 Aquatouch Wet Dry Shaver — Grey",
    brand: "Philips",
    subBrand: "AquaTouch",
    category: "home-appliances",
    subCategory: "personal-care-appliances",
    variant: "Grey",
    description: "Philips AT899/16 AquaTouch wet and dry electric shaver with aquatec seal.",
    price: 4499,
    originalPrice: 5499,
    discount: 18,
    image: "/assets/products/IN-HA-PHI-020.jpg",
    affiliateUrl: "/go/IN-HA-PHI-020",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.3,
    reviewCount: 12100,
    tags: ["home-appliances", "philips", "AquaTouch", "shaver", "electric-shaver"],
    apiSource: "amazon-pa-api-free"
  },

  // ── KITCHEN APPLIANCES (021–030) ────────────
  {
    id: "IN-HA-PHI-021",
    name: "Philips HL7756/00 Mixer Grinder 750W — White Blue",
    brand: "Philips",
    subBrand: "Philips Kitchen",
    category: "home-appliances",
    subCategory: "kitchen-appliances",
    variant: "White Blue",
    description: "Philips HL7756/00 750W mixer grinder with 3 jars and turbo-speed motor.",
    price: 3999,
    originalPrice: 4799,
    discount: 17,
    image: "/assets/products/IN-HA-PHI-021.jpg",
    affiliateUrl: "/go/IN-HA-PHI-021",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.3,
    reviewCount: 28400,
    tags: ["home-appliances", "philips", "Kitchen", "mixer-grinder", "kitchen"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PHI-022",
    name: "Philips HL7756/00 Mixer Grinder 750W — Red White",
    brand: "Philips",
    subBrand: "Philips Kitchen",
    category: "home-appliances",
    subCategory: "kitchen-appliances",
    variant: "Red White",
    description: "Philips HL7756/00 750W mixer grinder with 3 jars and turbo-speed motor.",
    price: 3999,
    originalPrice: 4799,
    discount: 17,
    image: "/assets/products/IN-HA-PHI-022.jpg",
    affiliateUrl: "/go/IN-HA-PHI-022",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.3,
    reviewCount: 25100,
    tags: ["home-appliances", "philips", "Kitchen", "mixer-grinder", "kitchen"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PHI-023",
    name: "Philips HL7707/00 Mixer Grinder 600W — White",
    brand: "Philips",
    subBrand: "Philips Kitchen",
    category: "home-appliances",
    subCategory: "kitchen-appliances",
    variant: "White",
    description: "Philips HL7707/00 600W mixer grinder with 4 jars including chutney jar.",
    price: 3499,
    originalPrice: 4199,
    discount: 17,
    image: "/assets/products/IN-HA-PHI-023.jpg",
    affiliateUrl: "/go/IN-HA-PHI-023",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.2,
    reviewCount: 18600,
    tags: ["home-appliances", "philips", "Kitchen", "mixer-grinder", "kitchen"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PHI-024",
    name: "Philips HL7707/00 Mixer Grinder 600W — Blue",
    brand: "Philips",
    subBrand: "Philips Kitchen",
    category: "home-appliances",
    subCategory: "kitchen-appliances",
    variant: "Blue",
    description: "Philips HL7707/00 600W mixer grinder with 4 jars including chutney jar.",
    price: 3499,
    originalPrice: 4199,
    discount: 17,
    image: "/assets/products/IN-HA-PHI-024.jpg",
    affiliateUrl: "/go/IN-HA-PHI-024",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.2,
    reviewCount: 16200,
    tags: ["home-appliances", "philips", "Kitchen", "mixer-grinder", "kitchen"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PHI-025",
    name: "Philips HR1854/00 Juicer Mixer Grinder — White",
    brand: "Philips",
    subBrand: "Philips Kitchen",
    category: "home-appliances",
    subCategory: "kitchen-appliances",
    variant: "White",
    description: "Philips HR1854/00 juicer mixer grinder with quick clean sieve and drip stop feature.",
    price: 4999,
    originalPrice: 5999,
    discount: 17,
    image: "/assets/products/IN-HA-PHI-025.jpg",
    affiliateUrl: "/go/IN-HA-PHI-025",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.1,
    reviewCount: 9800,
    tags: ["home-appliances", "philips", "Kitchen", "juicer-mixer", "kitchen"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PHI-026",
    name: "Philips HR1854/00 Juicer Mixer Grinder — Black",
    brand: "Philips",
    subBrand: "Philips Kitchen",
    category: "home-appliances",
    subCategory: "kitchen-appliances",
    variant: "Black",
    description: "Philips HR1854/00 juicer mixer grinder with quick clean sieve and drip stop feature.",
    price: 4999,
    originalPrice: 5999,
    discount: 17,
    image: "/assets/products/IN-HA-PHI-026.jpg",
    affiliateUrl: "/go/IN-HA-PHI-026",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.1,
    reviewCount: 8400,
    tags: ["home-appliances", "philips", "Kitchen", "juicer-mixer", "kitchen"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PHI-027",
    name: "Philips HD2582/49 Pop-up Toaster 1000W — White",
    brand: "Philips",
    subBrand: "Philips Kitchen",
    category: "home-appliances",
    subCategory: "kitchen-appliances",
    variant: "White",
    description: "Philips HD2582/49 1000W pop-up toaster with 8 browning settings and dust cover.",
    price: 1799,
    originalPrice: 2199,
    discount: 18,
    image: "/assets/products/IN-HA-PHI-027.jpg",
    affiliateUrl: "/go/IN-HA-PHI-027",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.3,
    reviewCount: 16200,
    tags: ["home-appliances", "philips", "Kitchen", "pop-up-toaster", "kitchen"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PHI-028",
    name: "Philips HD2582/49 Pop-up Toaster 1000W — Black",
    brand: "Philips",
    subBrand: "Philips Kitchen",
    category: "home-appliances",
    subCategory: "kitchen-appliances",
    variant: "Black",
    description: "Philips HD2582/49 1000W pop-up toaster with 8 browning settings and dust cover.",
    price: 1799,
    originalPrice: 2199,
    discount: 18,
    image: "/assets/products/IN-HA-PHI-028.jpg",
    affiliateUrl: "/go/IN-HA-PHI-028",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.3,
    reviewCount: 14100,
    tags: ["home-appliances", "philips", "Kitchen", "pop-up-toaster", "kitchen"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PHI-029",
    name: "Philips HD4929/01 Rice Cooker 1.8L — White",
    brand: "Philips",
    subBrand: "Philips Kitchen",
    category: "home-appliances",
    subCategory: "kitchen-appliances",
    variant: "White",
    description: "Philips HD4929/01 1.8L rice cooker with auto keep-warm and non-stick inner pot.",
    price: 2499,
    originalPrice: 2999,
    discount: 17,
    image: "/assets/products/IN-HA-PHI-029.jpg",
    affiliateUrl: "/go/IN-HA-PHI-029",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.2,
    reviewCount: 11400,
    tags: ["home-appliances", "philips", "Kitchen", "rice-cooker", "kitchen"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PHI-030",
    name: "Philips HD4929/01 Rice Cooker 1.8L — Silver",
    brand: "Philips",
    subBrand: "Philips Kitchen",
    category: "home-appliances",
    subCategory: "kitchen-appliances",
    variant: "Silver",
    description: "Philips HD4929/01 1.8L rice cooker with auto keep-warm and non-stick inner pot.",
    price: 2499,
    originalPrice: 2999,
    discount: 17,
    image: "/assets/products/IN-HA-PHI-030.jpg",
    affiliateUrl: "/go/IN-HA-PHI-030",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.2,
    reviewCount: 9800,
    tags: ["home-appliances", "philips", "Kitchen", "rice-cooker", "kitchen"],
    apiSource: "amazon-pa-api-free"
  },

  // ── LIGHTING (031–040) ──────────────────────
  {
    id: "IN-HA-PHI-031",
    name: "Philips Stellar Bright 9W LED Bulb B22 — Warm White 2700K",
    brand: "Philips",
    subBrand: "Stellar Bright",
    category: "home-appliances",
    subCategory: "lighting",
    variant: "Warm White 2700K",
    description: "Philips Stellar Bright 9W B22 LED bulb with high lumen output and long lifespan.",
    price: 99,
    originalPrice: 139,
    discount: 29,
    image: "/assets/products/IN-HA-PHI-031.jpg",
    affiliateUrl: "/go/IN-HA-PHI-031",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.4,
    reviewCount: 42100,
    tags: ["home-appliances", "philips", "Stellar Bright", "LED-bulb", "lighting"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PHI-032",
    name: "Philips Stellar Bright 9W LED Bulb B22 — Pack of 4",
    brand: "Philips",
    subBrand: "Stellar Bright",
    category: "home-appliances",
    subCategory: "lighting",
    variant: "Pack of 4",
    description: "Philips Stellar Bright 9W B22 LED bulb — value pack of 4 for whole-home lighting.",
    price: 359,
    originalPrice: 556,
    discount: 35,
    image: "/assets/products/IN-HA-PHI-032.jpg",
    affiliateUrl: "/go/IN-HA-PHI-032",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.4,
    reviewCount: 38200,
    tags: ["home-appliances", "philips", "Stellar Bright", "LED-bulb", "lighting", "combo"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PHI-033",
    name: "Philips Astra Line Plus 14W Batten — Cool Day Light",
    brand: "Philips",
    subBrand: "Astra Line",
    category: "home-appliances",
    subCategory: "lighting",
    variant: "Cool Day Light",
    description: "Philips Astra Line Plus 14W LED batten with wide light spread and slim design.",
    price: 249,
    originalPrice: 349,
    discount: 29,
    image: "/assets/products/IN-HA-PHI-033.jpg",
    affiliateUrl: "/go/IN-HA-PHI-033",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.3,
    reviewCount: 26400,
    tags: ["home-appliances", "philips", "Astra Line", "LED-batten", "lighting"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PHI-034",
    name: "Philips Astra Line Plus 14W Batten — Pack of 2",
    brand: "Philips",
    subBrand: "Astra Line",
    category: "home-appliances",
    subCategory: "lighting",
    variant: "Pack of 2",
    description: "Philips Astra Line Plus 14W LED batten — value pack of 2.",
    price: 469,
    originalPrice: 698,
    discount: 33,
    image: "/assets/products/IN-HA-PHI-034.jpg",
    affiliateUrl: "/go/IN-HA-PHI-034",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.3,
    reviewCount: 22100,
    tags: ["home-appliances", "philips", "Astra Line", "LED-batten", "lighting", "combo"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PHI-035",
    name: "Philips Smart Wi-Fi LED Bulb 9W — White Tunable",
    brand: "Philips",
    subBrand: "Philips Smart",
    category: "home-appliances",
    subCategory: "lighting",
    variant: "White Tunable",
    description: "Philips Smart Wi-Fi 9W LED bulb with voice control and app-based dimming.",
    price: 799,
    originalPrice: 999,
    discount: 20,
    image: "/assets/products/IN-HA-PHI-035.jpg",
    affiliateUrl: "/go/IN-HA-PHI-035",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.1,
    reviewCount: 8400,
    tags: ["home-appliances", "philips", "Smart", "smart-bulb", "lighting", "wifi"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PHI-036",
    name: "Philips Smart Wi-Fi LED Bulb 9W — Colour Tunable",
    brand: "Philips",
    subBrand: "Philips Smart",
    category: "home-appliances",
    subCategory: "lighting",
    variant: "Colour Tunable",
    description: "Philips Smart Wi-Fi 9W LED bulb with 16 million colours and voice control.",
    price: 999,
    originalPrice: 1299,
    discount: 23,
    image: "/assets/products/IN-HA-PHI-036.jpg",
    affiliateUrl: "/go/IN-HA-PHI-036",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.1,
    reviewCount: 7200,
    tags: ["home-appliances", "philips", "Smart", "smart-bulb", "lighting", "wifi", "RGB"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PHI-037",
    name: "Philips Smart LED Strip 2M — White",
    brand: "Philips",
    subBrand: "Philips Smart",
    category: "home-appliances",
    subCategory: "lighting",
    variant: "White",
    description: "Philips Smart 2M LED strip with adhesive backing and app control.",
    price: 1499,
    originalPrice: 1899,
    discount: 21,
    image: "/assets/products/IN-HA-PHI-037.jpg",
    affiliateUrl: "/go/IN-HA-PHI-037",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.0,
    reviewCount: 5100,
    tags: ["home-appliances", "philips", "Smart", "LED-strip", "lighting"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PHI-038",
    name: "Philips Smart LED Strip 2M — Colour RGB",
    brand: "Philips",
    subBrand: "Philips Smart",
    category: "home-appliances",
    subCategory: "lighting",
    variant: "Colour RGB",
    description: "Philips Smart 2M RGB LED strip with 16 million colours and music sync.",
    price: 1999,
    originalPrice: 2499,
    discount: 20,
    image: "/assets/products/IN-HA-PHI-038.jpg",
    affiliateUrl: "/go/IN-HA-PHI-038",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.0,
    reviewCount: 4200,
    tags: ["home-appliances", "philips", "Smart", "LED-strip", "lighting", "RGB"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PHI-039",
    name: "Philips Deco LED Night Lamp 0.5W — Blue",
    brand: "Philips",
    subBrand: "Deco",
    category: "home-appliances",
    subCategory: "lighting",
    variant: "Blue",
    description: "Philips Deco 0.5W LED night lamp — ideal for hallways and kids rooms.",
    price: 49,
    originalPrice: 65,
    discount: 25,
    image: "/assets/products/IN-HA-PHI-039.jpg",
    affiliateUrl: "/go/IN-HA-PHI-039",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.2,
    reviewCount: 18600,
    tags: ["home-appliances", "philips", "Deco", "night-lamp", "lighting"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PHI-040",
    name: "Philips Deco LED Night Lamp 0.5W — Pink",
    brand: "Philips",
    subBrand: "Deco",
    category: "home-appliances",
    subCategory: "lighting",
    variant: "Pink",
    description: "Philips Deco 0.5W LED night lamp — ideal for hallways and kids rooms.",
    price: 49,
    originalPrice: 65,
    discount: 25,
    image: "/assets/products/IN-HA-PHI-040.jpg",
    affiliateUrl: "/go/IN-HA-PHI-040",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.2,
    reviewCount: 16400,
    tags: ["home-appliances", "philips", "Deco", "night-lamp", "lighting"],
    apiSource: "amazon-pa-api-free"
  },

  // ── VACUUM CLEANERS (041–050) ───────────────
  {
    id: "IN-HA-PHI-041",
    name: "Philips FC8293/61 PowerPro 1900W Compact — Red",
    brand: "Philips",
    subBrand: "PowerPro Compact",
    category: "home-appliances",
    subCategory: "vacuum-cleaners",
    variant: "Red",
    description: "Philips FC8293/61 PowerPro 1900W compact vacuum cleaner with PowerCyclone 5 technology.",
    price: 7999,
    originalPrice: 9499,
    discount: 16,
    image: "/assets/products/IN-HA-PHI-041.jpg",
    affiliateUrl: "/go/IN-HA-PHI-041",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.2,
    reviewCount: 12400,
    tags: ["home-appliances", "philips", "PowerPro", "vacuum-cleaner", "cleaning"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PHI-042",
    name: "Philips FC8293/61 PowerPro 1900W Compact — Blue",
    brand: "Philips",
    subBrand: "PowerPro Compact",
    category: "home-appliances",
    subCategory: "vacuum-cleaners",
    variant: "Blue",
    description: "Philips FC8293/61 PowerPro 1900W compact vacuum cleaner with PowerCyclone 5 technology.",
    price: 7999,
    originalPrice: 9499,
    discount: 16,
    image: "/assets/products/IN-HA-PHI-042.jpg",
    affiliateUrl: "/go/IN-HA-PHI-042",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.2,
    reviewCount: 10800,
    tags: ["home-appliances", "philips", "PowerPro", "vacuum-cleaner", "cleaning"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PHI-043",
    name: "Philips FC8383/01 PowerPro Active — Blue",
    brand: "Philips",
    subBrand: "PowerPro Active",
    category: "home-appliances",
    subCategory: "vacuum-cleaners",
    variant: "Blue",
    description: "Philips FC8383/01 PowerPro Active bagless vacuum with allergy filter.",
    price: 9999,
    originalPrice: 11999,
    discount: 17,
    image: "/assets/products/IN-HA-PHI-043.jpg",
    affiliateUrl: "/go/IN-HA-PHI-043",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.3,
    reviewCount: 8600,
    tags: ["home-appliances", "philips", "PowerPro Active", "vacuum-cleaner", "cleaning"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PHI-044",
    name: "Philips FC8383/01 PowerPro Active — Silver",
    brand: "Philips",
    subBrand: "PowerPro Active",
    category: "home-appliances",
    subCategory: "vacuum-cleaners",
    variant: "Silver",
    description: "Philips FC8383/01 PowerPro Active bagless vacuum with allergy filter.",
    price: 9999,
    originalPrice: 11999,
    discount: 17,
    image: "/assets/products/IN-HA-PHI-044.jpg",
    affiliateUrl: "/go/IN-HA-PHI-044",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.3,
    reviewCount: 7200,
    tags: ["home-appliances", "philips", "PowerPro Active", "vacuum-cleaner", "cleaning"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PHI-045",
    name: "Philips FC9352/01 PowerPro Expert — Blue",
    brand: "Philips",
    subBrand: "PowerPro Expert",
    category: "home-appliances",
    subCategory: "vacuum-cleaners",
    variant: "Blue",
    description: "Philips FC9352/01 PowerPro Expert with HEPA 13 filter and TriActive+ nozzle.",
    price: 14999,
    originalPrice: 17999,
    discount: 17,
    image: "/assets/products/IN-HA-PHI-045.jpg",
    affiliateUrl: "/go/IN-HA-PHI-045",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.4,
    reviewCount: 6100,
    tags: ["home-appliances", "philips", "PowerPro Expert", "vacuum-cleaner", "HEPA"],
    isFeatured: true,
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PHI-046",
    name: "Philips FC9352/01 PowerPro Expert — Grey",
    brand: "Philips",
    subBrand: "PowerPro Expert",
    category: "home-appliances",
    subCategory: "vacuum-cleaners",
    variant: "Grey",
    description: "Philips FC9352/01 PowerPro Expert with HEPA 13 filter and TriActive+ nozzle.",
    price: 14999,
    originalPrice: 17999,
    discount: 17,
    image: "/assets/products/IN-HA-PHI-046.jpg",
    affiliateUrl: "/go/IN-HA-PHI-046",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.4,
    reviewCount: 5200,
    tags: ["home-appliances", "philips", "PowerPro Expert", "vacuum-cleaner", "HEPA"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PHI-047",
    name: "Philips SpeedPro Max FC6823/61 Cordless — Blue Black",
    brand: "Philips",
    subBrand: "SpeedPro Max",
    category: "home-appliances",
    subCategory: "vacuum-cleaners",
    variant: "Blue Black",
    description: "Philips SpeedPro Max FC6823/61 cordless stick vacuum with 360° suction nozzle.",
    price: 24999,
    originalPrice: 29999,
    discount: 17,
    image: "/assets/products/IN-HA-PHI-047.jpg",
    affiliateUrl: "/go/IN-HA-PHI-047",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.5,
    reviewCount: 4800,
    tags: ["home-appliances", "philips", "SpeedPro Max", "cordless-vacuum", "cleaning"],
    isFeatured: true,
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PHI-048",
    name: "Philips SpeedPro Max FC6823/61 Cordless — Black",
    brand: "Philips",
    subBrand: "SpeedPro Max",
    category: "home-appliances",
    subCategory: "vacuum-cleaners",
    variant: "Black",
    description: "Philips SpeedPro Max FC6823/61 cordless stick vacuum with 360° suction nozzle.",
    price: 24999,
    originalPrice: 29999,
    discount: 17,
    image: "/assets/products/IN-HA-PHI-048.jpg",
    affiliateUrl: "/go/IN-HA-PHI-048",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.5,
    reviewCount: 3900,
    tags: ["home-appliances", "philips", "SpeedPro Max", "cordless-vacuum", "cleaning"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PHI-049",
    name: "Philips SpeedPro Aqua FC6723/61 Cordless — Blue Black",
    brand: "Philips",
    subBrand: "SpeedPro Aqua",
    category: "home-appliances",
    subCategory: "vacuum-cleaners",
    variant: "Blue Black",
    description: "Philips SpeedPro Aqua FC6723/61 cordless vacuum with wet mopping attachment.",
    price: 19999,
    originalPrice: 23999,
    discount: 17,
    image: "/assets/products/IN-HA-PHI-049.jpg",
    affiliateUrl: "/go/IN-HA-PHI-049",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.3,
    reviewCount: 5600,
    tags: ["home-appliances", "philips", "SpeedPro Aqua", "cordless-vacuum", "wet-mop"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PHI-050",
    name: "Philips SpeedPro Aqua FC6723/61 Cordless — Silver",
    brand: "Philips",
    subBrand: "SpeedPro Aqua",
    category: "home-appliances",
    subCategory: "vacuum-cleaners",
    variant: "Silver",
    description: "Philips SpeedPro Aqua FC6723/61 cordless vacuum with wet mopping attachment.",
    price: 19999,
    originalPrice: 23999,
    discount: 17,
    image: "/assets/products/IN-HA-PHI-050.jpg",
    affiliateUrl: "/go/IN-HA-PHI-050",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.3,
    reviewCount: 4500,
    tags: ["home-appliances", "philips", "SpeedPro Aqua", "cordless-vacuum", "wet-mop"],
    apiSource: "amazon-pa-api-free"
  }
]

// ──────────────────────────────────────────────
// TTK PRESTIGE — 50 products (IN-HA-PRE-001 → 050)
// ──────────────────────────────────────────────

export const PRESTIGE_PRODUCTS: IndiaProduct[] = [
  // ── PRESSURE COOKERS (001–010) ──────────────
  {
    id: "IN-HA-PRE-001",
    name: "Prestige Popular Plus Aluminium Pressure Cooker 2L — Silver",
    brand: "TTK Prestige",
    subBrand: "Popular Plus",
    category: "home-appliances",
    subCategory: "pressure-cookers",
    variant: "Silver / 2L",
    description: "Prestige Popular Plus 2L aluminium pressure cooker with metallic safety plug.",
    price: 899,
    originalPrice: 1099,
    discount: 18,
    image: "/assets/products/IN-HA-PRE-001.jpg",
    affiliateUrl: "/go/IN-HA-PRE-001",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.3,
    reviewCount: 48200,
    tags: ["home-appliances", "prestige", "Popular Plus", "pressure-cooker", "kitchen"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PRE-002",
    name: "Prestige Popular Plus Aluminium Pressure Cooker 2L — 2-Pack",
    brand: "TTK Prestige",
    subBrand: "Popular Plus",
    category: "home-appliances",
    subCategory: "pressure-cookers",
    variant: "2-Pack / 2L",
    description: "Prestige Popular Plus 2L aluminium pressure cooker — value 2-pack combo.",
    price: 1699,
    originalPrice: 2198,
    discount: 23,
    image: "/assets/products/IN-HA-PRE-002.jpg",
    affiliateUrl: "/go/IN-HA-PRE-002",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.3,
    reviewCount: 42100,
    tags: ["home-appliances", "prestige", "Popular Plus", "pressure-cooker", "kitchen", "combo"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PRE-003",
    name: "Prestige Popular Plus Aluminium 3L — Silver",
    brand: "TTK Prestige",
    subBrand: "Popular Plus",
    category: "home-appliances",
    subCategory: "pressure-cookers",
    variant: "Silver / 3L",
    description: "Prestige Popular Plus 3L aluminium pressure cooker with precision weight valve.",
    price: 1099,
    originalPrice: 1349,
    discount: 19,
    image: "/assets/products/IN-HA-PRE-003.jpg",
    affiliateUrl: "/go/IN-HA-PRE-003",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.4,
    reviewCount: 52400,
    tags: ["home-appliances", "prestige", "Popular Plus", "pressure-cooker", "kitchen"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PRE-004",
    name: "Prestige Popular Plus Aluminium 3L — With Rack",
    brand: "TTK Prestige",
    subBrand: "Popular Plus",
    category: "home-appliances",
    subCategory: "pressure-cookers",
    variant: "With Rack / 3L",
    description: "Prestige Popular Plus 3L aluminium pressure cooker with stainless steel rack.",
    price: 1249,
    originalPrice: 1499,
    discount: 17,
    image: "/assets/products/IN-HA-PRE-004.jpg",
    affiliateUrl: "/go/IN-HA-PRE-004",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.4,
    reviewCount: 46800,
    tags: ["home-appliances", "prestige", "Popular Plus", "pressure-cooker", "kitchen"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PRE-005",
    name: "Prestige Deluxe Plus Hard Anodised 3L — Black",
    brand: "TTK Prestige",
    subBrand: "Deluxe Plus",
    category: "home-appliances",
    subCategory: "pressure-cookers",
    variant: "Black / 3L",
    description: "Prestige Deluxe Plus 3L hard anodised pressure cooker with Gasket Release System.",
    price: 1999,
    originalPrice: 2399,
    discount: 17,
    image: "/assets/products/IN-HA-PRE-005.jpg",
    affiliateUrl: "/go/IN-HA-PRE-005",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.5,
    reviewCount: 34200,
    tags: ["home-appliances", "prestige", "Deluxe Plus", "pressure-cooker", "hard-anodised"],
    isTrending: true,
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PRE-006",
    name: "Prestige Deluxe Plus Hard Anodised 3L — With Rack",
    brand: "TTK Prestige",
    subBrand: "Deluxe Plus",
    category: "home-appliances",
    subCategory: "pressure-cookers",
    variant: "With Rack / 3L",
    description: "Prestige Deluxe Plus 3L hard anodised pressure cooker with rack and GRS.",
    price: 2199,
    originalPrice: 2599,
    discount: 15,
    image: "/assets/products/IN-HA-PRE-006.jpg",
    affiliateUrl: "/go/IN-HA-PRE-006",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.5,
    reviewCount: 29800,
    tags: ["home-appliances", "prestige", "Deluxe Plus", "pressure-cooker", "hard-anodised"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PRE-007",
    name: "Prestige Deluxe Plus Stainless Steel 3L — Silver",
    brand: "TTK Prestige",
    subBrand: "Deluxe Plus SS",
    category: "home-appliances",
    subCategory: "pressure-cookers",
    variant: "Silver / 3L",
    description: "Prestige Deluxe Plus 3L stainless steel pressure cooker with lugs for easy handling.",
    price: 2499,
    originalPrice: 2999,
    discount: 17,
    image: "/assets/products/IN-HA-PRE-007.jpg",
    affiliateUrl: "/go/IN-HA-PRE-007",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.4,
    reviewCount: 26400,
    tags: ["home-appliances", "prestige", "Deluxe Plus", "pressure-cooker", "stainless-steel"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PRE-008",
    name: "Prestige Deluxe Plus Stainless Steel 3L — Combo",
    brand: "TTK Prestige",
    subBrand: "Deluxe Plus SS",
    category: "home-appliances",
    subCategory: "pressure-cookers",
    variant: "Combo / 3L",
    description: "Prestige Deluxe Plus 3L stainless steel pressure cooker combo with lid and gasket.",
    price: 2799,
    originalPrice: 3399,
    discount: 18,
    image: "/assets/products/IN-HA-PRE-008.jpg",
    affiliateUrl: "/go/IN-HA-PRE-008",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.4,
    reviewCount: 22100,
    tags: ["home-appliances", "prestige", "Deluxe Plus", "pressure-cooker", "stainless-steel", "combo"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PRE-009",
    name: "Prestige Clip-on Stainless Steel Pressure Cooker 6L — Silver",
    brand: "TTK Prestige",
    subBrand: "Clip-on",
    category: "home-appliances",
    subCategory: "pressure-cookers",
    variant: "Silver / 6L",
    description: "Prestige Clip-on 6L stainless steel pressure cooker with innovative clip-on lid.",
    price: 3999,
    originalPrice: 4799,
    discount: 17,
    image: "/assets/products/IN-HA-PRE-009.jpg",
    affiliateUrl: "/go/IN-HA-PRE-009",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.5,
    reviewCount: 18600,
    tags: ["home-appliances", "prestige", "Clip-on", "pressure-cooker", "stainless-steel"],
    isFeatured: true,
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PRE-010",
    name: "Prestige Clip-on Stainless Steel Pressure Cooker 6L — Combo",
    brand: "TTK Prestige",
    subBrand: "Clip-on",
    category: "home-appliances",
    subCategory: "pressure-cookers",
    variant: "Combo / 6L",
    description: "Prestige Clip-on 6L stainless steel pressure cooker combo with glass lid and stand.",
    price: 4499,
    originalPrice: 5399,
    discount: 17,
    image: "/assets/products/IN-HA-PRE-010.jpg",
    affiliateUrl: "/go/IN-HA-PRE-010",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.5,
    reviewCount: 15200,
    tags: ["home-appliances", "prestige", "Clip-on", "pressure-cooker", "stainless-steel", "combo"],
    apiSource: "amazon-pa-api-free"
  },

  // ── INDUCTION COOKTOPS (011–020) ────────────
  {
    id: "IN-HA-PRE-011",
    name: "Prestige PIC 15.0 Plus 1500W Induction Cooktop — Black",
    brand: "TTK Prestige",
    subBrand: "PIC",
    category: "home-appliances",
    subCategory: "induction-cooktops",
    variant: "Black",
    description: "Prestige PIC 15.0 Plus 1500W induction cooktop with anti-magnetic wall protection.",
    price: 2199,
    originalPrice: 2699,
    discount: 19,
    image: "/assets/products/IN-HA-PRE-011.jpg",
    affiliateUrl: "/go/IN-HA-PRE-011",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.2,
    reviewCount: 24600,
    tags: ["home-appliances", "prestige", "PIC", "induction-cooktop", "kitchen"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PRE-012",
    name: "Prestige PIC 15.0 Plus 1500W Induction Cooktop — Black Glass",
    brand: "TTK Prestige",
    subBrand: "PIC",
    category: "home-appliances",
    subCategory: "induction-cooktops",
    variant: "Black Glass",
    description: "Prestige PIC 15.0 Plus 1500W induction cooktop with crystal glass top.",
    price: 2199,
    originalPrice: 2699,
    discount: 19,
    image: "/assets/products/IN-HA-PRE-012.jpg",
    affiliateUrl: "/go/IN-HA-PRE-012",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.2,
    reviewCount: 21800,
    tags: ["home-appliances", "prestige", "PIC", "induction-cooktop", "kitchen"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PRE-013",
    name: "Prestige PIC 20 2000W Induction Cooktop — Black",
    brand: "TTK Prestige",
    subBrand: "PIC",
    category: "home-appliances",
    subCategory: "induction-cooktops",
    variant: "Black",
    description: "Prestige PIC 20 2000W induction cooktop with Indian menu option and timer.",
    price: 2799,
    originalPrice: 3399,
    discount: 18,
    image: "/assets/products/IN-HA-PRE-013.jpg",
    affiliateUrl: "/go/IN-HA-PRE-013",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.3,
    reviewCount: 19200,
    tags: ["home-appliances", "prestige", "PIC", "induction-cooktop", "kitchen"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PRE-014",
    name: "Prestige PIC 20 2000W Induction Cooktop — White",
    brand: "TTK Prestige",
    subBrand: "PIC",
    category: "home-appliances",
    subCategory: "induction-cooktops",
    variant: "White",
    description: "Prestige PIC 20 2000W induction cooktop with Indian menu option and timer.",
    price: 2799,
    originalPrice: 3399,
    discount: 18,
    image: "/assets/products/IN-HA-PRE-014.jpg",
    affiliateUrl: "/go/IN-HA-PRE-014",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.3,
    reviewCount: 16400,
    tags: ["home-appliances", "prestige", "PIC", "induction-cooktop", "kitchen"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PRE-015",
    name: "Prestige PIC 3.1 V3 1600W Induction Cooktop — Black",
    brand: "TTK Prestige",
    subBrand: "PIC",
    category: "home-appliances",
    subCategory: "induction-cooktops",
    variant: "Black",
    description: "Prestige PIC 3.1 V3 1600W induction cooktop with automatic voltage regulator.",
    price: 1999,
    originalPrice: 2499,
    discount: 20,
    image: "/assets/products/IN-HA-PRE-015.jpg",
    affiliateUrl: "/go/IN-HA-PRE-015",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.1,
    reviewCount: 28400,
    tags: ["home-appliances", "prestige", "PIC", "induction-cooktop", "kitchen"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PRE-016",
    name: "Prestige PIC 3.1 V3 1600W Induction Cooktop — Red",
    brand: "TTK Prestige",
    subBrand: "PIC",
    category: "home-appliances",
    subCategory: "induction-cooktops",
    variant: "Red",
    description: "Prestige PIC 3.1 V3 1600W induction cooktop with automatic voltage regulator.",
    price: 1999,
    originalPrice: 2499,
    discount: 20,
    image: "/assets/products/IN-HA-PRE-016.jpg",
    affiliateUrl: "/go/IN-HA-PRE-016",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.1,
    reviewCount: 24600,
    tags: ["home-appliances", "prestige", "PIC", "induction-cooktop", "kitchen"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PRE-017",
    name: "Prestige PPIC 1.0 1200W Portable Induction — Black",
    brand: "TTK Prestige",
    subBrand: "PPIC",
    category: "home-appliances",
    subCategory: "induction-cooktops",
    variant: "Black",
    description: "Prestige PPIC 1.0 portable 1200W induction cooktop — compact for small kitchens.",
    price: 1599,
    originalPrice: 1999,
    discount: 20,
    image: "/assets/products/IN-HA-PRE-017.jpg",
    affiliateUrl: "/go/IN-HA-PRE-017",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.0,
    reviewCount: 14800,
    tags: ["home-appliances", "prestige", "PPIC", "induction-cooktop", "portable", "kitchen"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PRE-018",
    name: "Prestige PPIC 1.0 1200W Portable Induction — Grey",
    brand: "TTK Prestige",
    subBrand: "PPIC",
    category: "home-appliances",
    subCategory: "induction-cooktops",
    variant: "Grey",
    description: "Prestige PPIC 1.0 portable 1200W induction cooktop — compact for small kitchens.",
    price: 1599,
    originalPrice: 1999,
    discount: 20,
    image: "/assets/products/IN-HA-PRE-018.jpg",
    affiliateUrl: "/go/IN-HA-PRE-018",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.0,
    reviewCount: 12200,
    tags: ["home-appliances", "prestige", "PPIC", "induction-cooktop", "portable", "kitchen"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PRE-019",
    name: "Prestige Atlas Induction 1800W — Black",
    brand: "TTK Prestige",
    subBrand: "Atlas",
    category: "home-appliances",
    subCategory: "induction-cooktops",
    variant: "Black",
    description: "Prestige Atlas 1800W induction cooktop with feather touch buttons and soft touch handles.",
    price: 2499,
    originalPrice: 2999,
    discount: 17,
    image: "/assets/products/IN-HA-PRE-019.jpg",
    affiliateUrl: "/go/IN-HA-PRE-019",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.2,
    reviewCount: 11600,
    tags: ["home-appliances", "prestige", "Atlas", "induction-cooktop", "kitchen"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PRE-020",
    name: "Prestige Atlas Induction 1800W — Black Glass",
    brand: "TTK Prestige",
    subBrand: "Atlas",
    category: "home-appliances",
    subCategory: "induction-cooktops",
    variant: "Black Glass",
    description: "Prestige Atlas 1800W induction cooktop with crystal glass top finish.",
    price: 2499,
    originalPrice: 2999,
    discount: 17,
    image: "/assets/products/IN-HA-PRE-020.jpg",
    affiliateUrl: "/go/IN-HA-PRE-020",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.2,
    reviewCount: 9800,
    tags: ["home-appliances", "prestige", "Atlas", "induction-cooktop", "kitchen"],
    apiSource: "amazon-pa-api-free"
  },

  // ── COOKWARE (021–030) ──────────────────────
  {
    id: "IN-HA-PRE-021",
    name: "Prestige Omega Deluxe Non-Stick Tawa 250mm — Black",
    brand: "TTK Prestige",
    subBrand: "Omega Deluxe",
    category: "home-appliances",
    subCategory: "cookware",
    variant: "Black / 250mm",
    description: "Prestige Omega Deluxe 250mm non-stick tawa with metalspoon-friendly coating.",
    price: 699,
    originalPrice: 849,
    discount: 18,
    image: "/assets/products/IN-HA-PRE-021.jpg",
    affiliateUrl: "/go/IN-HA-PRE-021",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.3,
    reviewCount: 21400,
    tags: ["home-appliances", "prestige", "Omega Deluxe", "tawa", "cookware", "non-stick"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PRE-022",
    name: "Prestige Omega Deluxe Non-Stick Tawa 250mm — 2-Pack",
    brand: "TTK Prestige",
    subBrand: "Omega Deluxe",
    category: "home-appliances",
    subCategory: "cookware",
    variant: "2-Pack / 250mm",
    description: "Prestige Omega Deluxe 250mm non-stick tawa — value 2-pack.",
    price: 1299,
    originalPrice: 1698,
    discount: 23,
    image: "/assets/products/IN-HA-PRE-022.jpg",
    affiliateUrl: "/go/IN-HA-PRE-022",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.3,
    reviewCount: 18200,
    tags: ["home-appliances", "prestige", "Omega Deluxe", "tawa", "cookware", "non-stick", "combo"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PRE-023",
    name: "Prestige Omega Select Plus Non-Stick Kadhai 240mm — Black",
    brand: "TTK Prestige",
    subBrand: "Omega Select Plus",
    category: "home-appliances",
    subCategory: "cookware",
    variant: "Black / 240mm",
    description: "Prestige Omega Select Plus 240mm non-stick kadhai with gas and induction compatible base.",
    price: 899,
    originalPrice: 1099,
    discount: 18,
    image: "/assets/products/IN-HA-PRE-023.jpg",
    affiliateUrl: "/go/IN-HA-PRE-023",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.2,
    reviewCount: 16800,
    tags: ["home-appliances", "prestige", "Omega Select Plus", "kadhai", "cookware", "non-stick"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PRE-024",
    name: "Prestige Omega Select Plus Non-Stick Kadhai 240mm — With Lid",
    brand: "TTK Prestige",
    subBrand: "Omega Select Plus",
    category: "home-appliances",
    subCategory: "cookware",
    variant: "With Lid / 240mm",
    description: "Prestige Omega Select Plus 240mm non-stick kadhai with glass lid.",
    price: 1099,
    originalPrice: 1349,
    discount: 19,
    image: "/assets/products/IN-HA-PRE-024.jpg",
    affiliateUrl: "/go/IN-HA-PRE-024",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.2,
    reviewCount: 14200,
    tags: ["home-appliances", "prestige", "Omega Select Plus", "kadhai", "cookware", "non-stick"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PRE-025",
    name: "Prestige Svachh Non-Stick Fry Pan 200mm — Black",
    brand: "TTK Prestige",
    subBrand: "Svachh",
    category: "home-appliances",
    subCategory: "cookware",
    variant: "Black / 200mm",
    description: "Prestige Svachh 200mm non-stick fry pan with 5-star non-stick coating.",
    price: 599,
    originalPrice: 749,
    discount: 20,
    image: "/assets/products/IN-HA-PRE-025.jpg",
    affiliateUrl: "/go/IN-HA-PRE-025",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.1,
    reviewCount: 19600,
    tags: ["home-appliances", "prestige", "Svachh", "fry-pan", "cookware", "non-stick"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PRE-026",
    name: "Prestige Svachh Non-Stick Fry Pan 200mm — With Cover",
    brand: "TTK Prestige",
    subBrand: "Svachh",
    category: "home-appliances",
    subCategory: "cookware",
    variant: "With Cover / 200mm",
    description: "Prestige Svachh 200mm non-stick fry pan with splatter-proof lid.",
    price: 799,
    originalPrice: 999,
    discount: 20,
    image: "/assets/products/IN-HA-PRE-026.jpg",
    affiliateUrl: "/go/IN-HA-PRE-026",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.1,
    reviewCount: 16800,
    tags: ["home-appliances", "prestige", "Svachh", "fry-pan", "cookware", "non-stick"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PRE-027",
    name: "Prestige Aluminium Stainless Steel Combo Set 3-Piece — Silver",
    brand: "TTK Prestige",
    subBrand: "Prestige Combo",
    category: "home-appliances",
    subCategory: "cookware",
    variant: "3-Piece",
    description: "Prestige 3-piece aluminium and stainless steel cookware combo set.",
    price: 1999,
    originalPrice: 2499,
    discount: 20,
    image: "/assets/products/IN-HA-PRE-027.jpg",
    affiliateUrl: "/go/IN-HA-PRE-027",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.2,
    reviewCount: 12400,
    tags: ["home-appliances", "prestige", "cookware-set", "combo", "kitchen"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PRE-028",
    name: "Prestige Aluminium Stainless Steel Combo Set 7-Piece — Silver",
    brand: "TTK Prestige",
    subBrand: "Prestige Combo",
    category: "home-appliances",
    subCategory: "cookware",
    variant: "7-Piece",
    description: "Prestige 7-piece aluminium and stainless steel cookware combo set for complete kitchen.",
    price: 3999,
    originalPrice: 4999,
    discount: 20,
    image: "/assets/products/IN-HA-PRE-028.jpg",
    affiliateUrl: "/go/IN-HA-PRE-028",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.2,
    reviewCount: 9800,
    tags: ["home-appliances", "prestige", "cookware-set", "combo", "kitchen"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PRE-029",
    name: "Prestige Hard Anodised Cookware Set 3-Piece — Black",
    brand: "TTK Prestige",
    subBrand: "Hard Anodised",
    category: "home-appliances",
    subCategory: "cookware",
    variant: "3-Piece",
    description: "Prestige 3-piece hard anodised cookware set with scratch-resistant finish.",
    price: 2499,
    originalPrice: 2999,
    discount: 17,
    image: "/assets/products/IN-HA-PRE-029.jpg",
    affiliateUrl: "/go/IN-HA-PRE-029",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.3,
    reviewCount: 8600,
    tags: ["home-appliances", "prestige", "hard-anodised", "cookware-set", "kitchen"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PRE-030",
    name: "Prestige Hard Anodised Cookware Set 5-Piece — Black",
    brand: "TTK Prestige",
    subBrand: "Hard Anodised",
    category: "home-appliances",
    subCategory: "cookware",
    variant: "5-Piece",
    description: "Prestige 5-piece hard anodised cookware set — tawa, kadhai, fry pan, sauce pan, dosa tawa.",
    price: 3999,
    originalPrice: 4799,
    discount: 17,
    image: "/assets/products/IN-HA-PRE-030.jpg",
    affiliateUrl: "/go/IN-HA-PRE-030",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.3,
    reviewCount: 7200,
    tags: ["home-appliances", "prestige", "hard-anodised", "cookware-set", "kitchen"],
    apiSource: "amazon-pa-api-free"
  },

  // ── GAS STOVES (031–040) ────────────────────
  {
    id: "IN-HA-PRE-031",
    name: "Prestige Royale Gas Stove 3 Burner GTM03L — Black",
    brand: "TTK Prestige",
    subBrand: "Royale",
    category: "home-appliances",
    subCategory: "gas-stoves",
    variant: "Black / 3 Burner",
    description: "Prestige Royale GTM03L 3-burner gas stove with powder-coated body and spill-proof design.",
    price: 3499,
    originalPrice: 4199,
    discount: 17,
    image: "/assets/products/IN-HA-PRE-031.jpg",
    affiliateUrl: "/go/IN-HA-PRE-031",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.3,
    reviewCount: 18200,
    tags: ["home-appliances", "prestige", "Royale", "gas-stove", "3-burner", "kitchen"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PRE-032",
    name: "Prestige Royale Gas Stove 3 Burner GTM03L — Glass Black",
    brand: "TTK Prestige",
    subBrand: "Royale",
    category: "home-appliances",
    subCategory: "gas-stoves",
    variant: "Glass Black / 3 Burner",
    description: "Prestige Royale GTM03L 3-burner gas stove with toughened glass top.",
    price: 3799,
    originalPrice: 4499,
    discount: 16,
    image: "/assets/products/IN-HA-PRE-032.jpg",
    affiliateUrl: "/go/IN-HA-PRE-032",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.3,
    reviewCount: 15600,
    tags: ["home-appliances", "prestige", "Royale", "gas-stove", "3-burner", "glass-top"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PRE-033",
    name: "Prestige Marvel 3 Burner — Black Glass",
    brand: "TTK Prestige",
    subBrand: "Marvel",
    category: "home-appliances",
    subCategory: "gas-stoves",
    variant: "Black Glass / 3 Burner",
    description: "Prestige Marvel 3-burner gas stove with toughened black glass top and brass burners.",
    price: 3299,
    originalPrice: 3999,
    discount: 18,
    image: "/assets/products/IN-HA-PRE-033.jpg",
    affiliateUrl: "/go/IN-HA-PRE-033",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.2,
    reviewCount: 14200,
    tags: ["home-appliances", "prestige", "Marvel", "gas-stove", "3-burner", "glass-top"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PRE-034",
    name: "Prestige Marvel 3 Burner — SS",
    brand: "TTK Prestige",
    subBrand: "Marvel",
    category: "home-appliances",
    subCategory: "gas-stoves",
    variant: "Stainless Steel / 3 Burner",
    description: "Prestige Marvel 3-burner gas stove with stainless steel body.",
    price: 2999,
    originalPrice: 3699,
    discount: 19,
    image: "/assets/products/IN-HA-PRE-034.jpg",
    affiliateUrl: "/go/IN-HA-PRE-034",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.2,
    reviewCount: 12400,
    tags: ["home-appliances", "prestige", "Marvel", "gas-stove", "3-burner", "stainless-steel"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PRE-035",
    name: "Prestige Royale Plus 4 Burner GTM04L — Black",
    brand: "TTK Prestige",
    subBrand: "Royale Plus",
    category: "home-appliances",
    subCategory: "gas-stoves",
    variant: "Black / 4 Burner",
    description: "Prestige Royale Plus GTM04L 4-burner gas stove with multi-spark ignition.",
    price: 4999,
    originalPrice: 5999,
    discount: 17,
    image: "/assets/products/IN-HA-PRE-035.jpg",
    affiliateUrl: "/go/IN-HA-PRE-035",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.4,
    reviewCount: 11200,
    tags: ["home-appliances", "prestige", "Royale Plus", "gas-stove", "4-burner", "kitchen"],
    isFeatured: true,
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PRE-036",
    name: "Prestige Royale Plus 4 Burner GTM04L — Glass Black",
    brand: "TTK Prestige",
    subBrand: "Royale Plus",
    category: "home-appliances",
    subCategory: "gas-stoves",
    variant: "Glass Black / 4 Burner",
    description: "Prestige Royale Plus GTM04L 4-burner gas stove with toughened glass top.",
    price: 5499,
    originalPrice: 6499,
    discount: 15,
    image: "/assets/products/IN-HA-PRE-036.jpg",
    affiliateUrl: "/go/IN-HA-PRE-036",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.4,
    reviewCount: 9600,
    tags: ["home-appliances", "prestige", "Royale Plus", "gas-stove", "4-burner", "glass-top"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PRE-037",
    name: "Prestige Gas Stove 2 Burner Iris Plus — Black",
    brand: "TTK Prestige",
    subBrand: "Iris Plus",
    category: "home-appliances",
    subCategory: "gas-stoves",
    variant: "Black / 2 Burner",
    description: "Prestige Iris Plus 2-burner gas stove with ergonomic knobs and sturdy pan support.",
    price: 2199,
    originalPrice: 2699,
    discount: 19,
    image: "/assets/products/IN-HA-PRE-037.jpg",
    affiliateUrl: "/go/IN-HA-PRE-037",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.1,
    reviewCount: 16800,
    tags: ["home-appliances", "prestige", "Iris Plus", "gas-stove", "2-burner", "kitchen"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PRE-038",
    name: "Prestige Gas Stove 2 Burner Iris Plus — Black Glass",
    brand: "TTK Prestige",
    subBrand: "Iris Plus",
    category: "home-appliances",
    subCategory: "gas-stoves",
    variant: "Black Glass / 2 Burner",
    description: "Prestige Iris Plus 2-burner gas stove with toughened glass top.",
    price: 2499,
    originalPrice: 2999,
    discount: 17,
    image: "/assets/products/IN-HA-PRE-038.jpg",
    affiliateUrl: "/go/IN-HA-PRE-038",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.1,
    reviewCount: 14200,
    tags: ["home-appliances", "prestige", "Iris Plus", "gas-stove", "2-burner", "glass-top"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PRE-039",
    name: "Prestige Hob Top 4 Burner Built-in — Black Glass",
    brand: "TTK Prestige",
    subBrand: "Hob Top",
    category: "home-appliances",
    subCategory: "gas-stoves",
    variant: "Black Glass / 4 Burner",
    description: "Prestige 4-burner built-in hob with auto-ignition and flame failure device.",
    price: 8999,
    originalPrice: 10999,
    discount: 18,
    image: "/assets/products/IN-HA-PRE-039.jpg",
    affiliateUrl: "/go/IN-HA-PRE-039",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.4,
    reviewCount: 7800,
    tags: ["home-appliances", "prestige", "Hob Top", "built-in-hob", "4-burner", "kitchen"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PRE-040",
    name: "Prestige Hob Top 4 Burner Built-in — Tempered Glass",
    brand: "TTK Prestige",
    subBrand: "Hob Top",
    category: "home-appliances",
    subCategory: "gas-stoves",
    variant: "Tempered Glass / 4 Burner",
    description: "Prestige 4-burner built-in hob with tempered glass top and Italian gas valves.",
    price: 9499,
    originalPrice: 11499,
    discount: 17,
    image: "/assets/products/IN-HA-PRE-040.jpg",
    affiliateUrl: "/go/IN-HA-PRE-040",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.4,
    reviewCount: 6400,
    tags: ["home-appliances", "prestige", "Hob Top", "built-in-hob", "4-burner", "kitchen"],
    apiSource: "amazon-pa-api-free"
  },

  // ── KITCHEN TOOLS AND ACCESSORIES (041–050) ─
  {
    id: "IN-HA-PRE-041",
    name: "Prestige Electric Kettle PKOSS 1500W 1.5L — Silver",
    brand: "TTK Prestige",
    subBrand: "PKOSS",
    category: "home-appliances",
    subCategory: "kitchen-tools",
    variant: "Silver",
    description: "Prestige PKOSS 1500W 1.5L electric kettle with auto shut-off and concealed element.",
    price: 699,
    originalPrice: 849,
    discount: 18,
    image: "/assets/products/IN-HA-PRE-041.jpg",
    affiliateUrl: "/go/IN-HA-PRE-041",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.2,
    reviewCount: 32400,
    tags: ["home-appliances", "prestige", "PKOSS", "electric-kettle", "kitchen"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PRE-042",
    name: "Prestige Electric Kettle PKOSS 1500W 1.5L — Black",
    brand: "TTK Prestige",
    subBrand: "PKOSS",
    category: "home-appliances",
    subCategory: "kitchen-tools",
    variant: "Black",
    description: "Prestige PKOSS 1500W 1.5L electric kettle with auto shut-off and concealed element.",
    price: 699,
    originalPrice: 849,
    discount: 18,
    image: "/assets/products/IN-HA-PRE-042.jpg",
    affiliateUrl: "/go/IN-HA-PRE-042",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.2,
    reviewCount: 28600,
    tags: ["home-appliances", "prestige", "PKOSS", "electric-kettle", "kitchen"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PRE-043",
    name: "Prestige Iris 750W Sandwich Toaster — Black",
    brand: "TTK Prestige",
    subBrand: "Iris",
    category: "home-appliances",
    subCategory: "kitchen-tools",
    variant: "Black",
    description: "Prestige Iris 750W sandwich toaster with non-stick grill plates.",
    price: 1299,
    originalPrice: 1599,
    discount: 19,
    image: "/assets/products/IN-HA-PRE-043.jpg",
    affiliateUrl: "/go/IN-HA-PRE-043",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.1,
    reviewCount: 14800,
    tags: ["home-appliances", "prestige", "Iris", "sandwich-toaster", "kitchen"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PRE-044",
    name: "Prestige Iris 750W Sandwich Toaster — White",
    brand: "TTK Prestige",
    subBrand: "Iris",
    category: "home-appliances",
    subCategory: "kitchen-tools",
    variant: "White",
    description: "Prestige Iris 750W sandwich toaster with non-stick grill plates.",
    price: 1299,
    originalPrice: 1599,
    discount: 19,
    image: "/assets/products/IN-HA-PRE-044.jpg",
    affiliateUrl: "/go/IN-HA-PRE-044",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.1,
    reviewCount: 12200,
    tags: ["home-appliances", "prestige", "Iris", "sandwich-toaster", "kitchen"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PRE-045",
    name: "Prestige PSMM 600W Sandwich Maker — Black",
    brand: "TTK Prestige",
    subBrand: "PSMM",
    category: "home-appliances",
    subCategory: "kitchen-tools",
    variant: "Black",
    description: "Prestige PSMM 600W sandwich maker with fixed triangle plates.",
    price: 999,
    originalPrice: 1249,
    discount: 20,
    image: "/assets/products/IN-HA-PRE-045.jpg",
    affiliateUrl: "/go/IN-HA-PRE-045",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.0,
    reviewCount: 18600,
    tags: ["home-appliances", "prestige", "PSMM", "sandwich-maker", "kitchen"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PRE-046",
    name: "Prestige PSMM 600W Sandwich Maker — Red",
    brand: "TTK Prestige",
    subBrand: "PSMM",
    category: "home-appliances",
    subCategory: "kitchen-tools",
    variant: "Red",
    description: "Prestige PSMM 600W sandwich maker with fixed triangle plates.",
    price: 999,
    originalPrice: 1249,
    discount: 20,
    image: "/assets/products/IN-HA-PRE-046.jpg",
    affiliateUrl: "/go/IN-HA-PRE-046",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.0,
    reviewCount: 15400,
    tags: ["home-appliances", "prestige", "PSMM", "sandwich-maker", "kitchen"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PRE-047",
    name: "Prestige PCTKS 600W Coffee Maker — Black",
    brand: "TTK Prestige",
    subBrand: "PCTKS",
    category: "home-appliances",
    subCategory: "kitchen-tools",
    variant: "Black",
    description: "Prestige PCTKS 600W drip coffee maker with 6-cup capacity and anti-drip valve.",
    price: 1499,
    originalPrice: 1799,
    discount: 17,
    image: "/assets/products/IN-HA-PRE-047.jpg",
    affiliateUrl: "/go/IN-HA-PRE-047",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.1,
    reviewCount: 8200,
    tags: ["home-appliances", "prestige", "PCTKS", "coffee-maker", "kitchen"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PRE-048",
    name: "Prestige PCTKS 600W Coffee Maker — Silver",
    brand: "TTK Prestige",
    subBrand: "PCTKS",
    category: "home-appliances",
    subCategory: "kitchen-tools",
    variant: "Silver",
    description: "Prestige PCTKS 600W drip coffee maker with 6-cup capacity and anti-drip valve.",
    price: 1499,
    originalPrice: 1799,
    discount: 17,
    image: "/assets/products/IN-HA-PRE-048.jpg",
    affiliateUrl: "/go/IN-HA-PRE-048",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.1,
    reviewCount: 6800,
    tags: ["home-appliances", "prestige", "PCTKS", "coffee-maker", "kitchen"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PRE-049",
    name: "Prestige PRCK 600W Rice Cooker 1.8L — White",
    brand: "TTK Prestige",
    subBrand: "PRCK",
    category: "home-appliances",
    subCategory: "kitchen-tools",
    variant: "White",
    description: "Prestige PRCK 600W 1.8L electric rice cooker with detachable power cord and cool-touch handles.",
    price: 1799,
    originalPrice: 2199,
    discount: 18,
    image: "/assets/products/IN-HA-PRE-049.jpg",
    affiliateUrl: "/go/IN-HA-PRE-049",
    affiliatePlatform: "amazon",
    affiliateSource: "amazon-pa-api-free",
    inStock: true,
    rating: 4.2,
    reviewCount: 14200,
    tags: ["home-appliances", "prestige", "PRCK", "rice-cooker", "kitchen"],
    apiSource: "amazon-pa-api-free"
  },
  {
    id: "IN-HA-PRE-050",
    name: "Prestige PRCK 600W Rice Cooker 1.8L — Silver",
    brand: "TTK Prestige",
    subBrand: "PRCK",
    category: "home-appliances",
    subCategory: "kitchen-tools",
    variant: "Silver",
    description: "Prestige PRCK 600W 1.8L electric rice cooker with detachable power cord and cool-touch handles.",
    price: 1799,
    originalPrice: 2199,
    discount: 18,
    image: "/assets/products/IN-HA-PRE-050.jpg",
    affiliateUrl: "/go/IN-HA-PRE-050",
    affiliatePlatform: "flipkart",
    affiliateSource: "flipkart-affiliate-free",
    inStock: true,
    rating: 4.2,
    reviewCount: 12100,
    tags: ["home-appliances", "prestige", "PRCK", "rice-cooker", "kitchen"],
    apiSource: "amazon-pa-api-free"
  }
]
